import { StyleSheet, Platform } from "react-native";
import { AppColor, AppFontFamily, Dimensions } from "./../../Themes";
export default StyleSheet.create({
  mainContainer: {
    flex: 1,
    backgroundColor: AppColor.colors.white,
  },
  mainSearchView: {
    width: "100%",
    flexDirection: "row",
    marginTop: 20,
    paddingBottom: Platform.OS == "ios" ? 15 : 0,
    // paddingBottom: 10,
    borderBottomWidth: 0.5,
    borderBottomColor: AppColor.colors.placeHolder,
    overflow: "hidden",
    alignItems: "center",
    justifyContent: "center",
  },
  searchImage: {
    width: 20,
    height: 20,
  },
  searchText: {
    color: AppColor.colors.placeHolder,
    fontFamily: AppFontFamily.fontFamily.regular,
    fontSize: 14,
    marginLeft: 15,
    width: "80%",
  },
  buttonContainer: {
    marginTop: 15,
    width: "100%",
    height: 45,
    flexDirection: "row",
    borderRadius: 5,
    borderWidth: 0.5,
    borderColor: AppColor.colors.placeHolder,
    overflow: "hidden",
  },
  selectedButton: {
    flex: 0.5,
    height: 45,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: AppColor.colors.darkBlue,
  },
  unSelectedButton: {
    flex: 0.5,
    height: 45,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: AppColor.colors.white,
  },
  unSelectedButtonText: {
    color: AppColor.colors.darkBlue,
    fontFamily: AppFontFamily.fontFamily.regular,
    fontSize: 17,
  },
  selectedButtonText: {
    color: AppColor.colors.white,
    fontFamily: AppFontFamily.fontFamily.regular,
    fontSize: 17,
  },
  tabArrow: {
    width: 20,
    height: 20,
    top: -11,
  },
  tabArrowContainer: {
    flexDirection: "row",
    width: "100%",
  },
  tabArrowView: {
    alignItems: "center",
    width: "50%",
  },
  listMainContainer: {
    width: "100%",
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 12,
    marginBottom: 12,
    width: "95%",
    alignSelf: "center",
  },
  followButton: {
    minHeight: 25,
    borderRadius: 5,
    borderWidth: 1,
    borderColor: AppColor.colors.darkBlue,
    justifyContent: "center",
    alignItems: "center",
    alignSelf: "center",
  },
  userImage: {
    width: 15,
    height: 15,
    marginRight: 5,
    alignSelf: "center",
  },
  lineView: {
    width: "95%",
    height: 0.5,
    backgroundColor: AppColor.colors.placeHolder,
    alignSelf: "center",
  },
  arrowImage: {
    width: 12,
    height: 12,
  },
  userText: {
    color: AppColor.colors.darkBlue,
    fontFamily: AppFontFamily.fontFamily.regular,
    fontSize: 14,
  },
  nameText: {
    color: AppColor.colors.twoTwo,
    fontFamily: AppFontFamily.fontFamily.regular,
    fontSize: 15,
  },
  headerListContainer: { paddingBottom: 15, paddingTop: 30 },
  noValueText: {
    color: AppColor.colors.twoTwo,
    fontFamily: AppFontFamily.fontFamily.regular,
    fontSize: 16,
  },
  listEmptyComponentView: {
    height: Dimensions.deviceHeight / 1.7,
    justifyContent: "center",
    alignItems: "center",
  },
  buttonView: {
    flex: 0.4,
    alignItems: "flex-end",
    justifyContent: "center",
  },
  customContainer: {
    width: "60%",
    height: 35,
    borderRadius: 2,
  },
  nameText: {
    color: AppColor.colors.black,
    fontFamily: AppFontFamily.fontFamily.regular,
    fontSize: 15,
    paddingLeft: 8,
  },
  textView: {
    flex: 0.6,
    justifyContent: "center",
  },
  numberText: {
    color: AppColor.colors.placeHolder,
    fontFamily: AppFontFamily.fontFamily.regular,
    fontSize: 15,
    paddingLeft: 8,
  },
  renderView: {
    flex: 1,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 5,
    borderWidth: 1,
    borderColor: AppColor.colors.placeHolder,
    overflow: "hidden",
    marginTop: 5,
    marginBottom: 5,
  },
});
