import { StyleSheet } from "react-native";
import { AppColor, AppFontFamily, Dimensions } from "../../Themes";
export default StyleSheet.create({
  mainContainer: {
    flex: 1,
    backgroundColor: AppColor.colors.white,
  },
  mainSearchView: {
    // width: "100%",
    // flexDirection: 'row',
    // marginTop: 20,
    // paddingBottom: 10,
    // borderBottomWidth: 0.5,
    // borderBottomColor: AppColor.colors.placeHolder,
    // overflow: "hidden",
    // alignItems:'center',
    // paddingTop:15
    // backgroundColor:'red'
    width: "100%",
    flexDirection: "row",
    // marginTop: 20,
    alignItems: "center",
    paddingTop: 15,
    // height:60,
    // paddingBottom: 10,
    paddingBottom: Platform.OS == "ios" ? 15 : 0,
    borderBottomWidth: 0.5,
    borderBottomColor: AppColor.colors.placeHolder,
    overflow: "hidden",
  },
  searchImage: {
    width: 20,
    height: 20,
  },
  searchText: {
    color: AppColor.colors.placeHolder,
    fontFamily: AppFontFamily.fontFamily.regular,
    fontSize: 16,
    // marginLeft: 15,
    width: "90%",
    // backgroundColor:'red'
  },
  bottomView: {
    // paddingHorizontal:20,
    width: "90%",
    position: "absolute",
    bottom: 30,
    alignSelf: "center",
  },
  textInput: {
    paddingLeft: 5,
    paddingRight: 5,
    paddingTop: 14,
    paddingBottom: 14,
    height: 50,
    fontFamily: AppFontFamily.fontFamily.regular,
    color: AppColor.colors.placeHolder,
    fontSize: 16,
    // width: "90%",
    width: "85%",
  },
  bottomContainer: {
    width: "100%",
    alignSelf: "center",
    borderWidth: 1,
    backgroundColor: AppColor.colors.white,
    borderColor: AppColor.colors.imageBackground,
    // overflow: "hidden",
    flexDirection: "row",
  },
  imageView: {
    right: 10,
    width: 60,
    height: 50,
    backgroundColor: AppColor.colors.darkBlue,
    justifyContent: "center",
    alignItems: "center",
  },
  sendImage: {
    width: 25,
    height: 25,
  },
  noValueText: {
    color: AppColor.colors.twoTwo,
    fontFamily: AppFontFamily.fontFamily.regular,
    fontSize: 16,
    textAlign: "center",
    marginLeft: 15,
  },

  listEmptyComponentView: {
    height: Dimensions.deviceHeight / 1.2,
    justifyContent: "center",
  },

  button: {
    borderRadius: 14,
    height: 50,
  },
  buttonView: {
    marginHorizontal: 25,
    justifyContent: "flex-end",
    marginVertical: 20,
    // paddingBottom:20,
  },
  userPostsText: {
    color: AppColor.colors.twoTwo,
    fontFamily: AppFontFamily.fontFamily.regular,
    fontSize: 16,
    textAlign: "center",
    marginLeft: 15,
  },
  crossButton: {
    position: "absolute",
    right: -10,
    top: -10,
    zIndex: 1,
    backgroundColor: "gray",
    height: 20,
    width: 20,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  tagRenderContainer: {
    padding: 5,
    maxWidth: "90%",
    borderRadius: 4,
    margin: 5,
    marginTop: 10,
    marginRight: 8,
    // marginTop: 10,
    backgroundColor: "#29a2e1",
  },
});
