const constants = {
  API_LOGIN_LOAD: "API_LOGIN_LOAD",
  API_LOGIN_SUCCESS: "API_LOGIN_SUCCESS",
  API_LOGIN_FAIL: "API_LOGIN_FAIL",
  API_LOGIN_ERROR: "API_LOGIN_ERROR",

  API_OTP_VERIFY_LOAD: "API_OTP_VERIFY_LOAD",
  API_OTP_VERIFY_SUCCESS: "API_OTP_VERIFY_SUCCESS",
  API_OTP_VERIFY_FAIL: "API_OTP_VERIFY_FAIL",
  API_OTP_VERIFY_ERROR: "API_OTP_VERIFY_ERROR",

  API_REGISTER_LOAD: "API_REGISTER_LOAD",
  API_REGISTER_SUCCESS: "API_REGISTER_SUCCESS",
  API_REGISTER_FAIL: "API_REGISTER_FAIL",
  API_REGISTER_ERROR: "API_REGISTER_ERROR",

  API_OTP_LOAD: "API_OTP_LOAD",
  API_OTP_SUCCESS: "API_OTP_SUCCESS",
  API_OTP_FAIL: "API_OTP_FAIL",
  API_OTP_ERROR: "API_OTP_ERROR",

  API_UPDATE_PHONE_NUMBER_LOAD: "API_UPDATE_PHONE_NUMBER_LOAD",
  API_UPDATE_PHONE_NUMBER_SUCCESS: "API_UPDATE_PHONE_NUMBER_SUCCESS",
  API_UPDATE_PHONE_NUMBER_FAIL: "API_UPDATE_PHONE_NUMBER_FAIL",
  API_UPDATE_PHONE_NUMBER_ERROR: ".API_UPDATE_PHONE_NUMBER_ERROR",

  API_CHECK_USER_LOAD: "API_CHECK_USER_LOAD",
  API_CHECK_USER_SUCCESS: "API_CHECK_USER_SUCCESS",
  API_CHECK_USER_FAIL: "API_CHECK_USER_FAIL",
  API_CHECK_USER_ERROR: "API_CHECK_USER_ERROR",

  API_RESET_PASSWORD_LOAD: "API_RESET_PASSWORD_LOAD",
  API_RESET_PASSWORD_SUCCESS: "API_RESET_PASSWORD_SUCCESS",
  API_RESET_PASSWORD_FAIL: "API_RESET_PASSWORD_FAIL",
  API_RESET_PASSWORD_ERROR: "API_RESET_PASSWORD_ERROR",

  API_HOME_LOAD: "API_HOME_LOAD",
  API_HOME_SUCCESS: "API_HOME_SUCCESS",
  API_HOME_FAIL: "API_HOME_FAIL",
  API_HOME_ERROR: "API_HOME_ERROR",
  API_HOME_UNAUTHENTICATED: "API_HOME_UNAUTHENTICATED",
  SET_HOME_CHAT_COUNT: "SET_HOME_CHAT_COUNT",
  API_HOME_UNREAD_COUNT: "API_HOME_UNREAD_COUNT",

  API_ON_REACH_END_TERMINAL: "API_ON_REACH_END_TERMINAL",
  API_ON_REACH_END_TERMINAL_SUCCESS: "API_ON_REACH_END_TERMINAL_SUCCESS",
  API_ON_REACH_END_TERMINAL_ERROR: "API_ON_REACH_END_TERMINAL_ERROR",
  SELECTED_TERMINAL_ITEM: "SELECTED_TERMINAL_ITEM",

  API_TERMINAL_DETAIL_LOAD: "API_TERMINAL_DETAIL_LOAD",
  API_TERMINAL_DETAIL_SUCCESS: "API_TERMINAL_DETAIL_SUCCESS",
  API_TERMINAL_DETAIL_FAIL: "API_TERMINAL_DETAIL_FAIL",
  API_TERMINAL_DETAIL_ERROR: "API_TERMINAL_DETAIL_ERROR",
  API_TERMINAL_DETAIL_UNAUTHENTICATED: "API_TERMINAL_DETAIL_UNAUTHENTICATED",

  API_TERMINAL_DETAIL_LOAD_END: "API_TERMINAL_DETAIL_LOAD_END",
  API_TERMINAL_DETAIL_SUCCESS_END: "API_TERMINAL_DETAIL_SUCCESS_END",
  API_TERMINAL_DETAIL_FAIL_END: "API_TERMINAL_DETAIL_FAIL_END",
  API_TERMINAL_DETAIL_ERROR_END: "API_TERMINAL_DETAIL_ERROR_END",
  API_TERMINAL_DETAIL_UNAUTHENTICATED_END:
    "API_TERMINAL_DETAIL_UNAUTHENTICATED_END",

    API_VIDEO_UPLOAD_EDIT_LOAD: "API_VIDEO_UPLOAD_EDIT_LOAD",
  API_VIDEO_UPLOAD_EDIT_SUCCESS: "API_VIDEO_UPLOAD_EDIT_SUCCESS",
  API_VIDEO_UPLOAD_EDIT_FAIL: "API_VIDEO_UPLOAD_EDIT_FAIL",
  API_VIDEO_UPLOAD_EDIT_ERROR: "API_VIDEO_UPLOAD_EDIT_ERROR",

  API_VIDEO_UPLOAD_LOAD: "API_VIDEO_UPLOAD_LOAD",
  API_VIDEO_UPLOAD_SUCCESS: "API_VIDEO_UPLOAD_SUCCESS",
  API_VIDEO_UPLOAD_FAIL: "API_VIDEO_UPLOAD_FAIL",
  API_VIDEO_UPLOAD_ERROR: "API_VIDEO_UPLOAD_ERROR",
  API_VIDEO_UPLOAD_UNAUTHENTICATED: "API_VIDEO_UPLOAD_UNAUTHENTICATED",

  API_LIKE_DISLIKE_LOAD: "API_LIKE_DISLIKE_LOAD",
  API_LIKE_DISLIKE_SUCCESS: "API_LIKE_DISLIKE_SUCCESS",
  API_LIKE_DISLIKE_FAIL: "API_LIKE_DISLIKE_FAIL",
  API_LIKE_DISLIKE_ERROR: "API_LIKE_DISLIKE_ERROR",
  API_LIKE_DISLIKE_UNAUTHENTICATED: "API_LIKE_DISLIKE_UNAUTHENTICATED",

  API_FOLLOW_UNFOLLOW_TERMINAL_LOAD: "API_FOLLOW_UNFOLLOW_TERMINAL_LOAD",
  API_FOLLOW_UNFOLLOW_TERMINAL_SUCCESS: "API_FOLLOW_UNFOLLOW_TERMINAL_SUCCESS",
  API_FOLLOW_UNFOLLOW_TERMINAL_FAIL: "API_FOLLOW_UNFOLLOW_TERMINAL_FAIL",
  API_FOLLOW_UNFOLLOW_TERMINAL_ERROR: "API_FOLLOW_UNFOLLOW_TERMINAL_ERROR",
  API_FOLLOW_UNFOLLOW_TERMINAL_UNAUTHENTICATED:
    "API_FOLLOW_UNFOLLOW_UNAUTHENTICATED",

  API_GETCONTACT_LOAD: "API_GETCONTACT_LOAD",
  API_GETCONTACT_SUCCESS: "API_GETCONTACT_SUCCESS",
  API_GETCONTACT_FAIL: "API_GETCONTACT_FAIL",
  API_GETCONTACT_ERROR: "API_GETCONTACT_ERROR",
  API_GETCONTACT_UNAUTHENTICATED: "API_GETCONTACT_UNAUTHENTICATED",

  API_SENTINVITE_LOAD: "API_SENTINVITE_LOAD",
  API_SENTINVITE_SUCCESS: "API_SENTINVITE_SUCCESS",
  API_SENTINVITE_FAIL: "API_SENTINVITE_FAIL",
  API_SENTINVITE_ERROR: "API_SENTINVITE_ERROR",
  API_SENTINVITE_UNAUTHENTICATED: "API_SENTINVITE_UNAUTHENTICATED",

  API_FRIENDS_LOAD: "API_FRIENDS_LOAD",
  API_FRIENDS_SUCCESS: "API_FRIENDS_SUCCESS",
  API_FRIENDS_FAIL: "API_FRIENDS_FAIL",
  API_FRIENDS_ERROR: "API_FRIENDS_ERROR",
  API_FRIENDS_UNAUTHENTICATED: "API_FRIENDS_UNAUTHENTICATED",

  API_MY_FRIENDS_LOAD: "API_MY_FRIENDS_LOAD",
  API_MY_FRIENDS_SUCCESS: "API_MY_FRIENDS_SUCCESS",
  API_MY_FRIENDS_FAIL: "API_MY_FRIENDS_FAIL",
  API_MY_FRIENDS_ERROR: "API_MY_FRIENDS_ERROR",
  API_MY_FRIENDS_UNAUTHENTICATED: "API_MY_FRIENDS_UNAUTHENTICATED",

  API_SEARCH_TERMINAL_LOAD: "API_SEARCH_TERMINAL_LOAD",
  API_SEARCH_TERMINAL_SUCCESS: "API_SEARCH_TERMINAL_SUCCESS",
  API_SEARCH_TERMINAL_FAIL: "API_SEARCH_TERMINAL_FAIL",
  API_SEARCH_TERMINAL_ERROR: "API_SEARCH_TERMINAL_ERROR",
  API_SEARCH_TERMINAL_UNAUTHENTICATED: "API_SEARCH_TERMINAL_UNAUTHENTICATED",

  API_SEARCH_USER_LOAD: "API_SEARCH_USER_LOAD",
  API_SEARCH_USER_SUCCESS: "API_SEARCH_USER_SUCCESS",
  API_SEARCH_USER_FAIL: "API_SEARCH_USER_FAIL",
  API_SEARCH_USER_ERROR: "API_SEARCH_USER_ERROR",
  API_SEARCH_USER_UNAUTHENTICATED: "API_SEARCH_USER_UNAUTHENTICATED",

  API_NEAR_TERMINALS_LOAD: "API_NEAR_TERMINALS_LOAD",
  API_NEAR_TERMINALS_SUCCESS: "API_NEAR_TERMINALS_SUCCESS",
  API_NEAR_TERMINALS_FAIL: "API_NEAR_TERMINALS_FAIL",
  API_NEAR_TERMINALS_ERROR: "API_NEAR_TERMINALS_ERROR",
  API_NEAR_TERMINALS_UNAUTHENTICATED: "API_NEAR_TERMINALS_UNAUTHENTICATED",

  API_ACCEPT_FRIEND_LOAD: "API_ACCEPT_FRIEND_LOAD",
  API_ACCEPT_FRIEND_SUCCESS: "API_ACCEPT_FRIEND_SUCCESS",
  API_ACCEPT_FRIEND_FAIL: "API_ACCEPT_FRIEND_FAIL",
  API_ACCEPT_FRIEND_ERROR: "API_ACCEPT_FRIEND_ERROR",
  API_ACCEPT_FRIEND_UNAUTHENTICATED: "API_ACCEPT_FRIEND_UNAUTHENTICATED",

  API_REMOVE_FRIEND_LOAD: "API_REMOVE_FRIEND_LOAD",
  API_REMOVE_FRIEND_SUCCESS: "API_REMOVE_FRIEND_SUCCESS",
  API_REMOVE_FRIEND_FAIL: "API_REMOVE_FRIEND_FAIL",
  API_REMOVE_FRIEND_ERROR: "API_REMOVE_FRIEND_ERROR",
  API_REMOVE_FRIEND_UNAUTHENTICATED: "API_REMOVE_FRIEND_UNAUTHENTICATED",

  API_CANCEL_FRIEND_LOAD: "API_CANCEL_FRIEND_LOAD",
  API_CANCEL_FRIEND_SUCCESS: "API_CANCEL_FRIEND_SUCCESS",
  API_CANCEL_FRIEND_FAIL: "API_CANCEL_FRIEND_FAIL",
  API_CANCEL_FRIEND_ERROR: "API_CANCEL_FRIEND_ERROR",
  API_CANCEL_FRIEND_UNAUTHENTICATED: "API_CANCEL_FRIEND_UNAUTHENTICATED",

  API_CHAT_HISTORY_LOAD: "API_CHAT_HISTORY_LOAD",
  API_CHAT_HISTORY_SUCCESS: "API_CHAT_HISTORY_SUCCESS",
  API_CHAT_HISTORY_FAIL: "API_CHAT_HISTORY_FAIL",
  API_CHAT_HISTORY_ERROR: "API_CHAT_HISTORY_ERROR",
  API_CHAT_HISTORY_UNAUTHENTICATED: "API_CHAT_HISTORY_UNAUTHENTICATED",

  API_CHAT_USER_HISTORY_LOAD: "API_CHAT_USER_HISTORY_LOAD",
  API_CHAT_USER_HISTORY_SUCCESS: "API_CHAT_USER_HISTORY_SUCCESS",
  API_CHAT_USER_HISTORY_FAIL: "API_CHAT_USER_HISTORY_FAIL",
  API_CHAT_USER_HISTORY_ERROR: "API_CHAT_USER_HISTORY_ERROR",

  API_CHAT_USER_HISTORY_CLEAR_LOAD:"API_CHAT_USER_HISTORY_CLEAR_LOAD",

  API_CHAT_USER_HISTORY_UNAUTHENTICATED:
    "API_CHAT_USER_HISTORY_UNAUTHENTICATED",

  API_ONE_TO_ONE_CHAT_LOAD: "API_ONE_TO_ONE_CHAT_LOAD",
  API_ONE_TO_ONE_CHAT_SUCCESS: "API_ONE_TO_ONE_CHAT_SUCCESS",
  API_ONE_TO_ONE_CHAT_FAIL: "API_ONE_TO_ONE_CHAT_FAIL",
  API_ONE_TO_ONE_CHAT_ERROR: "API_ONE_TO_ONE_CHAT_ERROR",
  API_ONE_TO_ONE_CHAT_UNAUTHENTICATED: "API_ONE_TO_ONE_CHAT_UNAUTHENTICATED",

  API_WARN_CONTACTS_LOAD: "API_WARN_CONTACTS_LOAD",
  API_WARN_CONTACTS_SUCCESS: "API_WARN_CONTACTS_SUCCESS",
  API_WARN_CONTACTS_FAIL: "API_WARN_CONTACTS_FAIL",
  API_WARN_CONTACTS_ERROR: "API_WARN_CONTACTS_ERROR",
  API_WARN_CONTACTS_UNAUTHENTICATED: "API_WARN_CONTACTS_UNAUTHENTICATED",

  NOTIFICATION_MESSAGE: "NOTIFICATION_MESSAGE",

  API_TERMINAL_CHAT_LOAD: "API_TERMINAL_CHAT_LOAD",
  API_TERMINAL_CHAT_SUCCESS: "API_TERMINAL_CHAT_SUCCESS",
  API_TERMINAL_CHAT_FAIL: "API_TERMINAL_CHAT_FAIL",
  API_TERMINAL_CHAT_ERROR: "API_TERMINAL_CHAT_ERROR",
  API_TERMINAL_CHAT_UNAUTHENTICATED: "API_TERMINAL_CHAT_UNAUTHENTICATED",

  API_TERMINAL_CHAT_HISTORY_LOAD: "API_TERMINAL_CHAT_HISTORY_LOAD",
  API_TERMINAL_CHAT_HISTORY_SUCCESS: "API_TERMINAL_CHAT_HISTORY_SUCCESS",
  API_TERMINAL_CHAT_HISTORY_FAIL: "API_TERMINAL_CHAT_HISTORY_FAIL",
  API_TERMINAL_CHAT_HISTORY_ERROR: "API_TERMINAL_CHAT_HISTORY_ERROR",
  API_TERMINAL_CHAT_HISTORY_UNAUTHENTICATED:
    "API_TERMINAL_CHAT_HISTORY_UNAUTHENTICATED",

  API_LOG_OUT_LOAD: "API_LOG_OUT_LOAD",
  API_LOG_OUT_SUCCESS: "API_LOG_OUT_SUCCESS",
  API_LOG_OUT_FAIL: "API_LOG_OUT_FAIL",
  API_LOG_OUT_ERROR: "API_LOG_OUT_ERROR",
  API_LOG_OUT_UNAUTHENTICATED: "API_LOG_OUT_UNAUTHENTICATED",

  UPDATE_FRIEND_ID: "UPDATE_FRIEND_ID",
  CLEAR_TERMINAL_DETAIL: "CLEAR_TERMINAL_DETAIL",

  API_CHANGE_PASSWORD_LOAD: "API_CHANGE_PASSWORD_LOAD",
  API_CHANGE_PASSWORD_SUCCESS: "API_CHANGE_PASSWORD_SUCCESS",
  API_CHANGE_PASSWORD_FAIL: "API_CHANGE_PASSWORD_FAIL",
  API_CHANGE_PASSWORD_ERROR: "API_CHANGE_PASSWORD_ERROR",
  API_CHANGE_PASSWORD_UNAUTHENTICATED: "API_CHANGE_PASSWORD_UNAUTHENTICATED",

  API_GET_USER_PROFILE_LOAD: "API_GET_USER_PROFILE_LOAD",
  API_GET_USER_PROFILE_SUCCESS: "API_GET_USER_PROFILE_SUCCESS",
  API_GET_USER_PROFILE_FAIL: "API_GET_USER_PROFILE_FAIL",
  API_GET_USER_PROFILE_ERROR: "API_GET_USER_PROFILE_ERROR",
  API_GET_USER_PROFILE_UNAUTHENTICATED: "API_GET_USER_PROFILE_UNAUTHENTICATED",

  API_UPDATE_USER_PROFILE_LOAD: "API_UPDATE_USER_PROFILE_LOAD",
  API_UPDATE_USER_PROFILE_SUCCESS: "API_UPDATE_USER_PROFILE_SUCCESS",
  API_UPDATE_USER_PROFILE_FAIL: "API_UPDATE_USER_PROFILE_FAIL",
  API_UPDATE_USER_PROFILE_ERROR: "API_UPDATE_USER_PROFILE_ERROR",
  API_UPDATE_USER_PROFILE_UNAUTHENTICATED:
    "API_UPDATE_USER_PROFILE_UNAUTHENTICATED",

  API_SUPPORT_LOAD: "API_SUPPORT_LOAD",
  API_SUPPORT_SUCCESS: "API_SUPPORT_SUCCESS",
  API_SUPPORT_FAIL: "API_SUPPORT_FAIL",
  API_SUPPORT_ERROR: "API_SUPPORT_ERROR",
  API_SUPPORT_UNAUTHENTICATED: "API_SUPPORT_UNAUTHENTICATED",

  API_PENDING_FRIEND_REQUEST_LOAD: "API_PENDING_FRIEND_REQUEST_LOAD",
  API_PENDING_FRIEND_REQUEST_SUCCESS: "API_PENDING_FRIEND_REQUEST_SUCCESS",
  API_PENDING_FRIEND_REQUEST_FAIL: "API_PENDING_FRIEND_REQUEST_FAIL",
  API_PENDING_FRIEND_REQUEST_ERROR: "API_PENDING_FRIEND_REQUEST_ERROR",
  API_PENDING_FRIEND_REQUEST_UNAUTHENTICATED:
    "API_PENDING_FRIEND_REQUEST_UNAUTHENTICATED",

  API_REPORT_USER_LOAD: "API_REPORT_USER_LOAD",
  API_REPORT_USER_SUCCESS: "API_REPORT_USER_SUCCESS",
  API_REPORT_USER_FAIL: "API_REPORT_USER_FAIL",
  API_REPORT_USER_ERROR: "API_REPORT_USER_ERROR",
  API_REPORT_USER_UNAUTHENTICATED: "API_REPORT_USER_UNAUTHENTICATED",

  API_MY_POSTS_LOAD: "API_MY_POSTS_LOAD",
  API_MY_POSTS_SUCCESS: "API_MY_POSTS_SUCCESS",
  API_MY_POSTS_FAIL: "API_MY_POSTS_FAIL",
  API_MY_POSTS_ERROR: "API_MY_POSTS_ERROR",
  API_MY_POSTS_UNAUTHENTICATED: "API_MY_POSTS_UNAUTHENTICATED",

  API_FRIEND_REQUEST_LOAD: "API_FRIEND_REQUEST_LOAD",
  API_FRIEND_REQUEST_SUCCESS: "API_FRIEND_REQUEST_SUCCESS",
  API_FRIEND_REQUEST_FAIL: "API_FRIEND_REQUEST_FAIL",
  API_FRIEND_REQUEST_ERROR: "API_FRIEND_REQUEST_ERROR",
  API_FRIEND_REQUEST_UNAUTHENTICATED: "API_FRIEND_REQUEST_UNAUTHENTICATED",

  API_ADD_FRIEND_LOAD: "API_ADD_FRIEND_LOAD",
  API_ADD_FRIEND_SUCCESS: "API_ADD_FRIEND_SUCCESS",
  API_ADD_FRIEND_FAIL: "API_ADD_FRIEND_FAIL",
  API_ADD_FRIEND_ERROR: "API_ADD_FRIEND_ERROR",
  API_ADD_FRIEND_UNAUTHENTICATED: "API_ADD_FRIEND_UNAUTHENTICATED",

  API_CANCEL_FRIEND_LOAD: "API_CANCEL_FRIEND_LOAD",
  API_CANCEL_FRIEND_SUCCESS: "API_CANCEL_FRIEND_SUCCESS",
  API_CANCEL_FRIEND_FAIL: "API_CANCEL_FRIEND_FAIL",
  API_CANCEL_FRIEND_ERROR: "API_CANCEL_FRIEND_ERROR",
  API_CANCEL_FRIEND_UNAUTHENTICATED: "API_CANCEL_FRIEND_UNAUTHENTICATED",

  API_REMOVE_FRIEND_LOAD: "API_REMOVE_FRIEND_LOAD",
  API_REMOVE_FRIEND_SUCCESS: "API_REMOVE_FRIEND_SUCCESS",
  API_REMOVE_FRIEND_FAIL: "API_REMOVE_FRIEND_FAIL",
  API_REMOVE_FRIEND_ERROR: "API_REMOVE_FRIEND_ERROR",
  API_REMOVE_FRIEND_UNAUTHENTICATED: "API_REMOVE_FRIEND_UNAUTHENTICATED",

  API_VIDEO_PLAY_LOAD: "API_VIDEO_PLAY_LOAD",
  API_VIDEO_PLAY_SUCCESS: "API_VIDEO_PLAY_SUCCESS",
  API_VIDEO_PLAY_FAIL: "API_VIDEO_PLAY_FAIL",
  API_VIDEO_PLAY_ERROR: "API_VIDEO_PLAY_ERROR",
  API_VIDEO_PLAY_UNAUTHENTICATED: "API_VIDEO_PLAY_UNAUTHENTICATED",

  API_NEAR_TERMINAL_NOTIFICATION_INITIATE: "API_NEAR_TERMINAL_NOTIFICATION_INITIATE",
  API_NEAR_TERMINAL_NOTIFICATION_SUCCESS: "API_NEAR_TERMINAL_NOTIFICATION_SUCCESS",
  API_NEAR_TERMINAL_NOTIFICATION_ERROR: "API_NEAR_TERMINAL_NOTIFICATION_ERROR",

  DELETE_POST_INITIATE: 'DELETE_POST_INITIATE',
  DELETE_POST_SUCCESS: 'DELETE_POST_SUCCESS',
  DELETE_POST_ERROR: 'DELETE_POST_ERROR',

  API_NOTIFICATION_READ_LOAD: 'API_NOTIFICATION_READ_LOAD',
  API_NOTIFICATION_READ_SUCCESS: 'API_NOTIFICATION_READ_SUCCESS',
  API_NOTIFICATION_READ_ERROR: 'API_NOTIFICATION_READ_ERROR',
  API_NOTIFICATION_READ_FAIL: 'API_NOTIFICATION_READ_FAIL',

  API_NOTIFICATION_DELETE_LOAD: 'API_NOTIFICATION_DELETE_LOAD',
  API_NOTIFICATION_DELETE_SUCCESS: 'API_NOTIFICATION_DELETE_SUCCESS',
  API_NOTIFICATION_DELETE_ERROR: 'API_NOTIFICATION_DELETE_ERROR',
  API_NOTIFICATION_DELETE_FAIL: 'API_NOTIFICATION_DELETE_FAIL',

  ON_REACH_END_POST_INITATE: "ON_REACH_END_POST_INITATE",
  ON_REACH_END_POST_SUCCESS: "ON_REACH_END_POST_SUCCESS",
  ON_REACH_END_POST_ERROR: "ON_REACH_END_POST_ERROR",

  REPORT_TERMINAL_POST_DETAIL_INITIATE: "REPORT_TERMINAL_POST_DETAIL_INITIATE",
  REPORT_TERMINAL_POST_DETAIL_SUCCESS: "REPORT_TERMINAL_POST_DETAIL_SUCCESS",
  REPORT_TERMINAL_POST_DETAIL_ERROR: "REPORT_TERMINAL_POST_DETAIL_ERROR",

  DELETE_POST_TERMINAL_DETAIL_INITATE: 'DELETE_POST_TERMINAL_DETAIL_INITATE',
  DELETE_POST_TERMINAL_DETAIL_SUCCESS: 'DELETE_POST_TERMINAL_DETAIL_SUCCESS',
  DELETE_POST_TERMINAL_DETAIL_ERROR: 'DELETE_POST_TERMINAL_DETAIL_ERROR',
  ADD_Count: 'ADD_Count',

  FEED_POST_INITIATE: 'FEED_POST_INITIATE',
  FEED_POST_SUCCESS: 'FEED_POST_SUCCESS',
  FEED_POST_ERROR: 'FEED_POST_ERROR',

  ADD_POST_BOTTOM_TERMINAL_INITIATE: 'ADD_POST_BOTTOM_TERMINAL_INITIATE',
  ADD_POST_BOTTOM_TERMINAL_SUCCESS: 'ADD_POST_BOTTOM_TERMINAL_SUCCESS',
  ADD_POST_BOTTOM_TERMINAL_ERROR: 'ADD_POST_BOTTOM_TERMINAL_ERROR',

  SEARCH_TERMINAL_INITIATE: 'SEARCH_TERMINAL_INITIATE',
  SEARCH_TERMINAL_ERROR: 'SEARCH_TERMINAL_ERROR',
  SEARCH_TERMINAL_SUCCESS: 'SEARCH_TERMINAL_SUCCESS',
  NOTIFY_NOTIFICATION_INITATE: 'NOTIFY_NOTIFICATION_INITATE',
  NOTIFY_NOTIFICATION_SUCCESS: 'NOTIFY_NOTIFICATION_SUCCESS',
  NOTIFY_NOTIFICATION_ERROR: 'NOTIFY_NOTIFICATION_ERROR',

  PROFILE_DATA_INITATE: 'PROFILE_DATA_INITATE',
  PROFILE_DATA_SUCCESS: 'PROFILE_DATA_SUCCESS',
  PROFILE_DATA_ERROR: 'PROFILE_DATA_ERROR',

  Add_USER_IMAGE_INITATE: 'Add_USER_IMAGE_INITATE',
  Add_USER_IMAGE_SUCCESS: 'Add_USER_IMAGE_SUCCESS',
  Add_USER_IMAGE_ERROR: 'Add_USER_IMAGE_ERROR',

  NOTIFICATION_CHAT_INIT: 'NOTIFICATION_CHAT_INIT',
  NOTIFICATION_CHAT_SUCCESS: 'NOTIFICATION_CHAT_SUCCESS',
  NOTIFICATION_CHAT_ERROR: 'NOTIFICATION_CHAT_ERROR',

  API_POST_LOAD: "API_POST_LOAD",
  API_POST_SUCCESS: "API_POST_SUCCESS",
  API_POST_FAIL: "API_POST_FAIL",
  API_POST_ERROR: "API_POST_ERROR",

  API_ROUTE_POST_CREATE_LOAD: "API_ROUTE_POST_CREATE_LOAD",
  API_ROUTE_POST_CREATE_SUCCESS: "API_ROUTE_POST_CREATE_SUCCESS",
  API_ROUTE_POST_CREATE_FAIL: "API_ROUTE_POST_CREATE_FAIL",
  API_ROUTE_POST_CREATE_ERROR: "API_ROUTE_POST_CREATE_ERROR",

  API_ROUTE_DELETE_LOAD: "API_ROUTE_DELETE_LOAD",
  API_ROUTE_DELETE_SUCCESS: "API_ROUTE_DELETE_SUCCESS",
  API_ROUTE_DELETE_FAIL: "API_ROUTE_DELETE_FAIL",
  API_ROUTE_DELETE_ERROR: "API_ROUTE_DELETE_ERROR",

  API_ROUTE_EDIT_LOAD: "API_ROUTE_EDIT_LOAD",
  API_ROUTE_EDIT_SUCCESS: "API_ROUTE_EDIT_SUCCESS",
  API_ROUTE_EDIT_FAIL: "API_ROUTE_EDIT_FAIL",
  API_ROUTE_EDIT_ERROR: "API_ROUTE_EDIT_ERROR",

  API_TIMELINE_GET_LOAD: "API_TIMELINE_GET_LOAD",
  API_TIMELINE_GET_SUCCESS: "API_TIMELINE_GET_SUCCESS",
  API_TIMELINE_GET_FAIL: "API_TIMELINE_GET_FAIL",
  API_TIMELINE_GET_ERROR: "API_TIMELINE_GET_ERROR",

  API_TIMELINE_ADD_LOAD:'API_TIMELINE_ADD_LOAD',
  API_TIMELINE_ADD_SUCCESS:'API_TIMELINE_ADD_SUCCESS',
  API_TIMELINE_ADD_FAIL: "API_TIMELINE_ADD_FAIL",
  API_TIMELINE_ADD_ERROR: "API_TIMELINE_ADD_ERROR",
  
  API_TIMELINE_LIKE_LOAD:'API_TIMELINE_LIKE_LOAD',
  API_TIMELINE_LIKE_SUCCESS:'API_TIMELINE_LIKE_SUCCESS',
  API_TIMELINE_LIKE_FAIL: "API_TIMELINE_LIKE_FAIL",
  API_TIMELINE_LIKE_ERROR: "API_TIMELINE_LIKE_ERROR",

  API_TIMELINE_SHARE_LOAD:'API_TIMELINE_SHARE_LOAD',
  API_TIMELINE_SHARE_SUCCESS:'API_TIMELINE_SHARE_SUCCESS',
  API_TIMELINE_SHARE_FAIL: "API_TIMELINE_SHARE_FAIL",
  API_TIMELINE_SHARE_ERROR: "API_TIMELINE_SHARE_ERROR",

  API_TIMELINE_SHARE_LIST_LOAD:'API_TIMELINE_SHARE_LIST_LOAD',
  API_TIMELINE_SHARE_LIST_SUCCESS:'API_TIMELINE_SHARE_LIST_SUCCESS',
  API_TIMELINE_SHARE_LIST_FAIL: "API_TIMELINE_SHARE_LIST_FAIL",
  API_TIMELINE_SHARE_LIST_ERROR: "API_TIMELINE_SHARE_LIST_ERROR",
  
  //like user list
  API_TIMELINE_LIKE_LIST_LOAD:'API_TIMELINE_LIKE_LIST_LOAD',
  API_TIMELINE_LIKE_LIST_SUCCESS:'API_TIMELINE_LIKE_LIST_SUCCESS',
  API_TIMELINE_LIKE_LIST_FAIL: "API_TIMELINE_LIKE_LIST_FAIL",
  API_TIMELINE_LIKE_LIST_ERROR: "API_TIMELINE_LIKE_LIST_ERROR",

  API_TIMELINE_COMMENT_LOAD:'API_TIMELINE_COMMENT_LOAD',
  API_TIMELINE_COMMENT_SUCCESS:'API_TIMELINE_COMMENT_SUCCESS',
  API_TIMELINE_COMMENT_FAIL: "API_TIMELINE_COMMENT_FAIL",
  API_TIMELINE_COMMENT_ERROR: "API_TIMELINE_COMMENT_ERROR",

  API_TIMELINE_COMMENT_DELETE_LOAD:'API_TIMELINE_COMMENT_DELETE_LOAD',
  API_TIMELINE_COMMENT_DELETE_SUCCESS:'API_TIMELINE_COMMENT_DELETE_SUCCESS',
  API_TIMELINE_COMMENT_DELETE_FAIL: "API_TIMELINE_COMMENT_DELETE_FAIL",
  API_TIMELINE_COMMENT_DELETE_ERROR: "API_TIMELINE_COMMENT_DELETE_ERROR",

  API_TIMELINE_COMMENT_EDIT_LOAD:'API_TIMELINE_COMMENT_EDIT_LOAD',
  API_TIMELINE_COMMENT_EDIT_SUCCESS:'API_TIMELINE_COMMENT_EDIT_SUCCESS',
  API_TIMELINE_COMMENT_EDIT_FAIL: "API_TIMELINE_COMMENT_EDIT_FAIL",
  API_TIMELINE_COMMENT_EDIT_ERROR: "API_TIMELINE_COMMENT_EDIT_ERROR",


  API_TIMELINE_COMMENT_LIKE_LOAD:'API_TIMELINE_COMMENT_LIKE_LOAD',
  API_TIMELINE_COMMENT_LIKE_SUCCESS:'API_TIMELINE_COMMENT_LIKE_SUCCESS',
  API_TIMELINE_COMMENT_LIKE_FAIL: "API_TIMELINE_COMMENT_LIKE_FAIL",
  API_TIMELINE_COMMENT_LIKE_ERROR: "API_TIMELINE_COMMENT_LIKE_ERROR",

  API_TIMELINE_POST_DETAIL_LOAD:'API_TIMELINE_POST_DETAIL_LOAD',
  API_TIMELINE_POST_DETAIL_SUCCESS:'API_TIMELINE_POST_DETAIL_SUCCESS',
  API_TIMELINE_POST_DETAIL_FAIL: "API_TIMELINE_POST_DETAIL_FAIL",
  API_TIMELINE_POST_DETAIL_ERROR: "API_TIMELINE_POST_DETAIL_ERROR",

  ROUTE_POST_DETAIL_LOAD:'ROUTE_POST_DETAIL_LOAD',
  ROUTE_POST_DETAIL_SUCESS:'ROUTE_POST_DETAIL_SUCESS',
  ROUTE_POST_DETAIL_FAIL:'ROUTE_POST_DETAIL_FAIL',
  ROUTE_POST_DETAIL_ERROR:'ROUTE_POST_DETAIL_ERROR',

  ROUTE_POST_INTERCHANGE_ADD_LOAD:'ROUTE_POST_INTERCHANGE_ADD_LOAD',
  ROUTE_POST_INTERCHANGE_ADD_SUCESS:'ROUTE_POST_INTERCHANGE_ADD_SUCESS',
  ROUTE_POST_INTERCHANGE_ADD_FAIL:'ROUTE_POST_INTERCHANGE_ADD_FAIL',
  ROUTE_POST_INTERCHANGE_ADD_ERROR:'ROUTE_POST_INTERCHANGE_ADD_ERROR',

  ROUTE_POST_INTERCHANGE_EDIT_LOAD:'ROUTE_POST_INTERCHANGE_EDIT_LOAD',
  ROUTE_POST_INTERCHANGE_EDIT_SUCESS:'ROUTE_POST_INTERCHANGE_EDIT_SUCESS',
  ROUTE_POST_INTERCHANGE_EDIT_FAIL:'ROUTE_POST_INTERCHANGE_EDIT_FAIL',
  ROUTE_POST_INTERCHANGE_EDIT_ERROR:'ROUTE_POST_INTERCHANGE_EDIT_ERROR',

  ROUTE_POST_INTERCHANGE_DELETE_LOAD:'ROUTE_POST_INTERCHANGE_DELETE_LOAD',
  ROUTE_POST_INTERCHANGE_DELETE_SUCESS:'ROUTE_POST_INTERCHANGE_DELETE_SUCESS',
  ROUTE_POST_INTERCHANGE_DELETE_FAIL:'ROUTE_POST_INTERCHANGE_DELETE_FAIL',
  ROUTE_POST_INTERCHANGE_DELETE_ERROR:'ROUTE_POST_INTERCHANGE_DELETE_ERROR',

  ROUTE_POST_EQUIPMENT_ADD_LOAD:'ROUTE_POST_EQUIPMENT_ADD_LOAD',
  ROUTE_POST_EQUIPMENT_ADD_SUCESS:'ROUTE_POST_EQUIPMENT_ADD_SUCESS',
  ROUTE_POST_EQUIPMENT_ADD_FAIL:'ROUTE_POST_EQUIPMENT_ADD_FAIL',
  ROUTE_POST_EQUIPMENT_ADD_ERROR:'ROUTE_POST_EQUIPMENT_ADD_ERROR',

  ROUTE_POST_EQUIPMENT_EDIT_LOAD:'ROUTE_POST_EQUIPMENT_EDIT_LOAD',
  ROUTE_POST_EQUIPMENT_EDIT_SUCESS:'ROUTE_POST_EQUIPMENT_EDIT_SUCESS',
  ROUTE_POST_EQUIPMENT_EDIT_FAIL:'ROUTE_POST_EQUIPMENT_EDIT_FAIL',
  ROUTE_POST_EQUIPMENT_EDIT_ERROR:'ROUTE_POST_EQUIPMENT_EDIT_ERROR',

  ROUTE_POST_EQUIPMENT_DELETE_LOAD:'ROUTE_POST_EQUIPMENT_DELETE_LOAD',
  ROUTE_POST_EQUIPMENT_DELETE_SUCESS:'ROUTE_POST_EQUIPMENT_DELETE_SUCESS',
  ROUTE_POST_EQUIPMENT_DELETE_FAIL:'ROUTE_POST_EQUIPMENT_DELETE_FAIL',
  ROUTE_POST_EQUIPMENT_DELETE_ERROR:'ROUTE_POST_EQUIPMENT_DELETE_ERROR',

  ROUTE_POST_VIDEO_ADD_LOAD:'ROUTE_POST_VIDEO_ADD_LOAD',
  ROUTE_POST_VIDEO_ADD_SUCESS:'ROUTE_POST_VIDEO_ADD_SUCESS',
  ROUTE_POST_VIDEO_ADD_FAIL:'ROUTE_POST_VIDEO_ADD_FAIL',
  ROUTE_POST_VIDEO_ADD_ERROR:'ROUTE_POST_VIDEO_ADD_ERROR',

  ROUTE_POST_VIDEO_DELETE_LOAD:'ROUTE_POST_VIDEO_DELETE_LOAD',
  ROUTE_POST_VIDEO_DELETE_SUCESS:'ROUTE_POST_VIDEO_DELETE_SUCESS',
  ROUTE_POST_VIDEO_DELETE_FAIL:'ROUTE_POST_VIDEO_DELETE_FAIL',
  ROUTE_POST_VIDEO_DELETE_ERROR:'ROUTE_POST_VIDEO_DELETE_ERROR',

  ROUTE_POST_VIDEO_EDIT_LOAD:'ROUTE_POST_VIDEO_EDIT_LOAD',
  ROUTE_POST_VIDEO_EDIT_SUCESS:'ROUTE_POST_VIDEO_EDIT_SUCESS',
  ROUTE_POST_VIDEO_EDIT_FAIL:'ROUTE_POST_VIDEO_EDIT_FAIL',
  ROUTE_POST_VIDEO_EDIT_ERROR:'ROUTE_POST_VIDEO_EDIT_ERROR',

  ROUTE_POST_PRIVATE_LOAD:'ROUTE_POST_PRIVATE_LOAD',
  ROUTE_POST_PRIVATE_SUCESS:'ROUTE_POST_PRIVATE_SUCESS',
  ROUTE_POST_PRIVATE_FAIL:'ROUTE_POST_PRIVATE_FAIL',
  ROUTE_POST_PRIVATE_ERROR:'ROUTE_POST_PRIVATE_ERROR',

  API_APPVERSION_LOAD: "API_APPVERSION_LOAD",
  API_APPVERSION_SUCCESS: "API_APPVERSION_SUCCESS",
  API_APPVERSION_FAIL: "API_APPVERSION_FAIL",
  API_APPVERSION_ERROR: "API_APPVERSION_ERROR",

  API_CREATE_MANUAL_TIMELINE_LOAD:'API_CREATE_MANUAL_TIMELINE_LOAD',
  API_CREATE_MANUAL_TIMELINE_SUCESS:'API_CREATE_MANUAL_TIMELINE_SUCESS',
  API_CREATE_MANUAL_TIMELINE_FAIL:'API_CREATE_MANUAL_TIMELINE_FAIL',
  API_CREATE_MANUAL_TIMELINE_ERROR:'API_CREATE_MANUAL_TIMELINE_ERROR',

  API_EDIT_MANUAL_TIMELINE_LOAD:'API_EDIT_MANUAL_TIMELINE_LOAD',
  API_EDIT_MANUAL_TIMELINE_SUCESS:'API_EDIT_MANUAL_TIMELINE_SUCESS',
  API_EDIT_MANUAL_TIMELINE_FAIL:'API_EDIT_MANUAL_TIMELINE_FAIL',
  API_EDIT_MANUAL_TIMELINE_ERROR:'API_EDIT_MANUAL_TIMELINE_ERROR'

};

module.exports = {
  constants,
};
