import {imageBaseUrl} from '../Config/index'

const constants = {
  // TermsUrl:"http://18.205.207.176:3000/public/pdf/Fr8_App_Terms_Of_Use.pdf",
  // PrivacyUrl:"http://18.205.207.176:3000/public/pdf/Fr8_App_Privacy_Policy.pdf",
  // // TermsUrl:"http://1.6.98.141/Mobile/fr8/public/pdf/Fr8_App_Terms_Of_Use.pdf",
  // TermsUrl: imageBaseUrl +"public/pdf/Fr8_App_Terms_Of_Use.pdf",
  // // PrivacyUrl:"http://1.6.98.141/Mobile/fr8/public/pdf/Fr8_App_Privacy_Policy.pdf",
  // PrivacyUrl: imageBaseUrl+"public/pdf/Fr8_App_Privacy_Policy.pdf",
  TermsUrl:"https://www.fr8.ai/terms",
  // TermsUrl: imageBaseUrl +"public/pdf/Fr8_App_Terms_Of_Use.pdf",
  // PrivacyUrl:"http://18.205.207.176:3000/public/pdf/Fr8_App_Privacy_Policy.pdf",
  PrivacyUrl:"https://www.fr8.ai/privacy",
  Email: "Correo electrónico",
  Enter_Email: "Ingrese correo electrónico",//need to change
  Password: ' Contraseña',
  Enter_Password: ' Introducir contraseña',
  Enter_New_Password: ' Ingrese Nueva Contraseña',
  Forgot_Your_Password: ' ¿Olvidó su contraseña?',
  Login: ' Iniciar sesión',
  Doesnt_have_an_account: ' ¿No tiene cuenta?',
  Sign_up: ' Registrarse',
  Enter_Name: ' Introduzca su nombre',
  Enter_first_Name: "Ingrese el nombre",
  Enter_last_Name: "Introduzca el apellido",
  Enter_Your_Phone_Number: ' Introduzca su número telefónico',
  Enter_Six_Digit_Verification_Code: ' Ingrese el código de verificación de 6 dígitos',
  Resend_Verification_Code: ' Vuelva a enviar el código de verificación',
  Contact_Permission: ' Por favor habilite el permiso de contactos para mantener seguros a sus amigos.',
  Register: ' Registrarse',
  Full_Name: ' Nombre completo',
  Enter_Full_Name: ' Ingrese su nombre completo',
  Username: ' Nombre de usuario',
  Enter_Username: ' Introduzca su nombre de usuario',
  Email_Address: ' Dirección de correo electrónico',
  Enter_Email_Address: ' Introducir dirección de correo electrónico',
  User_Type: ' Tipo de usuario',
  Select_User_Type: ' Seleccionar tipo de usuario',
  Phone_Number: ' Número de teléfono',
  Enter_Phone_Number: ' Introducción número telefónico',
  Date_Of_Birth: ' Fecha de nacimiento',
  Select_Date_Of_Birth: ' Seleccionar fecha de nacimiento',
  Confirm_Password: ' Confirmar contraseña',
  Enter_Confirm_Password: ' Ingrese Confirmar contraseña',
  Agree_Terms_and_Condition: ' Aceptar términos y condiciones',
  Forgot_Password: ' Olvidé la contraseña',
  Submit: ' Enviar',
  OTP: ' OTP',
  Enter_OTP: ' Introducir OTP',
  Reset_Password: ' Restablecer la contraseña',
  Edit_Profile: ' Editar perfil',
  Edit_Phone_Number: ' Editar número de teléfono',
  Update: ' Actualizar',
  Change_Password: ' Cambiar la contraseña',
  Old_Password: ' Contraseña antigua',
  Enter_Old_Password: ' Ingrese la contraseña anterior',
  FAQs: ' Preguntas frecuentes',
  Social_Media_Accounts: ' Cuentas de redes sociales',
  Settings: ' Configuraciones',
  FR8: ' FR8',
  Support_Center: ' Centro de Ayuda',
  Terms_And_Conditions: ' Términos y Condiciones',
  Privacy_Policy: ' Política de privacidad',
  Change_Language: ' Cambiar idioma',
  Logout: ' Cerrar sesión',
  Log_out: ' Cerrar Sesión',
  Confirm: 'Confirmar',
  Cancel: ' Cancelar',
  Please_Select: ' Por favor seleccione',
  Warn_Contacts: ' Advertir a contactos',
  Search_contacts: ' Buscar contactos',
  Friend_Requests: ' Solicitudes de amistad',
  Friend_Request: ' Solicitud de amistad',
  My_Posts: ' Mis publicaciones',
  posts: 'Publicaciones',
  post: 'Enviar',
  Search_friends: ' Buscar amigos, terminales, contactos',
  My_Freighting_Network: ' Mi red de transporte',
  My_Network: ' Mi red',
  Report_Post: "Reportar publicacion",
  Places: ' Lugares',
  Friends: ' Amigos',
  Friend: 'Amigos',
  Nearby_Terminals: ' Terminales cercanas',
  Explore: ' Explorar',
  Contacts: ' Contactos',
  Name_Of_User: ' Nombre del usuario',
  Add_Friend: ' Añadir amigo',
  Remove_Friend: ' Eliminar amigo',
  Chat: ' Chat',
  Post_Details: ' Detalles de la publicación',
  Live_Streams: ' Transmisiones en vivo',
  CreatePost: ' Crear publicación',
  SocialMediaAccounts: ' Cuentas de redes sociales',
  Instagram: ' Instagram',
  Google: ' Google',
  Facebook: ' Facebook',
  Support: ' Ayuda',
  Tittle: ' Título',
  Enter_Tittle: ' Introducir Título',
  FR8: ' FR8',
  UserName: ' Nombre de usuario',
  TerminalDetails: ' Detalles de la terminal',
  Location: ' Ubicación',
  Un_Follow: ' Dejar de seguir',
  Follow: ' Seguir',
  Record: ' Grabar',
  Warn: ' Advertir',
  ChatHistory: ' Historial de chat',
  TerminalName: ' Nombre de terminal',
  Terminal: ' Terminal',
  English: ' Inglés',
  Spanish: ' Español',
  Driver_Type: ' Tipo de conductor',
  Select_Driver_Type: ' Seleccionar el tipo de controlador',
  Users: ' Usuarios',
  Enter_Title: ' Ingrese el Título',
  Type_Message_Here: ' Escriba el mensaje aquí...',
  Change_Language: ' Cambiar idioma',
  Skip: ' Omitir',
  Friend_request_not_found: ' Solicitud de amistad no encontrada.',
  Change_Mobile_Number: ' Cambiar número de móvil',
  resend_Otp: ' Reenviar el código de verificación',
  enter_email_alert: ' Por favor ingrese la dirección de correo electrónico.',
  enter_valid_email_alert: ' Por favor ingrese una dirección de correo electrónico válida.',
  enter_password_alert: ' Por favor ingrese la contraseña.',
  // enter_full_name_alert: ' Por favor ingrese su nombre completo.',
  // enter_full_name_aplhanumeric_alert: ' Por favor ingrese alfanumérico en el nombre completo.',
  enter_full_name_alert: ' Por favor ingrese el nombre.',
  enter_full_name_aplhanumeric_alert: ' Ingrese alfanumérico en el nombre.',
  enter_user_name_alert: ' Por favor ingrese el nombre de usuario.',
  enter_user_type_alert: ' Por favor seleccione el tipo de usuario.',
  enter_driver_type_alert: ' Por favor seleccione el tipo de conductor',
  enter_phone_number_alert: ' Por favor ingrese el número de teléfono.',
  enter_phone_number_length_alert: ' El número de teléfono debe ser entre 8 y 15 dígitos.',
  enter_Numbers_allowed__phone_alert: ' Solo se permiten números en el campo de teléfono.',
  enter_date_of_birth_alert: ' Por favor seleccione la fecha de nacimiento.',
  enter_password_length_alert: ' La contraseña debe tener al menos 6 caracteres.',
  enter_confirm_password_alert: ' Por favor ingresar confirmar contraseña.',
  enter_password_not_match_alert: ' La contraseña y la confirmación de contraseña deben ser iguales.',
  enter_terms_conditions_alert: ' Por favor acepte los términos y condiciones.',
  enter_otp_alert: ' Por favor ingrese el código de verificación.',
  enter__valid_otp_alert: ' Por favor ingrese un código de verificación válido.',
  enter_old_password_alert: ' Por favor introduzca la contraseña anterior.',
  enter_old_password_length_alert: ' La contraseña anterior debe tener al menos 6 caracteres.',
  enter_new_password_alert: ' Por favor introduzca una nueva contraseña.',
  enter_new_password_length_alert: ' La nueva contraseña debe tener al menos 6 caracteres.',
  enter_old_cofirm_not_valid_alert: ' La contraseña anterior y la contraseña de confirmación deben ser las mismas.',
  Stream_stopped_by_user: ' Video en video terminado por',
  Loading_streams: ' Cargando transmisiones',
  you_are_live_now: ' Ahora está en vivo.',
  end_publisher_video: ' ¿Está seguro de que desea finalizar este video en vivo?',
  logOutAlert: ' ¿Está seguro de que desea cerrar la sesión?',
  end_publisher_video_successfully: ' Video en vivo finalizado.',
  Alert: ' Alerta',
  PhoneNumber_required_for_login: ' Se requiere un número de teléfono para iniciar sesión, que también nos ayuda a moderar la comunidad y proteger a nuestros usuarios.',
  Privacy_policy: ' AL CONTINUAR, ACEPTA NUESTROS',
  Terms: ' TÉRMINOS DE USO',
  Policy: ' POLÍTICA DE PRIVACIDAD',
  Why_you_need_my_phone_number: ' POR QUÉ NECESITAN MI NÚMERO DE TELÉFONO',
  Why_we_need_your_phone_number: ' POR QUÉ NECESITAMOS SU NÚMERO DE TELÉFONO',
  verifyAccount: ' VERIFIQUE SU CUENTA',
  terminalNotFound: ' Terminal no encontrada.',
  Profile: ' Perfil',
  App_Settings: ' Ajustes de Aplicación',
  Citizen_safety_message: ' Fr8 es una red de transporte de mercancías. Requerimos un número de teléfono tanto para verificar su identidad como para garantizar que quienes violen los estándares de nuestra comunidad puedan ser eliminados de la red, cuando corresponda.',
  'something_went_wrong': ' Algo salió mal.',
  'please_check_your_internet_connection': ' Por favor revise su conexion a internet.',
  startEndAlert: ' La hora de inicio debe ser menor que la hora de finalización.',
  addPost: ' Agregar publicación',
  permissionTitle: ' Había denegado el permiso para seleccionar fotos de la biblioteca.',
  permissionBody: ' ¿Le gustaría acceder a esto y luego permitir el permiso en la configuración?',
  videoPermissionTitle: ' Denegó el permiso para seleccionar videos de la biblioteca.',
  TimeLine_post_not_found: 'Publica tu actualización.',
  Timeline_Posts: ' Publicaciones de la Cronología',
  Timeline: ' Cronología',
  trackAtimeLine: ' Haga un seguimiento de su tiempo de espera',
  Journey: 'No se encontró una línea de tiempo.',
  KM: ' mi',
  Distance_Travelled: ' Distancia recorrida',
  hrs: ' horas',
  secs: ' segundos',
  mins: ' minutos',
  time: ' Hora',
  wait_time: ' Tiempo promedio de espera',
  Equiment_Photo: ' Foto del equipo',
  Interchange_Receipt: ' Recibo de intercambio',
  video: ' Vídeo',
  Share: ' Compartir',
  start_time: ' En',
  endTime: ' Afuera',
  openTime: ' Tiempo abierto',
  closeTime: ' Hora de cierre',
  distance: ' Distancia',
  Total_time: ' Tiempo Total',
  Edit_Timeline: ' Editar Calendario',
  "Edit": "Editar",
  messageAlert: ' Por favor ingrese algún mensaje.',
  enterMessage: ' Ingrese su mensaje...',
  Trending_Post: ' Publicación de tendencia',
  PleaseEnterReportResion: ' Por favor ingrese el motivo del informe.',
  trendingPostNotFound: ' No se encontró ninguna publicación de tendencia.',
  Accept: ' Aceptar',
  Reject: ' Rechazar',
  Allow: ' Permitir',
  Invite: ' Invitación',
  postNotFound: ' No se encontró ninguna publicación.',
  Cancel_Friend_Request: ' Cancelar solicitud de amistad',
  User_Posts: ' Publicaciones de usuario',
  Notifications: ' Notificaciones',
  No_notifications: ' No se encontraron notificaciones.',
  And: ' Y',
  Delete: 'Eliminar',
  deletePostAlert: ' ¿Está seguro de que quiere eliminar esta publicación?',
  Yes: ' Sí',
  No: ' No',
  enterTitle: ' Por favor ingrese el título.',
  pleaseEnterMessage: ' Por favor ingrese el mensaje.',
  Post_Create: ' Crear publicación',
  description: ' Ingrese su descripción...',
  enterDescription: ' Por favor ingrese la descripción.',
  descriptionMax: ' Por favor introduzca una descripción de menos de 1000 caracteres.',
  descriptionMin: ' La descripción debe tener al menos 10 caracteres.',
  Preview: ' Vista previa',
  messageMax: ' Por favor ingrese un mensaje de menos de 1000 caracteres.',
  noUser: ' Usuario no encontrado.',
  New: ' Nuevo',
  No_chat_found: ' No se encontró ningún chat reciente',
  messageCopy: 'Mensaje copiado',
  Search_Terminal: ' Buscar Terminal',
  'estimatedTime': 'Hora prevista',
  'estimatedWaitTime': 'Minutos de espera',
  // 'estimatedWaitTime': 'Tiempo de espera estimado',
  'youHaveLeft': "Te has ido",
  'avaliable24Hours': 'Disponible las 24 horas',//self change
  // "Receipt_Private": 'Recibo privado',//need to change
  "Receipt_Private": 'Hacer privado',//need to change
  "photo": "FOTO",
  'photoLibrary': 'LIBRERÍA FOTOGRÁFICA',


  "photoL": "Foto",
  'photoLibraryL': 'Librería fotográfica',

  'noResult': 'No se han encontrado resultados.',
  'reportUser': 'Reportar',
  'reasonOfReport': 'Razón del informe',
  'reportPostAlert': '¿Estás seguro de que quieres denunciar esta publicación?',
  'postShareMessage': ' ha compartido una publicación \n Haga clic en el enlace de abajo para ver la publicación ',
  'postShareMessage2': ' ha compartido una publicación \n Haga clic en el enlace de abajo para ver la publicación ',
  "ForegroundServiceTitle": "Se está ejecutando Detention Pay Tracker",
  // "ForegroundServiceTitle": "La aplicación FR8 administra tu ubicación en segundo plano",
  "Portuguese": "Portugal",
  "interChangeDelete": "¿Estás segura de que quieres eliminar el recibo de intercambio?",
  "equipmentDelete": "¿Estás seguro de que deseas eliminar la foto del equipo?",
  "deleteVideo": "¿Estás segura de que quieres eliminar el video?",
  // 'sentAmessage':'envió un mensaje:'
  'sentAMessage': 'envió un mensaje:',
  'editMessage': 'Editar mensaje',
  'continue': 'Continuar',
  'noContact': 'No se encontraron contactos',


  'ownerOperator': 'Operador propietario',
  'companyDriver': 'Conductor de la empresa',


  'Driver': "Conductor",
  'Owner Operator': 'Operador propietario',
  "Company": 'Compañía',
  "Air Cargo Carrier": 'Transportista de carga aérea',
  "Exporter": "Exportador",
  "Freight Broker": 'Corredor de carga',
  "Importer": "Importador",
  "Shipper": "Expedidor",
  "Trucking": "Camionaje",
  "Warehouse": "Depósito",
  'Owner Operator': 'Operador propietario',
  'Company Driver': 'Conductor de la empresa',
  'OKAY':'BUENO',
  'installMessage':'Oye, descarga la aplicación FR8 para que puedas calcular los tiempos de espera en el puerto | terminales ferroviarias: http://onelink.to/fr8app',
  'warned':'prevenida',
  "WaitingAt":'Esperando en',
  'openFr8':'Abra la aplicación Fr8 para mostrar su tiempo de espera estimado.',
  "day":"día",
  "days":"dias",
  "hour":" hora",
  "hours":" horas",
  "minute":" minuto",
  "minutes":" minutos",
  "second":" segundo",
  "seconds":" segundos",
  // 'openApp':'Abra la aplicación FR8.',
  'openApp': 'Abra la aplicación para sincronizar su estado',
  'openAppBody': 'Para obtener la mejor experiencia, permita que la aplicación FR8 permanezca abierta en segundo plano. Esto mantiene su línea de tiempo y el sello de tiempo del terminal precisos.',
  "Comment":"Comentario",
  "Comments":"Comentarios",
  "Like":"Me gusta",
  'noComment':"No se encontraron comentarios",
  'deleteCommentAlert':"¿Estás seguro de que quieres eliminar el comentario?",
  'enterTheComment':"Por favor ingrese el comentario.",
  'enterYourComment':"Ingrese su comentario ...",
  'DeeplinkShare':'Compartir Deeplink',
  'Shares': 'Comparte',
  'shareasPost':"Compartir post",
  'hasShared':'ha compartido',
  'whatsOnMind':"¿Qué tienes en mente?",
  'inGate':'En',
  'outGate':'Afuera',
  'enter_last_name_alert': "Por favor ingrese su apellido.",
  'With':'con',
  'others':'otros',
  'tagFriends':'Etiqueta amigos',
  'done':'Hecho',
  'friendSearch':'Buscar amigos',
  'checkIN':'Registrarse',
  'tagUsers':'Usuarios etiquetados',
  'safeTrip':' Ahora puedes compartir tu espera hora. ¡Ten un viaje seguro!',
  'addLocation':'Añadir lugar',
  'locationSelect':'Seleccione la ubicación.',
  'attach':'Adjuntar archivos',
  'selectImage':'Seleccione imágenes o video para publicar.',
  'noPlace':'No se encontraron lugares',
  'deleteMedia':'¿Está seguro de que desea eliminar este medio?',
  'deleteNotification':'¿Está seguro de que desea eliminar esta notificación?',
  'loading':'Cargando...',
  'next':"Próximo",
  'ttlUserInterminal':'Número de usuarios dentro de la terminal: ',
  'members':'miembros dentro',
  'member':'miembro dentro',
  DescriptionText:'Descripción',
  NotificationDetail:'Detalles de la notificación',

  //newly added
  useLocation:'Use your location',
  firstPermissionTitle:'To see maps for automatically tracked activities, allow FR8 to use your location all of the time.',
  noThanks:'No thanks',
  turnOn:'Turn on',
  newVersion:'New version ',
  // versionDescription:'The version of the app you are using is outdated, please update to the latest version for the most accurate wait times.',
  versionDescription:`Esta versión de la aplicación está desactualizada, actualice a la última versión para desbloquear nuevas funciones increíbles que lo ayuden a obtener las funciones nuevas más precisas y sorprendentes. No olvide establecer los permisos de ubicación en Permitir siempre para que la aplicación calcule los tiempos de espera de la terminal en segundo plano.`,
  firstPermissionDesc:'FR8 will use your location in the background to enable your precise recordings of your trips in terminals and calculate wait time and time stamp.',
  enter_user_name_length_alert: "El nombre de usuario debe tener al menos 3 caracteres.",
  validUserName:'Solo se permiten letras (a-z), números (0-9), puntos (.) Y guión bajo (_).',
  user_name_start: "El nombre de usuario no debe comenzar con puntos (.)",
  onlyNumberAlert:"El nombre de usuario no puede contener solo números.",
  user_name_end:"El nombre de usuario no debe terminar con puntos (.)",
  twoDots:'El nombre de usuario no debe tener más de un punto (.) En una fila.',
Ok:"OK",
followingTerminal:'Siguiendo',
pdfDownload:'Descargar PDF',
timelineCancel:'¿Estás seguro de que deseas cancelar la línea de tiempo?',
"Truck Stop":"Parada de camiones",
"Gas Station":"Gasolinera",
"Weight Station":"Estación de peso",
location_name_enter:"Ingrese el nombre de la ubicación.",
locationNameLong:'El nombre de la ubicación debe tener al menos 2 caracteres.',
locationAddressLong:"La dirección de la ubicación debe tener al menos 2 caracteres.",
locationAddress:"Ingrese la dirección de la ubicación.",
Name:"Nombre",
"Hold to Stop":"Mantenga pulsado para detener",
"Location Address":"Dirección del sitio",
"Phone Number":"Número de teléfono",
"Add":"Agregar",
"Category":"Categoría",
backgroundProcess:"Su línea de tiempo se ejecutará en segundo plano cuando se mueva a otras pantallas.",
NotMoving:"¿Aún no te mudas?",
oneMinuteLongerAlert:"Para terminar y guardar, FR8 necesita al menos 1 minuto más de actividad, con un cambio de ubicación.",
editPost:"Edit Post",
vedioLimit:"La duración del video debe ser de un máximo de 30 segundos.",
selectCurentLocation:"Seleccione la ubicación actual",
noCommentYet:"Sin comentarios aún",
enterFirstComment:"Sé el primero en comentar.",
App_Share:'Compartir aplicación',
'appShareMessage': ' ha compartido la aplicación FR8. Haga clic en el enlace a continuación para ver la aplicación móvil y ver los tiempos de espera actuales hoy. ',
'appShareMessage2': 'FR8\n Haga clic en el enlace a continuación para ver la aplicación móvil y ver los tiempos de espera actuales hoy. ',
location_Setting:'Configuración de ubicación',
postlikeHeading:'Personas a las que les gusta la publicación',
commentLikeHeading:'Las personas a las que les gusta comentar',
viewProfile:'Ver perfil',
shareListHeading:'Personas que compartieron la publicación',
enter_first_name_length_alert: "El nombre debe tener al menos 3 caracteres.",
enter_last_name_length_alert: "El apellido debe tener al menos 3 caracteres.",
'deleteCommentReplyAlert':"¿Está seguro de que desea eliminar esta respuesta de comentario?",
Reply :"Respuesta",
"Reply to": "Responder a",
Like: "Me gusta",
Dislike :"Disgusto",
Smile :"Sonrisa",
Angry :"Enojado",
"Rolling Eyes":"ojos rodantes",
Thinking:"Pensando",
Stop:"Detener",
switchFrom:'Reciba notificaciones de seguridad precisas cambiando de',
'Always Allow':'Permitir siempre',
'While Using':'Durante el uso',
'Ask next time':'pregunta la proxima vez',
'Never':'Nunca',
"Manage location Settings":'Administrar configuración de ubicación',

/////////////////////////////////
"SavetoPhone":"Guardar en teléfono",
"All":'Todos',
"ADD":"AGREGAR",



"Italian":`italiano`,
"Chinese":`Chinês simplificado (mandarim)`,
"Hindi":`hindi`,
"Filipino":`Filipino`,
"Vietnamese":`vietnamita`,
"Arabic":`árabe`,
"French":`francês`,
"Korean":`coreano`,
"Russian":`russo`,
"Bengali":`bengali`,
"German":`alemão`,

regionlNotFound: 'Region not found.',
Region:"Region",

"All":'Todos',
in: 'en',


"All":"Todos",
"saveToPhone":"Guardar en teléfono",
"ADD":"AGREGAR",
"deleteAccount":"Borrar cuenta",
"deleteAccountAlert":"¿Está seguro de que desea eliminar su cuenta?",
"replyWrite":"Escribe una respuesta...",
"Camera":"Cámara",
"Image Gallery":"galería de imágenes",
"regionlNotFound":"Región no encontrada.",
"Region":"Región",
"regionSelectAlert":"El usuario puede seleccionar un máximo de 3 regiones.",

"CALL":"LLAMAR",
"ADDRESS":"DIRECCIÓN",
"MIN":"MÍN.",
"About":"Sobre",
"Overview":"Visión general",
"Review":"Revisar",
"Timelines":"Cronologías",
"Rate & Review":"Revisión de tasas",
"ratings":"Revisión de tasas",
"Write Your Review":"Escribe tu reseña",
"Just now":"En este momento",
'waitTimeIndicator':'Indicador de tiempo de espera',
currentWaitTime:"Tiempo de espera promedio actual",
addmobile:'Agregar número de móvil',
addAccount:'Añadir cuenta',



}

module.exports = {
  constants
}