import {imageBaseUrl} from '../Config/index'
const constants = {
   // TermsUrl:"http://18.205.207.176:3000/public/pdf/Fr8_App_Terms_Of_Use.pdf",
   TermsUrl:"https://www.fr8.ai/terms",
   // TermsUrl: imageBaseUrl +"public/pdf/Fr8_App_Terms_Of_Use.pdf",
   // PrivacyUrl:"http://18.205.207.176:3000/public/pdf/Fr8_App_Privacy_Policy.pdf",
   PrivacyUrl:"https://www.fr8.ai/privacy",
   // PrivacyUrl: imageBaseUrl + "public/pdf/Fr8_App_Privacy_Policy.pdf",
"Email":`이메일`,
"Enter_Email":`이메일 입력`,
"Password":`비밀번호`,
"Enter_Password":`비밀번호 입력`,
"Enter_New_Password":`새 비밀번호 입력`,
"Forgot_Your_Password":`비밀번호를 잊으셨나요?`,
"Login":`로그인`,
"Doesnt_have_an_account":`계정이 아직 없으신가요?`,
"Sign_up":`회원 가입`,
"Enter_Name":`이름 입력`,
"Enter_first_Name":`이름 입력`,
"Enter_last_Name":`성 입력`,
"Enter_Your_Phone_Number":`전화번호를 입력하세요.`,
"Enter_Six_Digit_Verification_Code":`6자리 검증 코드를 입력하세요`,
"Resend_Verification_Code":`검증 코드 재전송`,
"Contact_Permission":`여러분의 친구들을 계속 안전하게 유지하시려면 연락처 권한을 허용해주세요.`,
"Register":`등록`,
"Full_Name":`성명`,
"Enter_Full_Name":`성명을 입력하세요`,
"Username":`아이디`,
"Enter_Username":`아이디를 입력하세요`,
"Email_Address":`이메일 주소`,
"Enter_Email_Address":`이메일 주소를 입력하세요`,
"User_Type":`사용자 유형`,
"Select_User_Type":`사용자 유형을 선택하세요`,
"Phone_Number":`전화번호`,
"Enter_Phone_Number":`전화번호를 입력하세요`,
"Date_Of_Birth":`생년월일`,
"Select_Date_Of_Birth":`생년월일을 선택하세요`,
"Confirm_Password":`비밀번호 확인`,
"Enter_Confirm_Password":`비밀번호를 한 번 더 입력해주세요`,
"Agree_Terms_and_Condition":`이용 약관 동의`,
"Forgot_Password":`비밀번호를 잊었습니다`,
"Submit":`제출`,
"OTP":`OTP`,
"Enter_OTP":`OTP 입력`,
"Reset_Password":`비밀번호 재설정`,
"Edit_Profile":`프로필 편집`,
"Edit_Phone_Number":`전화번호 편집`,
"Update":`업데이트`,
"Change_Password":`비밀번호 변경`,
"Old_Password":`예전 비밀번호`,
"Enter_Old_Password":`예전 비밀번호를 입력하세요`,
"FAQs":`자주 묻는 질문`,
"Social_Media_Accounts":`소셜 미디어 계정`,
"Settings":`설정`,
"FR8":`FR8`,
"Support_Center":`고객 지원 센터`,
"Terms_And_Conditions":`이용 약관`,
"Privacy_Policy":`개인 정보 보호 정책`,
"Change_Language":`언어 선택`,
"Logout":`로그아웃`,
"Log_out":`로그아웃`,
"Confirm":`확인`,
"Cancel":`취소`,
"Please_Select":`선택해주세요`,
"Warn_Contacts":`경고 연락처`,
"Search_contacts":`연락처 검색`,
"Friend_Requests":`친구 요청`,
"Friend_Request":`친구 요청`,
"My_Posts":`내 게시물`,
"Search_friends":`친구, 터미널, 연락처 검색`,
"My_Freighting_Network":`내 화물 운송 네트워크`,
"My_Network":`내 네트워크`,
"Places":`장소`,
"Friends":`친구`,
"Nearby_Terminals":`근처 터미널`,
"Explore":`살펴보기`,
"Contacts":`연락처`,
"Name_Of_User":`사용자 이름`,
"Add_Friend":`친구 추가`,
"Remove_Friend":`친구 제거`,
"Chat":`채팅`,
"Post_Details":`세부 사항 게시`,
"Live_Streams":`생방송`,
"CreatePost":`게시물 생성`,
"SocialMediaAccounts":`소셜 미디어 계정`,
"Instagram":`인스타그램`,
"Google":`구글`,
"Facebook":`페이스북`,
"Support":`지원`,
"Tittle":`제목`,
"DescriptionText":`설명`,
"Enter_Tittle":`제목을 입력하세요`,
"UserName":`사용자 이름`,
"TerminalDetails":`터미널 세부 사항`,
"Location":`장소`,
"Un_Follow":`팔로우 취소`,
"Follow":`팔로우`,
"Record":`기록`,
"Warn":`경고`,
"ChatHistory":`채팅 이력`,
"TerminalName":`터미널 이름`,
"Terminal":`터미널`,
"English":`영어`,
"Spanish":`스페인어`,
"Driver_Type":`운전자 유형`,
"Select_Driver_Type":`운전자 유형을 선택하세요`,
"Users":`사용자들`,
"Enter_Title":`제목을 편집하세요`,
"Type_Message_Here":`메시지를 여기 입력하세요`,
"Skip":`건너 뛰기`,
"Friend_request_not_found":`친구 요청 찾을 수 없음`,
"Change_Mobile_Number":`휴대폰 번호 변경`,
"resend_Otp":`검증 코드 재전송`,
"post":`게시하다`,
"Friend":`친구`,
"NotificationDetail":`알림 세부정보`,
"noResult":`검색된 결과가 없습니다.`,
"enter_email_alert":`이메일 주소를 입력하세요.`,
"enter_valid_email_alert":`유효한 이메일 주소를 입력하세요.`,
"enter_password_alert":`비밀번호를 입력하세요.`,
"enter_full_name_alert":`성명을 입력하세요.`,
"enter_last_name_alert":`성을 입력하세요.`,
"enter_full_name_aplhanumeric_alert":`성명에 글자와 숫자를 입력하세요.`,
"enter_user_name_alert":`사용자 이름을 입력하세요.`,
"enter_user_name_length_alert":`사용자 이름은 3자 이상이어야 합니다.`,
"enter_user_type_alert":`사용자 유형을 선택하세요.`,
"enter_driver_type_alert":`기사 유형을 선택하세요.`,
"enter_phone_number_alert":`전화번호를 입력하세요.`,
"enter_phone_number_length_alert":`전화번호는 8자리에서 15자리 사이여야 합니다.`,
"enter_Numbers_allowed__phone_alert":`전화번호 필드에는 숫자만 입력 가능합니다.`,
"enter_date_of_birth_alert":`생년월일을 입력하세요.`,
"enter_password_length_alert":`비밀번호는 최소 6자여야 합니다.`,
"enter_confirm_password_alert":`비밀번호를 확인해주세요.`,
"enter_password_not_match_alert":`비밀번호와 확인 비밀번호는 일치해야 합니다.`,
"enter_terms_conditions_alert":`이용 약관에 동의해주세요.`,
"enter_otp_alert":`검증 코드를 입력하세요.`,
"enter__valid_otp_alert":`유효한 검증 코드를 입력하세요.`,
"enter_old_password_alert":`이전 비밀번호를 입력하세요.`,
"enter_old_password_length_alert":`이전 비밀번호는 6자 이상이어야 합니다.`,
"enter_new_password_alert":`새 비밀번호를 입력하세요.`,
"enter_new_password_length_alert":`새 비밀번호는 6자 이상이어야 합니다.`,
"enter_old_cofirm_not_valid_alert":`비밀번호와 확인 비밀번호는 동일해야 합니다.`,
"Stream_stopped_by_user":`라이브 동영상이 다음 사람에 의해 종료되었습니다`,
"Loading_streams":`스트리밍 동영상 불러오는 중`,
"you_are_live_now":`이제 생방송 중입니다.`,
"end_publisher_video":`정말 이 라이브 동영상을 종료하시겠습니까?`,
"logOutAlert":`정말 로그아웃하시겠습니까?`,
"end_publisher_video_successfully":`라이브 동영상이 종료되었습니다.`,
"Alert":`알림`,
"PhoneNumber_required_for_login":`전화번호는 로그인에 필요합니다. 이는 커뮤니티 중재와 저희 사용자 보호를 돕습니다.`,
"Privacy_policy":`계속하심으로써 여러분은 저희의 다음 내용에 동의합니다:`,
"Terms":`이용 약관`,
"Policy":`개인 정보 보호 정책`,
"Why_you_need_my_phone_number":`왜 제 전화번호가 필요한가요`,
"Why_we_need_your_phone_number":`왜 저희가 여러분의 전화번호가 필요한가요`,
"verifyAccount":`계정을 검증하세요`,
"terminalNotFound":`터미널을 찾을 수 없습니다.`,
"Profile":`프로필`,
"App_Settings":`앱 설정`,
"estimatedTime":`예상 시간`,
"estimatedWaitTime":`대기 시간(분)`,
"youHaveLeft":`당신은 떠났다`,
"Citizen_safety_message":`Fr8은 화물 배송 네트워크입니다. 저희는 여러분의 신원 검증 및 커뮤니티 표준 위반자들을 네트워크에서 제거하기 위해 전화번호가 필요합니다.`,
"something_went_wrong":`무엇인가 잘못되었습니다.`,
"please_check_your_internet_connection":`인터넷 연결을 확인해주세요.`,
"startEndAlert":`시작 시간은 종료 시간보다 앞서야 합니다.`,
"addPost":`우편물 추가`,
"permissionTitle': 'You had denied the permission to take photo from library',":`라이브러리에서 사진 촬영 권한을 거부하셨습니다.`,
"permissionBody":`설정 화면에서 이 권한을 허용해주시겠어요?`,
"videoPermissionTitle":`라이브러리에서 동영상 촬영 권한을 거부하셨습니다.`,
"TimeLine_post_not_found":`타임라인 게시물을 찾을 수 없습니다.`,
"Timeline_Posts":`타임라인 게시물`,
"Timeline":`타임라인`,
"trackAtimeLine":`대기 시간을 추적하세요.`,
"Journey":`타임라인을 찾을 수 없습니다.`,
"KM":`킬로미터`,
"Distance_Travelled":`이동 거리`,
"hrs":`시간`,
"secs":`초`,
"mins":`분`,
"time":`시간`,
"wait_time":`평균 대기 시간`,
"Equiment_Photo":`장비 사진`,
"Interchange_Receipt":`교환 영수증`,
"video":`동영상`,
"Share":`공유`,
"start_time":`시작 시간`,
"Report_Post":`게시물 신고`,
"endTime":`종료 시간`,
"openTime":`오픈 시간`,
"closeTime":`마감 시간`,
"distance":`거리`,
"Total_time":`총 시간`,
"Edit_Timeline":`타임라인 수정`,
"messageAlert":`약간의 메시지를 입력하세요.`,
"enterMessage":`메시지를 입력하세요.`,
"Trending_Post":`핫한 게시물`,
"PleaseEnterReportResion":`신고 이유를 입력하세요.`,
"trendingPostNotFound":`핫한 게시물이 없습니다.`,
"Accept":`승인`,
"Reject":`거절`,
"Allow":`허용`,
"Invite":`초대`,
"postNotFound":`우편물을 찾을 수 없었습니다.`,
"Cancel_Friend_Request":`친구 요청 삭제`,
"User_Posts":`사용자 우편물`,
"Notifications":`알림`,
"No_notifications":`알림을 찾을 수 없었습니다.`,
"And":`그리고`,
"deletePostAlert":`정말 이 우편물을 삭제하시겠습니까?`,
"Yes":`예`,
"No":`아니오`,
"enterTitle":`제목을 입력하세요.`,
"pleaseEnterMessage":`메시지를 입력하세요.`,
"Post_Create":`우편물 생성`,
"description":`설명을 입력해주세요.`,
"enterDescription":`설명을 입력해주세요.`,
"descriptionMax":`설명을 최대 1000자 이내로 입력해주세요.`,
"descriptionMin":`설명은 최소 10자여야 합니다.`,
"Preview":`미리보기`,
"messageMax":`메시지는 100자 이내로 입력해주세요.`,
"noUser":`사용자를 찾을 수 없습니다.`,
"New":`신규`,
"No_chat_found":`최근 채팅 기록을 찾을 수 없습니다`,
"Search_Terminal":`터미널 검색`,
"Receipt_Private":`영수증 비공개`,
"Edit":`편집하다`,
"Delete":`삭제`,
"postShareMessage":`게시물을 공유했습니다 게시물을 보려면 아래 링크를 클릭하십시오`,
"postShareMessage2":`게시물을 공유했습니다 게시물을 보려면 아래 링크를 클릭하십시오`,
"shareSubject":`FR8 타임라인 포스트`,
"messageCopy":`메시지 복사됨`,
"avaliable24Hours":`24시간 이용 가능`,
"photo":`사진`,
"photoLibrary":`사진 라이브러리`,
"photoL":`사진`,
"photoLibraryL":`사진 라이브러리`,
"reportUser":`보고서 사용자`,
"reasonOfReport":`신고 이유`,
"reportPostAlert":`이 게시물을 신고하시겠습니까?`,
// "ForegroundServiceTitle":`FR8 앱이 백그라운드에서 위치를 관리하고 있습니다.`,
"ForegroundServiceTitle":`구금 추적기가 실행 중입니다.`,
"Portuguese":`포르투갈`,
"interChangeDelete":`정말로, 교환 영수증을 삭제하시겠습니까?`,
"equipmentDelete":`장비 사진을 삭제하시겠습니까?`,
"deleteVideo":`동영상을 삭제하시겠습니까?`,
"sentAMessage":`메시지를 보냈습니다:`,
"editMessage":`메시지 수정`,
"continue":`계속하다`,
"noContact":`연락처를 찾을 수 없습니다`,
"Driver":`운전사`,
"Owner Operator":`소유자 운영자`,
"Company":`회사`,
"Air Cargo Carrier":`항공화물 운송업체`,
"Exporter":`수출업자`,
"Freight Broker":`화물 중개인`,
"Importer":`수입자`,
"Shipper":`하주`,
"Trucking":`트럭 운송`,
"Warehouse":`창고`,
"Company Driver":`회사 드라이버`,
"OKAY":`괜찮아`,
"installMessage":`안녕하세요 FR8 응용 프로그램을 설치하도록 초대하고 싶습니다.`,
"warned":`경고`,
"WaitingAt":`대기 중`,
"openFr8":`Fr8 앱을 열어 예상 대기 시간을 표시합니다.`,
"day":`일`,
"days":`날`,
"hour":`  시`,
"hours":`  시간`,
"minute":`  분`,
"minutes":`  분`,
"second":`  초`,
"seconds":`  초`,
"openApp":`앱을 열어 상태를 동기화하세요.`,
"openAppBody":`최상의 경험을 위해 FR8 앱이 백그라운드에서 열려 있도록 허용하십시오. 이렇게 하면 타임라인과 터미널 타임스탬프가 정확해집니다.`,
"Comment":`논평`,
"Comments":`코멘트`,
"Like":`좋다`,
"noComment":`댓글이 없습니다`,
"deleteCommentAlert":`댓글을 삭제하시겠습니까?`,
"enterTheComment":`댓글을 입력해주세요.`,
"enterYourComment":`댓글을 입력하세요...`,
"DeeplinkShare":`링크로 공유`,
"Shares":`주식`,
"shareasPost":`게시물 공유`,
"hasShared":`공유했습니다`,
"whatsOnMind":`무슨 생각을 하고 있니?`,
"inGate":`에`,
"outGate":`밖`,
"With":`~와 함께`,
"others":`기타`,
"tagFriends":`친구 태그하기`,
"done":`완료`,
"friendSearch":`친구 검색`,
"checkIN":`체크인`,
"tagUsers":`태그가 지정된 사용자`,
"safeTrip":` 이제 대기 시간을 공유할 수 있습니다. 안전한 여행 되세요!`,
"addLocation":`위치 추가`,
"locationSelect":`위치를 선택해 주세요.`,
"attach":`파일 첨부`,
"selectImage":`게시할 이미지 또는 동영상을 선택하세요.`,
"noPlace":`장소를 찾을 수 없습니다`,
"deleteMedia":`이 미디어를 삭제하시겠습니까?`,
"deleteNotification":`이 알림을 삭제하시겠습니까?`,
"loading":`로드 중…`,
"next":`다음`,
"ttlUserInterminal":`터미널 내부 사용자 수:`,
"members":`내부 구성원`,
"member":`내부 회원`,
"useLocation":`내 위치 사용`,
"firstPermissionTitle":`자동으로 추적되는 활동에 대한 지도를 보려면 FR8이 항상 귀하의 위치를 `,
"noThanks":`고맙지 만 사양 할게`,
"turnOn":`켜다`,
"newVersion":`새로운 버전`,
"versionDescription":`이 앱 버전은 오래되었습니다. 가장 정확하고 놀라운 새 기능을 사용하는 데 도움이 되는 놀라운 새 기능을 잠금 해제하려면 최신 버전으로 업데이트하십시오. 앱이 백그라운드에서 터미널 대기 시간을 계산할 수 있도록 위치 권한을 항상 허용으로 설정하는 것을 잊지 마십시오.`,
"firstPermissionDesc":`FR8은 백그라운드에서 사용자의 위치를 `,
"validUserName":`문자(a-z), 숫자(0-9), 마침표(.) 및 밑줄(_)만 허용됩니다.`,
"user_name_start":`사용자 이름은 마침표(.)로 시작하면 안 됩니다.`,
"onlyNumberAlert":`사용자 이름은 숫자만 포함할 수 없습니다.`,
"user_name_end":`사용자 이름은 마침표(.)로 끝나서는 안 됩니다.`,
"twoDots":`사용자 이름은 한 행에 마침표(.)가 한 개 이상 있어서는 안 됩니다.`,
"Ok":`좋아요`,
"followingTerminal":`수행원`,
"pdfDownload":`PDF 다운로드`,
"timelineCancel":`정말, 타임라인을 취소하시겠습니까?`,
"Truck Stop":`트럭 정류장`,
"Gas Station":`주유소`,
"Weight Station":`웨이트 스테이션`,
"location_name_enter":`위치 이름을 입력하세요.`,
"locationNameLong":`위치 이름은 2자 이상이어야 합니다.`,
"locationAddressLong":`위치 주소는 2자 이상이어야 합니다.`,
"locationAddress":`위치 주소를 입력하세요.`,
"Name":`이름`,
"Hold to Stop":`정지하려면 길게 누르세요`,
"Location Address":`위치 주소`,
"Phone Number":`전화 번호`,
"Add":`추가하다`,
"Category":`범주`,
"backgroundProcess":`타임라인은 다른 화면으로 이동할 때 백그라운드에서 실행됩니다.`,
"NotMoving":`아직 움직이지 않습니까?`,
"oneMinuteLongerAlert":`완료하고 저장하려면 FR8이 위치 변경과 함께 최소 1분 더 긴 활동이 필요합니다.`,
"editPost":`게시물 수정`,
"vedioLimit":`동영상 길이는 최대 30초여야 합니다.`,
"selectCurentLocation":`현재 위치 선택`,
"noCommentYet":`아직 댓글이 없습니다`,
"enterFirstComment":`첫 댓글을 남겨보세요.`,
"App_Share":`애플리케이션 공유`,
"appShareMessage":`FR8 앱을 공유했습니다. 아래 링크를 클릭하면 모바일 애플리케이션과 오늘의 현재 대기 시간을 볼 수 있습니다.`,
"appShareMessage2":`FR8 \n 아래 링크를 클릭하면 모바일 애플리케이션과 오늘의 현재 대기 시간을 볼 수 있습니다.`,
"deleteCommentReplyAlert":`이 댓글 답글을 삭제하시겠습니까?`,
"enter_first_name_length_alert":`이름은 3자 이상이어야 합니다.`,
"enter_last_name_length_alert":`성은 3자 이상이어야 합니다.`,
"location_Setting":`위치 설정`,
"postlikeHeading":`포스트를 좋아하는 사람들`,
"commentLikeHeading":`댓글을 좋아하는 사람들`,
"viewProfile":`프로필보기`,
"shareListHeading":`게시물을 공유한 사람들`,
"Reply":`회신하다`,
"Reply to":`답장하다`,
"Dislike":`싫어함`,
"Smile":`웃다`,
"Angry":`화난`,
"Rolling Eyes":`눈을 굴리다`,
"Thinking":`생각`,
"Stop":`중지`,
"switchFrom":`에서 전환하여 정확한 안전 알림을 수신합니다.`,
"Always Allow":`항상 허용`,
"While Using":`사용 중`,
"Ask next time":`다음에 물어봐`,
"Never":`절대`,
"Manage location Settings":`위치 설정 관리`,
"Italian":`이탈리아 사람`,
"Chinese":`중국어 간체(북경어)`,
"Hindi":`힌디 어`,
"Filipino":`필리핀`,
"Vietnamese":`베트남어`,
"Arabic":`아라비아 말`,
"French":`프랑스 국민`,
"Korean":`한국인`,
"Russian":`러시아인`,
"Bengali":`벵골 사람`,
"German":`독일 사람`,  
regionlNotFound: 'Region not found.',
Region:"Region",
in: '~에',
posts: '게시물',

"All":"모두",
"saveToPhone":"전화에 저장",
"ADD":"추가하다",
"deleteAccount":"계정 삭제",
"deleteAccountAlert":"정말, 계정을 삭제하시겠습니까?",
"replyWrite":"대답을 적다...",
"Camera":"카메라",
"Image Gallery":"이미지 갤러리",
"regionlNotFound":"지역을 찾을 수 없습니다.",
"Region":"지역",
"regionSelectAlert":"사용자는 최대 3개의 지역을 선택할 수 있습니다.",

"CALL":"전화",
"ADDRESS":"주소",
"MIN":"분",
"About":"에 대한",
"Overview":"개요",
"Review":"검토",
"Timelines":"타임라인",
"Rate & Review":"평가 및 검토",
"ratings":"평가 및 검토",
"Write Your Review":"리뷰 작성",
"Just now":"방금",
'waitTimeIndicator':`대기 시간 표시기`,
currentWaitTime:"현재 평균 대기 시간",

};

module.exports = {
  constants
};
