import {imageBaseUrl} from '../Config/index'
const constants = {
   // TermsUrl:"http://18.205.207.176:3000/public/pdf/Fr8_App_Terms_Of_Use.pdf",
   TermsUrl:"https://www.fr8.ai/terms",
   // TermsUrl: imageBaseUrl +"public/pdf/Fr8_App_Terms_Of_Use.pdf",
   // PrivacyUrl:"http://18.205.207.176:3000/public/pdf/Fr8_App_Privacy_Policy.pdf",
   PrivacyUrl:"https://www.fr8.ai/privacy",
   // PrivacyUrl: imageBaseUrl + "public/pdf/Fr8_App_Privacy_Policy.pdf",
// "Email":`Email`,
// "Enter_Email":``,
// "Password":`Mật khẩu`,
// "Enter_Password":`Nhập Mật Khẩu`,
// "Enter_New_Password":`Nhập Mật Khẩu Mới`,
// "Forgot_Your_Password":`Quên Mật Khẩu Của Bạn?`,
// "Login":`Đăng nhập`,
// "Doesnt_have_an_account":`Không Có Tài Khoản?`,
// "Sign_up":`Đăng ký`,
// "Enter_Name":`Nhập tên`,
// "Enter_first_Name":`Nhập tên đầu tiên`,
// "Enter_last_Name":`Nhập họ`,
// "Enter_Your_Phone_Number":`Nhập số điện thoại của bạn`,
// "Enter_Six_Digit_Verification_Code":`Nhập mã xác minh 6 chữ số`,
// "Resend_Verification_Code":`Gửi lại mã xác minh`,
// "Contact_Permission":`Vui lòng cho phép truy cập liên hệ để có thể giữ an toàn cho bạn bè của bạn`,
// "Register":`Đăng ký`,
// "Full_Name":`Họ và tên`,
// "Enter_Full_Name":`Nhập Họ và Tên`,
// "Username":`Tên đăng nhập`,
// "Enter_Username":`Nhập tên đăng nhập`,
// "Email_Address":`Địa chỉ email`,
// "Enter_Email_Address":`Nhập địa chỉ email`,
// "User_Type":`Kiểu người dùng`,
// "Select_User_Type":`Chọn người dùng`,
// "Phone_Number":`Số điện thoại`,
// "Enter_Phone_Number":`Nhập số điện thoại`,
// "Date_Of_Birth":`Ngày sinh`,
// "Select_Date_Of_Birth":`Chọn ngày sinh`,
// "Confirm_Password":`Xác nhận mật khẩu`,
// "Enter_Confirm_Password":`Nhập xác nhận mật khẩu`,
// "Agree_Terms_and_Condition":`Đồng ý Điều khoản & Điều kiện`,
// "Forgot_Password":`Quên mật khẩu`,
// "Submit":`Nộp`,
// "OTP":`OTP`,
// "Enter_OTP":`Nhập TOP`,
// "Reset_Password":`Đặt lại mật khẩu`,
// "Edit_Profile":`Chỉnh sửa hồ sơ`,
// "Edit_Phone_Number":`Chỉnh sửa số điện thoại`,
// "Update":`Cập nhật`,
// "Change_Password":`Đổi mật khẩu`,
// "Old_Password":`Mật khẩu cũ`,
// "Enter_Old_Password":`Nhập mật khẩu cũ`,
// "FAQs":`Hỏi đáp thường gặp`,
// "Social_Media_Accounts":`Tài khoản mạng xã hội`,
// "Settings":`Cài đặt`,
// "FR8":`FR8`,
// "Support_Center":`Trung tâm hỗ trợ`,
// "Terms_And_Conditions":`Điều khoản & Điều kiện`,
// "Privacy_Policy":`Chính Sách Bảo Mật`,
// "Change_Language":`Thay đổi ngôn ngữ`,
// "Logout":`Đăng xuất`,
// "Log_out":`Đăng xuất`,
// "Confirm":`Xác nhận`,
// "Cancel":`Huỷ bỏ`,
// "Please_Select":`Vui lòng chọn`,
// "Warn_Contacts":`Liên hệ khẩn cấp`,
// "Search_contacts":`Tìm liên lạc`,
// "Friend_Requests":`Yêu cầu kết bạn`,
// "Friend_Request":`Yêu cầu kết bạn`,
// "My_Posts":`Bài đăng của tôi`,
// "Search_friends":`Tìm bạn bè, trạm, liên hệ`,
// "My_Freighting_Network":`Mạng lưới vận tải hàng hóa của tôi`,
// "My_Network":`Mạng lưới của tôi`,
// "Places":`Nơi chốn`,
// "Friends":`Bạn bè`,
// "Nearby_Terminals":`Trạm gần đây`,
// "Explore":`Khám phá`,
// "Contacts":`Liên lạc`,
// "Name_Of_User":`Tên người dùng`,
// "Add_Friend":`Thêm bạn`,
// "Remove_Friend":`Xóa bạn bè`,
// "Chat":`Trò chuyện`,
// "Post_Details":`Đăng chi tiết`,
// "Live_Streams":`Live Streams`,
// "CreatePost":`Tạo bài đăng`,
// "SocialMediaAccounts":`Tài khoản mạng xã hội`,
// "Instagram":`Instagram`,
// "Google":`Google`,
// "Facebook":`Facebook`,
// "Support":`Hỗ trợ`,
// "Tittle":`Tựa`,
// "DescriptionText":`Sự miêu tả`,
// "Enter_Tittle":`Nhập tựa`,
// "UserName":`Tên đăng nhập`,
// "TerminalDetails":`Chi tiết về trạm`,
// "Location":`Vị trí`,
// "Un_Follow":`Hủy theo dõi`,
// "Follow":`Theo dõi`,
// "Record":`Ghi chú`,
// "Warn":`Khẩn cấp`,
// "ChatHistory":`Lịch sử chat`,
// "TerminalName":`Tên trạm`,
// "Terminal":`Trạm`,
// "English":`Tiếng Anh`,
// "Spanish":`Tiếng Tây Ban Nha`,
// "Driver_Type":`Kiểu tài xế`,
// "Select_Driver_Type":`Chọn kiểu tài xế`,
// "Users":`Người dùng`,
// "Enter_Title":`Nhập tựa`,
// "Type_Message_Here":`Nhập tin nhắn ở đây`,
// "Skip":`Bỏ qua`,
// "Friend_request_not_found":`Không tìm thấy yêu cầu kết bạn.`,
// "Change_Mobile_Number":`Thay đổi số điện thoại di động`,
// "resend_Otp":`Gửi lại mã xác minh`,
// "post":``,
// "Friend":``,
// "NotificationDetail":`Chi tiết thông báo`,
// "noResult":`Không có kết quả nào.`,
// "enter_email_alert":`Vui lòng nhập địa chỉ email.`,
// "enter_valid_email_alert":`Vui lòng nhập địa chỉ email hợp lệ.`,
// "enter_password_alert":`Xin vui lòng nhập mật khẩu.`,
// "enter_full_name_alert":`Vui lòng nhập họ tên đầy đủ.`,
// "enter_last_name_alert":`Vui lòng nhập họ.`,
// "enter_full_name_aplhanumeric_alert":`Vui lòng nhập họ tên đầy đủ bằng ký tự chữ`,
// "enter_user_name_alert":`Vui lòng nhập tên đăng nhập`,
// "enter_user_name_length_alert":`Tên người dùng phải dài ít nhất 3 ký tự.`,
// "enter_user_type_alert":`Vui lòng chọn kiểu Người dùng.`,
// "enter_driver_type_alert":`Vui lòng chọn kiểu Tài xế.`,
// "enter_phone_number_alert":`Vui lòng nhập số điện thoại.`,
// "enter_phone_number_length_alert":`Số điện thoại phải có 8 đến 15 số.`,
// "enter_Numbers_allowed__phone_alert":`Trường số điện thoại chỉ nhận ký tự số.`,
// "enter_date_of_birth_alert":`Vui lòng chọn ngày sinh.`,
// "enter_password_length_alert":`Mật khẩu phải có ít nhất 6 ký tự.`,
// "enter_confirm_password_alert":`Vui lòng nhập mật khẩu xác nhận.`,
// "enter_password_not_match_alert":`Mật khẩu và Xác nhận Mật khẩu phải giống nhau.`,
// "enter_terms_conditions_alert":`enter_terms_conditions_alert: Vui lòng đồng ý Điều khoản & Điều kiện.",`,
// "enter_otp_alert":`Vui lòng nhập mã xác minh.`,
// "enter__valid_otp_alert":`Vui lòng nhập mã xác minh hợp lệ.`,
// "enter_old_password_alert":`Vui lòng nhập mật khẩu cũ.`,
// "enter_old_password_length_alert":`Mật khẩu cũ phải có ít nhất 6 ký tự.`,
// "enter_new_password_alert":`Vui lòng nhập mật khẩu mới.`,
// "enter_new_password_length_alert":`Mật khẩu mới phải có ít nhất 6 ký tự.`,
// "enter_old_cofirm_not_valid_alert":`Mật khẩu cũ và mật khẩu xác nhận phải giống nhau.`,
// "Stream_stopped_by_user":`Video trực tiếp kết thúc bởi`,
// "Loading_streams":`Đang tải stream`,
// "you_are_live_now":`Bạn đang phát trực tiếp.`,
// "end_publisher_video":`Bạn có chắc chắn muốn kết thúc video này không?`,
// "logOutAlert":`Bạn có chắc chắn muốn đăng xuất không?`,
// "end_publisher_video_successfully":`Video trực tiếp kết thúc.`,
// "Alert":`Cảnh báo`,
// "PhoneNumber_required_for_login":`Cần có số điện thoại để đăng nhập. Điều này giúp chúng tôi quản lý cộng đồng và bảo vệ người dùng.`,
// "Privacy_policy":`BẰNG CÁCH TIẾP TỤC BẠN ĐỒNG Ý VỚI`,
// "Terms":`ĐIỀU KHOẢN SỬ DỤNG`,
// "Policy":`CHÍNH SÁCH BẢO MẬT`,
// "Why_you_need_my_phone_number":`TẠI SAO CÁC BẠN CẦN SỐ ĐIỆN THOẠI CỦA TÔI`,
// "Why_we_need_your_phone_number":`TẠI SAO CHÚNG TÔI CẦN SỐ ĐIỆN THOẠI CỦA BẠN`,
// "verifyAccount":`XÁC MINH TÀI KHOẢN`,
// "terminalNotFound":`Không tìm ra trạm`,
// "Profile":`Hồ sơ`,
// "App_Settings":`Cài đặt ứng dụng`,
// "estimatedTime":`Thời gian dự kiến`,
// "estimatedWaitTime":`Phút chờ đợi`,
// "youHaveLeft":`Bạn đã rời đi`,
// "Citizen_safety_message":`Fr8 là mạng vận chuyển. Chúng tôi yêu cầu phải có số điện thoại để xác minh danh tính của bạn và để đảm bảo khi thích hợp sẽ loại đi những ai vi phạm quy chuẩn cộng đồng của chúng tôi.`,
// "something_went_wrong":`Có lỗi xảy ra.`,
// "please_check_your_internet_connection":`Vui lòng kiểm tra kết nối internet của bạn.`,
// "startEndAlert":`Thời gian bắt đầu phải sớm hơn thời gian kết thúc.`,
// "addPost":`Thêm bài đăng`,
// "permissionTitle': 'You had denied the permission to take photo from library',":`Bạn đã từ chối cấp quyền truy cập thư viện ảnh.`,
// "permissionBody":`Bạn muốn cấp quyền truy cập, hãy cấp phép trong mục cài đặt.`,
// "videoPermissionTitle":`Bạn đã từ chối cấp quyền truy cập thư viện ảnh.`,
// "TimeLine_post_not_found":`Không tìm thấy bài đăng trên Dòng Thời Gian`,
// "Timeline_Posts":`Bài đăng Dòng Thời Gian`,
// "Timeline":`Dòng Thời Gian`,
// "trackAtimeLine":`Theo dõi thời gian chờ`,
// "Journey":`Không tìm thấy dòng thời gian.`,
// "KM":`km`,
// "Distance_Travelled":`Khoảng cách di chuyển`,
// "hrs":`giờ`,
// "secs":`giây`,
// "mins":`phút`,
// "time":`Thời gian`,
// "wait_time":`Thời gian chờ trung bình`,
// "Equiment_Photo":`Trang bị ảnh`,
// "Interchange_Receipt":`Hóa đơn thay đổi`,
// "video":`Video`,
// "Share":`Chia sẻ`,
// "start_time":`Thời gian bắt đầu`,
// "Report_Post":`Báo cáo về bài đăng`,
// "endTime":`Thời gian kết thúc`,
// "openTime":``,
// "closeTime":``,
// "distance":`Khoảng cách`,
// "Total_time":`Tổng thời gian`,
// "Edit_Timeline":`Chỉnh sửa Dòng thời gian`,
// "messageAlert":`Vui lòng nhập nội dung`,
// "enterMessage":`Nhập tin nhắn...`,
// "Trending_Post":`Bài viết đang là xu hướng`,
// "PleaseEnterReportResion":`Vui lòng nhập lý do báo cáo`,
// "trendingPostNotFound":`Không tìm thấy xu hướng.`,
// "Accept":`Chấp nhận`,
// "Reject":`Từ chối`,
// "Allow":`Cho phép`,
// "Invite":`Mời`,
// "postNotFound":`Không tìm thấy bài đăng.`,
// "Cancel_Friend_Request":`Hủy yêu cầu kết bạn`,
// "User_Posts":`Bài đăng của người dùng`,
// "Notifications":`Thông báo`,
// "No_notifications":`Không tìm thấy thông báo.`,
// "And":`VÀ`,
// "deletePostAlert":`Bạn có chắc chắn muốn xóa bài viết này không?`,
// "Yes":`Có.`,
// "No":`Không`,
// "enterTitle":`Vui lòng nhập tiêu đề.`,
// "pleaseEnterMessage":`Vui lòng nhập tin nhắn.`,
// "Post_Create":`Tạo bài đăng`,
// "description":`Nhập mô tả của bạn ...`,
// "enterDescription":`Vui lòng nhập mô tả.`,
// "descriptionMax":`Vui lòng nhập mô tả ít hơn 1.000 ký tự.`,
// "descriptionMin":`Mô tả phải dài ít nhất 10 ký tự.`,
// "Preview":`Xem trước`,
// "messageMax":`Vui lòng nhập tin nhắn ít hơn 1.000 ký tự.`,
// "noUser":`Không tìm thấy người dùng.`,
// "New":`Mới`,
// "No_chat_found":`Không tìm thấy cuộc trò chuyện gần đây`,
// "Search_Terminal":`Tìm kiếm Trạm`,
// "Receipt_Private":`Biên nhận Riêng tư`,
// "Edit":``,
// "Delete":``,
// "postShareMessage":`đã chia sẻ bài viết Nhấp vào liên kết dưới đây để xem bài viết`,
// "shareSubject":`FR8 TimeLine Post`,
// "messageCopy":`Đã sao chép tin nhắn`,
// "avaliable24Hours":`Có sẵn 24 giờ`,
// "photo":``,
// "photoLibrary":``,
// "photoL":``,
// "photoLibraryL":``,
// "reportUser":`Báo cáo người dùng`,
// "reasonOfReport":`Lý do Báo cáo`,
// "reportPostAlert":`Bạn có chắc chắn muốn báo cáo bài này?`,
// "ForegroundServiceTitle":`Ứng dụng FR8 đang quản lý vị trí của bạn trong nền`,
// "Portuguese":`Bồ Đào Nha`,
// "interChangeDelete":`Bạn có chắc chắn muốn xóa Biên lai trao đổi không?`,
// "equipmentDelete":`Bạn có chắc chắn muốn xóa ảnh thiết bị không?`,
// "deleteVideo":`Bạn có chắc chắn muốn xóa video không?`,
// "sentAMessage":`đã gửi một tin nhắn:`,
// "editMessage":`Chỉnh sửa tin nhắn`,
// "continue":`Tiếp tục`,
// "noContact":`Không tìm thấy địa chỉ liên hệ`,
// "Driver":``,
// "Owner Operator":``,
// "Company":``,
// "Air Cargo Carrier":``,
// "Exporter":``,
// "Freight Broker":``,
// "Importer":``,
// "Shipper":``,
// "Trucking":``,
// "Warehouse":``,
// "Company Driver":``,
// "OKAY":`ĐƯỢC CHỨ`,
// "installMessage":`Xin chào FR8, bạn muốn mời cài đặt ứng dụng.`,
// "warned":`cảnh báo`,
// "WaitingAt":`Đang đợi lúc`,
// "openFr8":`Mở ứng dụng Fr8 để hiển thị thời gian chờ ước tính của bạn.`,
// "day":`ngày`,
// "days":`ngày`,
// "hour":``,
// "hours":``,
// "minute":``,
// "minutes":``,
// "second":``,
// "seconds":``,
// "openApp":`Mở ứng dụng để đồng bộ trạng thái của bạn`,
// "openAppBody":`Để có trải nghiệm tốt nhất, hãy cho phép Ứng dụng FR8 tiếp tục mở trong nền. Điều này giữ cho dòng thời gian và dấu thời gian đầu cuối của bạn luôn chính xác.`,
// "Comment":`Bình luận`,
// "Comments":`Bình luận`,
// "Like":`Thích`,
// "noComment":`Không tìm thấy bình luận`,
// "deleteCommentAlert":`Bạn có chắc chắn muốn xóa nhận xét không?`,
// "enterTheComment":`Vui lòng nhập bình luận.`,
// "enterYourComment":`Nhập bình luận của bạn ...`,
// "DeeplinkShare":`Chia sẻ dưới dạng liên kết`,
// "Shares":`Chia sẻ`,
// "shareasPost":`Chia sẻ bài đăng`,
// "hasShared":`đã chia sẻ`,
// "whatsOnMind":`Bạn đang nghĩ gì vậy?`,
// "inGate":`Trong`,
// "outGate":`Ngoài`,
// "With":`với`,
// "others":`khác`,
// "tagFriends":`Gắn thẻ bạn bè`,
// "done":`Xong`,
// "friendSearch":`Tìm bạn`,
// "checkIN":`Đăng ký vào`,
// "tagUsers":`Người dùng được gắn thẻ`,
// "safeTrip":` Bây giờ bạn có thể chia sẻ thời gian chờ đợi của mình. Chúc bạn có một chuyến đi an toàn!`,
// "addLocation":`Thêm vị trí`,
// "locationSelect":`Vui lòng chọn vị trí.`,
// "attach":`Đính kèm tệp`,
// "selectImage":`Vui lòng chọn hình ảnh hoặc video để đăng.`,
// "noPlace":`Không tìm thấy Địa điểm`,
// "deleteMedia":`Bạn có chắc chắn muốn xóa phương tiện này không?`,
// "deleteNotification":`Bạn có chắc chắn muốn xóa thông báo này không?`,
// "loading":`Đang tải…`,
// "next":`Kế tiếp`,
// "ttlUserInterminal":``,
// "members":`Các thành viên bên trong`,
// "member":`Thành viên bên trong`,
// "useLocation":`Sử dụng vị trí của bạn`,
// "firstPermissionTitle":`Để xem bản đồ cho các hoạt động được theo dõi tự động, hãy cho phép FR8 sử dụng vị trí của bạn mọi lúc.`,
// "noThanks":`Không, cám ơn`,
// "turnOn":`Bật`,
// "newVersion":`Phiên bản mới`,
// "versionDescription":`Phiên bản ứng dụng này đã lỗi thời, vui lòng cập nhật lên phiên bản mới nhất để mở khóa các tính năng mới tuyệt vời giúp bạn có được các tính năng mới chính xác và tuyệt vời nhất. Đừng quên đặt quyền vị trí thành Luôn cho phép để ứng dụng tính toán Thời gian chờ của thiết bị đầu cuối cho bạn trong nền.`,
// "firstPermissionDesc":`FR8 sẽ sử dụng vị trí của bạn trong nền để cho phép bạn ghi lại chính xác các chuyến đi của bạn trong các nhà ga và tính toán thời gian chờ và thời gian.`,
// "validUserName":`Chỉ cho phép các chữ cái (a-z), số (0-9), dấu chấm (.) Và dấu gạch dưới (_).`,
// "user_name_start":`Tên người dùng không được bắt đầu bằng dấu chấm (.)`,
// "onlyNumberAlert":`Tên người dùng không thể chỉ chứa số.`,
// "user_name_end":`Tên người dùng không được kết thúc bằng dấu chấm (.)`,
// "twoDots":`Tên người dùng không được có nhiều dấu chấm (.) Liên tiếp.`,
// "Ok":``,
// "followingTerminal":``,
// "pdfDownload":``,
// "timelineCancel":`Bạn có chắc chắn muốn hủy dòng thời gian không?`,
// "Truck Stop":`Bến đỗ xe tải`,
// "Gas Station":`Trạm xăng`,
// "Weight Station":`Trạm cân`,
// "location_name_enter":`Vui lòng nhập tên Vị trí.`,
// "locationNameLong":`Tên vị trí phải dài ít nhất 2 ký tự.`,
// "locationAddressLong":`Địa chỉ vị trí phải dài ít nhất 2 ký tự.`,
// "locationAddress":`Vui lòng nhập địa chỉ vị trí.`,
// "Name":`Tên`,
// "Hold to Stop":`Giữ để dừng`,
// "Location Address":`Địa chỉ Vị trí`,
// "Phone Number":`Số điện thoại`,
// "Add":`cộng`,
// "Category":``,
// "backgroundProcess":``,
// "NotMoving":``,
// "oneMinuteLongerAlert":``,
// "editPost":``,
// "vedioLimit":``,
// "selectCurentLocation":``,
// "noCommentYet":`Chưa có bình luận nào`,
// "enterFirstComment":`Hãy trở thành người đầu tiên bình luận.`,
// "App_Share":`Chia sẻ ứng dụng`,
// "appShareMessage":`đã chia sẻ ứng dụng FR8. Nhấp vào liên kết bên dưới để xem ứng dụng di động và xem thời gian chờ hiện tại ngay hôm nay.`,
// "deleteCommentReplyAlert":`Bạn có chắc chắn muốn xóa câu trả lời bình luận này không?`,
// "enter_first_name_length_alert":`Tên phải dài ít nhất 3 ký tự.`,
// "enter_last_name_length_alert":`Họ phải dài ít nhất 3 ký tự.`,
// "location_Setting":`Cài đặt vị trí`,
// "postlikeHeading":`Những người thích bài đăng`,
// "commentLikeHeading":`Những người thích bình luận`,
// "viewProfile":`Xem lí lịch`,
// "shareListHeading":`Những người đã chia sẻ bài đăng`,
// "Reply":`Hồi đáp`,
// "Reply to":`Trả lời`,
// "Dislike":`Không thích`,
// "Smile":`Mỉm cười`,
// "Angry":`Tức giận`,
// "Rolling Eyes":`Tròn mắt`,
// "Thinking":`tư duy`,
// "Stop":`Ngừng lại`,
// "switchFrom":`Nhận thông báo an toàn chính xác bằng cách chuyển từ`,
// "Always Allow":`Luôn luôn đồng ý`,
// "While Using":`Trong khi sử dụng`,
// "Ask next time":`Hỏi lần sau`,
// "Never":`Không bao giờ`,
// "Manage location Settings":``,
// "Italian":`người Ý`,
// "Chinese":`Tiếng Trung giản thể (Quan thoại),`,
// "Hindi":`Tiếng Hindi`,
// " Filipino :":` Người Phi Luật Tân`,
// "Vietnamese":`Tiếng Việt`,
// "Arabic":`tiếng Ả Rập`,
// "French":`người Pháp`,
// "Korean":`Hàn Quốc`,
// "Russian":`tiếng Nga`,
// " Bengali ":` Tiếng Bengali`,
// "German":`tiếng Đức`,
"Email":`Email`,
"Enter_Email":`Nhập Email`,
"Password":`Mật khẩu`,
"Enter_Password":`Nhập Mật Khẩu`,
"Enter_New_Password":`Nhập Mật Khẩu Mới`,
"Forgot_Your_Password":`Quên Mật Khẩu Của Bạn?`,
"Login":`Đăng nhập`,
"Doesnt_have_an_account":`Không Có Tài Khoản?`,
"Sign_up":`Đăng ký`,
"Enter_Name":`Nhập tên`,
"Enter_first_Name":`Nhập tên đầu tiên`,
"Enter_last_Name":`Nhập họ`,
"Enter_Your_Phone_Number":`Nhập số điện thoại của bạn`,
"Enter_Six_Digit_Verification_Code":`Nhập mã xác minh 6 chữ số`,
"Resend_Verification_Code":`Gửi lại mã xác minh`,
"Contact_Permission":`Vui lòng cho phép truy cập liên hệ để có thể giữ an toàn cho bạn bè của bạn`,
"Register":`Đăng ký`,
"Full_Name":`Họ và tên`,
"Enter_Full_Name":`Nhập Họ và Tên`,
"Username":`Tên đăng nhập`,
"Enter_Username":`Nhập tên đăng nhập`,
"Email_Address":`Địa chỉ email`,
"Enter_Email_Address":`Nhập địa chỉ email`,
"User_Type":`Kiểu người dùng`,
"Select_User_Type":`Chọn người dùng`,
"Phone_Number":`Số điện thoại`,
"Enter_Phone_Number":`Nhập số điện thoại`,
"Date_Of_Birth":`Ngày sinh`,
"Select_Date_Of_Birth":`Chọn ngày sinh`,
"Confirm_Password":`Xác nhận mật khẩu`,
"Enter_Confirm_Password":`Nhập xác nhận mật khẩu`,
"Agree_Terms_and_Condition":`Đồng ý Điều khoản & Điều kiện`,
"Forgot_Password":`Quên mật khẩu`,
"Submit":`Nộp`,
"OTP":`OTP`,
"Enter_OTP":`Nhập TOP`,
"Reset_Password":`Đặt lại mật khẩu`,
"Edit_Profile":`Chỉnh sửa hồ sơ`,
"Edit_Phone_Number":`Chỉnh sửa số điện thoại`,
"Update":`Cập nhật`,
"Change_Password":`Đổi mật khẩu`,
"Old_Password":`Mật khẩu cũ`,
"Enter_Old_Password":`Nhập mật khẩu cũ`,
"FAQs":`Hỏi đáp thường gặp`,
"Social_Media_Accounts":`Tài khoản mạng xã hội`,
"Settings":`Cài đặt`,
"FR8":`FR8`,
"Support_Center":`Trung tâm hỗ trợ`,
"Terms_And_Conditions":`Điều khoản & Điều kiện`,
"Privacy_Policy":`Chính Sách Bảo Mật`,
"Change_Language":`Thay đổi ngôn ngữ`,
"Logout":`Đăng xuất`,
"Log_out":`Đăng xuất`,
"Confirm":`Xác nhận`,
"Cancel":`Huỷ bỏ`,
"Please_Select":`Vui lòng chọn`,
"Warn_Contacts":`Liên hệ khẩn cấp`,
"Search_contacts":`Tìm liên lạc`,
"Friend_Requests":`Yêu cầu kết bạn`,
"Friend_Request":`Yêu cầu kết bạn`,
"My_Posts":`Bài đăng của tôi`,
"Search_friends":`Tìm bạn bè, trạm, liên hệ`,
"My_Freighting_Network":`Mạng lưới vận tải hàng hóa của tôi`,
"My_Network":`Mạng lưới của tôi`,
"Places":`Nơi chốn`,
"Friends":`Bạn bè`,
"Nearby_Terminals":`Trạm gần đây`,
"Explore":`Khám phá`,
"Contacts":`Liên lạc`,
"Name_Of_User":`Tên người dùng`,
"Add_Friend":`Thêm bạn`,
"Remove_Friend":`Xóa bạn bè`,
"Chat":`Trò chuyện`,
"Post_Details":`Đăng chi tiết`,
"Live_Streams":`Live Streams`,
"CreatePost":`Tạo bài đăng`,
"SocialMediaAccounts":`Tài khoản mạng xã hội`,
"Instagram":`Instagram`,
"Google":`Google`,
"Facebook":`Facebook`,
"Support":`Hỗ trợ`,
"Tittle":`Tựa`,
"DescriptionText":`Sự miêu tả`,
"Enter_Tittle":`Nhập tựa`,
"UserName":`Tên đăng nhập`,
"TerminalDetails":`Chi tiết về trạm`,
"Location":`Vị trí`,
"Un_Follow":`Hủy theo dõi`,
"Follow":`Theo dõi`,
"Record":`Ghi chú`,
"Warn":`Khẩn cấp`,
"ChatHistory":`Lịch sử chat`,
"TerminalName":`Tên trạm`,
"Terminal":`Trạm`,
"English":`Tiếng Anh`,
"Spanish":`Tiếng Tây Ban Nha`,
"Driver_Type":`Kiểu tài xế`,
"Select_Driver_Type":`Chọn kiểu tài xế`,
"Users":`Người dùng`,
"Enter_Title":`Nhập tựa`,
"Type_Message_Here":`Nhập tin nhắn ở đây`,
"Skip":`Bỏ qua`,
"Friend_request_not_found":`Không tìm thấy yêu cầu kết bạn.`,
"Change_Mobile_Number":`Thay đổi số điện thoại di động`,
"resend_Otp":`Gửi lại mã xác minh`,
"post":`Bưu kiện`,
"Friend":`Bạn bè`,
"NotificationDetail":`Chi tiết thông báo`,
"noResult":`Không có kết quả nào.`,
"enter_email_alert":`Vui lòng nhập địa chỉ email.`,
"enter_valid_email_alert":`Vui lòng nhập địa chỉ email hợp lệ.`,
"enter_password_alert":`Xin vui lòng nhập mật khẩu.`,
"enter_full_name_alert":`Vui lòng nhập họ tên đầy đủ.`,
"enter_last_name_alert":`Vui lòng nhập họ.`,
"enter_full_name_aplhanumeric_alert":`Vui lòng nhập họ tên đầy đủ bằng ký tự chữ`,
"enter_user_name_alert":`Vui lòng nhập tên đăng nhập`,
"enter_user_name_length_alert":`Tên người dùng phải dài ít nhất 3 ký tự.`,
"enter_user_type_alert":`Vui lòng chọn kiểu Người dùng.`,
"enter_driver_type_alert":`Vui lòng chọn kiểu Tài xế.`,
"enter_phone_number_alert":`Vui lòng nhập số điện thoại.`,
"enter_phone_number_length_alert":`Số điện thoại phải có 8 đến 15 số.`,
"enter_Numbers_allowed__phone_alert":`Trường số điện thoại chỉ nhận ký tự số.`,
"enter_date_of_birth_alert":`Vui lòng chọn ngày sinh.`,
"enter_password_length_alert":`Mật khẩu phải có ít nhất 6 ký tự.`,
"enter_confirm_password_alert":`Vui lòng nhập mật khẩu xác nhận.`,
"enter_password_not_match_alert":`Mật khẩu và Xác nhận Mật khẩu phải giống nhau.`,
"enter_terms_conditions_alert":`enter_terms_conditions_alert: Vui lòng đồng ý Điều khoản & Điều kiện.",`,
"enter_otp_alert":`Vui lòng nhập mã xác minh.`,
"enter__valid_otp_alert":`Vui lòng nhập mã xác minh hợp lệ.`,
"enter_old_password_alert":`Vui lòng nhập mật khẩu cũ.`,
"enter_old_password_length_alert":`Mật khẩu cũ phải có ít nhất 6 ký tự.`,
"enter_new_password_alert":`Vui lòng nhập mật khẩu mới.`,
"enter_new_password_length_alert":`Mật khẩu mới phải có ít nhất 6 ký tự.`,
"enter_old_cofirm_not_valid_alert":`Mật khẩu cũ và mật khẩu xác nhận phải giống nhau.`,
"Stream_stopped_by_user":`Video trực tiếp kết thúc bởi`,
"Loading_streams":`Đang tải stream`,
"you_are_live_now":`Bạn đang phát trực tiếp.`,
"end_publisher_video":`Bạn có chắc chắn muốn kết thúc video này không?`,
"logOutAlert":`Bạn có chắc chắn muốn đăng xuất không?`,
"end_publisher_video_successfully":`Video trực tiếp kết thúc.`,
"Alert":`Cảnh báo`,
"PhoneNumber_required_for_login":`Cần có số điện thoại để đăng nhập. Điều này giúp chúng tôi quản lý cộng đồng và bảo vệ người dùng.`,
"Privacy_policy":`BẰNG CÁCH TIẾP TỤC BẠN ĐỒNG Ý VỚI`,
"Terms":`ĐIỀU KHOẢN SỬ DỤNG`,
"Policy":`CHÍNH SÁCH BẢO MẬT`,
"Why_you_need_my_phone_number":`TẠI SAO CÁC BẠN CẦN SỐ ĐIỆN THOẠI CỦA TÔI`,
"Why_we_need_your_phone_number":`TẠI SAO CHÚNG TÔI CẦN SỐ ĐIỆN THOẠI CỦA BẠN`,
"verifyAccount":`XÁC MINH TÀI KHOẢN`,
"terminalNotFound":`Không tìm ra trạm`,
"Profile":`Hồ sơ`,
"App_Settings":`Cài đặt ứng dụng`,
"estimatedTime":`Thời gian dự kiến`,
"estimatedWaitTime":`Phút chờ đợi`,
"youHaveLeft":`Bạn đã rời đi`,
"Citizen_safety_message":`Fr8 là mạng vận chuyển. Chúng tôi yêu cầu phải có số điện thoại để xác minh danh tính của bạn và để đảm bảo khi thích hợp sẽ loại đi những ai vi phạm quy chuẩn cộng đồng của chúng tôi.`,
"something_went_wrong":`Có lỗi xảy ra.`,
"please_check_your_internet_connection":`Vui lòng kiểm tra kết nối internet của bạn.`,
"startEndAlert":`Thời gian bắt đầu phải sớm hơn thời gian kết thúc.`,
"addPost":`Thêm bài đăng`,
"permissionTitle': 'You had denied the permission to take photo from library',":`Bạn đã từ chối cấp quyền truy cập thư viện ảnh.`,
"permissionBody":`Bạn muốn cấp quyền truy cập, hãy cấp phép trong mục cài đặt.`,
"videoPermissionTitle":`Bạn đã từ chối cấp quyền truy cập thư viện ảnh.`,
"TimeLine_post_not_found":`Không tìm thấy bài đăng trên Dòng Thời Gian`,
"Timeline_Posts":`Bài đăng Dòng Thời Gian`,
"Timeline":`Dòng Thời Gian`,
"trackAtimeLine":`Theo dõi thời gian chờ`,
"Journey":`Không tìm thấy dòng thời gian.`,
"KM":`km`,
"Distance_Travelled":`Khoảng cách di chuyển`,
"hrs":`giờ`,
"secs":`giây`,
"mins":`phút`,
"time":`Thời gian`,
"wait_time":`Thời gian chờ trung bình`,
"Equiment_Photo":`Trang bị ảnh`,
"Interchange_Receipt":`Hóa đơn thay đổi`,
"video":`Video`,
"Share":`Chia sẻ`,
"start_time":`Thời gian bắt đầu`,
"Report_Post":`Báo cáo về bài đăng`,
"endTime":`Thời gian kết thúc`,
"openTime":`Thời gian mở cửa`,
"closeTime":`Thời gian đóng`,
"distance":`Khoảng cách`,
"Total_time":`Tổng thời gian`,
"Edit_Timeline":`Chỉnh sửa Dòng thời gian`,
"messageAlert":`Vui lòng nhập nội dung`,
"enterMessage":`Nhập tin nhắn...`,
"Trending_Post":`Bài viết đang là xu hướng`,
"PleaseEnterReportResion":`Vui lòng nhập lý do báo cáo`,
"trendingPostNotFound":`Không tìm thấy xu hướng.`,
"Accept":`Chấp nhận`,
"Reject":`Từ chối`,
"Allow":`Cho phép`,
"Invite":`Mời`,
"postNotFound":`Không tìm thấy bài đăng.`,
"Cancel_Friend_Request":`Hủy yêu cầu kết bạn`,
"User_Posts":`Bài đăng của người dùng`,
"Notifications":`Thông báo`,
"No_notifications":`Không tìm thấy thông báo.`,
"And":`VÀ`,
"deletePostAlert":`Bạn có chắc chắn muốn xóa bài viết này không?`,
"Yes":`Có.`,
"No":`Không`,
"enterTitle":`Vui lòng nhập tiêu đề.`,
"pleaseEnterMessage":`Vui lòng nhập tin nhắn.`,
"Post_Create":`Tạo bài đăng`,
"description":`Nhập mô tả của bạn ...`,
"enterDescription":`Vui lòng nhập mô tả.`,
"descriptionMax":`Vui lòng nhập mô tả ít hơn 1.000 ký tự.`,
"descriptionMin":`Mô tả phải dài ít nhất 10 ký tự.`,
"Preview":`Xem trước`,
"messageMax":`Vui lòng nhập tin nhắn ít hơn 1.000 ký tự.`,
"noUser":`Không tìm thấy người dùng.`,
"New":`Mới`,
"No_chat_found":`Không tìm thấy cuộc trò chuyện gần đây`,
"Search_Terminal":`Tìm kiếm Trạm`,
"Receipt_Private":`Biên nhận Riêng tư`,
"Edit":`Biên tập`,
"Delete":`Xóa bỏ`,
"postShareMessage":`đã chia sẻ bài viết Nhấp vào liên kết dưới đây để xem bài viết`,
"postShareMessage2":`đã chia sẻ bài viết Nhấp vào liên kết dưới đây để xem bài viết`,
"shareSubject":`FR8 TimeLine Post`,
"messageCopy":`Đã sao chép tin nhắn`,
"avaliable24Hours":`Có sẵn 24 giờ`,
"photo":`HÌNH CHỤP`,
"photoLibrary":`THƯ VIỆN ẢNH`,
"photoL":`hình chụp`,
"photoLibraryL":`Thư viện ảnh`,
"reportUser":`Báo cáo người dùng`,
"reasonOfReport":`Lý do Báo cáo`,
"reportPostAlert":`Bạn có chắc chắn muốn báo cáo bài này?`,
// "ForegroundServiceTitle":`Ứng dụng FR8 đang quản lý vị trí của bạn trong nền`,
"ForegroundServiceTitle":`Detention Pay Tracker đang chạy`,
"Portuguese":`Bồ Đào Nha`,
"interChangeDelete":`Bạn có chắc chắn muốn xóa Biên lai trao đổi không?`,
"equipmentDelete":`Bạn có chắc chắn muốn xóa ảnh thiết bị không?`,
"deleteVideo":`Bạn có chắc chắn muốn xóa video không?`,
"sentAMessage":`đã gửi một tin nhắn:`,
"editMessage":`Chỉnh sửa tin nhắn`,
"continue":`Tiếp tục`,
"noContact":`Không tìm thấy địa chỉ liên hệ`,
"Driver":`Người lái xe`,
"Owner Operator":`Người điều hành chủ sở hữu`,
"Company":`Công ty`,
"Air Cargo Carrier":`Hãng hàng không`,
"Exporter":`Nhà xuất khẩu`,
"Freight Broker":`Người môi giới hàng hóa`,
"Importer":`Nhà nhập khẩu`,
"Shipper":`Người giao hàng`,
"Trucking":`Vận tải đường bộ`,
"Warehouse":`Kho`,
"Company Driver":`Tài xế công ty`,
"OKAY":`ĐƯỢC CHỨ`,
"installMessage":`Xin chào FR8, bạn muốn mời cài đặt ứng dụng.`,
"warned":`cảnh báo`,
"WaitingAt":`Đang đợi lúc`,
"openFr8":`Mở ứng dụng Fr8 để hiển thị thời gian chờ ước tính của bạn.`,
"day":`ngày`,
"days":`ngày`,
"hour":`  giờ`,
"hours":`  giờ`,
"minute":`  phút`,
"minutes":`  phút`,
"second":`  thứ hai`,
"seconds":`  giây`,
"openApp":`Mở ứng dụng để đồng bộ trạng thái của bạn`,
"openAppBody":`Để có trải nghiệm tốt nhất, hãy cho phép Ứng dụng FR8 tiếp tục mở trong nền. Điều này giữ cho dòng thời gian và dấu thời gian đầu cuối của bạn luôn chính xác.`,
"Comment":`Bình luận`,
"Comments":`Bình luận`,
"Like":`Thích`,
"noComment":`Không tìm thấy bình luận`,
"deleteCommentAlert":`Bạn có chắc chắn muốn xóa nhận xét không?`,
"enterTheComment":`Vui lòng nhập bình luận.`,
"enterYourComment":`Nhập bình luận của bạn ...`,
"DeeplinkShare":`Chia sẻ dưới dạng liên kết`,
"Shares":`Chia sẻ`,
"shareasPost":`Chia sẻ bài đăng`,
"hasShared":`đã chia sẻ`,
"whatsOnMind":`Bạn đang nghĩ gì vậy?`,
"inGate":`Trong`,
"outGate":`Ngoài`,
"With":`với`,
"others":`khác`,
"tagFriends":`Gắn thẻ bạn bè`,
"done":`Xong`,
"friendSearch":`Tìm bạn`,
"checkIN":`Đăng ký vào`,
"tagUsers":`Người dùng được gắn thẻ`,
"safeTrip":` Bây giờ bạn có thể chia sẻ thời gian chờ đợi của mình. Chúc bạn có một chuyến đi an toàn!`,
"addLocation":`Thêm vị trí`,
"locationSelect":`Vui lòng chọn vị trí.`,
"attach":`Đính kèm tệp`,
"selectImage":`Vui lòng chọn hình ảnh hoặc video để đăng.`,
"noPlace":`Không tìm thấy Địa điểm`,
"deleteMedia":`Bạn có chắc chắn muốn xóa phương tiện này không?`,
"deleteNotification":`Bạn có chắc chắn muốn xóa thông báo này không?`,
"loading":`Đang tải…`,
"next":`Kế tiếp`,
"ttlUserInterminal":`Số lượng người dùng bên trong thiết bị đầu cuối:`,
"members":`Các thành viên bên trong`,
"member":`Thành viên bên trong`,
"useLocation":`Sử dụng vị trí của bạn`,
"firstPermissionTitle":`Để xem bản đồ cho các hoạt động được theo dõi tự động, hãy cho phép FR8 sử dụng vị trí của bạn mọi lúc.`,
"noThanks":`Không, cám ơn`,
"turnOn":`Bật`,
"newVersion":`Phiên bản mới`,
"versionDescription":`Phiên bản ứng dụng này đã lỗi thời, vui lòng cập nhật lên phiên bản mới nhất để mở khóa các tính năng mới tuyệt vời giúp bạn có được các tính năng mới chính xác và tuyệt vời nhất. Đừng quên đặt quyền vị trí thành Luôn cho phép để ứng dụng tính toán Thời gian chờ của thiết bị đầu cuối cho bạn trong nền.`,
"firstPermissionDesc":`FR8 sẽ sử dụng vị trí của bạn trong nền để cho phép bạn ghi lại chính xác các chuyến đi của bạn trong các nhà ga và tính toán thời gian chờ và thời gian.`,
"validUserName":`Chỉ cho phép các chữ cái (a-z), số (0-9), dấu chấm (.) Và dấu gạch dưới (_).`,
"user_name_start":`Tên người dùng không được bắt đầu bằng dấu chấm (.)`,
"onlyNumberAlert":`Tên người dùng không thể chỉ chứa số.`,
"user_name_end":`Tên người dùng không được kết thúc bằng dấu chấm (.)`,
"twoDots":`Tên người dùng không được có nhiều dấu chấm (.) Liên tiếp.`,
"Ok":`VÂNG`,
"followingTerminal":`Tiếp theo`,
"pdfDownload":`tải PDF`,
"timelineCancel":`Bạn có chắc chắn muốn hủy dòng thời gian không?`,
"Truck Stop":`Bến đỗ xe tải`,
"Gas Station":`Trạm xăng`,
"Weight Station":`Trạm cân`,
"location_name_enter":`Vui lòng nhập tên Vị trí.`,
"locationNameLong":`Tên vị trí phải dài ít nhất 2 ký tự.`,
"locationAddressLong":`Địa chỉ vị trí phải dài ít nhất 2 ký tự.`,
"locationAddress":`Vui lòng nhập địa chỉ vị trí.`,
"Name":`Tên`,
"Hold to Stop":`Giữ để dừng`,
"Location Address":`Địa chỉ Vị trí`,
"Phone Number":`Số điện thoại`,
"Add":`cộng`,
"Category":`Danh mục`,
"backgroundProcess":`Dòng thời gian của bạn sẽ chạy trong nền khi bạn chuyển sang các màn hình khác.`,
"NotMoving":`Vẫn chưa di chuyển?`,
"oneMinuteLongerAlert":`Để hoàn thành và lưu, FR8 cần hoạt động lâu hơn ít nhất 1 phút, với sự thay đổi về vị trí.`,
"editPost":`Chỉnh sửa bài`,
"vedioLimit":`Thời lượng video phải dài tối đa 30 giây.`,
"selectCurentLocation":`Chọn vị trí hiện tại`,
"noCommentYet":`Chưa có bình luận nào`,
"enterFirstComment":`Hãy trở thành người đầu tiên bình luận.`,
"App_Share":`Chia sẻ ứng dụng`,
"appShareMessage":`đã chia sẻ ứng dụng FR8. Nhấp vào liên kết bên dưới để xem ứng dụng di động và xem thời gian chờ hiện tại ngay hôm nay.`,
"appShareMessage2":`FR8\n Nhấp vào liên kết bên dưới để xem ứng dụng di động và xem thời gian chờ hiện tại ngay hôm nay.`,
"deleteCommentReplyAlert":`Bạn có chắc chắn muốn xóa câu trả lời bình luận này không?`,
"enter_first_name_length_alert":`Tên phải dài ít nhất 3 ký tự.`,
"enter_last_name_length_alert":`Họ phải dài ít nhất 3 ký tự.`,
"location_Setting":`Cài đặt vị trí`,
"postlikeHeading":`Những người thích bài đăng`,
"commentLikeHeading":`Những người thích bình luận`,
"viewProfile":`Xem lí lịch`,
"shareListHeading":`Những người đã chia sẻ bài đăng`,
"Reply":`Hồi đáp`,
"Reply to":`Trả lời`,
"Dislike":`Không thích`,
"Smile":`Mỉm cười`,
"Angry":`Tức giận`,
"Rolling Eyes":`Tròn mắt`,
"Thinking":`tư duy`,
"Stop":`Ngừng lại`,
"switchFrom":`Nhận thông báo an toàn chính xác bằng cách chuyển từ`,
"Always Allow":`Luôn luôn đồng ý`,
"While Using":`Trong khi sử dụng`,
"Ask next time":`Hỏi lần sau`,
"Never":`Không bao giờ`,
"Manage location Settings":`Quản lý cài đặt vị trí`,
"Italian":`người Ý`,
"Chinese":`Tiếng Trung giản thể (Quan thoại)`,
"Hindi":`Tiếng Hindi`,
"Filipino":`Người Phi Luật Tân`,
"Vietnamese":`Tiếng Việt`,
"Arabic":`tiếng Ả Rập`,
"French":`người Pháp`,
"Korean":`Hàn Quốc`,
"Russian":`tiếng Nga`,
"Bengali":`Tiếng Bengali`,
"German":`tiếng Đức`,
regionlNotFound: 'Region not found.',
Region:"Region",
in: 'trong',
posts: 'Bài đăng',

"All":"Tất cả các",
"saveToPhone":"Lưu vào điện thoại",
"ADD":"CỘNG",
"deleteAccount":"Xóa tài khoản",
"deleteAccountAlert":"Bạn có chắc rằng bạn muốn xóa tài khoản của bạn?",
"replyWrite":"Viết phản hồi...",
"Camera":"Máy ảnh",
"Image Gallery":"thư viện hình ảnh",
"regionlNotFound":"Không tìm thấy khu vực.",
"Region":"Vùng đất",
"regionSelectAlert":"Người dùng có thể chọn tối đa 3 vùng.",

"CALL":"CUỘC GỌI",
"ADDRESS":"ĐỊA CHỈ",
"MIN":"MIN",
"About":"Về",
"Overview":"Tổng quan",
"Review":"Kiểm tra lại",
"Timelines":"Dòng thời gian",
"Rate & Review":"Đánh giá tỉ lệ",
"ratings":"Đánh giá tỉ lệ",
"Write Your Review":"Viết đánh giá của bạn",
"Just now":"Vừa rồi",
'waitTimeIndicator':'Chỉ báo thời gian chờ',
currentWaitTime:"Thời gian chờ trung bình hiện tại",

};

module.exports = {
  constants
};
