import {imageBaseUrl} from '../Config/index'
const constants = {
   // TermsUrl:"http://18.205.207.176:3000/public/pdf/Fr8_App_Terms_Of_Use.pdf",
   TermsUrl:"https://www.fr8.ai/terms",
   // TermsUrl: imageBaseUrl +"public/pdf/Fr8_App_Terms_Of_Use.pdf",
   // PrivacyUrl:"http://18.205.207.176:3000/public/pdf/Fr8_App_Privacy_Policy.pdf",
   PrivacyUrl:"https://www.fr8.ai/privacy",
   // PrivacyUrl: imageBaseUrl + "public/pdf/Fr8_App_Privacy_Policy.pdf",
  // Email: "Email",
  // Enter_Email: "Enter Email",
  // Password: "Password",
  // Enter_Password: "Enter Password",
  // Enter_New_Password: "Enter New Password",
  // Forgot_Your_Password: "Forgot Your Password?",
  // Login: "Login",
  // Doesnt_have_an_account: "Doesn't have an account?",
  // Sign_up: "Sign up",

  // Enter_Name: "Enter name",
  // Enter_first_Name: "Enter first name",
  // Enter_last_Name: "Enter last name",
  // Enter_Your_Phone_Number: "Enter your phone number",
  // Enter_Six_Digit_Verification_Code: "Enter 6 digit verification code",
  // Resend_Verification_Code: "Resend verification code",
  // Contact_Permission:
  //   "Please enable contacts permission in order to keep your friends safe.",

  // Register: "Register",
  // Full_Name: "Full Name",
  // Enter_Full_Name: "Enter Full Name",
  // Username: "Username",
  // Enter_Username: "Enter username",
  // Email_Address: "Email address",
  // Enter_Email_Address: "Enter email address",
  // User_Type: "User Type",
  // Select_User_Type: "Select user type",
  // Phone_Number: "Phone number",
  // Enter_Phone_Number: "Enter phone number",
  // Date_Of_Birth: "Date Of Birth",
  // Select_Date_Of_Birth: "Select Date Of Birth",
  // Confirm_Password: "Confirm Password",
  // Enter_Confirm_Password: "Enter Confirm Password",
  // Agree_Terms_and_Condition: "Agree Terms and Conditions",

  // Forgot_Password: "Forgot Password",
  // Submit: "Submit",
  // OTP: "OTP",
  // Enter_OTP: "Enter OTP",
  // Reset_Password: "Reset Password",
  // Edit_Profile: "Edit Profile",
  // Edit_Phone_Number: "Edit Phone Number",
  // Update: "Update",
  // Change_Password: "Change Password",
  // Old_Password: "Old Password",
  // Enter_Old_Password: "Enter Old Password",
  // FAQs: "FAQs",
  // Social_Media_Accounts: "Social Media Accounts",
  // Settings: "Settings",
  // "FR8": "FR8",
  // Support_Center: "Support Center",
  // Terms_And_Conditions: "Terms And Conditions",
  // Privacy_Policy: "Privacy Policy",
  // Change_Language: "Change Language",
  // Logout: "Logout",
  // Log_out: "Log Out",
  // Confirm: "Confirm",
  // Cancel: "Cancel",
  // Please_Select: "Please Select",
  // Warn_Contacts: "Warn Contacts",
  // Search_contacts: "Search contacts",
  // Friend_Requests: "Friend Requests",
  // Friend_Request: "Friend Request",
  // My_Posts: "My Posts",
  // Search_friends: "Search friends, terminals, contacts",
  // My_Freighting_Network: "My Freighting Network",
  // 'My_Network': 'My Network',
  // Places: "Places",
  // Friends: "Friends",
  // Nearby_Terminals: "Nearby Terminals",
  // Explore: "Explore",
  // Contacts: "Contacts",
  // Name_Of_User: "Name Of User",
  // Add_Friend: "Add Friend",
  // Remove_Friend: "Remove Friend",
  // Chat: "Chat",
  // Post_Details: "Post Details",
  // Live_Streams: "Live Streams",
  // CreatePost: "Create Post",
  // SocialMediaAccounts: "Social Media Accounts",
  // Instagram: "Instagram",
  // Google: "Google",
  // Facebook: "Facebook",
  // Support: "Support",
  // Tittle: "Title",
  // Enter_Tittle: "Enter Title",
  // FR8: "FR8",
  // UserName: "User Name",
  // TerminalDetails: "Terminal Details",
  // Location: "Location",
  // Un_Follow: "Unfollow",
  // Follow: "Follow",
  // Record: "Record",
  // Warn: "Warn",
  // ChatHistory: "Chat History",
  // TerminalName: "Terminal Name",
  // Terminal: 'Terminal',
  // English: "English",
  // Spanish: "Spanish",
  // Driver_Type: "Driver Type",
  // Select_Driver_Type: "Select driver type",
  // Users: "Users",
  // Enter_Title: "Enter Title",
  // Type_Message_Here: "Type Message Here...",
  // Change_Language: "Change Language",
  // Skip: "Skip",
  // Friend_request_not_found: "Friend request not found.",
  // Change_Mobile_Number: "Change Mobile Number",
  // resend_Otp: "Resend Verification Code",
  posts: 'Mga Posts.',
  

"Email":`Email/Sulatroniko`,
"Enter_Email":`Ipasok ang Email`,
"Password":`Password/Hudyat`,
"Enter_Password":`Ilagay ang Password`,
"Enter_New_Password":`Ilagay ang Bagong Password`,
"Forgot_Your_Password":`Nakalimutan ang iyong Password?`,
"Login":`Mag Log-In`,
"Doesnt_have_an_account":`Walang Account?`,
"Sign_up":`Mag Sign-Up`,
"Enter_Name":`Ilagay ang Pangalan`,
"Enter_first_Name":`Ilagay ang pangalan`,
"Enter_last_Name":`Ilagay ang apelyido`,
"Enter_Your_Phone_Number":`Ilagay ang iyong numero ng telepono`,
"Enter_Six_Digit_Verification_Code":`Ilagay ang 6 digit verification code`,
"Resend_Verification_Code":`Muling magpadala ng verification code`,
"Contact_Permission":`Mangyaring paganahin ang pahintulot sa mga contact upang mapanatiling ligtas ang iyong mga kaibigan.`,
"Register":`Magparehistro`,
"Full_Name":`Buong Pangalan`,
"Enter_Full_Name":`Ilagay ang Buong Pangalan`,
"Username":`Username`,
"Enter_Username":`Ilagay ang username`,
"Email_Address":`Email address`,
"Enter_Email_Address":`Ilagay ang Email address`,
"User_Type":`Uri ng Gumagamit`,
"Select_User_Type":`Piliin ang Uri ng Gumagamit`,
"Phone_Number":`Numero ng Telepono`,
"Enter_Phone_Number":`Ilagay ang Numero ng Telepono`,
"Date_Of_Birth":`Araw ng Kapanganakan`,
"Select_Date_Of_Birth":`Piliin ang Araw ng Kapanganakan`,
"Confirm_Password":`Kumpirmahin ang Password`,
"Enter_Confirm_Password":`Ilagay ang Kumpirmadong Password`,
"Agree_Terms_and_Condition":`Sang-ayon sa mga tuntunin at kundisyon`,
"Forgot_Password":`Nakalimutan ang Password`,
"Submit":`Ipasa`,
"OTP":`OTP`,
"Enter_OTP":`Ilagay ang OTP`,
"Reset_Password":`i-Reset ang Password`,
"Edit_Profile":`i-Edit ang Profile`,
"Edit_Phone_Number":`i-Edit ang Numero ng Telepono`,
"Update":`i-Update`,
"Change_Password":`Baguhin ang Password`,
"Old_Password":`Lumang Password`,
"Enter_Old_Password":`Ilagay ang Lumang Password`,
"FAQs":`FAQs`,
"Social_Media_Accounts":`Mga Account sa Social Media`,
"Settings":`Mga Settings`,
"FR8":`FR8`,
"Support_Center":`Sentro ng Suporta`,
"Terms_And_Conditions":`Tuntunin at Kundisyon`,
"Privacy_Policy":`Patakaran sa Pagkapribado/Privacy`,
"Change_Language":`Baguhin ang wika/lengguwahe`,
"Logout":`Mag Log-out`,
"Log_out":`Mag Log-out`,
"Confirm":`Kumpirmahin`,
"Cancel":`Kansel`,
"Please_Select":`Pakipili`,
"Warn_Contacts":`Balaan ang mga Contacts`,
"Search_contacts":`Hanapin ang mga Contacts`,
"Friend_Requests":`Mga kahilingang maging kaibigan`,
"Friend_Request":`Kahilingang maging kaibigan`,
"My_Posts":`Mga Posts Ko/Aking mga Posts`,
"Search_friends":`Hanaping ang mga Kaibigan, mga Terminals, mga Contatcs`,
"My_Freighting_Network":`Ang Network ng Aking Kargamento`,
"My_Network":`Network Ko/Ang Aking Network`,
"Places":`Mga Lugar`,
"Friends":`Mga Kaibigan`,
"Nearby_Terminals":`Mga Kalapit na mga Terminal`,
"Explore":`Galugarin`,
"Contacts":`Mga Contacts`,
"Name_Of_User":`Pangalan ng Gumagamit`,
"Add_Friend":`Magdagdag ng Kaibigan`,
"Remove_Friend":`Alisin ang Kaibigan`,
"Chat":`Chat`,
"Post_Details":`Mga detalye ng Post`,
"Live_Streams":`Live Streams`,
"CreatePost":`Gumawa ng Post`,
"SocialMediaAccounts":`Mga Social Media Accounts`,
"Instagram":`Instagram`,
"Google":`Google`,
"Facebook":`Faccebook`,
"Support":`Supporta`,
"Tittle":`Pamagat`,
"DescriptionText":`Paglalarawan`,
"Enter_Tittle":`Ilagay ang Pamagat`,
"UserName":`User Name/Pangalan ng Gumagamit`,
"TerminalDetails":`Detalye ng mga Terminal`,
"Location":`Lokasyon`,
"Un_Follow":`I-unfollow`,
"Follow":`Follow/Sundan`,
"Record":`Record/Talaan`,
"Warn":`Balaan`,
"ChatHistory":`Kasaysayan ng Chat`,
"TerminalName":`Pangalan ng Terminal`,
"Terminal":`Terminal`,
"English":`Ingles`,
"Spanish":`Espanyol`,
"Driver_Type":`Uri ng Drayber`,
"Select_Driver_Type":`Pumili ng Uri ng Drayber`,
"Users":`Mga User`,
"Enter_Title":`Ilagay ang Pamagat`,
"Type_Message_Here":`Mag-type ng Mensahe dito`,
"Skip":`Lakwatan`,
"Friend_request_not_found":`Walang friend request na natagpuan.`,
"Change_Mobile_Number":`Baguhin ang Numero ng Telepono`,
"resend_Otp":`Muling Ipadala ang Verification Code`,
"post":`Post`,
"Friend":`kaibigan`,
"NotificationDetail":`Mga Detalye ng Abiso`,
"noResult":`Walang natagpuang resulta.`,
"enter_email_alert":`Paki lagay ang email address.`,
"enter_valid_email_alert":`Paki lagay ang wastong email address`,
"enter_password_alert":`Paki lagay ang Password`,
"enter_full_name_alert":`Paki lagay ang Buong Pangalan`,
"enter_last_name_alert":`Pakilagay ang apelyido.`,
"enter_full_name_aplhanumeric_alert":`Paki lagay ang Buong Pangalan ng naka Alphanumeric`,
"enter_user_name_alert":`Paki lagay ang User Name`,
"enter_user_name_length_alert":`Dapat na hindi bababa sa 3 character ang haba ng username.`,
"enter_user_type_alert":`Pakipili ang Uri ng Gumagamit`,
"enter_driver_type_alert":`Pakipili ang Uri ng Drayber`,
"enter_phone_number_alert":`Paki lagay ang Numero ng Telepono`,
"enter_phone_number_length_alert":`Ang Numero ng Telepono ay dapat mula walo hanggang labinglima.`,
"enter_Numbers_allowed__phone_alert":`Numero lamang ang maaring ilagay sa patlang ng telepono`,
"enter_date_of_birth_alert":`Pakilagay ang Araw ng Kapanganakan`,
"enter_password_length_alert":`Ang password ay dapat na hindi bababa sa 6 na mga characters.`,
"enter_confirm_password_alert":`Paki lagay ang kumpirmadong password.`,
"enter_password_not_match_alert":`Ang Password at ang kumpirmadong password ay dapat pareho.`,
"enter_terms_conditions_alert":`Ilagay_ang_alerto_ng_tuntunin_at_Kundisyon: Tanggapin po ninyo ang mga tuntunin at kundisyon`,
"enter_otp_alert":`Paki lagay ang Verification Code`,
"enter__valid_otp_alert":`Paki lagay ang wastong Verification Code`,
"enter_old_password_alert":`Paki lagay ang lumang password.`,
"enter_old_password_length_alert":`Ang lumang password ay dapat na hindi bababa sa 6 na mga characters.`,
"enter_new_password_alert":`Ang lumang password ay dapat na hindi bababa sa 6 na mga characters.`,
"enter_new_password_length_alert":`Ang bagong password ay dapat na hindi bababa sa 6 na mga characters.`,
"enter_old_cofirm_not_valid_alert":`Ang lumang password at ang kumpirmadong password ay dapat pareho.`,
"Stream_stopped_by_user":`Ang Live Video ay tinapos ni:`,
"Loading_streams":`Loading Streams`,
"you_are_live_now":`Ikaw ay naka-Live ngayon.`,
"end_publisher_video":`Sigurado ka bang nais mong tapusin ang live video na ito?`,
"logOutAlert":`Sigurado ka bang nais mong mag log-out?`,
"end_publisher_video_successfully":`Tapos na ang Live Video`,
"Alert":`Alerto`,
"PhoneNumber_required_for_login":`Kinakailangan ang numero ng telepono upang mag-log in. Tumutulong din ito sa amin na i-moderate ang komunidad at protektahan ang aming mga gumagamit.`,
"Privacy_policy":`Sa Pagpatuloy, ikaw ay sumasang-ayon sa aming`,
"Terms":`Mga Tuntunin ng Paggamit`,
"Policy":`Patakaran sa Pagkapribado/Privacy`,
"Why_you_need_my_phone_number":`Bakit mo kailangan ang Numero ng aking Telepono`,
"Why_we_need_your_phone_number":`Bakit namin kailangan ang Numero ng iyongTelepono`,
"verifyAccount":`I-verify ang iyong Account`,
"terminalNotFound":`Walang Terminal na natagpuan.`,
"Profile":`Profile`,
"App_Settings":`Settings ng App`,
"estimatedTime":`Tinatayang Oras`,
"estimatedWaitTime":`Minutong Naghintay`,
"youHaveLeft":`umalis ka na`,
"Citizen_safety_message":`Ang Fr8 ay isang Network ng Kargamento. Kinakailangan namin ang numero ng iyong telepono upang parehong ma-verify ang iyong pagkakakilanlan at upang matiyak na ang mga lumalabag sa aming mga pamantayan sa komunidad ay maaring alisin mula sa network, kung naangkop.`,
"something_went_wrong":`May nangyaring mali.`,
"please_check_your_internet_connection":`Pakisuri ang koneksyon ng iyong internet.`,
"startEndAlert":`Ang oras ng pagsisimula ay dapat na mas kaunti kaysa sa oras ng pagtatapos.`,
"addPost":`Mag-add ng Post`,
"permissionTitle': 'You had denied the permission to take photo from library',":`Tinanggihan mo ang pahintulot na kumuha ng litrato mula sa library.`,
"permissionBody":`Nais mo bang i-access ito pagkatapos ay payagan ang pahintulot sa settings?`,
"videoPermissionTitle":`Tinanggihan mo ang pahintulot na kumuha ng video mula sa library.`,
"TimeLine_post_not_found":`Hindi nahanap ang Post sa Timeline.`,
"Timeline_Posts":`Post sa Timeline`,
"Timeline":`Timeline`,
"trackAtimeLine":`Subaybayan ang oras ng paghihintay`,
"Journey":`Walang nakitang timeline.`,
"KM":`Km`,
"Distance_Travelled":`Distanya ng Paglakbay`,
"hrs":`Oras`,
"secs":`Segundo`,
"mins":`Minuto`,
"time":`Oras`,
"wait_time":`Average na oras ng paghihintay`,
"Equiment_Photo":`Larawan ng kagamitan`,
"Interchange_Receipt":`Resibo ng Palitan`,
"video":`Video`,
"Share":`i-Share/Ibahagi`,
"start_time":`Oras ng Simula`,
"Report_Post":`Mag-ulat ng Post`,
"endTime":`Oras ng Pagtatapos`,
"openTime":`Open Time`,
"closeTime":`Oras ng Isara`,
"distance":`Distansya`,
"Total_time":`Kabuuang Oras`,
"Edit_Timeline":`i-Edit ang Timeline`,
"messageAlert":`Mangyaring maglagay ng ilang mensahe`,
"enterMessage":`Ilagay ang iyong mensahe`,
"Trending_Post":`Trending Post`,
"PleaseEnterReportResion":`Mangyaring ilagay ang dahilan ng ulat. `,
"trendingPostNotFound":`Walang Trending Post na natagpuan.`,
"Accept":`Tanggapin`,
"Reject":`Tanggihan`,
"Allow":`Payagan`,
"Invite":`Mag-anyaya`,
"postNotFound":`Walang Post na natagpuan`,
"Cancel_Friend_Request":`Kanselhain ang kahilingan ng kaibigan`,
"User_Posts":`Post ng mga Gumagamit`,
"Notifications":`Mga Notification`,
"No_notifications":`Walang mga Notification na natagpuan.`,
"And":`at`,
"deletePostAlert":`Sigurado ka bang nais mong tanggalin ang post na ito?`,
"Yes":`Oo`,
"No":`Hindi`,
"enterTitle":`Paki lagay ang pamagat`,
"pleaseEnterMessage":`Paki lagay ang mensahe`,
"Post_Create":`Gumawa ng Post`,
"description":`Ilagay ang  iyong paglalarawan`,
"enterDescription":`Pakilagay ang paglalarawan`,
"descriptionMax":`Mangyaring ilagay ang paglalarawan na hindi bababa sa isang libong mga character.`,
"descriptionMin":`Hindi dapat bababa sa 10 character ang haba ng paglalarawan.`,
"Preview":`Preview`,
"messageMax":`Mangyaring ilagay ang mensahe na hindi bababa sa isang libong mga character.`,
"noUser":`Walang Gumagamit/User na natagpuan.`,
"New":`Bago`,
"No_chat_found":`Walang nahanap na kamakailang chat`,
"Search_Terminal":`Hanapin ang Terminal`,
"Receipt_Private":`Pribado ang Resibo`,
"Edit":`I-edit`,
"Delete":`Tanggalin`,
"postShareMessage":`ay nagbahagi ng post Mag-click sa link sa ibaba upang tingnan ang post`,
"postShareMessage2":`Mag-click sa link sa ibaba upang tingnan ang post`,
"shareSubject":`FR8 TimeLine Post`,
"messageCopy":`Kinopya ang mensahe`,
"avaliable24Hours":`Available 24 oras`,
"photo":`LARAWAN`,
"photoLibrary":`LIBRENG LIBRARY`,
"photoL":`Larawan`,
"photoLibraryL":`Photo Library`,
"reportUser":`Iulat ang User`,
"reasonOfReport":`Dahilan ng Ulat`,
"reportPostAlert":`Sigurado ka ba, gusto mong iulat ang post na ito?`,
"ForegroundServiceTitle":`Ang Detention Pay Tracker ay tumatakbo`,
// "ForegroundServiceTitle":`Pinamamahalaan ng FR8 app ang iyong lokasyon sa background`,
"Portuguese":`Portugal`,
"interChangeDelete":`Sigurado ka ba, gusto mong tanggalin ang Interchange Receipt?`,
"equipmentDelete":`Sigurado ka ba, gusto mong tanggalin ang larawan ng kagamitan?`,
"deleteVideo":`Sigurado ka ba, gusto mong tanggalin ang video?`,
"sentAMessage":`nagpadala ng mensahe:`,
"editMessage":`I-edit ang Mensahe`,
"continue":`Magpatuloy`,
"noContact":`Walang Nahanap na Mga Contact`,
"Driver":`Driver`,
"Owner Operator":`Tagapamahala`,
"Company":`kumpanya`,
"Air Cargo Carrier":`Air Cargo Carrier`,
"Exporter":`Exporter`,
"Freight Broker":`Broker ng kargamento`,
"Importer":`Importer`,
"Shipper":`Nagpapadala`,
"Trucking":`Trucking`,
"Warehouse":`Bodega`,
"Company Driver":`Driver ng Kumpanya`,
"OKAY":`SIGE`,
"installMessage":`Kamusta FR8 gusto mo bang anyayahan na i-install ang application.`,
"warned":`binalaan`,
"WaitingAt":`Naghihintay sa`,
"openFr8":`Buksan ang Fr8 app para ipakita ang iyong tinantyang oras ng paghihintay.`,
"day":`araw`,
"days":`araw`,
"hour":`  oras`,
"hours":`  oras`,
"minute":`  minuto`,
"minutes":`  minuto`,
"second":`  pangalawa`,
"seconds":`  segundo`,
"openApp":`Buksan ang App para I-sync ang iyong Status`,
"openAppBody":`Para sa pinakamagandang karanasan, payagan ang FR8 App na manatiling bukas sa background. Pinapanatili nitong tumpak ang iyong timeline at terminal time stamp.`,
"Comment":`Magkomento`,
"Comments":`Mga komento`,
"Like":`Gaya ng`,
"noComment":`Walang nakitang komento`,
"deleteCommentAlert":`Sigurado ka bang gusto mong tanggalin ang komento?`,
"enterTheComment":`Mangyaring ilagay ang komento.`,
"enterYourComment":`Ilagay ang iyong komento...`,
"DeeplinkShare":`Ibahagi bilang link`,
"Shares":`Mga pagbabahagi`,
"shareasPost":`Ibahagi ang Post`,
"hasShared":`ay nagbahagi`,
"whatsOnMind":`Ano ang nasa isip mo?`,
"inGate":`Sa`,
"outGate":`Out`,
"With":`kasama`,
"others":`iba pa`,
"tagFriends":`Tag Kaibigan`,
"done":`Tapos na`,
"friendSearch":`Maghanap ng mga Kaibigan`,
"checkIN":`Mag-check In`,
"tagUsers":`Mga Naka-tag na User`,
"safeTrip":` Maaari mo na ngayong ibahagi ang iyong oras ng paghihintay. Mag-ingat ka sa pagbibiyahe!`,
"addLocation":`Magdagdag ng Lokasyon`,
"locationSelect":`Mangyaring piliin ang lokasyon.`,
"attach":`Mag-attach ng mga File`,
"selectImage":`Mangyaring pumili ng mga larawan o video na ipo-post.`,
"noPlace":`Walang nakitang Lugar`,
"deleteMedia":`Sigurado ka ba, gusto mong tanggalin ang media na ito?`,
"deleteNotification":`Sigurado ka ba, gusto mong tanggalin ang notification na ito?`,
"loading":`Naglo-load…`,
"next":`Susunod`,
"ttlUserInterminal":`Bilang ng mga user sa loob ng terminal:`,
"members":`Mga miyembro sa loob`,
"member":`Member sa loob`,
"useLocation":`Gamitin ang iyong lokasyon`,
"firstPermissionTitle":`Upang makakita ng mga mapa para sa mga awtomatikong sinusubaybayang aktibidad, payagan ang FR8 na gamitin ang iyong lokasyon sa lahat ng oras.`,
"noThanks":`Salamat nalang`,
"turnOn":`Buksan`,
"newVersion":`Bagong bersyon`,
"versionDescription":`Ang bersyon na ito ng app ay luma na, mangyaring mag-update sa pinakabagong bersyon upang i-unlock ang mga kamangha-manghang bagong feature upang matulungan kang makuha ang pinakatumpak at kamangha-manghang mga bagong feature. Huwag kalimutang itakda ang mga pahintulot sa lokasyon sa Palaging Payagan upang kalkulahin ng app ang terminal na Mga Oras ng Paghihintay para sa iyo sa background.`,
"firstPermissionDesc":`Gagamitin ng FR8 ang iyong lokasyon sa background upang paganahin ang iyong mga tumpak na pag-record ng iyong mga biyahe sa mga terminal at kalkulahin ang oras ng paghihintay at time stamp.`,
"validUserName":`Tanging mga titik (a-z), numero (0-9), tuldok (.) at underscore (_) ang pinapayagan.`,
"user_name_start":`Ang username ay hindi dapat magsimula sa mga tuldok (.)`,
"onlyNumberAlert":`Ang username ay hindi maaaring maglaman lamang ng mga numero.`,
"user_name_end":`Ang username ay hindi dapat magtapos sa mga tuldok (.)`,
"twoDots":`Ang username ay hindi dapat magkaroon ng higit sa isang tuldok (.) sa isang hilera.`,
"Ok":`OK`,
"followingTerminal":`Sumusunod`,
"pdfDownload":`Mag-download ng PDF`,
"timelineCancel":`Sigurado ka ba, gusto mong kanselahin ang timeline?`,
"Truck Stop":`Hintuan ng truck`,
"Gas Station":`Gasolinahan`,
"Weight Station":`Istasyon ng Timbang`,
"location_name_enter":`Pakipasok ang pangalan ng Lokasyon.`,
"locationNameLong":`Ang pangalan ng lokasyon ay dapat na hindi bababa sa 2 character ang haba.`,
"locationAddressLong":`Ang address ng lokasyon ay dapat na hindi bababa sa 2 character ang haba.`,
"locationAddress":`Mangyaring ipasok ang address ng lokasyon.`,
"Name":`Pangalan`,
"Hold to Stop":`Pindutin upang Ihinto`,
"Location Address":`Address ng Lokasyon`,
"Phone Number":`Numero ng telepono`,
"Add":`Idagdag`,
"Category":`Kategorya`,
"backgroundProcess":`Tatakbo ang iyong timeline sa background kapag lumipat ka sa iba pang mga screen.`,
"NotMoving":`Hindi pa gumagalaw?`,
"oneMinuteLongerAlert":`Para tapusin at i-save, kailangan ng FR8 ng hindi bababa sa 1 minutong mas mahabang aktibidad, na may pagbabago sa lokasyon.`,
"editPost":`I-edit ang Post`,
"vedioLimit":`Ang tagal ng video ay dapat na maximum na 30 segundo ang haba.`,
"selectCurentLocation":`Piliin ang Kasalukuyang Lokasyon`,
"noCommentYet":`Wala pang komento`,
"enterFirstComment":`Maunang magkomento.`,
"App_Share":`Ibahagi ang Application`,
"appShareMessage":`ay nagbahagi ng FR8 app. Mag-click sa link sa ibaba upang makita ang mobile application at makita ang mga kasalukuyang oras ng paghihintay ngayon.`,
"appShareMessage2":`FR8 app\n Mag-click sa link sa ibaba upang makita ang mobile application at makita ang mga kasalukuyang oras ng paghihintay ngayon.`,
"deleteCommentReplyAlert":`Sigurado ka ba, gusto mong tanggalin ang tugon sa komentong ito?`,
"enter_first_name_length_alert":`Dapat na hindi bababa sa 3 character ang haba ng pangalan.`,
"enter_last_name_length_alert":`Dapat na hindi bababa sa 3 character ang haba ng apelyido.`,
"location_Setting":`Mga Setting ng Lokasyon`,
"postlikeHeading":`Mga taong gustong mag-post`,
"commentLikeHeading":`Mga taong gustong magkomento`,
"viewProfile":`Tingnan ang Profile`,
"shareListHeading":`Mga taong nagbahagi ng post`,
"Reply":`Sumagot`,
"Reply to":`Tumugon sa`,
"Dislike":`hindi gusto`,
"Smile":`Ngiti`,
"Angry":`Galit`,
"Rolling Eyes":`Rolling Eyes`,
"Thinking":`Nag-iisip`,
"Stop":`Tumigil ka`,
"switchFrom":`Makatanggap ng tumpak na mga abiso sa kaligtasan sa pamamagitan ng paglipat mula sa`,
"Always Allow":`Palaging Payagan`,
"While Using":`Habang Gumagamit`,
"Ask next time":`Magtanong ka sa susunod`,
"Never":`Hindi kailanman`,
"Manage location Settings":`Pamahalaan ang Mga Setting ng lokasyon`,
"Italian":`Italyano`,
"Chinese":`Chinese Simplified (Mandarin)`,
"Hindi":`Hindi`,
"Filipino":`Filipino`,
"Vietnamese":`Vietnamese`,
"Arabic":`Arabic`,
"French":`Pranses`,
"Korean":`Koreano`,
"Russian":`Ruso`,
"Bengali":`Bengali`,
"German":`Aleman`,
regionlNotFound: 'Region not found.',
Region:"Region",
in: 'sa',
"All":'Lahat',


"All":"Lahat",
"saveToPhone":"I-save sa Telepono",
"ADD":"ADD",
"deleteAccount":"Tanggalin ang Account",
"deleteAccountAlert":"Sigurado ka ba, gusto mong tanggalin ang iyong account?",
"replyWrite":"Sumulat ng tugon...",
"Camera":"Camera",
"Image Gallery":"Gallery ng Larawan",
"regionlNotFound":"Hindi nahanap ang rehiyon.",
"Region":"Rehiyon",
"regionSelectAlert":"Maaaring pumili ang user ng maximum na 3 rehiyon.",


"CALL":"TAWAG",
"ADDRESS":"ADDRESS",
"MIN":"MIN",
"About":"Tungkol sa",
"Overview":"Pangkalahatang-ideya",
"Review":"Pagsusuri",
"Timelines":"Mga timeline",
"Rate & Review":"Rate at Review",
"ratings":"Write at Review",
"Write Your Review":"Isulat ang iyong pagkilatis",
"Just now":"Ngayon lang",
'waitTimeIndicator':'Tagapagpahiwatig ng Oras ng Paghihintay',
currentWaitTime:"Kasalukuyang Average na Oras ng Paghihintay",

};

module.exports = {
  constants
};
