import {imageBaseUrl} from '../Config/index'
const constants = {
   // TermsUrl:"http://18.205.207.176:3000/public/pdf/Fr8_App_Terms_Of_Use.pdf",
   TermsUrl:"https://www.fr8.ai/terms",
   // TermsUrl: imageBaseUrl +"public/pdf/Fr8_App_Terms_Of_Use.pdf",
   // PrivacyUrl:"http://18.205.207.176:3000/public/pdf/Fr8_App_Privacy_Policy.pdf",
   PrivacyUrl:"https://www.fr8.ai/privacy",
   // PrivacyUrl: imageBaseUrl + "public/pdf/Fr8_App_Privacy_Policy.pdf",

  "Email":`E-mail`,
  "Enter_Email":`Entrez l'e-mail`,
  "Password":`Mot de passe`,
  "Enter_Password":`Entrez le mot de passe`,
  "Enter_New_Password":`Entrez un nouveau mot de passe`,
  "Forgot_Your_Password":`Vous avez oublié votre mot de passe ?`,
  "Login":`Connexion`,
  "Doesnt_have_an_account":`Vous n'avez pas de compte ?`,
  "Sign_up":`S'inscrire`,
  "Enter_Name":`Entrez le nom`,
  "Enter_first_Name":`entrez votre prénom`,
  "Enter_last_Name":`Entrer le nom de famille`,
  "Enter_Your_Phone_Number":`Entrez votre numéro de téléphone`,
  "Enter_Six_Digit_Verification_Code":`Entrez le code de vérification à six chiffres`,
  "Resend_Verification_Code":`Renvoyer le code de vérification`,
  "Contact_Permission":`Veuillez activer l'autorisation des contacts afin de garantir la sécurité de vos amis.`,
  "Register":`S'inscrire`,
  "Full_Name":`Nom`,
  "Enter_Full_Name":`Entrez le nom`,
  "Username":`Nom d'utilisateur`,
  "Enter_Username":`Entrez le nom d'utilisateur`,
  "Email_Address":`Adresse e-mail`,
  "Enter_Email_Address":`Entrez l'adresse e-mail`,
  "User_Type":`Type d'utilisateur`,
  "Select_User_Type":`Sélectionnez un type d'utilisateur`,
  "Phone_Number":`Numéro de téléphone`,
  "Enter_Phone_Number":`Entrez un numéro de téléphone`,
  "Date_Of_Birth":`Date de naissance`,
  "Select_Date_Of_Birth":`Sélectionnez une date de naissance`,
  "Confirm_Password":`Confirmer le mot de passe`,
  "Enter_Confirm_Password":`Entrez la confirmation du mot de passe`,
  "Agree_Terms_and_Condition":`Accepter les conditions générales`,
  "Forgot_Password":`Mot de passe oublié`,
  "Submit":`Envoyer`,
  "OTP":`OTP`,
  "Enter_OTP":`Entrez un OTP`,
  "Reset_Password":`Réinitialiser le mot de passe`,
  "Edit_Profile":`Modifier le profil`,
  "Edit_Phone_Number":`Modifier le numéro de téléphone`,
  "Update":`Mettre à jour`,
  "Change_Password":`Modifier le mot de passe`,
  "Old_Password":`Ancien mot de passe`,
  "Enter_Old_Password":`Entrez l'ancien mot de passe`,
  "FAQs":`FAQ`,
  "Social_Media_Accounts":`Comptes réseaux sociaux`,
  "Settings":`Paramètres`,
  "FR8":`FR8`,
  "Support_Center":`Centre d'assistance`,
  "Terms_And_Conditions":`Conditions générales`,
  "Privacy_Policy":`Politique de confidentialité`,
  "Change_Language":`Modifier la langue`,
  "Logout":`Déconnexion`,
  "Log_out":`Se déconnecter`,
  "Confirm":`Confirmer`,
  "Cancel":`Annuler`,
  "Please_Select":`Veuillez sélectionner`,
  "Warn_Contacts":`Avertir les contacts`,
  "Search_contacts":`Chercher des contacts`,
  "Friend_Requests":`Demandes d'amis`,
  "Friend_Request":`Demande d'ami`,
  "My_Posts":`Mes publications`,
  "Search_friends":`Chercher des amis, des terminaux, des contacts`,
  "My_Freighting_Network":`Mon réseau de fret`,
  "My_Network":`Mon réseau`,
  "Places":`Lieux`,
  "Friends":`Amis`,
  "Nearby_Terminals":`Terminaux à proximité`,
  "Explore":`Explorer`,
  "Contacts":`Contacts`,
  "Name_Of_User":`Nom d'utilisateur`,
  "Add_Friend":`Ajouter un ami`,
  "Remove_Friend":`Supprimer un ami`,
  "Chat":`Chat`,
  "Post_Details":`Publier des détails`,
  "Live_Streams":`Streams live`,
  "CreatePost":`Créer une publication`,
  "SocialMediaAccounts":`Comptes réseaux sociaux`,
  "Instagram":`Instagram`,
  "Google":`Google`,
  "Facebook":`Facebook`,
  "Support":`Assistance`,
  "Tittle":`Titre`,
  "DescriptionText":`La description`,
  "Enter_Tittle":`Entrer le titre`,
  "UserName":`Nom d'utilisateur`,
  "TerminalDetails":`Détails de terminal`,
  "Location":`Lieu`,
  "Un_Follow":`Ne plus suivre`,
  "Follow":`Suivre`,
  "Record":`Enregistrer`,
  "Warn":`Avertir`,
  "ChatHistory":`Historique du chat`,
  "TerminalName":`Nom de terminal`,
  "Terminal":`Terminal`,
  "English":`Anglais`,
  "Spanish":`Espagnol`,
  "Driver_Type":`Type de conducteur`,
  "Select_Driver_Type":`Sélectionner un type de conducteur`,
  "Users":`Utilisateurs`,
  "Enter_Title":`Entrer un titre`,
  "Type_Message_Here":`Taper le message ici...`,
  "Skip":`Passer`,
  "Friend_request_not_found":`Demande d'ami non trouvée`,
  "Change_Mobile_Number":`Modifier le numéro de téléphone portable`,
  "resend_Otp":`Renvoyer le code de vérification`,
  "post":`Poster`,
  "Friend":`Ami`,
  "NotificationDetail":`Détails des notifications`,
  "noResult":`Aucun résultat trouvé.`,
  "enter_email_alert":`Veuillez entrer une adresse e-mail`,
  "enter_valid_email_alert":`Veuillez entrer une adresse e-mail valide`,
  "enter_password_alert":`Veuillez entrer un mot de passe`,
  "enter_full_name_alert":`Veuillez entrer votre nom`,
  "enter_last_name_alert":`Veuillez saisir le nom de famille.`,
  "enter_full_name_aplhanumeric_alert":`Veuillez entrer un nom entier alphanumérique`,
  "enter_user_name_alert":`Veuillez entrer un nom d'utilisateur`,
  "enter_user_name_length_alert":`Le nom d'utilisateur doit comporter au moins 3 caractères.`,
  "enter_user_type_alert":`Veuillez sélectionner le type d'utilisateur`,
  "enter_driver_type_alert":`Veuillez sélectionner le type de conducteur`,
  "enter_phone_number_alert":`Veuillez entrer un numéro de téléphone`,
  "enter_phone_number_length_alert":`Le numéro de téléphone devrait contenir entre 8 et 15 chiffres.`,
  "enter_Numbers_allowed__phone_alert":`Seuls les chiffres sont autorisés dans le champ téléphone.`,
  "enter_date_of_birth_alert":`Veuillez sélectionner une date de naissance.`,
  "enter_password_length_alert":`Le mot de passe doit contenir au moins 6 caractères.`,
  "enter_confirm_password_alert":`Veuillez entrer la confirmation du mot de passe.`,
  "enter_password_not_match_alert":`Le mot de passe et sa confirmation doivent correspondre.`,
  "enter_terms_conditions_alert":`Veuillez accepter les conditions générales.`,
  "enter_otp_alert":`Veuillez entrer le code de vérification.`,
  "enter__valid_otp_alert":`Veuillez entrer un code de vérification valide.`,
  "enter_old_password_alert":`Veuillez entrer l'ancien mot de passe.`,
  "enter_old_password_length_alert":`L'ancien mot de passe doit contenir au moins 6 caractères.`,
  "enter_new_password_alert":`Veuillez entrer le nouveau mot de passe.`,
  "enter_new_password_length_alert":`Le nouveau mot de passe doit contenir au moins 6 caractères.`,
  "enter_old_cofirm_not_valid_alert":`L'ancien mot de passe et la confirmation du mot de passe doivent correspondre.`,
  "Stream_stopped_by_user":`Vidéo live terminée par`,
  "Loading_streams":`Chargement des streams`,
  "you_are_live_now":`Vous êtes maintenant en direct.`,
  "end_publisher_video":`Êtes-vous sûr de vouloir terminer cette vidéo en direct ?`,
  "logOutAlert":`Êtes-vous sûr de vouloir vous déconnecter ?`,
  "end_publisher_video_successfully":`Vidéo en direct terminée.`,
  "Alert":`Alerte`,
  "PhoneNumber_required_for_login":`Un numéro de téléphone est requis pour se connecter. Cela nous aide aussi à modérer la communauté et à protéger nos utilisateurs.`,
  "Privacy_policy":`EN CONTINUANT VOUS ACCEPTEZ`,
  "Terms":`NOS CONDITIONS GÉNÉRALES`,
  "Policy":`POLITIQUE DE CONFIDENTIALITÉ`,
  "Why_you_need_my_phone_number":`POURQUOI AVEZ-VOUS BESOIN DE MON NUMÉRO DE TÉLÉPHONE ?`,
  "Why_we_need_your_phone_number":`POURQUOI NOUS AVONS BESOIN DE VOTRE  NUMÉRO DE TÉLÉPHONE ?`,
  "verifyAccount":`VÉRIFIER VOTRE COMPTE`,
  "terminalNotFound":`Terminal non trouvé.`,
  "Profile":`Profil`,
  "App_Settings":`Paramètres de l'application`,
  "estimatedTime":`Temps estimé`,
  "estimatedWaitTime":`Minutes d'attente`,
  "youHaveLeft":`Tu es parti`,
  "Citizen_safety_message":`FR8 est un réseau de fret. Nous avons besoin d'un numéro de téléphone à la fois pour vérifier votre identité et garantir que ceux qui ne respectent pas les standards de notre communauté peuvent être supprimés du réseau, lorsque cela est nécessaire.`,
  "something_went_wrong":`Une erreur a eu lieu.`,
  "please_check_your_internet_connection":`Veuillez vérifier votre connexion internet.`,
  "startEndAlert":`L'horaire de départ devrait être avant l'horaire de fin.`,
  "addPost":`Ajouter une publication.`,
  "permissionTitle': 'You had denied the permission to take photo from library',":`Vous avez refusé l'autorisation de prendre des photos à partir de la bibliothèque`,
  "permissionBody":`Voudriez-vous cet accès puis autoriser cela dans les paramètres ?`,
  "videoPermissionTitle":`Vous avez refusé l'autorisation de prendre des photos à partir de la bibliothèque`,
  "TimeLine_post_not_found":`La publication dans la timeline n'a pas été trouvée.`,
  "Timeline_Posts":`Publications Timeline`,
  "Timeline":`Timeline`,
  "trackAtimeLine":`Suivre votre temps d'attente`,
  "Journey":`Aucune chronologie trouvée.`,
  "KM":`km`,
  "Distance_Travelled":`Distance parcourue`,
  "hrs":`heures`,
  "secs":`secondes`,
  "mins":`minutes`,
  "time":`Temps`,
  "wait_time":`Temps d'attente moyen`,
  "Equiment_Photo":`Photo de l'équipement`,
  "Interchange_Receipt":`Réception de l'échange`,
  "video":`Vidéo`,
  "Share":`Partager`,
  "start_time":`Horaire de début`,
  "Report_Post":`Signaler la publication`,
  "endTime":`Horaire de fin`,
  "openTime":`Heure d'ouverture`,
  "closeTime":`La période de fermeture`,
  "distance":`Distance`,
  "Total_time":`Temps total`,
  "Edit_Timeline":`Modifier la timeline`,
  "messageAlert":`Veuillez entrer un message.`,
  "enterMessage":`Entrez votre message...`,
  "Trending_Post":`Publication tendance`,
  "PleaseEnterReportResion":`Veuillez entrer la raison du report.`,
  "trendingPostNotFound":`Aucune publication tendance trouvée.`,
  "Accept":`Accepter`,
  "Reject":`Rejeter`,
  "Allow":`Permettre`,
  "Invite":`Inviter`,
  "postNotFound":`Aucune publication trouvée.`,
  "Cancel_Friend_Request":`Annuler la demande d'ami`,
  "User_Posts":`Publications utilisateur`,
  "Notifications":`Notifications`,
  "No_notifications":`Aucune notification trouvée`,
  "And":`AND`,
  "deletePostAlert":`Êtes-vous sûr de vouloir supprimer cette publication ?`,
  "Yes":`Oui`,
  "No":`Non`,
  "enterTitle":`Veuillez entrer un titre`,
  "pleaseEnterMessage":`Veuillez entrer un message.`,
  "Post_Create":`Créer une publication`,
  "description":`Entrez votre description...`,
  "enterDescription":`Veuillez entrer la description.`,
  "descriptionMax":`Veuillez entrer la description en moins de 1 000 caractères.`,
  "descriptionMin":`La description doit contenir au moins 10 caractères.`,
  "Preview":`Aperçu`,
  "messageMax":`Veuillez entrer un message de moins de 1 000 caractères.`,
  "noUser":`Aucun utilisateur trouvé.`,
  "New":`Nouveau`,
  "No_chat_found":`Aucun chat récent trouvé`,
  "Search_Terminal":`Chercher un terminal`,
  "Receipt_Private":`Reçu privé`,
  "Edit":`Éditer`,
  "Delete":`Supprimer`,
  "postShareMessage":`a partagé la publication Cliquez sur le lien ci-dessous pour afficher la publication`,
  "postShareMessage2":`a partagé la publication Cliquez sur le lien ci-dessous pour afficher la publication`,
  "shareSubject":`FR8 TimeLine Post`,
  "messageCopy":`Message copié`,
  "avaliable24Hours":`Disponible 24 heures`,
  "photo":`PHOTO`,
  "photoLibrary":`GALERIE DE PHOTOS`,
  "photoL":`photo`,
  "photoLibraryL":`Galerie de photos`,
  "reportUser":`Dénoncer un utilisateur`,
  "reasonOfReport":`Raison du rapport`,
  "reportPostAlert":`Êtes-vous sûr de vouloir signaler cette publication ?`,
  // "ForegroundServiceTitle":`L'application FR8 gère votre position en arrière-plan`,
  "ForegroundServiceTitle":`Le suivi des paiements de détention est en cours d'exécution`,
  "Portuguese":`le Portugal`,
  "interChangeDelete":`Êtes-vous sûr de vouloir supprimer Interchange Receipt ?`,
  "equipmentDelete":`Êtes-vous sûr de vouloir supprimer la photo de l'équipement ?`,
  "deleteVideo":`Êtes-vous sûr de vouloir supprimer la vidéo ?`,
  "sentAMessage":`envoyé un message :`,
  "editMessage":`Modifier le message`,
  "continue":`Continuer`,
  "noContact":`Aucun contact trouvé`,
  "Driver":`Chauffeur`,
  "Owner Operator":`Opérateur propriétaire`,
  "Company":`Compagnie`,
  "Air Cargo Carrier":`Transporteur de fret aérien`,
  "Exporter":`Exportateur`,
  "Freight Broker":`Courtier de fret`,
  "Importer":`Importateur`,
  "Shipper":`Expéditeur`,
  "Trucking":`Camionnage`,
  "Warehouse":`Dépot`,
  "Company Driver":`Chauffeur de l'entreprise`,
  "OKAY":`D'ACCORD`,
  "installMessage":`Bonjour FR8 souhaitez-vous inviter à installer l'application.`,
  "warned":`averti`,
  "WaitingAt":`en attente à`,
  "openFr8":`Ouvrez l'application Fr8 pour afficher votre temps d'attente estimé.`,
  "day":`journée`,
  "days":`jours`,
  "hour":`  heure`,
  "hours":`  les heures`,
  "minute":`  minute`,
  "minutes":`  minutes`,
  "second":`  seconde`,
  "seconds":`  secondes`,
  "openApp":`Ouvrez l'application pour synchroniser votre statut`,
  "openAppBody":`Pour une expérience optimale, autorisez l'application FR8 à rester ouverte en arrière-plan. Cela permet de garder votre chronologie et l'horodatage du terminal précis.`,
  "Comment":`Commenter`,
  "Comments":`commentaires`,
  "Like":`Comme`,
  "noComment":`Aucun commentaire trouvé`,
  "deleteCommentAlert":`Êtes-vous sûr de vouloir supprimer le commentaire ?`,
  "enterTheComment":`Veuillez saisir le commentaire.`,
  "enterYourComment":`Entrez votre commentaire...`,
  "DeeplinkShare":`Partager en tant que lien`,
  "Shares":`Actions`,
  "shareasPost":`Partager l'article`,
  "hasShared":`a partagé`,
  "whatsOnMind":`Qu'est-ce qui préoccupe votre esprit?`,
  "inGate":`Dans`,
  "outGate":`Dehors`,
  "With":`avec`,
  "others":`autres`,
  "tagFriends":`Marquer des amis`,
  "done":`Terminé`,
  "friendSearch":`Rechercher des amis`,
  "checkIN":`Enregistrement`,
  "tagUsers":`Utilisateurs marqués`,
  "safeTrip":` Vous pouvez maintenant partager votre temps d'attente. Bon voyage !`,
  "addLocation":`Ajouter un emplacement`,
  "locationSelect":`Veuillez sélectionner l'emplacement.`,
  "attach":`Joindre des fichiers`,
  "selectImage":`Veuillez sélectionner des images ou une vidéo à publier.`,
  "noPlace":`Aucun endroit trouvé`,
  "deleteMedia":`Êtes-vous sûr de vouloir supprimer ce média ?`,
  "deleteNotification":`Êtes-vous sûr de vouloir supprimer cette notification ?`,
  "loading":`Chargement…`,
  "next":`Prochain`,
  "ttlUserInterminal":`Nombre d'utilisateurs à l'intérieur du terminal :`,
  "members":`Membres à l'intérieur`,
  "member":`Membre à l'intérieur`,
  "useLocation":`Utilisez votre emplacement`,
  "firstPermissionTitle":`Pour voir les cartes des activités suivies automatiquement, autorisez FR8 à utiliser votre position en permanence.`,
  "noThanks":`Non merci`,
  "turnOn":`Allumer`,
  "newVersion":`Nouvelle version`,
  "versionDescription":`Cette version de l'application est obsolète, veuillez mettre à jour la dernière version pour débloquer de nouvelles fonctionnalités étonnantes pour vous aider à obtenir les nouvelles fonctionnalités les plus précises et les plus étonnantes. N'oubliez pas de définir les autorisations de localisation sur Toujours autoriser afin que l'application calcule les temps d'attente du terminal pour vous en arrière-plan.`,
  "firstPermissionDesc":`FR8 utilisera votre localisation en arrière-plan pour permettre vos enregistrements précis de vos déplacements dans les terminaux et calculer le temps d'attente et l'horodatage.`,
  "validUserName":`Seuls les lettres (a-z), les chiffres (0-9), les points (.) et le trait de soulignement (_) sont autorisés.`,
  "user_name_start":`Le nom d'utilisateur ne doit pas commencer par des points (.)`,
  "onlyNumberAlert":`Le nom d'utilisateur ne peut pas contenir que des chiffres.`,
  "user_name_end":`Le nom d'utilisateur ne doit pas se terminer par des points (.)`,
  "twoDots":`Le nom d'utilisateur ne doit pas comporter plus d'un point (.) d'affilée.`,
  "Ok":`d'accord`,
  "followingTerminal":`Suivant`,
  "pdfDownload":`Télécharger le PDF`,
  "timelineCancel":`Êtes-vous sûr de vouloir annuler la chronologie ?`,
  "Truck Stop":`Arrêt de camion`,
  "Gas Station":`Station-essence`,
  "Weight Station":`Station de poids`,
  "location_name_enter":`Veuillez saisir le nom de l'emplacement.`,
  "locationNameLong":`Le nom de l'emplacement doit comporter au moins 2 caractères.`,
  "locationAddressLong":`L'adresse de l'emplacement doit comporter au moins 2 caractères.`,
  "locationAddress":`Veuillez saisir l'adresse du lieu.`,
  "Name":`Nom`,
  "Hold to Stop":`Tenir pour arrêter`,
  "Location Address":`Adresse de l'emplacement`,
  "Phone Number":`Numéro de téléphone`,
  "Add":`Ajouter`,
  "Category":`Catégorie`,
  "backgroundProcess":`Votre chronologie s'exécutera en arrière-plan lorsque vous passerez à d'autres écrans.`,
  "NotMoving":`Vous ne bougez pas encore ?`,
  "oneMinuteLongerAlert":`Pour terminer et enregistrer, FR8 a besoin d'au moins 1 minute d'activité supplémentaire, avec un changement de lieu.`,
  "editPost":`Modifier le message`,
  "vedioLimit":`La durée de la vidéo doit être de 30 secondes maximum.`,
  "selectCurentLocation":`Sélectionnez l'emplacement actuel`,
  "noCommentYet":`aucun commentaire pour l'instant`,
  "enterFirstComment":`Soyez le premier à commenter.`,
  "App_Share":`Partager l'application`,
  "appShareMessage":`a partagé l'application FR8. Cliquez sur le lien ci-dessous pour voir l'application mobile et voir les temps d'attente actuels aujourd'hui.`,
  "appShareMessage2":`FR8\n Cliquez sur le lien ci-dessous pour voir l'application mobile et voir les temps d'attente actuels aujourd'hui.`,
  "deleteCommentReplyAlert":`Êtes-vous sûr de vouloir supprimer cette réponse au commentaire ?`,
  "enter_first_name_length_alert":`Le prénom doit comporter au moins 3 caractères.`,
  "enter_last_name_length_alert":`Le nom de famille doit comporter au moins 3 caractères.`,
  "location_Setting":`Les paramètres de localisation`,
  "postlikeHeading":`Les gens qui aiment la publication`,
  "commentLikeHeading":`Les gens qui aiment commenter`,
  "viewProfile":`Voir le profil`,
  "shareListHeading":`Les personnes qui ont partagé la publication`,
  "Reply":`Répondre`,
  "Reply to":`Répondre à`,
  "Dislike":`Ne pas aimer`,
  "Smile":`Le sourire`,
  "Angry":`En colère`,
  "Rolling Eyes":`Yeux roulants`,
  "Thinking":`En pensant`,
  "Stop":`Arrêter`,
  "switchFrom":`Recevez des notifications de sécurité précises en passant de`,
  "Always Allow":`Toujours autoriser`,
  "While Using":`Tout en utilisant`,
  "Ask next time":`Demande la prochaine fois`,
  "Never":`Jamais`,
  "Manage location Settings":`Gérer les paramètres de localisation`,
  "Italian":`italien`,
  "Chinese":`chinois simplifié (mandarin)`,
  "Hindi":`hindi`,
  "Filipino":`Philippin`,
  "Vietnamese":`vietnamien`,
  "Arabic":`arabe`,
  "French":`français`,
  "Korean":`coréen`,
  "Russian":`russe`,
  "Bengali":`bengali`,
  "German":`Allemand`,
  regionlNotFound: 'Region not found.',
  Region:"Region",
  in: 'dans',
  posts: 'Publications',

  "All":"Tout",
"saveToPhone":"Enregistrer sur le téléphone",
"ADD":"AJOUTER",
"deleteAccount":"Supprimer le compte",
"deleteAccountAlert":"Êtes-vous sûr de vouloir supprimer votre compte ?",
"replyWrite":"Écrire une réponse...",
"Camera":"Appareil photo",
"Image Gallery":"Galerie d'images",
"regionlNotFound":"Région introuvable.",
"Region":"Région",
"regionSelectAlert":"L'utilisateur peut sélectionner un maximum de 3 régions.",

"CALL":"APPEL",
"ADDRESS":"ADRESSE",
"MIN":"MIN",
"About":"À propos de",
"Overview":"Aperçu",
"Review":"Examen",
"Timelines":"Délais",
"Rate & Review":"Noter et commenter",
"ratings":"Noter et commenter",
"Write Your Review":"Donnez votre avis",
"Just now":"Juste maintenant",
'waitTimeIndicator':`Indicateur de temps d'attente`,
currentWaitTime:"Temps d'attente moyen actuel",


};

module.exports = {
  constants
};
