import {imageBaseUrl} from '../Config/index'
const constants = {
   // TermsUrl:"http://18.205.207.176:3000/public/pdf/Fr8_App_Terms_Of_Use.pdf",
   TermsUrl:"https://www.fr8.ai/terms",
   // TermsUrl: imageBaseUrl +"public/pdf/Fr8_App_Terms_Of_Use.pdf",
   // PrivacyUrl:"http://18.205.207.176:3000/public/pdf/Fr8_App_Privacy_Policy.pdf",
   PrivacyUrl:"https://www.fr8.ai/privacy",
   // PrivacyUrl: imageBaseUrl + "public/pdf/Fr8_App_Privacy_Policy.pdf",
//   "Email":`E-Mail`,
// "Enter_Email":``,
// "Password":`Passwort`,
// "Enter_Password":`Passwort_eingeben`,
// "Enter_New_Password":`Neues Passwort eingeben`,
// "Forgot_Your_Password":`Passwort vergessen?`,
// "Login":`Einloggen`,
// "Doesnt_have_an_account":`Hat kein Konto?`,
// "Sign_up":`Registrieren`,
// "Enter_Name":`Name eingeben`,
// "Enter_first_Name":`Bitte Vornamen eingeben`,
// "Enter_last_Name":`Nachnamen eingeben`,
// "Enter_Your_Phone_Number":`Geben Sie Ihre Telefonnummer ein`,
// "Enter_Six_Digit_Verification_Code":`Geben Sie den 6-stelligen Bestätigungscode ein`,
// "Resend_Verification_Code":`Bestätigungscode erneut senden`,
// "Contact_Permission":`Bitte aktivieren Sie die Berechtigung für Kontakte, um Ihre Freunde zu schützen.`,
// "Register":`Registrieren`,
// "Full_Name":`Vollständiger Name`,
// "Enter_Full_Name":`Vollständigen Namen eingeben`,
// "Username":`Benutzername`,
// "Enter_Username":`Benutzernamen eingeben`,
// "Email_Address":`E-Mail-Adresse`,
// "Enter_Email_Address":`E-Mail-Adresse eingeben`,
// "User_Type":`Benutzertyp`,
// "Select_User_Type":`Benutzertyp auswählen`,
// "Phone_Number":`Telefonnummer`,
// "Enter_Phone_Number":`Telefonnummer eingeben`,
// "Date_Of_Birth":`Geburtsdatum`,
// "Select_Date_Of_Birth":`Geburtsdatum auswählen`,
// "Confirm_Password":`Passwort bestätigen`,
// "Enter_Confirm_Password":`Passwort-Bestätigung eingeben`,
// "Agree_Terms_and_Condition":`Allgemeinen Geschäftsbedingungen zustimmen`,
// "Forgot_Password":`Passwort vergessen  `,
// "Submit":`Abschicken`,
// "OTP":`OTP`,
// "Enter_OTP":`OTP_eingeben`,
// "Reset_Password":`Passwort zurücksetzen`,
// "Edit_Profile":`Profil bearbeiten`,
// "Edit_Phone_Number":`Telefonnummer bearbeiten`,
// "Update":`Aktualisieren`,
// "Change_Password":`Passwort ändern`,
// "Old_Password":`Altes Passwort`,
// "Enter_Old_Password":`Altes Passwort eingeben`,
// "FAQs":`FAQ`,
// "Social_Media_Accounts":`Konten auf sozialen Medien`,
// "Settings":`Einstellungen`,
// "FR8":`FR8`,
// "Support_Center":`Support Center`,
// "Terms_And_Conditions":`Allgemeine Geschäftsbedingungen `,
// "Privacy_Policy":`Datenschutzrichtlinie`,
// "Change_Language":`Sprache ändern`,
// "Logout":`Ausloggen`,
// "Log_out":`Ausloggen`,
// "Confirm":`Bestätigen`,
// "Cancel":`Abbrechen`,
// "Please_Select":`Bitte auswählen`,
// "Warn_Contacts":`Kontakte warnen`,
// "Search_contacts":`Kontakte durchsuchen`,
// "Friend_Requests":`Freundschaftsanfragen`,
// "Friend_Request":`Freundschaftsanfrage `,
// "My_Posts":`Meine Beiträge`,
// "Search_friends":`Nach Freunden, Terminals, Kontakten suchen`,
// "My_Freighting_Network":`Mein Frachtnetzwerk`,
// "My_Network":`Mein Netzwerk`,
// "Places":`Standorte`,
// "Friends":`Freunde`,
// "Nearby_Terminals":`Terminals in der Nähe`,
// "Explore":`Erkunden`,
// "Contacts":`Kontake`,
// "Name_Of_User":`Name des Benutzers`,
// "Add_Friend":`Freund hinzufügen`,
// "Remove_Friend":`Freund entfernen`,
// "Chat":`Chat`,
// "Post_Details":`Details posten`,
// "Live_Streams":`Live Streams`,
// "CreatePost":`Beitrag erstellen`,
// "SocialMediaAccounts":`Konten auf sozialen Medien`,
// "Instagram":`Instagram`,
// "Google":`Google`,
// "Facebook":`Facebook`,
// "Support":`Support`,
// "Tittle":`Titel   `,
// "DescriptionText":`Beschreibung`,
// "Enter_Tittle":`Titel eingeben`,
// "UserName":`Benutzername`,
// "TerminalDetails":`Terminal-Details`,
// "Location":`Standort `,
// "Un_Follow":`Nicht mehr folgen`,
// "Follow":`Folgen`,
// "Record":`Aufzeichnung`,
// "Warn":`Warnen`,
// "ChatHistory":`Chatverlauf`,
// "TerminalName":`Name des Terminals`,
// "Terminal":`Terminal`,
// "English":`Englisch`,
// "Spanish":`Spanisch`,
// "Driver_Type":`Fahrertyp`,
// "Select_Driver_Type":`Fahrertyp auswählen`,
// "Users":`Benutzer`,
// "Enter_Title":`Titel eingeben`,
// "Type_Message_Here":`Nachricht hier eingeben...`,
// "Skip":`Überspringen`,
// "Friend_request_not_found":`Freundschaftsanfrage nicht gefunden.`,
// "Change_Mobile_Number":`Handynummer ändern`,
// "resend_Otp":`Bestätigungscode erneut senden`,
// "post":``,
// "Friend":``,
// "NotificationDetail":`Benachrichtigungsdetails`,
// "noResult":`Keine Einträge gefunden.`,
// "enter_email_alert":`Bitte E-Mail-Adresse eingeben.`,
// "enter_valid_email_alert":`Bitte gültige E-Mail-Adresse eingeben.`,
// "enter_password_alert":`Bitte Passwort eingeben.`,
// "enter_full_name_alert":`Bitte vollständigen Namen eingeben.`,
// "enter_last_name_alert":`Bitte Nachnamen eingeben.`,
// "enter_full_name_aplhanumeric_alert":`Bitte alphanumerisch im vollständigen Namen eingeben.`,
// "enter_user_name_alert":`Bitte Benutzernamen eingeben.`,
// "enter_user_name_length_alert":`Der Benutzername sollte mindestens 3 Zeichen lang sein.`,
// "enter_user_type_alert":`Bitte Benutzertyp auswählen.`,
// "enter_driver_type_alert":`Bitte Fahrertyp auswählen.`,
// "enter_phone_number_alert":`Bitte Telefonnummer eingeben.`,
// "enter_phone_number_length_alert":`Telefonnummer sollte zwischen 8 und 15 Zeichen haben.`,
// "enter_Numbers_allowed__phone_alert":`Im Telefonfeld sind nur Nummern zulässig.`,
// "enter_date_of_birth_alert":`Bitte Geburtsdatum auswählen.`,
// "enter_password_length_alert":`Passwort muss mindestens 6 Zeichen lang sein.`,
// "enter_confirm_password_alert":`Bitte Passwortbestätigung eingeben.`,
// "enter_password_not_match_alert":`Passwort und Passwortbestätigung müssen übereinstimmen.`,
// "enter_terms_conditions_alert":`enter_terms_conditions_alert: "Bitte akzeptieren Sie die Allgemeinen Geschäftsbedingungen.",`,
// "enter_otp_alert":`Bitte Bestätigungscode eingeben.`,
// "enter__valid_otp_alert":`Bitte gültigen Bestätigungscode eingeben.`,
// "enter_old_password_alert":`Bitte altes Passwort eingeben.`,
// "enter_old_password_length_alert":`Altes Passwort muss mindestens 6 Zeichen lang sein.`,
// "enter_new_password_alert":`Bitte neues Passwort eingeben.`,
// "enter_new_password_length_alert":`Neues Passwort muss mindestens 6 Zeichen lang sein.`,
// "enter_old_cofirm_not_valid_alert":`Altes Passwort und Passwortbestätigung müssen übereinstimmen.`,
// "Stream_stopped_by_user":`Live-Video beendet von`,
// "Loading_streams":`Streams werden geladen`,
// "you_are_live_now":`Sie sind jetzt live.`,
// "end_publisher_video":`Sind Sie sicher, dass Sie dieses Live-Video beenden wollen?`,
// "logOutAlert":`Sind Sie sicher, dass Sie sich ausloggen wollen?`,
// "end_publisher_video_successfully":`Live-Video wurde beendet.`,
// "Alert":``,
// "PhoneNumber_required_for_login":`Für den Login ist eine Telefonnummer erforderlich. Das hilft uns außerdem, die Community zu moderieren und unsere Benutzer zu schützen.`,
// "Privacy_policy":`WENN SIE FORTFAHREN, AKZEPTIEREN SIE UNSERE`,
// "Terms":`ALLGEMEINEN GESCHÄFTSBEDINGUNGEN `,
// "Policy":`DATENSCHUTZRICHTLINIE`,
// "Why_you_need_my_phone_number":`WARUM BENÖTIGEN SIE MEINE TELEFONNUMMER`,
// "Why_we_need_your_phone_number":`WARUM WIR IHRE TELEFONNUMMER BENÖTIGEN`,
// "verifyAccount":`VERIFIZIEREN SIE IHR KONTO`,
// "terminalNotFound":`Terminal wurde nicht gefunden.`,
// "Profile":`Profil`,
// "App_Settings":`App-Einstellungen`,
// "estimatedTime":`Geschätzte Zeit`,
// "estimatedWaitTime":`Minuten gewartet`,
// "youHaveLeft":`Du bist gegangen`,
// "Citizen_safety_message":`Fr8 ist ein Frachtnetzwerk. Wir benötigen eine Telefonnummer, um Ihre Identität zu überprüfen und um sicherzustellen, dass diejenigen, die gegen unsere Community-Standards verstoßen, gegebenenfalls aus dem Netzwerk entfernt werden können.`,
// "something_went_wrong":`Etwas ist schiefgelaufen.`,
// "please_check_your_internet_connection":`Bitte überprüfen Sie Ihre Internetverbindung.`,
// "startEndAlert":`Die Startzeit sollte weniger als die Endzeit sein.`,
// "addPost":`Beitrag hinuzfügen`,
// "permissionTitle': 'You had denied the permission to take photo from library',":`Sie hatten die Berechtigung verweigert, Fotos aus der Bibliothek aufzunehmen`,
// "permissionBody":`Möchten Sie darauf zugreifen und dann die Berechtigung in den Einstellungen zulassen?`,
// "videoPermissionTitle":`Sie hatten die Berechtigung verweigert, Videos aus der Bibliothek aufzunehmen`,
// "TimeLine_post_not_found":`Beitrag in der Zeitlinie nicht gefunden.`,
// "Timeline_Posts":`Zeitlinien-Beiträge`,
// "Timeline":`Zeitlinie `,
// "trackAtimeLine":`Verfolgen Sie Ihre Wartezeit`,
// "Journey":`Keine Zeitachse gefunden.`,
// "KM":`km`,
// "Distance_Travelled":`Zurückgelegte Strecke`,
// "hrs":`Std`,
// "secs":`Sek`,
// "mins":`Min`,
// "time":`Zeit`,
// "wait_time":`Durschn. Wartezeit`,
// "Equiment_Photo":`Ausrüstungsfoto`,
// "Interchange_Receipt":`Interchange-Beleg`,
// "video":`Video`,
// "Share":`Teilen`,
// "start_time":`Startzeit`,
// "Report_Post":`Beitrag melden`,
// "endTime":`Endzeit`,
// "openTime":``,
// "closeTime":``,
// "distance":`Distanz`,
// "Total_time":`Gesamtzeit`,
// "Edit_Timeline":`Zeitlinie bearbeiten`,
// "messageAlert":`Bitte geben Sie eine Nachricht ein.`,
// "enterMessage":`Geben Sie Ihre Nachricht ein...`,
// "Trending_Post":`Trendender Beitrag`,
// "PleaseEnterReportResion":`Bitte geben Sie einen Grund für die Meldung ein.`,
// "trendingPostNotFound":`Kein trendender Beitrag gefunden.`,
// "Accept":`Akzeptieren`,
// "Reject":`Ablehnen`,
// "Allow":`Erlauben`,
// "Invite":`Einladen`,
// "postNotFound":`Kein Beitrag gefunden.`,
// "Cancel_Friend_Request":`Freundschaftsanfrage abbrechen`,
// "User_Posts":`Benutzerbeiträge`,
// "Notifications":`Benachrichtigungen`,
// "No_notifications":`Keine Benachrichtigungen gefunden.`,
// "And":`UND`,
// "deletePostAlert":`Sind Sie sicher, dass Sie diesen Beitrag löschen wollen?`,
// "Yes":`Ja`,
// "No":`Nein`,
// "enterTitle":`Bitte Titel eingeben.`,
// "pleaseEnterMessage":`Bitte Nachricht eingeben.`,
// "Post_Create":`Beitrag erstellen`,
// "description":`Geben Sie Ihre Beschreibung ein...`,
// "enterDescription":`Bitte die Beschreibung eingeben.`,
// "descriptionMax":`Bitte Beschreibung eingeben, die kürzer als 1000 Zeichen ist.`,
// "descriptionMin":`Beschreibung muss mindestens 10 Zeichen lang sein.`,
// "Preview":`Vorschau.`,
// "messageMax":`Bitte Nachricht mit weniger als als 1000 Zeichen eingeben.`,
// "noUser":`Kein Benutzer gefunden.`,
// "New":`Neu`,
// "No_chat_found":`Kein aktueller Chat gefunden`,
// "Search_Terminal":`Terminal suchen`,
// "Receipt_Private":`Empfang privat`,
// "Edit":``,
// "Delete":``,
// "postShareMessage":`hat einen Beitrag geteilt Klicken Sie auf den folgenden Link, um den Beitrag anzuzeigen`,
// "shareSubject":`FR8 Timeline-Beitrag`,
// "messageCopy":`Nachricht kopiert`,
// "avaliable24Hours":`24 Stunden verfügbar`,
// "photo":``,
// "photoLibrary":``,
// "photoL":``,
// "photoLibraryL":``,
// "reportUser":`Benutzer melden`,
// "reasonOfReport":`Grund der Meldung`,
// "reportPostAlert":`Möchten Sie diesen Beitrag wirklich melden?`,
// "ForegroundServiceTitle":`Die FR8-App verwaltet Ihren Standort im Hintergrund`,
// "Portuguese":`Portugal`,
// "interChangeDelete":`Sind Sie sicher, dass Sie die Interchange-Quittung löschen möchten?`,
// "equipmentDelete":`Sind Sie sicher, dass Sie das Gerätefoto löschen möchten?`,
// "deleteVideo":`Möchten Sie das Video wirklich löschen?`,
// "sentAMessage":`eine Nachricht gesendet:`,
// "editMessage":`Nachricht bearbeiten`,
// "continue":`Weitermachen`,
// "noContact":`Keine Kontakte gefunden`,
// "Driver":``,
// "Owner Operator":``,
// "Company":``,
// "Air Cargo Carrier":``,
// "Exporter":``,
// "Freight Broker":``,
// "Importer":``,
// "Shipper":``,
// "Trucking":``,
// "Warehouse":``,
// "Company Driver":``,
// "OKAY":`OKAY`,
// "installMessage":`Hallo FR8, möchten Sie einladen, die Anwendung zu installieren.`,
// "warned":`gewarnt`,
// "WaitingAt":`Warten um`,
// "openFr8":`Öffnen Sie die Fr8-App, um Ihre geschätzte Wartezeit anzuzeigen.`,
// "day":`Tag`,
// "days":`Tage`,
// "hour":``,
// "hours":``,
// "minute":``,
// "minutes":``,
// "second":``,
// "seconds":``,
// "openApp":`Öffnen Sie die App, um Ihren Status zu synchronisieren`,
// "openAppBody":`Lassen Sie die FR8-App für ein optimales Erlebnis im Hintergrund geöffnet. Dadurch bleiben Ihre Zeitleiste und der Terminal-Zeitstempel genau.`,
// "Comment":`Kommentar`,
// "Comments":`Kommentare`,
// "Like":`Mögen`,
// "noComment":`Kein Kommentar gefunden`,
// "deleteCommentAlert":`Möchten Sie den Kommentar wirklich löschen?`,
// "enterTheComment":`Bitte geben Sie den Kommentar ein.`,
// "enterYourComment":`Geben Sie Ihren Kommentar ein...`,
// "DeeplinkShare":`Als Link teilen`,
// "Shares":`Anteile`,
// "shareasPost":`Post teilen`,
// "hasShared":`hat geteilt`,
// "whatsOnMind":`Was haben Sie auf dem Herzen?`,
// "inGate":`In`,
// "outGate":`aus`,
// "With":`mit`,
// "others":`Andere`,
// "tagFriends":`Freunde markieren`,
// "done":`Fertig`,
// "friendSearch":`Freunde suchen`,
// "checkIN":`Check-In`,
// "tagUsers":`Getaggte Benutzer`,
// "safeTrip":` Sie können jetzt Ihre Wartezeit teilen. Komme gut nach Hause!`,
// "addLocation":`Ort hinzufügen`,
// "locationSelect":`Bitte wählen Sie den Standort aus.`,
// "attach":`Dateien anhängen`,
// "selectImage":`Bitte wählen Sie Bilder oder Videos zum Posten aus.`,
// "noPlace":`Keine Orte gefunden`,
// "deleteMedia":`Möchten Sie dieses Medium wirklich löschen?`,
// "deleteNotification":`Möchten Sie diese Benachrichtigung wirklich löschen?`,
// "loading":`Wird geladen…`,
// "next":`Nächste`,
// "ttlUserInterminal":``,
// "members":`Mitglieder drin`,
// "member":`Mitglied drin`,
// "useLocation":`Verwenden Sie Ihren Standort`,
// "firstPermissionTitle":`Um Karten für automatisch verfolgte Aktivitäten anzuzeigen, erlauben Sie dem FR8, Ihren Standort die ganze Zeit zu verwenden.`,
// "noThanks":`Nein danke`,
// "turnOn":`Anmachen`,
// "newVersion":`Neue Version`,
// "versionDescription":`Diese Version der App ist veraltet, bitte aktualisieren Sie auf die neueste Version, um erstaunliche neue Funktionen freizuschalten, damit Sie die genauesten und erstaunlichsten neuen Funktionen erhalten. Vergessen Sie nicht, die Standortberechtigungen auf „Immer zulassen“ zu setzen, damit die App im Hintergrund Terminal-Wartezeiten für Sie berechnet.`,
// "firstPermissionDesc":`FR8 verwendet Ihren Standort im Hintergrund, um Ihre Fahrten in Terminals präzise aufzuzeichnen und Wartezeiten und Zeitstempel zu berechnen.`,
// "validUserName":`Es sind nur Buchstaben (a-z), Zahlen (0-9), Punkte (.) und Unterstrich (_) erlaubt.`,
// "user_name_start":`Der Benutzername sollte nicht mit Punkten (.) beginnen.`,
// "onlyNumberAlert":`Benutzername darf nicht nur Zahlen enthalten.`,
// "user_name_end":`Der Benutzername darf nicht mit Punkten (.) enden.`,
// "twoDots":`Der Benutzername sollte nicht mehr als einen Punkt (.) hintereinander haben.`,
// "Ok":``,
// "followingTerminal":``,
// "pdfDownload":``,
// "timelineCancel":`Möchten Sie die Zeitachse wirklich abbrechen?`,
// "Truck Stop":`Raststätte`,
// "Gas Station":`Tankstelle`,
// "Weight Station":`Gewichtsstation`,
// "location_name_enter":`Bitte geben Sie den Standortnamen ein.`,
// "locationNameLong":`Der Standortname sollte mindestens 2 Zeichen lang sein.`,
// "locationAddressLong":`Die Standortadresse sollte mindestens 2 Zeichen lang sein.`,
// "locationAddress":`Bitte Standortadresse eingeben.`,
// "Name":`Name`,
// "Hold to Stop":`Zum Stoppen halten`,
// "Location Address":`Standort-Adresse`,
// "Phone Number":`Telefonnummer`,
// "Add":`Hinzufügen`,
// "Category":``,
// "backgroundProcess":``,
// "NotMoving":``,
// "oneMinuteLongerAlert":``,
// "editPost":``,
// "vedioLimit":``,
// "selectCurentLocation":``,
// "noCommentYet":`Noch keine Kommentare`,
// "enterFirstComment":`Sei der erste der kommentiert.`,
// "App_Share":`Anwendung teilen`,
// "appShareMessage":`hat die FR8-App geteilt. Klicken Sie auf den folgenden Link, um die mobile Anwendung anzuzeigen und die aktuellen Wartezeiten für heute anzuzeigen.`,
// "deleteCommentReplyAlert":`Möchten Sie diese Kommentarantwort wirklich löschen?`,
// "enter_first_name_length_alert":`Der Vorname sollte mindestens 3 Zeichen lang sein.`,
// "enter_last_name_length_alert":`Der Nachname sollte mindestens 3 Zeichen lang sein.`,
// "location_Setting":`Ortseinstellungen`,
// "postlikeHeading":`Leute, denen Post gefällt`,
// "commentLikeHeading":`Leute, die gerne kommentieren`,
// "viewProfile":`Profil anzeigen`,
// "shareListHeading":`Personen, die Beiträge geteilt haben`,
// "Reply":`Antwort`,
// "Reply to":`Antwort an`,
// "Dislike":`Nicht mögen`,
// "Smile":`Lächeln`,
// "Angry":`Verärgert`,
// "Rolling Eyes":`Augen rollen`,
// "Thinking":`Denken`,
// "Stop":`Stoppen`,
// "switchFrom":`Erhalten Sie genaue Sicherheitsmeldungen, indem Sie von wechseln`,
// "Always Allow":`Immer erlaubt`,
// "While Using":`Während dem Benutzen`,
// "Ask next time":`Frag beim nächsten Mal`,
// "Never":`noch nie`,
// "Manage location Settings":``,
// "Italian":`Italienisch`,
// "Chinese":`Chinesisch vereinfacht (Mandarin),`,
// "Hindi":`Hindi`,
// " Filipino :":` Philippinisch`,
// "Vietnamese":`Vietnamesisch`,
// "Arabic":`Arabisch`,
// "French":`Französisch`,
// "Korean":`Koreanisch`,
// "Russian":`Russisch`,
// " Bengali ":` Bengali`,
// "German":`Deutsch`,  



"Email":`E-Mail`,
"Enter_Email":`Email eingeben`,
"Password":`Passwort`,
"Enter_Password":`Passwort_eingeben`,
"Enter_New_Password":`Neues Passwort eingeben`,
"Forgot_Your_Password":`Passwort vergessen?`,
"Login":`Einloggen`,
"Doesnt_have_an_account":`Hat kein Konto?`,
"Sign_up":`Registrieren`,
"Enter_Name":`Name eingeben`,
"Enter_first_Name":`Bitte Vornamen eingeben`,
"Enter_last_Name":`Nachnamen eingeben`,
"Enter_Your_Phone_Number":`Geben Sie Ihre Telefonnummer ein`,
"Enter_Six_Digit_Verification_Code":`Geben Sie den 6-stelligen Bestätigungscode ein`,
"Resend_Verification_Code":`Bestätigungscode erneut senden`,
"Contact_Permission":`Bitte aktivieren Sie die Berechtigung für Kontakte, um Ihre Freunde zu schützen.`,
"Register":`Registrieren`,
"Full_Name":`Vollständiger Name`,
"Enter_Full_Name":`Vollständigen Namen eingeben`,
"Username":`Benutzername`,
"Enter_Username":`Benutzernamen eingeben`,
"Email_Address":`E-Mail-Adresse`,
"Enter_Email_Address":`E-Mail-Adresse eingeben`,
"User_Type":`Benutzertyp`,
"Select_User_Type":`Benutzertyp auswählen`,
"Phone_Number":`Telefonnummer`,
"Enter_Phone_Number":`Telefonnummer eingeben`,
"Date_Of_Birth":`Geburtsdatum`,
"Select_Date_Of_Birth":`Geburtsdatum auswählen`,
"Confirm_Password":`Passwort bestätigen`,
"Enter_Confirm_Password":`Passwort-Bestätigung eingeben`,
"Agree_Terms_and_Condition":`Allgemeinen Geschäftsbedingungen zustimmen`,
"Forgot_Password":`Passwort vergessen  `,
"Submit":`Abschicken`,
"OTP":`OTP`,
"Enter_OTP":`OTP_eingeben`,
"Reset_Password":`Passwort zurücksetzen`,
"Edit_Profile":`Profil bearbeiten`,
"Edit_Phone_Number":`Telefonnummer bearbeiten`,
"Update":`Aktualisieren`,
"Change_Password":`Passwort ändern`,
"Old_Password":`Altes Passwort`,
"Enter_Old_Password":`Altes Passwort eingeben`,
"FAQs":`FAQ`,
"Social_Media_Accounts":`Konten auf sozialen Medien`,
"Settings":`Einstellungen`,
"FR8":`FR8`,
"Support_Center":`Support Center`,
"Terms_And_Conditions":`Allgemeine Geschäftsbedingungen `,
"Privacy_Policy":`Datenschutzrichtlinie`,
"Change_Language":`Sprache ändern`,
"Logout":`Ausloggen`,
"Log_out":`Ausloggen`,
"Confirm":`Bestätigen`,
"Cancel":`Abbrechen`,
"Please_Select":`Bitte auswählen`,
"Warn_Contacts":`Kontakte warnen`,
"Search_contacts":`Kontakte durchsuchen`,
"Friend_Requests":`Freundschaftsanfragen`,
"Friend_Request":`Freundschaftsanfrage `,
"My_Posts":`Meine Beiträge`,
"Search_friends":`Nach Freunden, Terminals, Kontakten suchen`,
"My_Freighting_Network":`Mein Frachtnetzwerk`,
"My_Network":`Mein Netzwerk`,
"Places":`Standorte`,
"Friends":`Freunde`,
"Nearby_Terminals":`Terminals in der Nähe`,
"Explore":`Erkunden`,
"Contacts":`Kontake`,
"Name_Of_User":`Name des Benutzers`,
"Add_Friend":`Freund hinzufügen`,
"Remove_Friend":`Freund entfernen`,
"Chat":`Chat`,
"Post_Details":`Details posten`,
"Live_Streams":`Live Streams`,
"CreatePost":`Beitrag erstellen`,
"SocialMediaAccounts":`Konten auf sozialen Medien`,
"Instagram":`Instagram`,
"Google":`Google`,
"Facebook":`Facebook`,
"Support":`Support`,
"Tittle":`Titel   `,
"DescriptionText":`Beschreibung`,
"Enter_Tittle":`Titel eingeben`,
"UserName":`Benutzername`,
"TerminalDetails":`Terminal-Details`,
"Location":`Standort `,
"Un_Follow":`Nicht mehr folgen`,
"Follow":`Folgen`,
"Record":`Aufzeichnung`,
"Warn":`Warnen`,
"ChatHistory":`Chatverlauf`,
"TerminalName":`Name des Terminals`,
"Terminal":`Terminal`,
"English":`Englisch`,
"Spanish":`Spanisch`,
"Driver_Type":`Fahrertyp`,
"Select_Driver_Type":`Fahrertyp auswählen`,
"Users":`Benutzer`,
"Enter_Title":`Titel eingeben`,
"Type_Message_Here":`Nachricht hier eingeben...`,
"Skip":`Überspringen`,
"Friend_request_not_found":`Freundschaftsanfrage nicht gefunden.`,
"Change_Mobile_Number":`Handynummer ändern`,
"resend_Otp":`Bestätigungscode erneut senden`,
"post":`Post`,
"Friend":`Freund`,
"NotificationDetail":`Benachrichtigungsdetails`,
"noResult":`Keine Einträge gefunden.`,
"enter_email_alert":`Bitte E-Mail-Adresse eingeben.`,
"enter_valid_email_alert":`Bitte gültige E-Mail-Adresse eingeben.`,
"enter_password_alert":`Bitte Passwort eingeben.`,
"enter_full_name_alert":`Bitte vollständigen Namen eingeben.`,
"enter_last_name_alert":`Bitte Nachnamen eingeben.`,
"enter_full_name_aplhanumeric_alert":`Bitte alphanumerisch im vollständigen Namen eingeben.`,
"enter_user_name_alert":`Bitte Benutzernamen eingeben.`,
"enter_user_name_length_alert":`Der Benutzername sollte mindestens 3 Zeichen lang sein.`,
"enter_user_type_alert":`Bitte Benutzertyp auswählen.`,
"enter_driver_type_alert":`Bitte Fahrertyp auswählen.`,
"enter_phone_number_alert":`Bitte Telefonnummer eingeben.`,
"enter_phone_number_length_alert":`Telefonnummer sollte zwischen 8 und 15 Zeichen haben.`,
"enter_Numbers_allowed__phone_alert":`Im Telefonfeld sind nur Nummern zulässig.`,
"enter_date_of_birth_alert":`Bitte Geburtsdatum auswählen.`,
"enter_password_length_alert":`Passwort muss mindestens 6 Zeichen lang sein.`,
"enter_confirm_password_alert":`Bitte Passwortbestätigung eingeben.`,
"enter_password_not_match_alert":`Passwort und Passwortbestätigung müssen übereinstimmen.`,
"enter_terms_conditions_alert":`enter_terms_conditions_alert: "Bitte akzeptieren Sie die Allgemeinen Geschäftsbedingungen.",`,
"enter_otp_alert":`Bitte Bestätigungscode eingeben.`,
"enter__valid_otp_alert":`Bitte gültigen Bestätigungscode eingeben.`,
"enter_old_password_alert":`Bitte altes Passwort eingeben.`,
"enter_old_password_length_alert":`Altes Passwort muss mindestens 6 Zeichen lang sein.`,
"enter_new_password_alert":`Bitte neues Passwort eingeben.`,
"enter_new_password_length_alert":`Neues Passwort muss mindestens 6 Zeichen lang sein.`,
"enter_old_cofirm_not_valid_alert":`Altes Passwort und Passwortbestätigung müssen übereinstimmen.`,
"Stream_stopped_by_user":`Live-Video beendet von`,
"Loading_streams":`Streams werden geladen`,
"you_are_live_now":`Sie sind jetzt live.`,
"end_publisher_video":`Sind Sie sicher, dass Sie dieses Live-Video beenden wollen?`,
"logOutAlert":`Sind Sie sicher, dass Sie sich ausloggen wollen?`,
"end_publisher_video_successfully":`Live-Video wurde beendet.`,
"Alert":`Alarm`,
"PhoneNumber_required_for_login":`Für den Login ist eine Telefonnummer erforderlich. Das hilft uns außerdem, die Community zu moderieren und unsere Benutzer zu schützen.`,
"Privacy_policy":`WENN SIE FORTFAHREN, AKZEPTIEREN SIE UNSERE`,
"Terms":`ALLGEMEINEN GESCHÄFTSBEDINGUNGEN `,
"Policy":`DATENSCHUTZRICHTLINIE`,
"Why_you_need_my_phone_number":`WARUM BENÖTIGEN SIE MEINE TELEFONNUMMER`,
"Why_we_need_your_phone_number":`WARUM WIR IHRE TELEFONNUMMER BENÖTIGEN`,
"verifyAccount":`VERIFIZIEREN SIE IHR KONTO`,
"terminalNotFound":`Terminal wurde nicht gefunden.`,
"Profile":`Profil`,
"App_Settings":`App-Einstellungen`,
"estimatedTime":`Geschätzte Zeit`,
"estimatedWaitTime":`Minuten gewartet`,
"youHaveLeft":`Du bist gegangen`,
"Citizen_safety_message":`Fr8 ist ein Frachtnetzwerk. Wir benötigen eine Telefonnummer, um Ihre Identität zu überprüfen und um sicherzustellen, dass diejenigen, die gegen unsere Community-Standards verstoßen, gegebenenfalls aus dem Netzwerk entfernt werden können.`,
"something_went_wrong":`Etwas ist schiefgelaufen.`,
"please_check_your_internet_connection":`Bitte überprüfen Sie Ihre Internetverbindung.`,
"startEndAlert":`Die Startzeit sollte weniger als die Endzeit sein.`,
"addPost":`Beitrag hinuzfügen`,
"permissionTitle': 'You had denied the permission to take photo from library',":`Sie hatten die Berechtigung verweigert, Fotos aus der Bibliothek aufzunehmen`,
"permissionBody":`Möchten Sie darauf zugreifen und dann die Berechtigung in den Einstellungen zulassen?`,
"videoPermissionTitle":`Sie hatten die Berechtigung verweigert, Videos aus der Bibliothek aufzunehmen`,
"TimeLine_post_not_found":`Beitrag in der Zeitlinie nicht gefunden.`,
"Timeline_Posts":`Zeitlinien-Beiträge`,
"Timeline":`Zeitlinie `,
"trackAtimeLine":`Verfolgen Sie Ihre Wartezeit`,
"Journey":`Keine Zeitachse gefunden.`,
"KM":`km`,
"Distance_Travelled":`Zurückgelegte Strecke`,
"hrs":`Std`,
"secs":`Sek`,
"mins":`Min`,
"time":`Zeit`,
"wait_time":`Durschn. Wartezeit`,
"Equiment_Photo":`Ausrüstungsfoto`,
"Interchange_Receipt":`Interchange-Beleg`,
"video":`Video`,
"Share":`Teilen`,
"start_time":`Startzeit`,
"Report_Post":`Beitrag melden`,
"endTime":`Endzeit`,
"openTime":`Offene Zeit`,
"closeTime":`Schließzeit`,
"distance":`Distanz`,
"Total_time":`Gesamtzeit`,
"Edit_Timeline":`Zeitlinie bearbeiten`,
"messageAlert":`Bitte geben Sie eine Nachricht ein.`,
"enterMessage":`Geben Sie Ihre Nachricht ein...`,
"Trending_Post":`Trendender Beitrag`,
"PleaseEnterReportResion":`Bitte geben Sie einen Grund für die Meldung ein.`,
"trendingPostNotFound":`Kein trendender Beitrag gefunden.`,
"Accept":`Akzeptieren`,
"Reject":`Ablehnen`,
"Allow":`Erlauben`,
"Invite":`Einladen`,
"postNotFound":`Kein Beitrag gefunden.`,
"Cancel_Friend_Request":`Freundschaftsanfrage abbrechen`,
"User_Posts":`Benutzerbeiträge`,
"Notifications":`Benachrichtigungen`,
"No_notifications":`Keine Benachrichtigungen gefunden.`,
"And":`UND`,
"deletePostAlert":`Sind Sie sicher, dass Sie diesen Beitrag löschen wollen?`,
"Yes":`Ja`,
"No":`Nein`,
"enterTitle":`Bitte Titel eingeben.`,
"pleaseEnterMessage":`Bitte Nachricht eingeben.`,
"Post_Create":`Beitrag erstellen`,
"description":`Geben Sie Ihre Beschreibung ein...`,
"enterDescription":`Bitte die Beschreibung eingeben.`,
"descriptionMax":`Bitte Beschreibung eingeben, die kürzer als 1000 Zeichen ist.`,
"descriptionMin":`Beschreibung muss mindestens 10 Zeichen lang sein.`,
"Preview":`Vorschau.`,
"messageMax":`Bitte Nachricht mit weniger als als 1000 Zeichen eingeben.`,
"noUser":`Kein Benutzer gefunden.`,
"New":`Neu`,
"No_chat_found":`Kein aktueller Chat gefunden`,
"Search_Terminal":`Terminal suchen`,
"Receipt_Private":`Empfang privat`,
"Edit":`Bearbeiten`,
"Delete":`Löschen`,
"postShareMessage":`hat einen Beitrag geteilt Klicken Sie auf den folgenden Link, um den Beitrag anzuzeigen`,
"postShareMessage2":`hat einen Beitrag geteilt Klicken Sie auf den folgenden Link, um den Beitrag anzuzeigen`,
"shareSubject":`FR8 Timeline-Beitrag`,
"messageCopy":`Nachricht kopiert`,
"avaliable24Hours":`24 Stunden verfügbar`,
"photo":`FOTO`,
"photoLibrary":`FOTOBIBLIOTHEK`,
"photoL":`Foto`,
"photoLibraryL":`Fotobibliothek`,
"reportUser":`Benutzer melden`,
"reasonOfReport":`Grund der Meldung`,
"reportPostAlert":`Möchten Sie diesen Beitrag wirklich melden?`,
// "ForegroundServiceTitle":`Die FR8-App verwaltet Ihren Standort im Hintergrund`,
"ForegroundServiceTitle":`Detention Pay Tracker läuft`,
"Portuguese":`Portugal`,
"interChangeDelete":`Sind Sie sicher, dass Sie die Interchange-Quittung löschen möchten?`,
"equipmentDelete":`Sind Sie sicher, dass Sie das Gerätefoto löschen möchten?`,
"deleteVideo":`Möchten Sie das Video wirklich löschen?`,
"sentAMessage":`eine Nachricht gesendet:`,
"editMessage":`Nachricht bearbeiten`,
"continue":`Weitermachen`,
"noContact":`Keine Kontakte gefunden`,
"Driver":`Treiber`,
"Owner Operator":`Eigentümer und Betreiber`,
"Company":`Gesellschaft`,
"Air Cargo Carrier":`Luftfrachtunternehmen`,
"Exporter":`Exporteur`,
"Freight Broker":`Frachtmakler`,
"Importer":`Importeur`,
"Shipper":`Absender`,
"Trucking":`LKW-Transport`,
"Warehouse":`Lagerhaus`,
"Company Driver":`Firmenfahrer`,
"OKAY":`OKAY`,
"installMessage":`Hallo FR8, möchten Sie einladen, die Anwendung zu installieren.`,
"warned":`gewarnt`,
"WaitingAt":`Warten um`,
"openFr8":`Öffnen Sie die Fr8-App, um Ihre geschätzte Wartezeit anzuzeigen.`,
"day":`Tag`,
"days":`Tage`,
"hour":`  Stunde`,
"hours":`  Std`,
"minute":`  Minute`,
"minutes":`  Protokoll`,
"second":`  Sekunde`,
"seconds":`  Sekunden`,
"openApp":`Öffnen Sie die App, um Ihren Status zu synchronisieren`,
"openAppBody":`Lassen Sie die FR8-App für ein optimales Erlebnis im Hintergrund geöffnet. Dadurch bleiben Ihre Zeitleiste und der Terminal-Zeitstempel genau.`,
"Comment":`Kommentar`,
"Comments":`Kommentare`,
"Like":`Mögen`,
"noComment":`Kein Kommentar gefunden`,
"deleteCommentAlert":`Möchten Sie den Kommentar wirklich löschen?`,
"enterTheComment":`Bitte geben Sie den Kommentar ein.`,
"enterYourComment":`Geben Sie Ihren Kommentar ein...`,
"DeeplinkShare":`Als Link teilen`,
"Shares":`Anteile`,
"shareasPost":`Post teilen`,
"hasShared":`hat geteilt`,
"whatsOnMind":`Was haben Sie auf dem Herzen?`,
"inGate":`In`,
"outGate":`aus`,
"With":`mit`,
"others":`Andere`,
"tagFriends":`Freunde markieren`,
"done":`Fertig`,
"friendSearch":`Freunde suchen`,
"checkIN":`Check-In`,
"tagUsers":`Getaggte Benutzer`,
"safeTrip":` Sie können jetzt Ihre Wartezeit teilen. Komme gut nach Hause!`,
"addLocation":`Ort hinzufügen`,
"locationSelect":`Bitte wählen Sie den Standort aus.`,
"attach":`Dateien anhängen`,
"selectImage":`Bitte wählen Sie Bilder oder Videos zum Posten aus.`,
"noPlace":`Keine Orte gefunden`,
"deleteMedia":`Möchten Sie dieses Medium wirklich löschen?`,
"deleteNotification":`Möchten Sie diese Benachrichtigung wirklich löschen?`,
"loading":`Wird geladen…`,
"next":`Nächste`,
"ttlUserInterminal":`Anzahl der Benutzer im Terminal:`,
"members":`Mitglieder drin`,
"member":`Mitglied drin`,
"useLocation":`Verwenden Sie Ihren Standort`,
"firstPermissionTitle":`Um Karten für automatisch verfolgte Aktivitäten anzuzeigen, erlauben Sie dem FR8, Ihren Standort die ganze Zeit zu verwenden.`,
"noThanks":`Nein danke`,
"turnOn":`Anmachen`,
"newVersion":`Neue Version`,
"versionDescription":`Diese Version der App ist veraltet, bitte aktualisieren Sie auf die neueste Version, um erstaunliche neue Funktionen freizuschalten, damit Sie die genauesten und erstaunlichsten neuen Funktionen erhalten. Vergessen Sie nicht, die Standortberechtigungen auf „Immer zulassen“ zu setzen, damit die App im Hintergrund Terminal-Wartezeiten für Sie berechnet.`,
"firstPermissionDesc":`FR8 verwendet Ihren Standort im Hintergrund, um Ihre Fahrten in Terminals präzise aufzuzeichnen und Wartezeiten und Zeitstempel zu berechnen.`,
"validUserName":`Es sind nur Buchstaben (a-z), Zahlen (0-9), Punkte (.) und Unterstrich (_) erlaubt.`,
"user_name_start":`Der Benutzername sollte nicht mit Punkten (.) beginnen.`,
"onlyNumberAlert":`Benutzername darf nicht nur Zahlen enthalten.`,
"user_name_end":`Der Benutzername darf nicht mit Punkten (.) enden.`,
"twoDots":`Der Benutzername sollte nicht mehr als einen Punkt (.) hintereinander haben.`,
"Ok":`OK`,
"followingTerminal":`Folgend`,
"pdfDownload":`PDF Herunterladen`,
"timelineCancel":`Möchten Sie die Zeitachse wirklich abbrechen?`,
"Truck Stop":`Raststätte`,
"Gas Station":`Tankstelle`,
"Weight Station":`Gewichtsstation`,
"location_name_enter":`Bitte geben Sie den Standortnamen ein.`,
"locationNameLong":`Der Standortname sollte mindestens 2 Zeichen lang sein.`,
"locationAddressLong":`Die Standortadresse sollte mindestens 2 Zeichen lang sein.`,
"locationAddress":`Bitte Standortadresse eingeben.`,
"Name":`Name`,
"Hold to Stop":`Zum Stoppen halten`,
"Location Address":`Standort-Adresse`,
"Phone Number":`Telefonnummer`,
"Add":`Hinzufügen`,
"Category":`Kategorie`,
"backgroundProcess":`Ihre Timeline wird im Hintergrund ausgeführt, wenn Sie zu anderen Bildschirmen wechseln.`,
"NotMoving":`Noch nicht umgezogen?`,
"oneMinuteLongerAlert":`Zum Beenden und Speichern benötigt FR8 mindestens 1 Minute längere Aktivität mit einem Ortswechsel.`,
"editPost":`Beitrag bearbeiten`,
"vedioLimit":`Die Videodauer sollte maximal 30 Sekunden lang sein.`,
"selectCurentLocation":`Wählen Sie Aktueller Standort`,
"noCommentYet":`Noch keine Kommentare`,
"enterFirstComment":`Sei der erste der kommentiert.`,
"App_Share":`Anwendung teilen`,
"appShareMessage":`hat die FR8-App geteilt. Klicken Sie auf den folgenden Link, um die mobile Anwendung anzuzeigen und die aktuellen Wartezeiten für heute anzuzeigen.`,
"appShareMessage2":`FR8-App \n Klicken Sie auf den folgenden Link, um die mobile Anwendung anzuzeigen und die aktuellen Wartezeiten für heute anzuzeigen.`,
"deleteCommentReplyAlert":`Möchten Sie diese Kommentarantwort wirklich löschen?`,
"enter_first_name_length_alert":`Der Vorname sollte mindestens 3 Zeichen lang sein.`,
"enter_last_name_length_alert":`Der Nachname sollte mindestens 3 Zeichen lang sein.`,
"location_Setting":`Ortseinstellungen`,
"postlikeHeading":`Leute, denen Post gefällt`,
"commentLikeHeading":`Leute, die gerne kommentieren`,
"viewProfile":`Profil anzeigen`,
"shareListHeading":`Personen, die Beiträge geteilt haben`,
"Reply":`Antwort`,
"Reply to":`Antwort an`,
"Dislike":`Nicht mögen`,
"Smile":`Lächeln`,
"Angry":`Verärgert`,
"Rolling Eyes":`Augen rollen`,
"Thinking":`Denken`,
"Stop":`Stoppen`,
"switchFrom":`Erhalten Sie genaue Sicherheitsmeldungen, indem Sie von wechseln`,
"Always Allow":`Immer erlaubt`,
"While Using":`Während dem Benutzen`,
"Ask next time":`Frag beim nächsten Mal`,
"Never":`noch nie`,
"Manage location Settings":`Standorteinstellungen verwalten`,
"Italian":`Italienisch`,
"Chinese":`Chinesisch vereinfacht (Mandarin)`,
"Hindi":`Hindi`,
"Filipino":`Philippinisch`,
"Vietnamese":`Vietnamesisch`,
"Arabic":`Arabisch`,
"French":`Französisch`,
"Korean":`Koreanisch`,
"Russian":`Russisch`,
"Bengali":`Bengali`,
"German":`Deutsch`,
regionlNotFound: 'Region not found.',
Region:"Region",
in: 'in',
posts: 'Beiträge',
"All":"Alles",
"saveToPhone":"Auf Telefon speichern",
"ADD":"HINZUFÜGEN",
"deleteAccount":"Konto löschen",
"deleteAccountAlert":"Sind Sie sicher, dass Sie Ihr Konto löschen möchten?",
"replyWrite":"Eine Antwort schreiben...",
"Camera":"Kamera",
"Image Gallery":"Bildergalerie",
"regionlNotFound":"Region nicht gefunden.",
"Region":"Region",
"regionSelectAlert":"Der Benutzer kann maximal 3 Regionen auswählen.",

"CALL":"ANRUF",
"ADDRESS":"DIE ANSCHRIFT",
"MIN":"MINDEST",
"About":"Um",
"Overview":"Überblick",
"Review":"Rezension",
"Timelines":"Zeitleisten",
"Rate & Review":"Bewerten und überprüfen",
"ratings":"Bewerten und überprüfen",
"Write Your Review":"Schreibe deine Rezension",
"Just now":"Gerade jetzt",
'waitTimeIndicator':`Wartezeitanzeige`,
currentWaitTime:"Aktuelle durchschnittliche Wartezeit",

};

module.exports = {
  constants
};
