import {imageBaseUrl} from '../Config/index'
const constants = {
  // TermsUrl:"http://18.205.207.176:3000/public/pdf/Fr8_App_Terms_Of_Use.pdf",
  TermsUrl:"https://www.fr8.ai/terms",
  // TermsUrl: imageBaseUrl +"public/pdf/Fr8_App_Terms_Of_Use.pdf",
  // PrivacyUrl:"http://18.205.207.176:3000/public/pdf/Fr8_App_Privacy_Policy.pdf",
  PrivacyUrl:"https://www.fr8.ai/privacy",
  // PrivacyUrl: imageBaseUrl + "public/pdf/Fr8_App_Privacy_Policy.pdf",
  // PrivacyUrl: imageBaseUrl + "public/pdf/Fr8_App_Privacy_Policy.pdf",
//   "Notifications"	:`सूचनाएँ`,
// 'No_notifications'	:`कोई सूचनाएँ नहीं मिलीं।`,
posts	:`पोस्ट`,
// Timeline	:`टाइमलाइन`,
// trackAtimeLine	:`अपने प्रतीक्षा समय को ट्रैक करें`,
// hours	:`घंटे`,
// minutes	:`मिनट`,
// seconds	:`सैकंड`,
// post	:`पोस्ट`,
// video	:`वीडियो `,
// photoL	:`फोटो`,
// photoLibraryL	:`फोटो लाइब्रेरी`,
// Profile	:`प्रोफाइल`,
// My_Network	:`मेरा नेटवर्क`,
// Friends	:`दोस्त`,
// Friend_Request	:`फ्रेंड रिक्वेस्ट`,
// App_Settings	:`ऐप सेटिंग`,
// Log_out	:`लॉग आउट करें`,
// My_Freighting_Network	:`मेरा माल ढुलाई नेटवर्क `,
// Search_friends	:`दोस्त, टर्मिनल, संपर्क खोजें`,
// Places	:`स्थान`,
// Nearby_Terminals	:`नजदीकी टर्मिनल`,
// Contacts	:`संपर्क`,
// Invite	:`आमंत्रित करें`,
// Un_Follow	:`अनफॉलो करें`,
// Change_Mobile_Number	:`मोबाइल नंबर बदलें`,
// Terms_And_Conditions	:`नियम और शर्तें`,
// Privacy_Policy	:`गोपनीयता पॉलिसी`,
// Change_Language	:`भाषा बदलें`,
// Support_Center	:`सहायता केंद्र`,
// Edit_Profile	:`प्रोफाइल को संशोधित करें`,
// Update	:`अपडेट करें`,
// Driver	:`ड्राइवर`,
// 'Owner Operator'	:`मालिक संचालक`,
// Company	:`कंपनी`,
// 'Air Cargo Carrier'	:`एयर कार्गो कैरियर`,
// Exporter	:`निर्यातकर्ता`,
// 'Freight Broker'	:`माल दलाल`,
// Importer	:`आयातकर्ता`,
// Shipper	:`माल भेजने वाला`,
// Trucking	:`ट्रक चलन`,
// Warehouse	:`गोदाम`,
// Interchange_Receipt	:`अदला-बदली रसीद`,
// Equiment_Photo	:`उपकरण की फोटो`,
// Share	:`साझा करें`,
// Edit	:`संशोधित करें`,
// Delete	:`हटाएँ`,
// Post_Create	:`पोस्ट बनाएं`,
// distance	:`दूरी`,
// Submit	:`जमा करें`,
// Alert	:`अलर्ट`,
// logOutAlert	:`क्या आप लॉग आउट करना चाहते हैं?`,
// Cancel	:`रद्द करें`,
// Yes	:`हाँ`,

//   Italian:	'Italian',
//   Chinese:	'Chinese Simplified (Mandarin)', 
//   Hindi:	'Hindi',
//    Filipino :	 'Filipino' ,
//   Vietnamese:	'Vietnamese',
//   Arabic:	'Arabic',
//   French:	'French',
//   Korean:	'Korean',
//   Russian:	'Russian',
//    Bengali :	 'Bengali' ,
//   German:	'German',


//   //new added
//   'useLocation':"Use your location",
//   'allowToUseAllLocation':"To see maps for automatically tracked activities, allow FR8 to use your location all of the time.",
//   'enablePrecisesLocation':"FR8 will use your location in the background to enable your precise recordings of your trips in terminals and calculate wait time and time stamp.",
//   'noThanks':"No thanks",
//   'turnOn':"Turn on"
  

// "Email":`ईमेल`,
// "Enter_Email":`ईमेल दर्ज करें`,
// "Password":`पासवर्ड`,
// "Enter_Password":`पासवर्ड डालें`,
// "Enter_New_Password":`नया पासवर्ड डालें`,
// "Forgot_Your_Password":`अपना पासवर्ड भूल गए?`,
// "Login":`लॉगिन`,
// "Doesnt_have_an_account":`क्या आपके पास अकाउंट नहीं है?`,
// "Sign_up":`साइन अप`,
// "Enter_Name":`नाम डालें`,
// "Enter_first_Name":`पहला नाम दर्ज करें`,
// "Enter_last_Name":`अंतिम नाम दर्ज करो`,
// "Enter_Your_Phone_Number":`अपना फोन नम्बर डालें`,
// "Enter_Six_Digit_Verification_Code":`छः अंकों का सत्यापन कोड डालें`,
// "Resend_Verification_Code":`सत्यापन कोड दोबारा भेजें`,
// "Contact_Permission":`अपने मित्रों को सुरक्षित रखने के लिए सम्पर्क की अनुमति को कृपया सक्षम करें`,
// "Register":`पंजीकरण`,
// "Full_Name":`पूरा नाम`,
// "Enter_Full_Name":`पूरा नाम डालें`,
// "Username":`उपयोगकर्ता नाम`,
// "Enter_Username":`उपयोगकर्ता नाम डालें`,
// "Email_Address":`ईमेल पता`,
// "Enter_Email_Address":`ईमेल पता डालें`,
// "User_Type":`उपयोगकर्ता प्रकार`,
// "Select_User_Type":`उपयोगकर्ता प्रकार चुनें`,
// "Phone_Number":`फोन नंबर`,
// "Enter_Phone_Number":`फोन नंबर डालें`,
// "Date_Of_Birth":`जन्म तिथि`,
// "Select_Date_Of_Birth":`जन्म तिथि चुनें`,
// "Confirm_Password":`पुष्टि पासवर्ड`,
// "Enter_Confirm_Password":`पुष्टि पासवर्ड डालें`,
// "Agree_Terms_and_Condition":`नियमों और शर्तों से सहमति`,
// "Forgot_Password":`पासवर्ड भूल गए`,
// "Submit":`जमा करें`,
// "OTP":`OTP`,
// "Enter_OTP":`OTP डालें`,
// "Reset_Password":`पासवर्ड रीसेट करें`,
// "Edit_Profile":`प्रोफ़ाइल को संशोधित करें`,
// "Edit_Phone_Number":`फोन नम्बर को संशोधित करें`,
// "Update":`अपडेट करें`,
// "Change_Password":`पासवर्ड बदलें`,
// "Old_Password":`पुराना पासवर्ड `,
// "Enter_Old_Password":`पुराना पासवर्ड डालें`,
// "FAQs":`अधिकतर पूछे गए प्रश्न`,
// "Social_Media_Accounts":`सोशल मीडिया अकाउंट्स`,
// "Settings":`सेटिंग`,
// "FR8":`FR8`,
// "Support_Center":`सहायता केंद्र`,
// "Terms_And_Conditions":`नियम और शर्तें`,
// "Privacy_Policy":`गोपनीयता नीति`,
// "Change_Language":`भाषा बदलें`,
// "Logout":`लॉग आउट`,
// "Log_out":`लॉग आउट`,
// "Confirm":`पुष्टि करें`,
// "Cancel":`रद्द करें`,
// "Please_Select":`कृपया चुने`,
// "Warn_Contacts":`संपर्कों को चेतावनी दें`,
// "Search_contacts":`संपर्क खोजें`,
// "Friend_Requests":`मित्र अनुरोध`,
// "Friend_Request":`मित्र अनुरोध`,
// "My_Posts":`मेरी पोस्ट`,
// "Search_friends":`मित्रों, टर्मिनल, संपर्कों को खोजें `,
// "My_Freighting_Network":`मेरा माल नेटवर्क`,
// "My_Network":`मेरा नेटवर्क`,
// "Places":`स्थानों`,
// "Friends":`मित्र`,
// "Nearby_Terminals":`निकटवर्ती टर्मिनल`,
// "Explore":`खोजें`,
// "Contacts":`संपर्क`,
// "Name_Of_User":`उपयोगकर्ता का नाम`,
// "Add_Friend":`मित्र जोड़ें`,
// "Remove_Friend":`मित्र हटायें`,
// "Chat":`चैट`,
// "Post_Details":`विवरण पोस्ट करें`,
// "Live_Streams":`लाइव स्ट्रीम`,
// "CreatePost":`पोस्ट बनाएँ`,
// "SocialMediaAccounts":`सोशल मीडिया अकाउंट्स`,
// "Instagram":`इंस्टाग्राम`,
// "Google":`गूगल`,
// "Facebook":`फेसबुक`,
// "Support":`सहायता `,
// "Tittle":`बिंदु`,
// "DescriptionText":`विवरण`,
// "Enter_Tittle":`बिंदु डालें`,
// "UserName":`उपयोगकर्ता नाम`,
// "TerminalDetails":`टर्मिनल विवरण`,
// "Location":`स्थान`,
// "Un_Follow":`फ़ॉलो करना बंद करें`,
// "Follow":`फ़ॉलो करें`,
// "Record":`लेखा जोखा`,
// "Warn":`चेतावनी दें`,
// "ChatHistory":`चैट का लेखा जोखा`,
// "TerminalName":`टर्मिनल का नाम"`,
// "Terminal":`टर्मिनल`,
// "English":`अंग्रेज़ी`,
// "Spanish":`स्पेनिश`,
// "Driver_Type":`ड्राइवर का प्रकार`,
// "Select_Driver_Type":`ड्राइवर का प्रकार चुनें`,
// "Users":`उपयोगकर्ताओं`,
// "Enter_Title":`शीर्षक डालें`,
// "Type_Message_Here":`संदेश यहां लिखें ...`,
// "Skip":`छोड़ें`,
// "Friend_request_not_found":`मित्र अनुरोध नहीं मिला।`,
// "Change_Mobile_Number":`मोबाइल नंबर बदलें`,
// "resend_Otp":`सत्यापन कोड दोबारा भेजें`,
// "post":`पोस्ट`,
// "Friend":`दोस्त`,
// "NotificationDetail":`अधिसूचना विवरण`,
// "noResult":`कोई परिणाम नहीं मिला।`,
// "enter_email_alert":`कृपया ईमेल पता डालें।`,
// "enter_valid_email_alert":`कृपया मान्य ईमेल पता डालें।`,
// "enter_password_alert":`कृपया पासवर्ड डालें।`,
// "enter_full_name_alert":`कृपया पूरा नाम डालें।`,
// "enter_last_name_alert":`कृपया अंतिम नाम दर्ज करें।`,
// "enter_full_name_aplhanumeric_alert":`कृपया पूरें नाम में अल्फ़ान्यूमेरिक डालें।`,
// "enter_user_name_alert":`कृपया उपयोगकर्ता नाम डालें।`,
// "enter_user_name_length_alert":`उपयोगकर्ता नाम कम से कम 3 वर्ण लंबा होना चाहिए।`,
// "enter_user_type_alert":`कृपया उपयोगकर्ता प्रकार चुनें।`,
// "enter_driver_type_alert":`कृपया ड्राइवर प्रकार चुनें।`,
// "enter_phone_number_alert":`कृपया फ़ोन नंबर डालें।`,
// "enter_phone_number_length_alert":`फोन नंबर 8 से 15 के बीच होना चाहिए।`,
// "enter_Numbers_allowed__phone_alert":`फोन क्षेत्र में केवल संख्याओं की अनुमति है।`,
// "enter_date_of_birth_alert":`कृपया जन्म तिथि चुनें।`,
// "enter_password_length_alert":`पासवर्ड कम से कम 6 अंकों का होना चाहिए।`,
// "enter_confirm_password_alert":`कृपया पुष्टि पासवर्ड डालें।`,
// "enter_password_not_match_alert":`पासवर्ड और पुष्टि पासवर्ड एक ही होना चाहिए।`,
// "enter_terms_conditions_alert":`enter_terms_conditions_alert: "कृपया नियम और शर्तें स्वीकार करें।"`,
// "enter_otp_alert":`कृपया सत्यापन कोड डालें।`,
// "enter__valid_otp_alert":`कृपया मान्य सत्यापन कोड डालें।`,
// "enter_old_password_alert":`कृपया पुराना पासवर्ड डालें।`,
// "enter_old_password_length_alert":`पुराना पासवर्ड कम से कम 6 अक्षरों का होना चाहिए।`,
// "enter_new_password_alert":`कृपया नया पासवर्ड डालें।`,
// "enter_new_password_length_alert":`नया पासवर्ड कम से कम 6 अक्षरों का होना चाहिए।`,
// "enter_old_cofirm_not_valid_alert":`पुराना पासवर्ड और पुष्टि पासवर्ड एक ही होना चाहिए।`,
// "Stream_stopped_by_user":`लाइव वीडियो पर समाप्त`,
// "Loading_streams":`स्ट्रीम लोड हो रही हैं`,
// "you_are_live_now":`अब आप लाइव हो।`,
// "end_publisher_video":`क्या आप वाकई इस लाइव वीडियो को समाप्त करना चाहते हैं?`,
// "logOutAlert":`क्या आप लॉग आउट करना चाहते हैं?`,
// "end_publisher_video_successfully":`लाइव वीडियो समाप्त हो गया।`,
// "Alert":`चेतावनी`,
// "PhoneNumber_required_for_login":`लॉग इन करने के लिए एक फ़ोन नंबर की आवश्यकता है। यह हमें समुदाय को नियंत्रित करने और हमारे उपयोगकर्ताओं की सुरक्षा करने में भी मदद करता है।`,
// "Privacy_policy":`आगे जारी रखकर आप सहमत हैं हमारी `,
// "Terms":`उपयोग की शर्तें`,
// "Policy":`गोपनीयता नीति`,
// "Why_you_need_my_phone_number":`आपको क्यों मेरे फोन नंबर की जरूरत है?`,
// "Why_we_need_your_phone_number":`हमें क्यों आपके फोन नंबर की जरूरत है`,
// "verifyAccount":`अपने अकाउंट को सत्यापित करें`,
// "terminalNotFound":`टर्मिनल नहीं मिला।`,
// "Profile":`प्रोफ़ाइल`,
// "App_Settings":`एप्लिकेशन सेटिंग`,
// "estimatedTime":`अनुमानित समय`,
// "estimatedWaitTime":`मिनट प्रतीक्षा`,
// "youHaveLeft":`आप चले गए`,
// "Citizen_safety_message":`Fr8 एक माल ढुलाई नेटवर्क है। हमें आपकी पहचान सत्यापित करने के लिए फ़ोन नंबर की आवश्यकता है और यह सुनिश्चित करने के लिए कि ज़रूरत पड़ने पर हमारे समुदाय के मानकों का उल्लंघन करने वालों को नेटवर्क से हटाया जा सकता है।`,
// "something_went_wrong":`कुछ गलत हो गया।`,
// "please_check_your_internet_connection":`कृपया अपने इंटरनेट कनेक्शन की जाँच करें।`,
// "startEndAlert":`प्रारंभ समय समाप्ति के समय से कम होना चाहिए।`,
// "addPost":`पोस्ट जोड़ें`,
// "permissionTitle': 'You had denied the permission to take photo from library',":`आपने लाइब्रेरी से फोटो लेने की अनुमति से इनकार कर दिया था`,
// "permissionBody":`क्या आप इसे एक्सेस करना चाहते हैं तो फिर सेटिंग्स में अनुमति दें?`,
// "videoPermissionTitle":`आपने लाइब्रेरी से वीडियो लेने की अनुमति से इनकार कर दिया था`,
// "TimeLine_post_not_found":`टाइमलाइन पोस्ट नहीं मिली।`,
// "Timeline_Posts":`टाइमलाइन पोस्ट`,
// "Timeline":`टाइमलाइन`,
// "trackAtimeLine":`अपने प्रतीक्षा के समय को ट्रैक करें`,
// "Journey":`कोई समयरेखा नहीं मिली।`,
// "KM":`किमी`,
// "Distance_Travelled":`तय की गई दूरी`,
// "hrs":`घंटे`,
// "secs":`सेकेंड`,
// "mins":`मिनट`,
// "time":`समय`,
// "wait_time":`औसत प्रतीक्षा का समय`,
// "Equiment_Photo":`उपकरण फोटो`,
// "Interchange_Receipt":`इंटरचेंज रसीद`,
// "video":`वीडियो`,
// "Share":`शेयर`,
// "start_time":`प्रारंभ समय`,
// "Report_Post":`रिपोर्ट पोस्ट`,
// "endTime":`समाप्ति समय'`,
// "openTime":`खुला समय`,
// "closeTime":`बंद होने का समय`,
// "distance":`दूरी`,
// "Total_time":`कुल समय`,
// "Edit_Timeline":`टाइमलाइन को संशोधित करें`,
// "messageAlert":`कृपया कुछ संदेश डालें`,
// "enterMessage":`अपना संदेश डालें...`,
// "Trending_Post":`ट्रेंडिंग पोस्ट`,
// "PleaseEnterReportResion":`कृपया रिपोर्ट का कारण डालें।`,
// "trendingPostNotFound":`कोई ट्रेंडिंग पोस्ट नहीं मिला।`,
// "Accept":`स्वीकार करें`,
// "Reject":`अस्वीकार करें`,
// "Allow":`अनुमति`,
// "Invite":`आमंत्रित करें`,
// "postNotFound":`कोई पोस्ट नहीं मिली।`,
// "Cancel_Friend_Request":`मित्र अनुरोध रद्द करें`,
// "User_Posts":`उपयोगकर्ता पोस्ट`,
// "Notifications":`सूचनाएं`,
// "No_notifications":`कोई सूचनाएं नहीं मिलीं।`,
// "And":`तथा`,
// "deletePostAlert":`क्या आप वाकई इस पोस्ट को हटाना चाहते हैं?`,
// "Yes":`हाँ`,
// "No":`नहीं`,
// "enterTitle":`कृपया बिंदु डालें`,
// "pleaseEnterMessage":`कृपया संदेश डालें।`,
// "Post_Create":`पोस्ट बनाएँ`,
// "description":`अपना विवरण डालें...`,
// "enterDescription":`कृपया विवरण डालें।`,
// "descriptionMax":`कृपया विवरण को 1000 से कम अक्षरों में डालें।`,
// "descriptionMin":`विवरण कम से कम 10 अक्षरों का होना चाहिए।`,
// "Preview":`पूर्वावलोकन`,
// "messageMax":`कृपया संदेश को 1000 से कम अक्षरों में डालें।`,
// "noUser":`कोई उपयोगकर्ता नहीं मिला।`,
// "New":`नया`,
// "No_chat_found":`हाल की कोई चैट नहीं मिली`,
// "Search_Terminal":`टर्मिनल खोजें`,
// "Receipt_Private":`रसीद निजी`,
// "Edit":`संपादित करें`,
// "Delete":`हटाएं`,
// "postShareMessage":`पोस्ट शेयर किया है पोस्ट देखने के लिए नीचे दिए गए लिंक पर क्लिक करें`,
// "shareSubject":`FR8 टाइमलाइन पोस्ट`,
// "messageCopy":`संदेश कॉपी किया गया`,
// "avaliable24Hours":`24 घंटे उपलब्ध`,
// "photo":`तस्वीर`,
// "photoLibrary":`चित्र पुस्तकालय`,
// "photoL":`तस्वीर`,
// "photoLibraryL":`चित्र पुस्तकालय`,
// "reportUser":`उपयोगकर्ता को रिपोर्ट करें`,
// "reasonOfReport":`रिपोर्ट का कारण`,
// "reportPostAlert":`क्या आप निश्चित रूप से इस पोस्ट की रिपोर्ट करना चाहते हैं?`,
// "ForegroundServiceTitle":`FR8 ऐप बैकग्राउंड में आपकी लोकेशन मैनेज कर रहा है`,
// "Portuguese":`पुर्तगाल`,
// "interChangeDelete":`क्या आप वाकई इंटरचेंज रसीद को हटाना चाहते हैं?`,
// "equipmentDelete":`क्या आप सुनिश्चित हैं, आप उपकरण फ़ोटो हटाना चाहते हैं?`,
// "deleteVideo":`क्या आप सुनिश्चित हैं, आप वीडियो हटाना चाहते हैं?`,
// "sentAMessage":`एक संदेश भेजा:`,
// "editMessage":`संदेश संपादित करें`,
// "continue":`जारी रखना`,
// "noContact":`कोई संपर्क नहीं मिला`,
// "Driver":`चालक`,
// "Owner Operator":`मालिक ऑपरेटर`,
// "Company":`कंपनी`,
// "Air Cargo Carrier":`एयर कार्गो कैरियर`,
// "Exporter":`निर्यातक`,
// "Freight Broker":`फ्रेट ब्रोकर`,
// "Importer":`आयातक`,
// "Shipper":`शिपर`,
// "Trucking":`ट्रकिंग`,
// "Warehouse":`गोदाम`,
// "Company Driver":`कंपनी चालक`,
// "OKAY":`ठीक`,
// "installMessage":`हैलो FR8 क्या आप एप्लिकेशन इंस्टॉल करने के लिए आमंत्रित करना चाहेंगे।`,
// "warned":`आगाह`,
// "WaitingAt":`प्रतीक्षारत`,
// "openFr8":`अपना अनुमानित प्रतीक्षा समय दिखाने के लिए Fr8 ऐप खोलें।`,
// "day":`दिन`,
// "days":`दिन`,
// "hour":`घंटा`,
// "hours":`घंटे`,
// "minute":`मिनट`,
// "minutes":`मिनट`,
// "second":`सेकंड`,
// "seconds":`सेकंड`,
// "openApp":`अपना स्टेटस सिंक करने के लिए ऐप खोलें`,
// "openAppBody":`बेहतरीन अनुभव के लिए, FR8 ऐप को बैकग्राउंड में खुला रहने दें। यह आपकी टाइमलाइन और टर्मिनल टाइम स्टैम्प को सटीक रखता है।`,
// "Comment":`टिप्पणी`,
// "Comments":`टिप्पणियाँ`,
// "Like":`पसंद`,
// "noComment":`कोई टिप्पणी नहीं मिली`,
// "deleteCommentAlert":`क्या आप वाकई टिप्पणी हटाना चाहते हैं?`,
// "enterTheComment":`कृपया टिप्पणी दर्ज करें।`,
// "enterYourComment":`अपनी टिप्पणी दर्ज करें...`,
// "DeeplinkShare":`लिंक के रूप में शेयर करें`,
// "Shares":`शेयरों`,
// "shareasPost":`शेयर पोस्ट`,
// "hasShared":`साझा किया है`,
// "whatsOnMind":`आपके दिमाग मे क्या है?`,
// "inGate":`में`,
// "outGate":`बाहर`,
// "With":`साथ`,
// "others":`अन्य`,
// "tagFriends":`टैग फ्रेंड्स`,
// "done":`किया हुआ`,
// "friendSearch":`मित्र खोजें`,
// "checkIN":`चेक इन`,
// "tagUsers":`टैग किए गए उपयोगकर्ता`,
// "safeTrip":` अब आप अपना प्रतीक्षा समय साझा कर सकते हैं। यात्रा सुरक्षित हो!`,
// "addLocation":`स्थान जोड़ना`,
// "locationSelect":`कृपया स्थान का चयन करें।`,
// "attach":`फ़ाइलों को संलग्न करें`,
// "selectImage":`कृपया पोस्ट करने के लिए छवियों या वीडियो का चयन करें।`,
// "noPlace":`कोई स्थान नहीं मिला`,
// "deleteMedia":`क्या आप वाकई इस मीडिया को हटाना चाहते हैं?`,
// "deleteNotification":`क्या आप वाकई इस अधिसूचना को हटाना चाहते हैं?`,
// "loading":`लोड हो रहा है…`,
// "next":`अगला`,
// "ttlUserInterminal":`टर्मिनल के अंदर उपयोगकर्ताओं की संख्या:`,
// "members":`अंदर के सदस्य`,
// "member":`सदस्य अंदर`,
// "useLocation":`अपने स्थान का प्रयोग करें`,
// "firstPermissionTitle":`स्वचालित रूप से ट्रैक की गई गतिविधियों के लिए मानचित्र देखने के लिए, FR8 को हर समय अपने स्थान का उपयोग करने दें।`,
// "noThanks":`जी नहीं, धन्यवाद`,
// "turnOn":`चालू करो`,
// "newVersion":`नया संस्करण`,
// "versionDescription":`ऐप का यह संस्करण पुराना है, कृपया सबसे सटीक और अद्भुत नई सुविधाएं प्राप्त करने में आपकी सहायता के लिए अद्भुत नई सुविधाओं को अनलॉक करने के लिए नवीनतम संस्करण में अपडेट करें। स्थान अनुमतियों को हमेशा अनुमति पर सेट करना न भूलें ताकि ऐप पृष्ठभूमि में आपके लिए टर्मिनल प्रतीक्षा समय की गणना करे।`,
// "firstPermissionDesc":`FR8 टर्मिनलों में आपकी यात्राओं की आपकी सटीक रिकॉर्डिंग को सक्षम करने और प्रतीक्षा समय और समय टिकट की गणना करने के लिए पृष्ठभूमि में आपके स्थान का उपयोग करेगा।`,
// "validUserName":`केवल अक्षर (a-z), संख्याएँ (0-9), आवर्त (.) और अंडरस्कोर (_) की अनुमति है।`,
// "user_name_start":`उपयोगकर्ता नाम अवधियों (.) से प्रारंभ नहीं होना चाहिए`,
// "onlyNumberAlert":`उपयोगकर्ता नाम में केवल संख्याएँ नहीं हो सकतीं।`,
// "user_name_end":`उपयोगकर्ता नाम अवधियों (।) के साथ समाप्त नहीं होना चाहिए।`,
// "twoDots":`उपयोगकर्ता नाम में एक से अधिक अवधि (.) एक पंक्ति में नहीं होनी चाहिए।`,
// "Ok":`ठीक`,
// "followingTerminal":`अगले`,
// "pdfDownload":`डाउनलोड पीडीऍफ़`,
// "timelineCancel":`क्या आप वाकई टाइमलाइन रद्द करना चाहते हैं?`,
// "Truck Stop":`ट्र्क के रुकने की जगह`,
// "Gas Station":`पेट्रोल पंप`,
// "Weight Station":`वजन स्टेशन`,
// "location_name_enter":`कृपया स्थान का नाम दर्ज करें।`,
// "locationNameLong":`स्थान का नाम कम से कम 2 वर्ण लंबा होना चाहिए।`,
// "locationAddressLong":`स्थान का पता कम से कम 2 वर्ण लंबा होना चाहिए।`,
// "locationAddress":`कृपया स्थान का पता दर्ज करें।`,
// "Name":`नाम`,
// "Hold to Stop":`रुकने के लिए रुकें`,
// "Location Address":`स्थान का पता`,
// "Phone Number":`फ़ोन नंबर`,
// "Add":`जोड़ें`,
// "Category":`श्रेणी`,
// "backgroundProcess":`जब आप अन्य स्क्रीन पर जाएंगे तो आपकी टाइमलाइन पृष्ठभूमि में चलेगी।`,
// "NotMoving":`अभी नहीं चल रहा है?`,
// "oneMinuteLongerAlert":`समाप्त करने और सहेजने के लिए, FR8 को स्थान परिवर्तन के साथ कम से कम 1 मिनट लंबी गतिविधि की आवश्यकता होती है।`,
// "editPost":`संपादित पोस्ट`,
// "vedioLimit":`वीडियो की अवधि अधिकतम 30 सेकंड लंबी होनी चाहिए।'`,
// "selectCurentLocation":`वर्तमान स्थान चुनें`,
// "noCommentYet":`अब तक कोई टिप्पणी नहीं`,
// "enterFirstComment":`टिप्पणी करने वाले पहले बनो।`,
// "App_Share":`आवेदन साझा करें`,
// "appShareMessage":`FR8 ऐप साझा किया है। मोबाइल एप्लिकेशन देखने और आज का वर्तमान प्रतीक्षा समय देखने के लिए नीचे दिए गए लिंक पर क्लिक करें।`,
// "deleteCommentReplyAlert":`क्या आप सुनिश्चित हैं, आप इस टिप्पणी उत्तर को हटाना चाहते हैं?`,
// "enter_first_name_length_alert":`प्रथम नाम कम से कम 3 वर्ण लंबा होना चाहिए।`,
// "enter_last_name_length_alert":`उपनाम कम से कम 3 वर्ण लंबा होना चाहिए।`,
// "location_Setting":`स्थान सेटिंग्स`,
// "postlikeHeading":`पोस्ट पसंद करने वाले लोग`,
// "commentLikeHeading":`कमेंट पसंद करने वाले लोग`,
// "viewProfile":`प्रोफ़ाइल देखें`,
// "shareListHeading":`पोस्ट शेयर करने वाले लोग`,
// "Reply":`जवाब`,
// "Reply to":`को उत्तर`,
// "Dislike":`नापसन्द`,
// "Smile":`मुस्कान`,
// "Angry":`गुस्सा`,
// "Rolling Eyes":`आखें घुमाना`,
// "Thinking":`विचारधारा`,
// "Stop":`विराम`,
// "switchFrom":`से स्विच करके सटीक सुरक्षा सूचनाएं प्राप्त करें`,
// "Always Allow":`हमेशा की अनुमति`,
// "While Using":`प्रयोग करते समय`,
// "Ask next time":`अगली बार पूछें`,
// "Never":`कभी नहीँ`,
// "Manage location Settings":`स्थान सेटिंग प्रबंधित करें`,
// "Italian":`इतालवी`,
// "Chinese":`चीनी सरलीकृत (मंदारिन),`,
// "Hindi":`हिंदी`,
// " Filipino :":` filipino`,
// "Vietnamese":`वियतनामी`,
// "Arabic":`अरबी`,
// "French":`फ्रेंच`,
// "Korean":`कोरियाई`,
// "Russian":`रूसी`,
// " Bengali ":` बंगाली`,
// "German":`जर्मन`,
"Email":`ईमेल`,
"Enter_Email":`ईमेल दर्ज करें`,
"Password":`पासवर्ड`,
"Enter_Password":`पासवर्ड डालें`,
"Enter_New_Password":`नया पासवर्ड डालें`,
"Forgot_Your_Password":`अपना पासवर्ड भूल गए?`,
"Login":`लॉगिन`,
"Doesnt_have_an_account":`क्या आपके पास अकाउंट नहीं है?`,
"Sign_up":`साइन अप`,
"Enter_Name":`नाम डालें`,
"Enter_first_Name":`पहला नाम दर्ज करें`,
"Enter_last_Name":`अंतिम नाम दर्ज करो`,
"Enter_Your_Phone_Number":`अपना फोन नम्बर डालें`,
"Enter_Six_Digit_Verification_Code":`छः अंकों का सत्यापन कोड डालें`,
"Resend_Verification_Code":`सत्यापन कोड दोबारा भेजें`,
"Contact_Permission":`अपने मित्रों को सुरक्षित रखने के लिए सम्पर्क की अनुमति को कृपया सक्षम करें`,
"Register":`पंजीकरण`,
"Full_Name":`पूरा नाम`,
"Enter_Full_Name":`पूरा नाम डालें`,
"Username":`उपयोगकर्ता नाम`,
"Enter_Username":`उपयोगकर्ता नाम डालें`,
"Email_Address":`ईमेल पता`,
"Enter_Email_Address":`ईमेल पता डालें`,
"User_Type":`उपयोगकर्ता प्रकार`,
"Select_User_Type":`उपयोगकर्ता प्रकार चुनें`,
"Phone_Number":`फोन नंबर`,
"Enter_Phone_Number":`फोन नंबर डालें`,
"Date_Of_Birth":`जन्म तिथि`,
"Select_Date_Of_Birth":`जन्म तिथि चुनें`,
"Confirm_Password":`पुष्टि पासवर्ड`,
"Enter_Confirm_Password":`पुष्टि पासवर्ड डालें`,
"Agree_Terms_and_Condition":`नियमों और शर्तों से सहमति`,
"Forgot_Password":`पासवर्ड भूल गए`,
"Submit":`जमा करें`,
"OTP":`OTP `,
"Enter_OTP":`OTP डालें`,
"Reset_Password":`पासवर्ड रीसेट करें`,
"Edit_Profile":`प्रोफ़ाइल को संशोधित करें`,
"Edit_Phone_Number":`फोन नम्बर को संशोधित करें`,
"Update":`अपडेट करें`,
"Change_Password":`पासवर्ड बदलें`,
"Old_Password":`पुराना पासवर्ड `,
"Enter_Old_Password":`पुराना पासवर्ड डालें`,
"FAQs":`अधिकतर पूछे गए प्रश्न`,
"Social_Media_Accounts":`सोशल मीडिया अकाउंट्स`,
"Settings":`सेटिंग`,
"FR8":`FR8`,
"Support_Center":`सहायता केंद्र`,
"Terms_And_Conditions":`नियम और शर्तें`,
"Privacy_Policy":`गोपनीयता नीति`,
"Change_Language":`भाषा बदलें`,
"Logout":`लॉग आउट`,
"Log_out":`लॉग आउट`,
"Confirm":`पुष्टि करें`,
"Cancel":`रद्द करें`,
"Please_Select":`कृपया चुने`,
"Warn_Contacts":`संपर्कों को चेतावनी दें`,
"Search_contacts":`संपर्क खोजें`,
"Friend_Requests":`मित्र अनुरोध`,
"Friend_Request":`मित्र अनुरोध`,
"My_Posts":`मेरी पोस्ट`,
"Search_friends":`मित्रों, टर्मिनल, संपर्कों को खोजें `,
"My_Freighting_Network":`मेरा माल नेटवर्क`,
"My_Network":`मेरा नेटवर्क`,
"Places":`स्थानों`,
"Friends":`मित्र`,
"Nearby_Terminals":`निकटवर्ती टर्मिनल`,
"Explore":`खोजें`,
"Contacts":`संपर्क`,
"Name_Of_User":`उपयोगकर्ता का नाम`,
"Add_Friend":`मित्र जोड़ें`,
"Remove_Friend":`मित्र हटायें`,
"Chat":`चैट`,
"Post_Details":`विवरण पोस्ट करें`,
"Live_Streams":`लाइव स्ट्रीम`,
"CreatePost":`पोस्ट बनाएँ`,
"SocialMediaAccounts":`सोशल मीडिया अकाउंट्स`,
"Instagram":`इंस्टाग्राम`,
"Google":`गूगल`,
"Facebook":`फेसबुक`,
"Support":`सहायता `,
"Tittle":`बिंदु`,
"DescriptionText":`विवरण`,
"Enter_Tittle":`बिंदु डालें`,
"UserName":`उपयोगकर्ता नाम`,
"TerminalDetails":`टर्मिनल विवरण`,
"Location":`स्थान`,
"Un_Follow":`फ़ॉलो करना बंद करें`,
"Follow":`फ़ॉलो करें`,
"Record":`लेखा जोखा`,
"Warn":`चेतावनी दें`,
"ChatHistory":`चैट का लेखा जोखा`,
"TerminalName":`टर्मिनल का नाम"`,
"Terminal":`टर्मिनल`,
"English":`अंग्रेज़ी`,
"Spanish":`स्पेनिश`,
"Driver_Type":`ड्राइवर का प्रकार`,
"Select_Driver_Type":`ड्राइवर का प्रकार चुनें`,
"Users":`उपयोगकर्ताओं`,
"Enter_Title":`शीर्षक डालें`,
"Type_Message_Here":`संदेश यहां लिखें ...`,
"Skip":`छोड़ें`,
"Friend_request_not_found":`मित्र अनुरोध नहीं मिला।`,
"Change_Mobile_Number":`मोबाइल नंबर बदलें`,
"resend_Otp":`सत्यापन कोड दोबारा भेजें`,
"post":`पोस्ट`,
"Friend":`दोस्त`,
"NotificationDetail":`अधिसूचना विवरण`,
"noResult":`कोई परिणाम नहीं मिला।`,
"enter_email_alert":`कृपया ईमेल पता डालें।`,
"enter_valid_email_alert":`कृपया मान्य ईमेल पता डालें।`,
"enter_password_alert":`कृपया पासवर्ड डालें।`,
"enter_full_name_alert":`कृपया पूरा नाम डालें।`,
"enter_last_name_alert":`कृपया अंतिम नाम दर्ज करें।`,
"enter_full_name_aplhanumeric_alert":`कृपया पूरें नाम में अल्फ़ान्यूमेरिक डालें।`,
"enter_user_name_alert":`कृपया उपयोगकर्ता नाम डालें।`,
"enter_user_name_length_alert":`उपयोगकर्ता नाम कम से कम 3 वर्ण लंबा होना चाहिए।`,
"enter_user_type_alert":`कृपया उपयोगकर्ता प्रकार चुनें।`,
"enter_driver_type_alert":`कृपया ड्राइवर प्रकार चुनें।`,
"enter_phone_number_alert":`कृपया फ़ोन नंबर डालें।`,
"enter_phone_number_length_alert":`फोन नंबर 8 से 15 के बीच होना चाहिए।`,
"enter_Numbers_allowed__phone_alert":`फोन क्षेत्र में केवल संख्याओं की अनुमति है।`,
"enter_date_of_birth_alert":`कृपया जन्म तिथि चुनें।`,
"enter_password_length_alert":`पासवर्ड कम से कम 6 अंकों का होना चाहिए।`,
"enter_confirm_password_alert":`कृपया पुष्टि पासवर्ड डालें।`,
"enter_password_not_match_alert":`पासवर्ड और पुष्टि पासवर्ड एक ही होना चाहिए।`,
"enter_terms_conditions_alert":`enter_terms_conditions_alert: "कृपया नियम और शर्तें स्वीकार करें।"`,
"enter_otp_alert":`कृपया सत्यापन कोड डालें।`,
"enter__valid_otp_alert":`कृपया मान्य सत्यापन कोड डालें।`,
"enter_old_password_alert":`कृपया पुराना पासवर्ड डालें।`,
"enter_old_password_length_alert":`पुराना पासवर्ड कम से कम 6 अक्षरों का होना चाहिए।`,
"enter_new_password_alert":`कृपया नया पासवर्ड डालें।`,
"enter_new_password_length_alert":`नया पासवर्ड कम से कम 6 अक्षरों का होना चाहिए।`,
"enter_old_cofirm_not_valid_alert":`पुराना पासवर्ड और पुष्टि पासवर्ड एक ही होना चाहिए।`,
"Stream_stopped_by_user":`लाइव वीडियो पर समाप्त`,
"Loading_streams":`स्ट्रीम लोड हो रही हैं`,
"you_are_live_now":`अब आप लाइव हो।`,
"end_publisher_video":`क्या आप वाकई इस लाइव वीडियो को समाप्त करना चाहते हैं?`,
"logOutAlert":`क्या आप लॉग आउट करना चाहते हैं?`,
"end_publisher_video_successfully":`लाइव वीडियो समाप्त हो गया।`,
"Alert":`चेतावनी`,
"PhoneNumber_required_for_login":`लॉग इन करने के लिए एक फ़ोन नंबर की आवश्यकता है। यह हमें समुदाय को नियंत्रित करने और हमारे उपयोगकर्ताओं की सुरक्षा करने में भी मदद करता है।`,
"Privacy_policy":`आगे जारी रखकर आप सहमत हैं हमारी `,
"Terms":`उपयोग की शर्तें`,
"Policy":`गोपनीयता नीति`,
"Why_you_need_my_phone_number":`आपको क्यों मेरे फोन नंबर की जरूरत है?`,
"Why_we_need_your_phone_number":`हमें क्यों आपके फोन नंबर की जरूरत है`,
"verifyAccount":`अपने अकाउंट को सत्यापित करें`,
"terminalNotFound":`टर्मिनल नहीं मिला।`,
"Profile":`प्रोफ़ाइल`,
"App_Settings":`एप्लिकेशन सेटिंग`,
"estimatedTime":`अनुमानित समय`,
"estimatedWaitTime":`मिनट प्रतीक्षा`,
"youHaveLeft":`आप चले गए`,
"Citizen_safety_message":`Fr8 एक माल ढुलाई नेटवर्क है। हमें आपकी पहचान सत्यापित करने के लिए फ़ोन नंबर की आवश्यकता है और यह सुनिश्चित करने के लिए कि ज़रूरत पड़ने पर हमारे समुदाय के मानकों का उल्लंघन करने वालों को नेटवर्क से हटाया जा सकता है।`,
"something_went_wrong":`कुछ गलत हो गया।`,
"please_check_your_internet_connection":`कृपया अपने इंटरनेट कनेक्शन की जाँच करें।`,
"startEndAlert":`प्रारंभ समय समाप्ति के समय से कम होना चाहिए।`,
"addPost":`पोस्ट जोड़ें`,
"permissionTitle': 'You had denied the permission to take photo from library',":`आपने लाइब्रेरी से फोटो लेने की अनुमति से इनकार कर दिया था`,
"permissionBody":`क्या आप इसे एक्सेस करना चाहते हैं तो फिर सेटिंग्स में अनुमति दें?`,
"videoPermissionTitle":`आपने लाइब्रेरी से वीडियो लेने की अनुमति से इनकार कर दिया था`,
"TimeLine_post_not_found":`टाइमलाइन पोस्ट नहीं मिली।`,
"Timeline_Posts":`टाइमलाइन पोस्ट`,
"Timeline":`टाइमलाइन`,
"trackAtimeLine":`अपने प्रतीक्षा के समय को ट्रैक करें`,
"Journey":`कोई समयरेखा नहीं मिली।`,
"KM":`किमी`,
"Distance_Travelled":`तय की गई दूरी`,
"hrs":`घंटे`,
"secs":`सेकेंड`,
"mins":`मिनट`,
"time":`समय`,
"wait_time":`औसत प्रतीक्षा का समय`,
"Equiment_Photo":`उपकरण फोटो`,
"Interchange_Receipt":`इंटरचेंज रसीद`,
"video":`वीडियो`,
"Share":`शेयर`,
"start_time":`प्रारंभ समय`,
"Report_Post":`रिपोर्ट पोस्ट`,
"endTime":`समाप्ति समय'`,
"openTime":`खुला समय`,
"closeTime":`बंद होने का समय`,
"distance":`दूरी`,
"Total_time":`कुल समय`,
"Edit_Timeline":`टाइमलाइन को संशोधित करें`,
"messageAlert":`कृपया कुछ संदेश डालें`,
"enterMessage":`अपना संदेश डालें...`,
"Trending_Post":`ट्रेंडिंग पोस्ट`,
"PleaseEnterReportResion":`कृपया रिपोर्ट का कारण डालें।`,
"trendingPostNotFound":`कोई ट्रेंडिंग पोस्ट नहीं मिला।`,
"Accept":`स्वीकार करें`,
"Reject":`अस्वीकार करें`,
"Allow":`अनुमति`,
"Invite":`आमंत्रित करें`,
"postNotFound":`कोई पोस्ट नहीं मिली।`,
"Cancel_Friend_Request":`मित्र अनुरोध रद्द करें`,
"User_Posts":`उपयोगकर्ता पोस्ट`,
"Notifications":`सूचनाएं`,
"No_notifications":`कोई सूचनाएं नहीं मिलीं।`,
"And":`तथा`,
"deletePostAlert":`क्या आप वाकई इस पोस्ट को हटाना चाहते हैं?`,
"Yes":`हाँ`,
"No":`नहीं`,
"enterTitle":`कृपया बिंदु डालें`,
"pleaseEnterMessage":`कृपया संदेश डालें।`,
"Post_Create":`पोस्ट बनाएँ`,
"description":`अपना विवरण डालें...`,
"enterDescription":`कृपया विवरण डालें।`,
"descriptionMax":`कृपया विवरण को 1000 से कम अक्षरों में डालें।`,
"descriptionMin":`विवरण कम से कम 10 अक्षरों का होना चाहिए।`,
"Preview":`पूर्वावलोकन`,
"messageMax":`कृपया संदेश को 1000 से कम अक्षरों में डालें।`,
"noUser":`कोई उपयोगकर्ता नहीं मिला।`,
"New":`नया`,
"No_chat_found":`हाल की कोई चैट नहीं मिली`,
"Search_Terminal":`टर्मिनल खोजें`,
"Receipt_Private":`रसीद निजी`,
"Edit":`संपादित करें`,
"Delete":`हटाएं`,
"postShareMessage":`पोस्ट शेयर किया है पोस्ट देखने के लिए नीचे दिए गए लिंक पर क्लिक करें`,
"postShareMessage2":`पोस्ट देखने के लिए नीचे दिए गए लिंक पर क्लिक करें`,
"shareSubject":`FR8 टाइमलाइन पोस्ट`,
"messageCopy":`संदेश कॉपी किया गया`,
"avaliable24Hours":`24 घंटे उपलब्ध`,
"photo":`तस्वीर`,
"photoLibrary":`चित्र पुस्तकालय`,
"photoL":`तस्वीर`,
"photoLibraryL":`चित्र पुस्तकालय`,
"reportUser":`उपयोगकर्ता को रिपोर्ट करें`,
"reasonOfReport":`रिपोर्ट का कारण`,
"reportPostAlert":`क्या आप निश्चित रूप से इस पोस्ट की रिपोर्ट करना चाहते हैं?`,
// "ForegroundServiceTitle":`FR8 ऐप बैकग्राउंड में आपकी लोकेशन मैनेज कर रहा है`,
"ForegroundServiceTitle":`डिटेंशन पे ट्रैकर चल रहा हैहै`,
"Portuguese":`पुर्तगाल`,
"interChangeDelete":`क्या आप वाकई इंटरचेंज रसीद को हटाना चाहते हैं?`,
"equipmentDelete":`क्या आप सुनिश्चित हैं, आप उपकरण फ़ोटो हटाना चाहते हैं?`,
"deleteVideo":`क्या आप सुनिश्चित हैं, आप वीडियो हटाना चाहते हैं?`,
"sentAMessage":`एक संदेश भेजा:`,
"editMessage":`संदेश संपादित करें`,
"continue":`जारी रखना`,
"noContact":`कोई संपर्क नहीं मिला`,
"Driver":`चालक`,
"Owner Operator":`मालिक ऑपरेटर`,
"Company":`कंपनी`,
"Air Cargo Carrier":`एयर कार्गो कैरियर`,
"Exporter":`निर्यातक`,
"Freight Broker":`फ्रेट ब्रोकर`,
"Importer":`आयातक`,
"Shipper":`शिपर`,
"Trucking":`ट्रकिंग`,
"Warehouse":`गोदाम`,
"Company Driver":`कंपनी चालक`,
"OKAY":`ठीक`,
"installMessage":`हैलो FR8 क्या आप एप्लिकेशन इंस्टॉल करने के लिए आमंत्रित करना चाहेंगे।`,
"warned":`आगाह`,
"WaitingAt":`प्रतीक्षारत`,
"openFr8":`अपना अनुमानित प्रतीक्षा समय दिखाने के लिए Fr8 ऐप खोलें।`,
"day":`दिन`,
"days":`दिन`,
"hour":`  घंटा`,
"hours":`  घंटे`,
"minute":`  मिनट`,
"minutes":`  मिनट`,
"second":`  दूसरा`,
"seconds":`  सेकंड`,
"openApp":`अपना स्टेटस सिंक करने के लिए ऐप खोलें`,
"openAppBody":`बेहतरीन अनुभव के लिए, FR8 ऐप को बैकग्राउंड में खुला रहने दें। यह आपकी टाइमलाइन और टर्मिनल टाइम स्टैम्प को सटीक रखता है।`,
"Comment":`टिप्पणी`,
"Comments":`टिप्पणियाँ`,
"Like":`पसंद`,
"noComment":`कोई टिप्पणी नहीं मिली`,
"deleteCommentAlert":`क्या आप वाकई टिप्पणी हटाना चाहते हैं?`,
"enterTheComment":`कृपया टिप्पणी दर्ज करें।`,
"enterYourComment":`अपनी टिप्पणी दर्ज करें...`,
"DeeplinkShare":`लिंक के रूप में शेयर करें`,
"Shares":`शेयरों`,
"shareasPost":`शेयर पोस्ट`,
"hasShared":`साझा किया है`,
"whatsOnMind":`आपके दिमाग मे क्या है?`,
"inGate":`में`,
"outGate":`बाहर`,
"With":`साथ`,
"others":`अन्य`,
"tagFriends":`टैग फ्रेंड्स`,
"done":`किया हुआ`,
"friendSearch":`मित्र खोजें`,
"checkIN":`चेक इन`,
"tagUsers":`टैग किए गए उपयोगकर्ता`,
"safeTrip":` अब आप अपना प्रतीक्षा समय साझा कर सकते हैं। यात्रा सुरक्षित हो!`,
"addLocation":`स्थान जोड़ना`,
"locationSelect":`कृपया स्थान का चयन करें।`,
"attach":`फ़ाइलों को संलग्न करें`,
"selectImage":`कृपया पोस्ट करने के लिए छवियों या वीडियो का चयन करें।`,
"noPlace":`कोई स्थान नहीं मिला`,
"deleteMedia":`क्या आप वाकई इस मीडिया को हटाना चाहते हैं?`,
"deleteNotification":`क्या आप वाकई इस अधिसूचना को हटाना चाहते हैं?`,
"loading":`लोड हो रहा है…`,
"next":`अगला`,
"ttlUserInterminal":`टर्मिनल के अंदर उपयोगकर्ताओं की संख्या:`,
"members":`अंदर के सदस्य`,
"member":`सदस्य अंदर`,
"useLocation":`अपने स्थान का प्रयोग करें`,
"firstPermissionTitle":`स्वचालित रूप से ट्रैक की गई गतिविधियों के लिए मानचित्र देखने के लिए, FR8 को हर समय अपने स्थान का उपयोग करने दें।`,
"noThanks":`जी नहीं, धन्यवाद`,
"turnOn":`चालू करो`,
"newVersion":`नया संस्करण`,
"versionDescription":`ऐप का यह संस्करण पुराना है, कृपया सबसे सटीक और अद्भुत नई सुविधाएं प्राप्त करने में आपकी सहायता के लिए अद्भुत नई सुविधाओं को अनलॉक करने के लिए नवीनतम संस्करण में अपडेट करें। स्थान अनुमतियों को हमेशा अनुमति पर सेट करना न भूलें ताकि ऐप पृष्ठभूमि में आपके लिए टर्मिनल प्रतीक्षा समय की गणना करे।`,
"firstPermissionDesc":`FR8 टर्मिनलों में आपकी यात्राओं की आपकी सटीक रिकॉर्डिंग को सक्षम करने और प्रतीक्षा समय और समय टिकट की गणना करने के लिए पृष्ठभूमि में आपके स्थान का उपयोग करेगा।`,
"validUserName":`केवल अक्षर (a-z), संख्याएँ (0-9), आवर्त (.) और अंडरस्कोर (_) की अनुमति है।`,
"user_name_start":`उपयोगकर्ता नाम अवधियों (.) से प्रारंभ नहीं होना चाहिए`,
"onlyNumberAlert":`उपयोगकर्ता नाम में केवल संख्याएँ नहीं हो सकतीं।`,
"user_name_end":`उपयोगकर्ता नाम अवधियों (।) के साथ समाप्त नहीं होना चाहिए।`,
"twoDots":`उपयोगकर्ता नाम में एक से अधिक अवधि (.) एक पंक्ति में नहीं होनी चाहिए।`,
"Ok":`ठीक`,
"followingTerminal":`अगले`,
"pdfDownload":`डाउनलोड पीडीऍफ़`,
"timelineCancel":`क्या आप वाकई टाइमलाइन रद्द करना चाहते हैं?`,
"Truck Stop":`ट्र्क के रुकने की जगह`,
"Gas Station":`पेट्रोल पंप`,
"Weight Station":`वजन स्टेशन`,
"location_name_enter":`कृपया स्थान का नाम दर्ज करें।`,
"locationNameLong":`स्थान का नाम कम से कम 2 वर्ण लंबा होना चाहिए।`,
"locationAddressLong":`स्थान का पता कम से कम 2 वर्ण लंबा होना चाहिए।`,
"locationAddress":`कृपया स्थान का पता दर्ज करें।`,
"Name":`नाम`,
"Hold to Stop":`रुकने के लिए रुकें`,
"Location Address":`स्थान का पता`,
"Phone Number":`फ़ोन नंबर`,
"Add":`जोड़ें`,
"Category":`श्रेणी`,
"backgroundProcess":`जब आप अन्य स्क्रीन पर जाएंगे तो आपकी टाइमलाइन पृष्ठभूमि में चलेगी।`,
"NotMoving":`अभी नहीं चल रहा है?`,
"oneMinuteLongerAlert":`समाप्त करने और सहेजने के लिए, FR8 को स्थान परिवर्तन के साथ कम से कम 1 मिनट लंबी गतिविधि की आवश्यकता होती है।`,
"editPost":`संपादित पोस्ट`,
"vedioLimit":`वीडियो की अवधि अधिकतम 30 सेकंड लंबी होनी चाहिए।`,
"selectCurentLocation":`वर्तमान स्थान चुनें`,
"noCommentYet":`अब तक कोई टिप्पणी नहीं`,
"enterFirstComment":`टिप्पणी करने वाले पहले बनो।`,
"App_Share":`आवेदन साझा करें`,
"appShareMessage":`FR8 ऐप साझा किया है। मोबाइल एप्लिकेशन देखने और आज का वर्तमान प्रतीक्षा समय देखने के लिए नीचे दिए गए लिंक पर क्लिक करें।`,
"appShareMessage2":`FR8 ऐप \n मोबाइल एप्लिकेशन देखने और आज का वर्तमान प्रतीक्षा समय देखने के लिए नीचे दिए गए लिंक पर क्लिक करें।`,
"deleteCommentReplyAlert":`क्या आप सुनिश्चित हैं, आप इस टिप्पणी उत्तर को हटाना चाहते हैं?`,
"enter_first_name_length_alert":`प्रथम नाम कम से कम 3 वर्ण लंबा होना चाहिए।`,
"enter_last_name_length_alert":`उपनाम कम से कम 3 वर्ण लंबा होना चाहिए।`,
"location_Setting":`स्थान सेटिंग्स`,
"postlikeHeading":`पोस्ट पसंद करने वाले लोग`,
"commentLikeHeading":`कमेंट पसंद करने वाले लोग`,
"viewProfile":`प्रोफ़ाइल देखें`,
"shareListHeading":`पोस्ट शेयर करने वाले लोग`,
"Reply":`जवाब`,
"Reply to":`को उत्तर`,
"Dislike":`नापसन्द`,
"Smile":`मुस्कान`,
"Angry":`गुस्सा`,
"Rolling Eyes":`आखें घुमाना`,
"Thinking":`विचारधारा`,
"Stop":`विराम`,
"switchFrom":`से स्विच करके सटीक सुरक्षा सूचनाएं प्राप्त करें`,
"Always Allow":`हमेशा की अनुमति`,
"While Using":`प्रयोग करते समय`,
"Ask next time":`अगली बार पूछें`,
"Never":`कभी नहीँ`,
"Manage location Settings":`स्थान सेटिंग प्रबंधित करें`,
"Italian":`इतालवी`,
"Chinese":`चीनी सरलीकृत (मंदारिन)`,
"Hindi":`हिंदी`,
"Filipino":`filipino`,
"Vietnamese":`वियतनामी`,
"Arabic":`अरबी`,
"French":`फ्रेंच`,
"Korean":`कोरियाई`,
"Russian":`रूसी`,
"Bengali":`बंगाली`,
"German":`जर्मन`,
regionlNotFound: 'Region not found.',
Region:"Region",
in: 'में',

"All":"सभी",
"saveToPhone":"फ़ोन में सहेजें",
"ADD":"जोड़ें",
"deleteAccount":"खाता हटा दो",
"deleteAccountAlert":"क्या आप इस खाते को हटाने के लिए सुनिश्चित हैं?",
"replyWrite":"जवाब लिखें...",
"Camera":"कैमरा",
"Image Gallery":"छवि गैलरी",
"regionlNotFound":"क्षेत्र नहीं मिला।",
"Region":"क्षेत्र",
"regionSelectAlert":"उपयोगकर्ता अधिकतम 3 क्षेत्रों का चयन कर सकता है।",

"CALL":"बुलाना",
"ADDRESS":"पता",
"MIN":"मिनट",
"About":"के बारे में",
"Overview":"अवलोकन",
"Review":"समीक्षा",
"Timelines":"समयसीमा",
"Rate & Review":"दर और समीक्षा",
"ratings":"दर और समीक्षा",
"Write Your Review":"अपनी समीक्षा लिखिए",
"Just now":"अभी",
'waitTimeIndicator':'प्रतीक्षा संकेतक',
currentWaitTime:"वर्तमान औसत प्रतीक्षा समय",


};

module.exports = {
  constants
};
