import {imageBaseUrl} from '../Config/index'
const constants = {
   // TermsUrl:"http://18.205.207.176:3000/public/pdf/Fr8_App_Terms_Of_Use.pdf",
   TermsUrl:"https://www.fr8.ai/terms",
   // TermsUrl: imageBaseUrl +"public/pdf/Fr8_App_Terms_Of_Use.pdf",
   // PrivacyUrl:"http://18.205.207.176:3000/public/pdf/Fr8_App_Privacy_Policy.pdf",
   PrivacyUrl:"https://www.fr8.ai/privacy",
   // PrivacyUrl: imageBaseUrl + "public/pdf/Fr8_App_Privacy_Policy.pdf",
   posts: 'পোস্টসমূহ',
  
"Email":`ইমেইল`,
"Enter_Email":`ইমেইল প্রদান করুন`,
"Password":`পাসওয়ার্ড`,
"Enter_Password":`পাসওয়ার্ড_প্রবেশ করুন`,
"Enter_New_Password":`নতুন পাসওয়ার্ড প্রবেশ করুন`,
"Forgot_Your_Password":`আপনি কি পাসওয়ার্ড ভুলে গিয়েছেন?`,
"Login":`লগইন করুন`,
"Doesnt_have_an_account":`কোন অ্যাকাউন্ট নেই?`,
"Sign_up":`সাইন আপ করুন`,
"Enter_Name":`নাম প্রবেশ করুন`,
"Enter_first_Name":`প্রথম নাম লিখুন`,
"Enter_last_Name":`পদবি লিখুন`,
"Enter_Your_Phone_Number":`আপনার ফোন নম্বর প্রবেশ করুন`,
"Enter_Six_Digit_Verification_Code":`6 ডিজিটের যাচাইকরণ কোডটি লিখুন "`,
"Resend_Verification_Code":`যাচাইকরণ কোডটি পুনরায় পাঠান`,
"Contact_Permission":`আপনার বন্ধুদের সুরক্ষিত রাখতে যোগাযোগের অনুমতিটি সক্ষম করুন।`,
"Register":`রেজিস্টার করুন`,
"Full_Name":`পুরা নাম`,
"Enter_Full_Name":`পুরা নাম প্রবেশ করুন`,
"Username":`ব্যবহারকারীর নাম`,
"Enter_Username":`ব্যবহারকারীর নাম প্রবেশ করুন`,
"Email_Address":`ইমেইল ঠিকানা`,
"Enter_Email_Address":`ইমেইল ঠিকানা প্রবেশ করুন`,
"User_Type":`ব্যবহারকারীর ধরণ`,
"Select_User_Type":`ব্যবহারকারীর ধরণ নির্বাচন করুন`,
"Phone_Number":`ফোন নম্বর`,
"Enter_Phone_Number":`ফোন নম্বর প্রবেশ করুন`,
"Date_Of_Birth":`জন্মতারিখ`,
"Select_Date_Of_Birth":`জন্মতারিখ নির্বাচন করুন`,
"Confirm_Password":`পাসওয়ার্ড নিশ্চিত করুন`,
"Enter_Confirm_Password":`নিশ্চিত করা পাসওয়ার্ড প্রবেশ করুন`,
"Agree_Terms_and_Condition":`শর্তাবলীর সাথে সম্মত হন`,
"Forgot_Password":`পাসওয়ার্ড ভুলে গিয়েছেন`,
"Submit":`জমা দিন`,
"OTP":`ওটিপি`,
"Enter_OTP":`ওটিপি প্রবেশ করুন`,
"Reset_Password":`পাসওয়ার্ড রিসেট করুন`,
"Edit_Profile":`প্রোফাইল সম্পাদনা করুন`,
"Edit_Phone_Number":`ফোন নম্বর সম্পাদনা করুন`,
"Update":`হালনাগাদ`,
"Change_Password":`পাসওয়ার্ড পরিবর্তন করুন`,
"Old_Password":`পুরানো পাসওয়ার্ড`,
"Enter_Old_Password":`পুরানো পাসওয়ার্ড প্রবেশ করুন`,
"FAQs":`প্রায়শই জিজ্ঞাসিত প্রশ্নাবলী`,
"Social_Media_Accounts":`সামাজিক মিডিয়ার অ্যাকাউন্ট`,
"Settings":`সেটিংস`,
"FR8":`FR8`,
"Support_Center":`সহায়তা কেন্দ্র`,
"Terms_And_Conditions":`শর্তাবলী`,
"Privacy_Policy":`গোপনীয়তা নীতি`,
"Change_Language":`ভাষা পরিবর্তন করুন`,
"Logout":`লগআউট করুন`,
"Log_out":`লগ আউট`,
"Confirm":`নিশ্চিত করুন`,
"Cancel":`বাতিল করুন`,
"Please_Select":`অনুগ্রহ করে নির্বাচন করুন`,
"Warn_Contacts":`যোগাযোগগুলোকে সতর্ক করুন`,
"Search_contacts":`যোগাযোগগুলো অনুসন্ধান করুন`,
"Friend_Requests":`বন্ধুত্বের অনুরোধসমূহ`,
"Friend_Request":`বন্ধুত্বের অনুরোধ`,
"My_Posts":`আমার পোস্ট`,
"Search_friends":`বন্ধু, টার্মিনাল, যোগাযোগ অনুসন্ধান করুন`,
"My_Freighting_Network":`আমার ফ্রেইটিং নেটওয়ার্ক`,
"My_Network":`আমার নেটওয়ার্ক`,
"Places":`স্থানসমূহ`,
"Friends":`বন্ধুরা`,
"Nearby_Terminals":`কাছাকাছি টার্মিনাল`,
"Explore":`এক্সপ্লোর করুন`,
"Contacts":`যোগাযোগ`,
"Name_Of_User":`ব্যবহারকারীর নাম`,
"Add_Friend":`বন্ধু যোগ করুন`,
"Remove_Friend":`বন্ধু অপসারণ করুন`,
"Chat":`চ্যাট করুন`,
"Post_Details":`পোস্টের বিশদ`,
"Live_Streams":`লাইভ স্ট্রিম`,
"CreatePost":`পোস্ট তৈরি করুন`,
"SocialMediaAccounts":`সামাজিক মিডিয়া অ্যাকাউন্ট`,
"Instagram":`ইনস্টাগ্রাম`,
"Google":`গুগল`,
"Facebook":`ফেসবুক`,
"Support":`সমর্থন`,
"Tittle":`শিরোনাম`,
"DescriptionText":`বর্ণনা`,
"Enter_Tittle":`শিরোনাম প্রবেশ করুন`,
"UserName":`ব্যবহারকারীর নাম`,
"TerminalDetails":`টার্মিনালের বিশদ`,
"Location":`অবস্থান`,
"Un_Follow":`আনফলো করুন`,
"Follow":`ফলো করুন`,
"Record":`রেকর্ড`,
"Warn":`সতর্কতা`,
"ChatHistory":`চ্যাটের ইতিহাস`,
"TerminalName":`টার্মিনালের নাম"`,
"Terminal":`টার্মিনাল`,
"English":`ইংরেজি`,
"Spanish":`স্পেনীয়`,
"Driver_Type":`ড্রাইভারের ধরণ`,
"Select_Driver_Type":`ড্রাইভারের ধরন নির্বাচন করুন`,
"Users":`ব্যবহারকারী`,
"Enter_Title":`শিরোনাম প্রবেশ করুন`,
"Type_Message_Here":`এখানে বার্তা টাইপ করুন ...`,
"Skip":`এড়িয়ে যান`,
"Friend_request_not_found":`বন্ধুর অনুরোধ পাওয়া যায় নি।`,
"Change_Mobile_Number":`মোবাইল নম্বর পরিবর্তন করুন`,
"resend_Otp":`নিশ্চিতকরণ কোড আবার পাঠান`,
"post":`পোস্ট`,
"Friend":`বন্ধু`,
"NotificationDetail":`বিজ্ঞপ্তি বিবরণ`,
"noResult":`কোন ফলাফল পাওয়া যায়নি.`,
"enter_email_alert":`ইমেইল ঠিকানা প্রবেশ করুন।`,
"enter_valid_email_alert":`বৈধ ইমেইল ঠিকানা প্রবেশ করুন।`,
"enter_password_alert":`পাসওয়ার্ড প্রবেশ প্রবেশ করুন।`,
"enter_full_name_alert":`পুরো নাম প্রবেশ করুন।`,
"enter_last_name_alert":`শেষ নাম লিখুন দয়া করে.`,
"enter_full_name_aplhanumeric_alert":`সম্পূর্ণ নামের বর্ণানুক্রমিক প্রবেশ করুন।`,
"enter_user_name_alert":`ব্যবহারকারীর নাম প্রবেশ করুন।`,
"enter_user_name_length_alert":`ব্যবহারকারীর নাম কমপক্ষে 3 অক্ষর দীর্ঘ হওয়া উচিত।`,
"enter_user_type_alert":`ব্যবহারকারীর ধরণ নির্বাচন করুন।`,
"enter_driver_type_alert":`ড্রাইভারের ধরণ নির্বাচন করুন।`,
"enter_phone_number_alert":`ফোন নম্বর লিখুন।`,
"enter_phone_number_length_alert":`ফোন নম্বর 8 থেকে 15 এর মধ্যে হতে হবে।`,
"enter_Numbers_allowed__phone_alert":`ফোনের ক্ষেত্রের মধ্যে কেবলমাত্র নম্বর অনুমোদিত।`,
"enter_date_of_birth_alert":`জন্ম তারিখটি নির্বাচন করুন।`,
"enter_password_length_alert":`পাসওয়ার্ড কমপক্ষে 6টি অক্ষর হতে হবে।`,
"enter_confirm_password_alert":`নিশ্চিত পাসওয়ার্ড প্রবেশ করুন।`,
"enter_password_not_match_alert":`পাসওয়ার্ড এবং নিশ্চিত পাসওয়ার্ড অবশ্যই একই হতে হবে।`,
"enter_terms_conditions_alert":`enter_terms_conditions_alert: "শর্তাবলী মেনে নিন" "`,
"enter_otp_alert":`যাচাইকরণ কোড প্রবেশ করুন।`,
"enter__valid_otp_alert":`বৈধ যাচাইকরণ কোড প্রবেশ করুন।`,
"enter_old_password_alert":`পুরানো পাসওয়ার্ড প্রবেশ করুন।`,
"enter_old_password_length_alert":`পুরানো পাসওয়ার্ড কমপক্ষে 6টি অক্ষর হতে হবে।`,
"enter_new_password_alert":`নতুন পাসওয়ার্ড প্রবেশ করুন।`,
"enter_new_password_length_alert":`নতুন পাসওয়ার্ড কমপক্ষে 6টি অক্ষর হতে হবে।`,
"enter_old_cofirm_not_valid_alert":`পুরানো পাসওয়ার্ড এবং নিশ্চিত পাসওয়ার্ড অবশ্যই একই হতে হবে।`,
"Stream_stopped_by_user":`যিনি লাইভ ভিডিওটি শেষ করেছেন`,
"Loading_streams":`স্ট্রিম লোড হচ্ছে`,
"you_are_live_now":`আপনি এখন লাইভে আছেন।`,
"end_publisher_video":`আপনি কি নিশ্চিত যে আপনি এই লাইভ ভিডিওটি শেষ করতে চান?`,
"logOutAlert":`আপনি কি নিশ্চিত যে আপনি লগ আউট করতে চান?`,
"end_publisher_video_successfully":`লাইভ ভিডিওটি শেষ হয়েছে।`,
"Alert":`সতর্কতা`,
"PhoneNumber_required_for_login":`লগ ইন করার জন্য একটি ফোন নম্বর প্রয়োজন। এটি আমাদের সম্প্রদায়টি নিয়ন্ত্রণ করতে এবং আমাদের ব্যবহারকারীদের সুরক্ষা প্রদান করতে সহায়তা করে।`,
"Privacy_policy":`চালিয়ে যাওয়ার মাধ্যমে আপনি আমাদের শর্তাবলীর`,
"Terms":`সাথে সম্মত হয়েছেন`,
"Policy":`গোপনীয়তা নীতি`,
"Why_you_need_my_phone_number":`আপনার আমার ফোন নম্বর কেন প্রয়োজন`,
"Why_we_need_your_phone_number":`আপনার ফোন নম্বরটি কেন আমাদের প্রয়োজন`,
"verifyAccount":`আপনার অ্যাকাউন্টটি যাচাই করুন`,
"terminalNotFound":`টার্মিনালটি পাওয়া যায়নি।`,
"Profile":`প্রোফাইল`,
"App_Settings":`অ্যাপ সেটিংস`,
"estimatedTime":`আনুমানিক সময়`,
"estimatedWaitTime":`মিনিট অপেক্ষা`,
"youHaveLeft":`আপনি চলে গেছেন`,
"Citizen_safety_message":`Fr8 একটি ফ্রেইটিং নেটওয়ার্ক। আপনার পরিচয় যাচাই করার জন্য এবং উপযুক্ত সময়ে আমাদের সম্প্রদায়ের স্ট্যান্ডার্ড লঙ্ঘনকারীদের নেটওয়ার্ক থেকে অপসারণ করতে পারাটা নিশ্চিত করার জন্য উভয় ক্ষেত্রের জন্যই আমাদের একটি ফোন নম্বর প্রয়োজন।`,
"something_went_wrong":`কোন সমস্যা হয়েছে।`,
"please_check_your_internet_connection":`আপনার ইন্টারনেট সংযোগটি পরীক্ষা করুন।`,
"startEndAlert":`শুরুর সময় শেষ হওয়ার সময় থেকে কম হতে হবে। `,
"addPost":`পোস্ট যোগ করুন`,
"permissionTitle': 'You had denied the permission to take photo from library',":`আপনি লাইব্রেরি থেকে ফটো নেওয়ার অনুমতি দিতে অস্বীকার করেছিলেন`,
"permissionBody":`আপনি কি এটিকে অ্যাক্সেস এবং তারপর সেটিংসে যাওয়ার অনুমতি দিতে চান?`,
"videoPermissionTitle":`আপনি লাইব্রেরি থেকে ভিডিও নেওয়ার অনুমতি দিতে অস্বীকার করেছিলেন`,
"TimeLine_post_not_found":`টাইমলাইনের পোস্ট পাওয়া যায়নি।`,
"Timeline_Posts":`টাইমলাইন পোস্ট`,
"Timeline":`টাইমলাইন`,
"trackAtimeLine":`আপনার অপেক্ষার সময় ট্র্যাক করুন`,
"Journey":`কোনো টাইমলাইন পাওয়া যায়নি।`,
"KM":`কিমি`,
"Distance_Travelled":`ভ্রমণকৃত দূরত্ব`,
"hrs":`ঘন্টা`,
"secs":`সেকেন্ড`,
"mins":`মিনিট`,
"time":`সময়`,
"wait_time":`গড় অপেক্ষার সময়`,
"Equiment_Photo":`সরঞ্জামের ফটো`,
"Interchange_Receipt":`রসিদ বিনিময় করুন`,
"video":`ভিডিও`,
"Share":`শেয়ার করুন`,
"start_time":`শুরুর সময়`,
"Report_Post":`রিপোর্ট পোস্ট`,
"endTime":`শেষ হওয়ার সময়`,
"openTime":`খোলা সময়`,
"closeTime":`বন্ধ সময়`,
"distance":`দূরত্ব`,
"Total_time":`মোট সময়`,
"Edit_Timeline":`টাইমলাইন সম্পাদনা করুন`,
"messageAlert":`কিছু বার্তা প্রবেশ করুন।`,
"enterMessage":`আপনার মেসেজ প্রবেশ করুন...`,
"Trending_Post":`ট্রেন্ডিং পোস্ট`,
"PleaseEnterReportResion":`রিপোর্টের কারণ প্রবেশ করুন।`,
"trendingPostNotFound":`কোনও ট্রেন্ডিং পোস্ট পাওয়া যায়নি।`,
"Accept":`গ্রহণ করুন`,
"Reject":`প্রত্যাখ্যান করুন`,
"Allow":`অনুমতি দিন`,
"Invite":`আমন্ত্রণ জানান`,
"postNotFound":`কোন পোস্ট পাওয়া যায়নি।`,
"Cancel_Friend_Request":`বন্ধুর অনুরোধ বাতিল করুন`,
"User_Posts":`ব্যবহারকারীর পোস্ট`,
"Notifications":`বিজ্ঞপ্তি`,
"No_notifications":`কোন বিজ্ঞপ্তি পাওয়া যায়নি।`,
"And":`এবং`,
"deletePostAlert":`আপনি কি নিশ্চিত যে আপনি এই পোস্টটি মুছে ফেলতে চান?`,
"Yes":`হ্যাঁ`,
"No":`না`,
"enterTitle":`শিরোনাম প্রবেশ করুন।`,
"pleaseEnterMessage":`বার্তা প্রবেশ করুন।`,
"Post_Create":`পোস্ট তৈরি করুন`,
"description":`আপনার বিবরণ প্রবেশ করুন...`,
"enterDescription":`বিবরণ প্রবেশ করুন।`,
"descriptionMax":`1000 অক্ষরের কমের মধ্যে বিবরণ লিখুন।`,
"descriptionMin":`বিবরণটি কমপক্ষে 10 অক্ষর দীর্ঘ হতে হবে।`,
"Preview":`প্রিভিউ`,
"messageMax":`1000 অক্ষরের কমের মধ্যে বার্তা লিখুন।`,
"noUser":`কোন ব্যবহারকারী পাওয়া যায়নি।`,
"New":`নতুন`,
"No_chat_found":`কোন সাম্প্রতিক চ্যাট পাওয়া যায়নি`,
"Search_Terminal":`টার্মিনাল অনুসন্ধান করুন`,
"Receipt_Private":`রসিদ ব্যক্তিগত`,
"Edit":`সম্পাদনা করুন`,
"Delete":`মুছে ফেলা`,
"postShareMessage":`পোস্ট শেয়ার করেছেন পোস্ট দেখতে নিচের লিঙ্কে ক্লিক করুন`,
"postShareMessage2":`পোস্ট শেয়ার করেছেন পোস্ট দেখতে নিচের লিঙ্কে ক্লিক করুন`,
"shareSubject":`FR8 টাইমলাইন পোস্ট`,
"messageCopy":`বার্তা কপি করা হয়েছে`,
"avaliable24Hours":`24 ঘন্টা উপলব্ধ`,
"photo":`ফটো`,
"photoLibrary":`ফটো লাইব্রেরি`,
"photoL":`ছবি`,
"photoLibraryL":`ফটো লাইব্রেরি`,
"reportUser":`রিপোর্ট ব্যবহারকারী`,
"reasonOfReport":`রিপোর্টের কারণ`,
"reportPostAlert":`তুমি কি নিশ্চিত যে এই পোস্টটি রিপোর্ট করতে চাও?`,
// "ForegroundServiceTitle":`FR8 অ্যাপ ব্যাকগ্রাউন্ডে আপনার অবস্থান পরিচালনা করছে`,
"ForegroundServiceTitle":`ডিটেনশন পে ট্র্যাকার চলছে`,
"Portuguese":`পর্তুগাল`,
"interChangeDelete":`আপনি কি নিশ্চিত, আপনি ইন্টারচেঞ্জ রসিদ মুছতে চান?`,
"equipmentDelete":`আপনি কি নিশ্চিত, আপনি সরঞ্জামের ফটো মুছতে চান?`,
"deleteVideo":`আপনি কি নিশ্চিত, আপনি ভিডিও মুছে দিতে চান?`,
"sentAMessage":`একটি বার্তা পাঠিয়েছেন:`,
"editMessage":`বার্তা সম্পাদনা করুন`,
"continue":`চালিয়ে যান`,
"noContact":`কোন পরিচিতি পাওয়া যায়নি`,
"Driver":`ড্রাইভার`,
"Owner Operator":`মালিক অপারেটর`,
"Company":`প্রতিষ্ঠান`,
"Air Cargo Carrier":`এয়ার কার্গো ক্যারিয়ার`,
"Exporter":`রপ্তানিকারক`,
"Freight Broker":`মালবাহী দালাল`,
"Importer":`আমদানিকারক`,
"Shipper":`শিপার`,
"Trucking":`ট্রাকিং`,
"Warehouse":`গুদাম`,
"Company Driver":`কোম্পানির ড্রাইভার`,
"OKAY":`ঠিক আছে`,
"installMessage":`হ্যালো FR8 আপনি কি অ্যাপ্লিকেশনটি ইনস্টল করার জন্য আমন্ত্রণ জানাতে চান৷`,
"warned":`সতর্ক করা`,
"WaitingAt":`এ অপেক্ষা করছে`,
"openFr8":`আপনার আনুমানিক অপেক্ষার সময় দেখাতে Fr8 অ্যাপ খুলুন।`,
"day":`দিন`,
"days":`দিন`,
"hour":`  ঘন্টা`,
"hours":`  ঘন্টার`,
"minute":`  মিনিট`,
"minutes":`  মিনিট`,
"second":`  দ্বিতীয়`,
"seconds":`  সেকেন্ড`,
"openApp":`আপনার স্থিতি সিঙ্ক করতে অ্যাপটি খুলুন`,
"openAppBody":`সেরা অভিজ্ঞতার জন্য, FR8 অ্যাপটিকে ব্যাকগ্রাউন্ডে খোলা থাকার অনুমতি দিন। এটি আপনার টাইমলাইন এবং টার্মিনাল টাইম স্ট্যাম্প সঠিক রাখে।`,
"Comment":`মন্তব্য করুন`,
"Comments":`মন্তব্য`,
"Like":`লাইক`,
"noComment":`কোন মন্তব্য পাওয়া যায়নি`,
"deleteCommentAlert":`আপনি কি মন্তব্যটি মুছতে চান?`,
"enterTheComment":`মন্তব্য লিখুন.`,
"enterYourComment":`আপনার মন্তব্য লিখুন...`,
"DeeplinkShare":`লিঙ্ক হিসাবে শেয়ার করুন`,
"Shares":`শেয়ার`,
"shareasPost":`পোস্ট শেয়ার করুন`,
"hasShared":`ভাগ করেছে`,
"whatsOnMind":`কি ভাবছো?`,
"inGate":`ভিতরে`,
"outGate":`আউট`,
"With":`সঙ্গে`,
"others":`অন্যান্য`,
"tagFriends":`বন্ধুদের ট্যাগ করুন`,
"done":`সম্পন্ন`,
"friendSearch":`বন্ধুদের অনুসন্ধান করুন`,
"checkIN":`চেক ইন`,
"tagUsers":`ট্যাগ করা ব্যবহারকারী`,
"safeTrip":` আপনি এখন আপনার অপেক্ষার সময় ভাগ করতে পারেন। একটি নিরাপদ ট্রিপ আছে!`,
"addLocation":`ঠিকানা যোগ করুন`,
"locationSelect":`অবস্থান নির্বাচন করুন.`,
"attach":`সংযুক্ত নথি`,
"selectImage":`পোস্ট করতে ছবি বা ভিডিও নির্বাচন করুন.`,
"noPlace":`কোন স্থান পাওয়া যায়নি`,
"deleteMedia":`আপনি কি নিশ্চিত, আপনি এই মিডিয়া মুছে দিতে চান?`,
"deleteNotification":`আপনি কি নিশ্চিত, আপনি এই বিজ্ঞপ্তিটি মুছতে চান?`,
"loading":`লোড হচ্ছে...`,
"next":`পরবর্তী`,
"ttlUserInterminal":`টার্মিনালের ভিতরে ব্যবহারকারীর সংখ্যা:`,
"members":`ভেতরে সদস্যরা`,
"member":`ভিতরে সদস্য`,
"useLocation":`আপনার অবস্থান ব্যবহার করুন`,
"firstPermissionTitle":`স্বয়ংক্রিয়ভাবে ট্র্যাক করা কার্যকলাপের জন্য মানচিত্র দেখতে, FR8 কে সব সময় আপনার অবস্থান ব্যবহার করার অনুমতি দিন।`,
"noThanks":`না ধন্যবাদ`,
"turnOn":`চালু করা`,
"newVersion":`নতুন সংস্করণ`,
"versionDescription":`অ্যাপটির এই সংস্করণটি পুরানো হয়ে গেছে, আপনাকে সবচেয়ে সঠিক এবং আশ্চর্যজনক নতুন বৈশিষ্ট্যগুলি পেতে সাহায্য করার জন্য আশ্চর্যজনক নতুন বৈশিষ্ট্যগুলি আনলক করতে অনুগ্রহ করে সর্বশেষ সংস্করণে আপডেট করুন৷ অলওয়েজ অ্যালোতে অবস্থানের অনুমতি সেট করতে ভুলবেন না যাতে অ্যাপটি ব্যাকগ্রাউন্ডে আপনার জন্য টার্মিনাল ওয়েট টাইম গণনা করে।`,
"firstPermissionDesc":`টার্মিনালে আপনার ভ্রমণের সুনির্দিষ্ট রেকর্ডিং সক্ষম করতে এবং অপেক্ষার সময় এবং সময় স্ট্যাম্প গণনা করতে FR8 ব্যাকগ্রাউন্ডে আপনার অবস্থান ব্যবহার করবে।`,
"validUserName":`শুধুমাত্র অক্ষর (a-z), সংখ্যা (0-9), পিরিয়ড (.) এবং আন্ডারস্কোর (_) অনুমোদিত।`,
"user_name_start":`ব্যবহারকারীর নাম পিরিয়ড (.) দিয়ে শুরু করা উচিত নয়`,
"onlyNumberAlert":`ব্যবহারকারীর নামে শুধুমাত্র সংখ্যা থাকতে পারে না।`,
"user_name_end":`ব্যবহারকারীর নাম পিরিয়ড (.) দিয়ে শেষ হওয়া উচিত নয়`,
"twoDots":`ইউজারনেমে পরপর এক পিরিয়ড (.) এর বেশি থাকা উচিত নয়।`,
"Ok":`ঠিক আছে`,
"followingTerminal":`অনুসরণ করছে`,
"pdfDownload":`PDF ডাউনলোড করুন`,
"timelineCancel":`আপনি কি নিশ্চিত, আপনি টাইমলাইন বাতিল করতে চান?`,
"Truck Stop":`ট্রাক স্টপ`,
"Gas Station":`গ্যাস স্টেশন`,
"Weight Station":`ওজন স্টেশন`,
"location_name_enter":`অনুগ্রহ করে অবস্থানের নাম লিখুন।`,
"locationNameLong":`অবস্থানের নাম কমপক্ষে 2 অক্ষর দীর্ঘ হওয়া উচিত।`,
"locationAddressLong":`অবস্থান ঠিকানা কমপক্ষে 2 অক্ষর দীর্ঘ হওয়া উচিত।`,
"locationAddress":`অবস্থান ঠিকানা লিখুন দয়া করে.`,
"Name":`নাম`,
"Hold to Stop":`থামাতে হোল্ড করুন`,
"Location Address":`অবস্থান ঠিকানা`,
"Phone Number":`ফোন নম্বর`,
"Add":`যোগ করুন`,
"Category":`শ্রেণী`,
"backgroundProcess":`আপনি যখন অন্য স্ক্রিনে যাবেন তখন আপনার টাইমলাইন পটভূমিতে চলবে।`,
"NotMoving":`এখনও চলন্ত না?`,
"oneMinuteLongerAlert":`শেষ করতে এবং সংরক্ষণ করতে, FR8-এর অবস্থান পরিবর্তনের সাথে কমপক্ষে 1 মিনিট দীর্ঘ কার্যকলাপ প্রয়োজন।`,
"editPost":`পোস্ট সম্পাদনা করুন`,
"vedioLimit":`ভিডিওর সময়কাল সর্বাধিক 30 সেকেন্ড দীর্ঘ হওয়া উচিত।`,
"selectCurentLocation":`বর্তমান অবস্থান নির্বাচন করুন`,
"noCommentYet":`এখনো কোন মন্তব্য নেই`,
"enterFirstComment":`মন্তব্য করুন.`,
"App_Share":`আবেদন শেয়ার করুন`,
"appShareMessage":`FR8 অ্যাপ শেয়ার করেছে। মোবাইল অ্যাপ্লিকেশন দেখতে নীচের লিঙ্কে ক্লিক করুন এবং আজকের অপেক্ষার বর্তমান সময়গুলি দেখুন৷`,
"appShareMessage2":`FR8 \n মোবাইল অ্যাপ্লিকেশন দেখতে নীচের লিঙ্কে ক্লিক করুন এবং আজকের অপেক্ষার বর্তমান সময়গুলি দেখুন৷`,
"deleteCommentReplyAlert":`আপনি কি নিশ্চিত, আপনি এই মন্তব্যের উত্তর মুছে দিতে চান?`,
"enter_first_name_length_alert":`প্রথম নাম কমপক্ষে 3 অক্ষর দীর্ঘ হওয়া উচিত।`,
"enter_last_name_length_alert":`পদবি কমপক্ষে 3টি অক্ষর দীর্ঘ হওয়া উচিত।`,
"location_Setting":`অবস্থান সেটিংস`,
"postlikeHeading":`যারা পোস্ট পছন্দ করেন`,
"commentLikeHeading":`যারা লাইক কমেন্ট করেন`,
"viewProfile":`প্রোফাইল দেখুন`,
"shareListHeading":`পোস্ট শেয়ার করা মানুষ`,
"Reply":`উত্তর দিন`,
"Reply to":`প্রতিউত্তর`,
"Dislike":`অপছন্দ`,
"Smile":`হাসি`,
"Angry":`রাগ`,
"Rolling Eyes":`ঘূর্ণায়মান চোখ`,
"Thinking":`ভাবনা`,
"Stop":`থামুন`,
"switchFrom":`থেকে স্যুইচ করে সঠিক নিরাপত্তা বিজ্ঞপ্তি পান`,
"Always Allow":`সবসময় অনুমতি`,
"While Using":`ব্যবহার করার সময়`,
"Ask next time":`পরের বার জিজ্ঞাসা করুন`,
"Never":`কখনই না`,
"Manage location Settings":`অবস্থান সেটিংস পরিচালনা করুন`,
"Italian":`ইতালীয়`,
"Chinese":`চাইনিজ সরলীকৃত (ম্যান্ডারিন)`,
"Hindi":`হিন্দি`,
"Filipino":`ফিলিপিনো`,
"Vietnamese":`ভিয়েতনামী`,
"Arabic":`আরবি`,
"French":`ফরাসি`,
"Korean":`কোরিয়ান`,
"Russian":`রাশিয়ান`,
"Bengali":`বাংলা`,
"German":`জার্মান`,
regionlNotFound: 'Region not found.',
Region:"Region",
in: 'ভিতরে',
"All":'সব',

"All":"সব",
"saveToPhone":"ফোনে সেভ করুন",
"ADD":"যোগ করুন",
"deleteAccount":"হিসাব মুছে ফেলা",
"deleteAccountAlert":"আপনি আপনার একাউন্ট মুছে ফেলতে চান আপনি কি নিশ্চিত?",
"replyWrite":"একটি প্রতিউত্তর লেখ...",
"Camera":"ক্যামেরা",
"Image Gallery":"ছবির গ্যালারি",
"regionlNotFound":"অঞ্চল খুঁজে পাওয়া যায়নি.",
"Region":"অঞ্চল",
"regionSelectAlert":"ব্যবহারকারী সর্বোচ্চ 3টি অঞ্চল নির্বাচন করতে পারেন।",

"CALL":"কল করুন",
"ADDRESS":"ঠিকানা",
"MIN":"MIN",
"About":"সম্পর্কিত",
"Overview":"ওভারভিউ",
"Review":"পুনঃমূল্যায়ন",
"Timelines":"টাইমলাইন",
"Rate & Review":"রেট এবং পর্যালোচনা",
"ratings":"রেট এবং পর্যালোচনা",
"Write Your Review":"আপনার পর্যালোচনা লিখুন",
"Just now":"এক্ষুনি",
'waitTimeIndicator':`অপেক্ষার সময় নির্দেশক`,
currentWaitTime:"বর্তমান গড় অপেক্ষার সময়",

};

module.exports = {
  constants
};
