import {imageBaseUrl} from '../Config/index'
const constants = {
  // TermsUrl:"http://18.205.207.176:3000/public/pdf/Fr8_App_Terms_Of_Use.pdf",
  TermsUrl:"https://www.fr8.ai/terms",
  // TermsUrl: imageBaseUrl +"public/pdf/Fr8_App_Terms_Of_Use.pdf",
  // PrivacyUrl:"http://18.205.207.176:3000/public/pdf/Fr8_App_Privacy_Policy.pdf",
  PrivacyUrl:"https://www.fr8.ai/privacy",
  // PrivacyUrl: imageBaseUrl + "public/pdf/Fr8_App_Privacy_Policy.pdf",
  Email: "Email",
  Enter_Email: "Enter Email",
  Password: "Password",
  Enter_Password: "Enter Password",
  Enter_New_Password: "Enter New Password",
  Forgot_Your_Password: "Forgot Your Password?",
  Login: "Login",
  Doesnt_have_an_account: "Doesn't have an account?",
  Sign_up: "Sign up",

  Enter_Name: "Enter name",
  Enter_first_Name: "Enter first name",
  Enter_last_Name: "Enter last name",
  Enter_Your_Phone_Number: "Enter your phone number",
  Enter_Six_Digit_Verification_Code: "Enter 6 digit verification code",
  Resend_Verification_Code: "Resend verification code",
  Contact_Permission:
    "Please enable contacts permission in order to keep your friends safe.",

  Register: "Register",
  Full_Name: "Full Name",
  Enter_Full_Name: "Enter Full Name",
  Username: "Username",
  Enter_Username: "Enter username",
  Email_Address: "Email address",
  Enter_Email_Address: "Enter email address",
  User_Type: "User Type",
  Select_User_Type: "Select user type",
  Phone_Number: "Phone number",
  Enter_Phone_Number: "Enter phone number",
  Date_Of_Birth: "Date Of Birth",
  Select_Date_Of_Birth: "Select Date Of Birth",
  Confirm_Password: "Confirm Password",
  Enter_Confirm_Password: "Enter Confirm Password",
  Agree_Terms_and_Condition: "Agree Terms and Conditions",

  Forgot_Password: "Forgot Password",
  Submit: "Submit",
  OTP: "OTP",
  Enter_OTP: "Enter OTP",
  Reset_Password: "Reset Password",
  Edit_Profile: "Edit Profile",
  Edit_Phone_Number: "Edit Phone Number",
  Update: "Update",
  Change_Password: "Change Password",
  Old_Password: "Old Password",
  Enter_Old_Password: "Enter Old Password",
  FAQs: "FAQs",
  Social_Media_Accounts: "Social Media Accounts",
  Settings: "Settings",
  "FR8": "FR8",
  Support_Center: "Support Center",
  Terms_And_Conditions: "Terms And Conditions",
  Privacy_Policy: "Privacy Policy",
  Change_Language: "Change Language",
  Logout: "Logout",
  Log_out: "Log Out",
  Confirm: "Confirm",
  Cancel: "Cancel",
  Please_Select: "Please Select",
  Warn_Contacts: "Warn Contacts",
  Search_contacts: "Search contacts",
  Friend_Requests: "Friend Requests",
  Friend_Request: "Friend Request",
  My_Posts: "My Posts",
  Search_friends: "Search friends, terminals, contacts",
  My_Freighting_Network: "My Freighting Network",
  'My_Network': 'My Network',
  Places: "Places",
  Friends: "Friends",
  Nearby_Terminals: "Nearby Terminals",
  Explore: "Explore",
  Contacts: "Contacts",
  Name_Of_User: "Name Of User",
  Add_Friend: "Add Friend",
  Remove_Friend: "Remove Friend",
  Chat: "Chat",
  Post_Details: "Post Details",
  Live_Streams: "Live Streams",
  CreatePost: "Create Post",
  SocialMediaAccounts: "Social Media Accounts",
  Instagram: "Instagram",
  Google: "Google",
  Facebook: "Facebook",
  Support: "Support",
  Tittle: "Title",
  DescriptionText:'Description',
  Enter_Tittle: "Enter Title",
  FR8: "FR8",
  UserName: "User Name",
  TerminalDetails: "Terminal Details",
  Location: "Location",
  Un_Follow: "Unfollow",
  Follow: "Follow",
  Record: "Record",
  Warn: "Warn",
  ChatHistory: "Chat History",
  TerminalName: "Terminal Name",
  Terminal: 'Terminal',
  English: "English",
  Spanish: "Spanish",
  Driver_Type: "Driver Type",
  Select_Driver_Type: "Select driver type",
  Users: "Users",
  Enter_Title: "Enter Title",
  Type_Message_Here: "Type Message Here...",
  Change_Language: "Change Language",
  Skip: "Skip",
  Friend_request_not_found: "Friend request not found.",
  Change_Mobile_Number: "Change Mobile Number",
  resend_Otp: "Resend Verification Code",
  posts: 'Posts',
  
  post: 'Post',
  Friend: 'Friend',
  NotificationDetail:'Notification Details',
  'noResult': 'No result found.',

  /////////////// Alert Message /////////////////////

  enter_email_alert: "Please enter email address.",
  enter_valid_email_alert: "Please enter valid email address.",
  enter_password_alert: "Please enter password.",
  // enter_full_name_alert: "Please enter full name.",
  // enter_full_name_aplhanumeric_alert: "Please enter alphanumeric in full name.",
  enter_full_name_alert: "Please enter first name.",
  enter_last_name_alert: "Please enter last name.",
  enter_full_name_aplhanumeric_alert: "Please enter alphanumeric in name.",
  enter_user_name_alert: "Please enter username.",
  enter_user_name_length_alert: "Username should be at least 3 characters long.",

  enter_user_type_alert: "Please select user type.",
  enter_driver_type_alert: "Please select driver type.",
  enter_phone_number_alert: "Please enter phone number.",
  enter_phone_number_length_alert: "Phone number should be between 8 to 15 digits.",
  enter_Numbers_allowed__phone_alert: "Only number are allowed in phone field.",
  enter_date_of_birth_alert: "Please select date of birth.",
  enter_password_length_alert: "Password must be at least 6 characters.",
  enter_confirm_password_alert: "Please enter confirm password.",
  enter_password_not_match_alert: "Password and Confirm Password must be same.",
  enter_terms_conditions_alert: "Please accept terms & conditions.",
  enter_otp_alert: "Please enter verification code.",
  enter__valid_otp_alert: "Please enter valid verification code.",
  enter_old_password_alert: "Please enter old password.",
  enter_old_password_length_alert:
    "Old Password must be at least 6 characters.",
  enter_new_password_alert: "Please enter new password.",
  enter_new_password_length_alert:
    "New Password must be at least 6 characters.",
  enter_old_cofirm_not_valid_alert:
    "New Password and confirm new password must be same.",
  Stream_stopped_by_user: "Live video ended by ",
  Loading_streams: "Loading streams",
  you_are_live_now: "You are now live.",
  end_publisher_video: "Are you sure you want to end this live video?",
  logOutAlert: "Are you sure you want to logout?",
  end_publisher_video_successfully: "Live video ended.",
  Alert: "Alert",
  PhoneNumber_required_for_login:
    "A phone number is required to log in.It also helps us moderate the community and protect our users.",
  Privacy_policy:
    "BY CONTINUING YOU AGREE TO OUR",
  Terms: "TERMS OF USE",
  Policy: "PRIVACY POLICY",
  Why_you_need_my_phone_number: "WHY DO YOU NEED MY PHONE NUMBER",
  Why_we_need_your_phone_number: "WHY WE NEED YOUR PHONE NUMBER",
  verifyAccount: "VERIFY YOUR ACCOUNT",
  terminalNotFound: 'Terminal not found.',
  Profile: 'Profile',
  App_Settings: 'App Settings',
  'estimatedTime': 'Estimated Time',
  // 'estimatedWaitTime': 'Estimated Waiting time',
  'estimatedWaitTime': 'Minutes Waited',
  'youHaveLeft': "You’ve left",
  Citizen_safety_message:
    "Fr8 is a Freighting Network. We require a phone number to both verify your identity and to ensure those who violate our community standards can be removed from the network, when appropriate.",
  ///////////// Api message //////////////////
  "something_went_wrong": "Something went wrong.",
  "please_check_your_internet_connection":
    "Please check your internet connection.",
  startEndAlert: "Start time should be less then end time.",
  'addPost': 'Add Post',
  'permissionTitle': 'You had denied the permission to take photo from library',
  'permissionBody': 'Would you like access this then allow permission in settings?',
  'videoPermissionTitle': "You had denied the permission to take video from library",
  'TimeLine_post_not_found': 'Post your update.',
  Timeline_Posts: 'Timeline Posts',
  'Timeline': 'Timeline',
  // 'trackAtimeLine':'Track a wait time',
  'trackAtimeLine': 'Track Your Wait Time',
  'Journey': 'No timeline found.',
  'KM': 'mi',
  'Distance_Travelled': 'Distance Travelled',
  hrs: ' hrs',
  secs: ' secs',
  mins: " mins",
  time: 'Time',
  'wait_time': 'Avg. wait Time',
  'Equiment_Photo': 'Equipment Photo',
  'Interchange_Receipt': 'Interchange Receipt',
  'video': 'Video',
  'Share': 'Share',
  start_time: 'In',
  in: 'in',
  Report_Post: 'Report Post',
  endTime: 'Out',
  openTime: 'Open Time',
  closeTime: 'Close Time',
  'distance': "Distance",
  'Total_time': 'Total Time',
  'Edit_Timeline': 'Edit Timeline',
  'messageAlert': 'Please enter some message.',
  'enterMessage': 'Enter your message...',
  'Trending_Post': 'Trending Post',
  'PleaseEnterReportResion': 'Please enter the reason of report.',
  'trendingPostNotFound': 'No trending post found.',
  'Accept': 'Accept',
  'Reject': 'Reject',
  'Allow': "Allow",
  'Invite': 'Invite',
  'postNotFound': 'No post found.',
  'Cancel_Friend_Request': 'Cancel Friend Request',
  'User_Posts': "User Posts",
  'Notifications': 'Notifications',
  No_notifications: 'No notifications found.',
  'And': 'AND',
  'deletePostAlert': 'Are you sure, you want to delete this post?',
  'Yes': 'Yes',
  'No': 'No',
  'enterTitle': 'Please enter title.',
  'pleaseEnterMessage': 'Please enter message.',
  'Post_Create': 'Create Post',
  'description': 'Enter your description...',
  'enterDescription': 'Please enter the description.',
  'descriptionMax': 'Please enter description less then 1000 characters.',
  'descriptionMin': 'Description must be at least 10 characters long.',
  'Preview': "Preview",
  'messageMax': 'Please enter message less then 1000 characters .',
  'noUser': 'No user found.',
  'New': 'New',
  'No_chat_found': 'No recent chat found.',
  'Search_Terminal': 'Search Terminal',
  // "Receipt_Private": 'Receipt Private',
  "Receipt_Private": 'Make Private',
  'Edit': 'Edit',
  'Delete': 'Delete',
  'postShareMessage': ' has shared post\nClick on below link to view post ',
  'postShareMessage2': 'Click on below link to view post ',
  'shareSubject': 'FR8 TimeLine Post',
  'messageCopy': 'Message copied',
  'avaliable24Hours': 'Available 24 hours',
  "photo": "PHOTO",
  'photoLibrary': 'PHOTO LIBRARY',
  "photoL": "Photo",
  'photoLibraryL': 'Photo Library',
  // 'reportUser': 'Report User',
  'reportUser': 'Report',
  'reasonOfReport': 'Reason Of Report',
  'reportPostAlert': 'Are you sure, you want to report this post?',
  // "ForegroundServiceTitle": "FR8 app is managing your location in background",
  "ForegroundServiceTitle": "Detention Pay Tracker is running",
  "Portuguese": "Portugal",
  "interChangeDelete": 'Are you sure, you want to delete Interchange Receipt?',
  "equipmentDelete": "Are you sure, you want to delete equipment photo?",
  "deleteVideo": "Are you sure, you want to delete video?",
  'sentAMessage': 'sent a message:',
  'editMessage': 'Edit Message',
  'continue': 'Continue',
  'noContact': 'No Contacts Found',
  'Driver': "Driver",
  'Owner Operator': 'Owner Operator',
  "Company": 'Company',
  "Air Cargo Carrier": 'Air Cargo Carrier',
  "Exporter": "Exporter",
  "Freight Broker": 'Freight Broker',
  "Importer": "Importer",
  "Shipper": "Shipper",
  "Trucking": "Trucking",
  "Warehouse": "Warehouse",
  'Owner Operator': 'Owner Operator',
  'Company Driver': 'Company Driver',
  'OKAY': 'OKAY',
  'installMessage': `Hey, download the FR8 App so you can calculate the wait times at the port|rail terminals: http://onelink.to/fr8app`,
  'warned': 'warned',
  "WaitingAt": 'Waiting at',
  'openFr8': 'Open the Fr8 app to show your estimated wait time.',
  "day": "day",
  "days": "days",
  "hour": " hour",
  "hours": " hours",
  "minute": " minute",
  "minutes": " minutes",
  "second": " second",
  "seconds": " seconds",
  'openApp': 'Open the App to Sync your Status',
  'openAppBody': 'For the best experience, allow the FR8 App to remain open in the background. This keeps your timeline and terminal time stamp accurate.',
  "Comment":"Comment",
  "Comments":"Comments",
  "Like":"Like",
  'noComment':"No comment found",
  'deleteCommentAlert':"Are you sure, you want to delete the comment?",
  
  'enterTheComment':"Please enter the comment.",
  'enterYourComment':"Enter your comment...",
  'DeeplinkShare':'Share as link',
  'Shares': 'Shares',
  'shareasPost':"Share Post",
  'hasShared':'has shared',
  'whatsOnMind':"What's on your mind?",
  'inGate':'In',
  'outGate':'Out',
  'With':'with',
  'others':'others',
  'tagFriends':'Tag Friends',
  'done':'Done',
  'friendSearch':'Search Friends',
  'checkIN':'Check In',
  'tagUsers':'Tagged Users',
  'safeTrip':' You can now share your wait time. Have a Safe Trip!',
  'addLocation':'Add Location',
  'locationSelect':'Please select the location.',
  'attach':'Attach Files',
  'selectImage':'Please select images or video to post.',
  'noPlace':'No Places found',
  'deleteMedia':'Are you sure, you want to delete this media?',
  'deleteNotification':'Are you sure, you want to delete this notification?',
  'loading':'Loading...',
  'next':"Next",
  'ttlUserInterminal':"Number of users inside the terminal: ",
  'members':'members inside',
  'member':'member inside',
  useLocation:'Use your location',
firstPermissionTitle:'To see maps for automatically tracked activities, allow FR8 to use your location all of the time.',
noThanks:'No thanks',
turnOn:'Turn on',
newVersion:'New version ',
// versionDescription:'The version of the app you are using is outdated, please update to the latest version for the most accurate wait times.',
versionDescription:`This version of the app is outdated, please update to the latest version to unlock amazing new features to help you get the most accurate and amazing new features. Don't forget to set the location permissions to Always Allow so the app calculates terminal Wait Times for you in the background.`,
firstPermissionDesc:'FR8 will use your location in the background to enable your precise recordings of your trips in terminals and calculate wait time and time stamp.',
validUserName:'Only letters (a-z), numbers (0-9), periods (.) and underscore (_) are allowed.',
user_name_start: "Username should not be start with periods (.)",
onlyNumberAlert:"Username cannot contain only numbers.",
user_name_end:"Username should not be end with periods (.)",
twoDots:'Username should not have more the one period (.) in a row.',
Ok:"OK",
followingTerminal:'Following',
pdfDownload:'Download PDF',
timelineCancel:'Are you sure, you want to cancel the timeline?',
"Truck Stop":"Truck Stop",
"Gas Station":"Gas Station",
"Weight Station":"Weight Station",
location_name_enter:"Please enter Location name.",
locationNameLong:'Location name should be at least 2 characters long.',
locationAddressLong:"Location address should be at least 2 characters long.",
locationAddress:"Please enter location address.",
Name:"Name",
"Hold to Stop":"Hold to Stop",
"Location Address":"Location Address",
"Phone Number":"Phone Number",
"Add":"Add",
"Category":"Category",
backgroundProcess:"Your timeline will run in background when you move to other screens.",
NotMoving:"Not moving yet?",
oneMinuteLongerAlert:"To finish and save, FR8 needs at least 1 minute longer activity, with a change in location.",
editPost:"Edit Post",
vedioLimit:"Video duration should be maximum 30 seconds long.",
selectCurentLocation:"Select Current Location",
noCommentYet:"No comments yet",
enterFirstComment:"Be the first to comment.",
App_Share:'Share Application',
// 'appShareMessage': ' has shared FR8 app\nClick on below link to install the application. ',
'appShareMessage': ' has shared the FR8 app. Click on the below link to see the mobile application and see current wait times today.',
'appShareMessage2': 'The FR8 app\n Click on the below link to see the mobile application and see current wait times today.',
'deleteCommentReplyAlert':"Are you sure, you want to delete this comment reply?",
enter_first_name_length_alert: "First name should be at least 3 characters long.",
enter_last_name_length_alert: "Last name should be at least 3 characters long.",
location_Setting:'Location Settings',
postlikeHeading:'People who like post',
commentLikeHeading:'People who like comment',
viewProfile:'View Profile',
shareListHeading:'People who shared post',
Reply:'Reply', 
'Reply to':'Reply to',
"Like":"Like",
Dislike:"Dislike",
Smile:'Smile', 
Angry:'Angry',
"Rolling Eyes":'Rolling Eyes', 
"Thinking":"Thinking",
Stop:"Stop",
switchFrom:'Receive accurate safety notifications by switching from',
'Always Allow':'Always Allow',
'While Using':'While Using',
'Ask next time':'Ask next time',
'Never':'Never',
"Manage location Settings":'Manage location Settings',
"SavetoPhone":"Save to Phone",
Italian:	"Italian",
Chinese:	"Chinese Simplified (Mandarin)", 
Hindi:	"Hindi",
 Filipino :	 "Filipino" ,
Vietnamese:	"Vietnamese",
Arabic:	"Arabic",
French:	"French",
Korean:	"Korean",
Russian:	"Russian",
 Bengali :	 "Bengali",
German:	"German",


"All":'All',
"saveToPhone":'Save to Phone',
"ADD":"ADD",
"deleteAccount":"Delete Account",
"deleteAccountAlert": "Are you sure, you want to delete your account?",
"replyWrite":'Write a reply...',
"Camera":"Camera",
'Image Gallery':'Image Gallery',
"regionlNotFound": 'Region not found.',
"Region":"Regions",
"regionSelectAlert":"User can select maximum 3 regions.",
'FavouriteTerminals':'Favourite Terminals',
ratings: 'Write & Review',
'waitTimeIndicator':'Wait Indicator',
noData:'NO DATA',
currentWaitTime:"Current Average Wait Time",


"CALL":"CALL",
"ADDRESS":"ADDRESS",
"MIN":"MIN",
"About":"About",
"Overview":"Overview",
"Review":"Review",
"Timelines":"Timelines",
"Rate & Review":"Rate & Review",
"Write Your Review":"Write Your Review",
"Just now":"Just now",


addAccount:'Add Account',
addmobile:'Add Mobile Number',



};

module.exports = {
  constants
};
