import{imageBaseUrl}from'../Config/index'
const constants={
 // TermsUrl:"http://18.205.207.176:3000/public/pdf/Fr8_App_Terms_Of_Use.pdf",
 TermsUrl:"https://www.fr8.ai/terms",
 // TermsUrl: imageBaseUrl +"public/pdf/Fr8_App_Terms_Of_Use.pdf",
 // PrivacyUrl:"http://18.205.207.176:3000/public/pdf/Fr8_App_Privacy_Policy.pdf",
 PrivacyUrl:"https://www.fr8.ai/privacy",
 // PrivacyUrl: imageBaseUrl + "public/pdf/Fr8_App_Privacy_Policy.pdf",
"Email":`Email`,
"Enter_Email":`Inserisci l'email`,
"Password":`Password`,
"Enter_Password":`Inserisci password`,
"Enter_New_Password":`Inserisci la nuova password`,
"Forgot_Your_Password":`Hai dimenticato la password?`,
"Login":`Accedi`,
"Doesnt_have_an_account":`Non hai un account?`,
"Sign_up":`Iscriviti`,
"Enter_Name":`Inserisci nome`,
"Enter_first_Name":`Inserisci il nome`,
"Enter_last_Name":`Inserisci il cognome`,
"Enter_Your_Phone_Number":`Inserisci il tuo numero di telefono`,
"Enter_Six_Digit_Verification_Code":`Inserisci il codice di verifica di 6 cifre`,
"Resend_Verification_Code":`Invia di nuovo il codice di verifica`,
"Contact_Permission":`Attiva l'autorizzazione per i contatti allo scopo di mantenere al sicuro i tuoi amici.`,
"Register":`Iscriviti`,
"Full_Name":`Nome e cognome`,
"Enter_Full_Name":`Inserisci nome e cognome`,
"Username":`Nome utente`,
"Enter_Username":`Inserisci il nome utente`,
"Email_Address":`Indirizzo email`,
"Enter_Email_Address":`Inserisci l'indirizzo email`,
"User_Type":`Tipo di utente`,
"Select_User_Type":`Seleziona il tipo di utente`,
"Phone_Number":`Numero di telefono`,
"Enter_Phone_Number":`Inserisci il numero di telefono`,
"Date_Of_Birth":`Data di nascita`,
"Select_Date_Of_Birth":`Seleziona la data di nascita`,
"Confirm_Password":`Conferma la password`,
"Enter_Confirm_Password":`Inserisci la password di conferma`,
"Agree_Terms_and_Condition":`Accetta i termini e condizioni`,
"Forgot_Password":`Password dimenticata`,
"Submit":`Invia`,
"OTP":`OTP`,
"Enter_OTP":`Inserisci OTP`,
"Reset_Password":`Reimposta la password`,
"Edit_Profile":`Modifica profilo`,
"Edit_Phone_Number":`Modifica numero di telefono`,
"Update":`Aggiorna`,
"Change_Password":`Cambia password`,
"Old_Password":`Vecchia password`,
"Enter_Old_Password":`Inserisci la vecchia password`,
"FAQs":`FAQ`,
"Social_Media_Accounts":`Account social`,
"Settings":`Impostazioni`,
"FR8":`FR8`,
"Support_Center":`Centro assistenza`,
"Terms_And_Conditions":`Termini e condizioni`,
"Privacy_Policy":`Politica della privacy`,
"Change_Language":`Cambia lingua`,
"Logout":`Disconnessione`,
"Log_out":`Esci`,
"Confirm":`Conferma`,
"Cancel":`Annulla`,
"Please_Select":`Seleziona`,
"Warn_Contacts":`Avverti contatti`,
"Search_contacts":`Cerca contatti`,
"Friend_Requests":`Richieste di amicizia`,
"Friend_Request":`Richiesta di amicizia`,
"My_Posts":`I miei post`,
"Search_friends":`Cerca amici, terminal, contatti`,
"My_Freighting_Network":`La mia rete di trasporto merci`,
"My_Network":`La mia rete`,
"Places":`Luoghi`,
"Friends":`Amici`,
"Nearby_Terminals":`Terminal nelle vicinanze`,
"Explore":`Esplora`,
"Contacts":`Contatti`,
"Name_Of_User":`Nome dell'utente`,
"Add_Friend":`Aggiungi amico`,
"Remove_Friend":`Rimuovi amico`,
"Chat":`Chat`,
"Post_Details":`Dettagli post`,
"Live_Streams":`Live stream`,
"CreatePost":`Crea post`,
"SocialMediaAccounts":`Account social`,
"Instagram":`Instagram`,
"Google":`Google`,
"Facebook":`Facebook`,
"Support":`Assistenza`,
"Tittle":`Titolo`,
"DescriptionText":`Descrizione`,
"Enter_Tittle":`Inserisci titolo`,
"UserName":`Nome utente`,
"TerminalDetails":`Dettagli terminal`,
"Location":`Posizione`,
"Un_Follow":`Non seguire più`,
"Follow":`Segui`,
"Record":`Registra`,
"Warn":`Avverti`,
"ChatHistory":`Cronologia della chat`,
"TerminalName":`Nome del terminal`,
"Terminal":`Terminal`,
"English":`Inglese`,
"Spanish":`Spagnolo`,
"Driver_Type":`Tipo di autista`,
"Select_Driver_Type":`Seleziona il tipo di autista`,
"Users":`Utenti`,
"Enter_Title":`Inserisci titolo`,
"Type_Message_Here":`Digita il messaggio qui…`,
"Skip":`Salta`,
"Friend_request_not_found":`Richiesta di amicizia non trovata.`,
"Change_Mobile_Number":`Cambia numero di telefono`,
"resend_Otp":`Invia di nuovo il codice di verifica`,
"post":`Inviare`,
"Friend":`amico`,
"NotificationDetail":`Dettagli di notifica`,
"noResult":`Nessun risultato trovato.`,
"enter_email_alert":`Inserisci l'indirizzo email.`,
"enter_valid_email_alert":`Inserisci un indirizzo email valido.`,
"enter_password_alert":`Inserisci la password`,
"enter_full_name_alert":`Inserisci nome e cognome.`,
"enter_last_name_alert":`Si prega di inserire il cognome.`,
"enter_full_name_aplhanumeric_alert":`Inserisci nome e cognome in caratteri alfanumerici`,
"enter_user_name_alert":`Inserisci il nome utente.`,
"enter_user_name_length_alert":`Il nome utente deve essere lungo almeno 3 caratteri.`,
"enter_user_type_alert":`Inserisci il tipo di utente.`,
"enter_driver_type_alert":`Inserisci il tipo di autista.`,
"enter_phone_number_alert":`Inserisci il numero di telefono.`,
"enter_phone_number_length_alert":`Il numero di telefono deve essere lungo da 8 a 15 cifre.`,
"enter_Numbers_allowed__phone_alert":`Nel campo del telefono sono ammessi solo numeri.`,
"enter_date_of_birth_alert":`Seleziona la data di nascita.`,
"enter_password_length_alert":`La password deve essere almeno di 6 caratteri.`,
"enter_confirm_password_alert":`Inserisci la password di conferma.`,
"enter_password_not_match_alert":`La password e la password di conferma devono essere uguali.`,
"enter_terms_conditions_alert":`Accetta i termini e condizioni.`,
"enter_otp_alert":`Inserisci il codice di verifica.`,
"enter__valid_otp_alert":`Inserisci un codice di verifica valido.`,
"enter_old_password_alert":`Inserisci la vecchia password.`,
"enter_old_password_length_alert":`La vecchia password deve essere almeno di 6 caratteri.`,
"enter_new_password_alert":`Inserisci la nuova password.`,
"enter_new_password_length_alert":`La nuova password deve essere almeno di 6 caratteri.`,
"enter_old_cofirm_not_valid_alert":`La vecchia password e la password di conferma devono essere uguali.`,
"Stream_stopped_by_user":`Diretta video terminata da`,
"Loading_streams":`Caricamento streaming`,
"you_are_live_now":`Ora sei in diretta.`,
"end_publisher_video":`Confermi di voler interrompere questa diretta video?`,
"logOutAlert":`Confermi di volerti disconnettere?`,
"end_publisher_video_successfully":`Diretta video terminata.`,
"Alert":`Avviso`,
"PhoneNumber_required_for_login":`Per accedere è richiesto un numero di telefono. Inoltre ci permette di moderare la community e proteggere i nostri utenti.`,
"Privacy_policy":`CONTINUANDO ACCESSI I NOSTRI`,
"Terms":`TERMINI DI UTILIZZO`,
"Policy":`POLITICA DELLA PRIVACY`,
"Why_you_need_my_phone_number":`PERCHÉ VI SERVE IL MIO NUMERO DI TELEFONO`,
"Why_we_need_your_phone_number":`PERCHÉ CI SERVE IL MIO NUMERO DI TELEFONO`,
"verifyAccount":`VERIFICA IL TUO ACCOUNT`,
"terminalNotFound":`Terminale non trovato.`,
"Profile":`Profilo`,
"App_Settings":`Impostazioni app`,
"estimatedTime":`Tempo stimato`,
"estimatedWaitTime":`Minuti di attesa`,
"youHaveLeft":`te ne sei andato`,
"Citizen_safety_message":`Fr8 è una rete di trasporto merci. Richiediamo un numero di telefono sia per verificare la tua identità sia per assicurare che chi trasgredisce le regole della nostra community possa essere rimosso dalla rete, ove necessario.`,
"something_went_wrong":`C'è stato un problema.`,
"please_check_your_internet_connection":`Controlla la tua connessione a internet.`,
"startEndAlert":`L'orario di inizio deve essere precedente all'orario di fine.`,
"addPost":`Aggiungi post`,
"permissionTitle': 'You had denied the permission to take photo from library',":`Hai negato l'autorizzazione ad accedere alle foto della galleria`,
"permissionBody":`Desideri concedere questo accesso e quindi autorizzarlo nelle impostazioni?`,
"videoPermissionTitle":`Hai negato l'autorizzazione ad accedere ai video della galleria`,
"TimeLine_post_not_found":`Post della sequenza temporale non trovato.`,
"Timeline_Posts":`Post della sequenza temporale`,
"Timeline":`Sequenza temporale`,
"trackAtimeLine":`Monitora i tuoi tempi di attesa`,
"Journey":`Nessuna sequenza temporale trovata.`,
"KM":`km`,
"Distance_Travelled":`Distanza percorsa`,
"hrs":`ore`,
"secs":`secondi`,
"mins":`minuti`,
"time":`Tempo`,
"wait_time":`Tempo di attesa media`,
"Equiment_Photo":`Foto attrezzatura`,
"Interchange_Receipt":`Ricevuta di interscambio`,
"video":`Video`,
"Share":`Condividi`,
"start_time":`Orario di inizio`,
"Report_Post":`Segnala post`,
"endTime":`Orario di fine`,
"openTime":`Tempo aperto`,
"closeTime":`Chiudere il tempo`,
"distance":`Distanza`,
"Total_time":`Tempo totale`,
"Edit_Timeline":`Modifica sequenza temporale`,
"messageAlert":`Inserisci un messaggio.`,
"enterMessage":`Inserisci il tuo messaggio…`,
"Trending_Post":`Post di tendenza`,
"PleaseEnterReportResion":`Inserisci il motivo della segnalazione.`,
"trendingPostNotFound":`Nessun post di tendenza trovato.`,
"Accept":`Accetta`,
"Reject":`Rifiuta`,
"Allow":`Consenti`,
"Invite":`Invita`,
"postNotFound":`Nessun post trovato.`,
"Cancel_Friend_Request":`Annulla richiesta di amicizia`,
"User_Posts":`Post utente`,
"Notifications":`Notifiche`,
"No_notifications":`Nessuna notifica trovata`,
"And":`E`,
"deletePostAlert":`Confermi di voler eliminare questo post?`,
"Yes":`Sì`,
"No":`No`,
"enterTitle":`Inserisci il titolo.`,
"pleaseEnterMessage":`Inserisci il messaggio.`,
"Post_Create":`Crea port`,
"description":`Inserisci la tua descrizione…`,
"enterDescription":`Inserisci la descrizione.`,
"descriptionMax":`Inserisci una descrizione al massimo di 1000 caratteri.`,
"descriptionMin":`La descrizione deve essere almeno di 10 caratteri.`,
"Preview":`Anteprima`,
"messageMax":`Inserisci un messaggio al massimo di 1000 caratteri.`,
"noUser":`Nessun utente trovato.`,
"New":`Nuovo`,
"No_chat_found":`Nessuna chat recente trovata`,
"Search_Terminal":`Cerca terminal`,
"Receipt_Private":`Ricevuta privata`,
"Edit":`Modificare`,
"Delete":`Eliminare`,
"postShareMessage":`ha condiviso un post Fare clic sul collegamento sottostante per visualizzare il post`,
"postShareMessage2":`ha condiviso un post Fare clic sul collegamento sottostante per visualizzare il post`,
"shareSubject":`FR8 Timeline Post`,
"messageCopy":`Messaggio copiato`,
"avaliable24Hours":`Disponibile 24 ore`,
"photo":`FOTO`,
"photoLibrary":`BIBLIOTECA FOTOGRAFICA`,
"photoL":`Foto`,
"photoLibraryL":`Fototeca`,
"reportUser":`Segnala utente`,
"reasonOfReport":`Motivo della segnalazione`,
"reportPostAlert":`Sei sicuro di voler segnalare questo post?`,
// "ForegroundServiceTitle":`L'app FR8 sta gestendo la tua posizione in background`,
"ForegroundServiceTitle":`Detention Pay Tracker è in esecuzione`,
"Portuguese":`Portogallo`,
"interChangeDelete":`Sei sicuro di voler eliminare la ricevuta di interscambio?`,
"equipmentDelete":`Sei sicuro di voler eliminare la foto dell'attrezzatura?`,
"deleteVideo":`Sei sicuro di voler eliminare il video?`,
"sentAMessage":`ha inviato un messaggio:`,
"editMessage":`Modifica messaggio`,
"continue":`Continua`,
"noContact":`Nessun contatto trovato`,
"Driver":`Autista`,
"Owner Operator":`Proprietario Operatore`,
"Company":`Azienda`,
"Air Cargo Carrier":`Trasportatore di merci aviotrasportate`,
"Exporter":`Esportatore`,
"Freight Broker":`Spedizioniere`,
"Importer":`Importatore`,
"Shipper":`Spedizioniere`,
"Trucking":`Autotrasporti`,
"Warehouse":`Magazzino`,
"Company Driver":`Autista aziendale`,
"OKAY":`VA BENE`,
"installMessage":`Ciao FR8 vorresti invitare a installare l'applicazione.`,
"warned":`avvertito`,
"WaitingAt":`in attesa di`,
"openFr8":`Apri l'app Fr8 per mostrare il tempo di attesa stimato.`,
"day":`giorno`,
"days":`giorni`,
"hour":`  ora`,
"hours":`  ore`,
"minute":`  minuto`,
"minutes":`  minuti`,
"second":`  secondo`,
"seconds":`  secondi`,
"openApp":`Apri l'app per sincronizzare il tuo stato`,
"openAppBody":`Per un'esperienza ottimale, consentire all'app FR8 di rimanere aperta in background. Ciò mantiene accurata la cronologia e il timestamp del terminale.`,
"Comment":`Commento`,
"Comments":`Commenti`,
"Like":`Piace`,
"noComment":`Nessun commento trovato`,
"deleteCommentAlert":`Sei sicuro di voler eliminare il commento?`,
"enterTheComment":`Si prega di inserire il commento.`,
"enterYourComment":`Inserisci il tuo commento...`,
"DeeplinkShare":`Condividi come link`,
"Shares":`Azioni`,
"shareasPost":`Condividi post`,
"hasShared":`ha condiviso`,
"whatsOnMind":`Cos'hai in mente?`,
"inGate":`In`,
"outGate":`Fuori`,
"With":`insieme a`,
"others":`altri`,
"tagFriends":`Tagga gli amici`,
"done":`Fatto`,
"friendSearch":`Cerca amici`,
"checkIN":`Registrare`,
"tagUsers":`Utenti taggati`,
"safeTrip":` Ora puoi condividere il tuo tempo di attesa. Buon Viaggio!`,
"addLocation":`Aggiungi luogo`,
"locationSelect":`Si prega di selezionare la posizione.`,
"attach":`Allegati`,
"selectImage":`Seleziona immagini o video da pubblicare.`,
"noPlace":`Nessun luogo trovato`,
"deleteMedia":`Sei sicuro di voler eliminare questo supporto?`,
"deleteNotification":`Sei sicuro di voler eliminare questa notifica?`,
"loading":`Caricamento in corso…`,
"next":`Prossimo`,
"ttlUserInterminal":`Numero di utenti all'interno del terminale:`,
"members":`Membri dentro`,
"member":`Membro dentro`,
"useLocation":`Usa la tua posizione`,
"firstPermissionTitle":`Per visualizzare le mappe per le attività rilevate automaticamente, consenti a FR8 di utilizzare sempre la tua posizione.`,
"noThanks":`No grazie`,
"turnOn":`Accendere`,
"newVersion":`Nuova versione`,
"versionDescription":`Questa versione dell'app è obsoleta, aggiorna all'ultima versione per sbloccare nuove incredibili funzionalità che ti aiuteranno a ottenere le nuove funzionalità più accurate e sorprendenti. Non dimenticare di impostare le autorizzazioni di posizione su Consenti sempre in modo che l'app calcoli i tempi di attesa del terminale per te in background.`,
"firstPermissionDesc":`FR8 utilizzerà la tua posizione in background per consentire registrazioni precise dei tuoi viaggi nei terminali e calcolare il tempo di attesa e il timestamp.`,
"validUserName":`Sono consentiti solo lettere (a-z), numeri (0-9), punti (.) e trattino basso (_).`,
"user_name_start":`Il nome utente non deve iniziare con punti (.)`,
"onlyNumberAlert":`Il nome utente non può contenere solo numeri.`,
"user_name_end":`Il nome utente non deve terminare con punti (.)`,
"twoDots":`Il nome utente non deve contenere più di un punto (.) di fila.`,
"Ok":`ok`,
"followingTerminal":`A seguire`,
"pdfDownload":`Scarica il pdf`,
"timelineCancel":`Sei sicuro di voler annullare la timeline?`,
"Truck Stop":`Fermata camion`,
"Gas Station":`Stazione di servizio`,
"Weight Station":`Stazione Pesi`,
"location_name_enter":`Si prega di inserire il nome della posizione.`,
"locationNameLong":`Il nome della località deve essere lungo almeno 2 caratteri.`,
"locationAddressLong":`L'indirizzo della località deve essere lungo almeno 2 caratteri.`,
"locationAddress":`Inserisci l'indirizzo della località.`,
"Name":`Nome`,
"Hold to Stop":`Tieni premuto per fermarti`,
"Location Address":`Posizione Indirizzo`,
"Phone Number":`Numero di telefono`,
"Add":`Aggiungere`,
"Category":`Categoria`,
"backgroundProcess":`La tua sequenza temporale verrà eseguita in background quando ti sposti su altre schermate.`,
"NotMoving":`Non ti muovi ancora?`,
"oneMinuteLongerAlert":`Per terminare e salvare, FR8 necessita di almeno 1 minuto di attività in più, con un cambio di posizione.`,
"editPost":`Modifica post`,
"vedioLimit":`La durata del video deve essere al massimo di 30 secondi.`,
"selectCurentLocation":`Seleziona Posizione attuale`,
"noCommentYet":`Ancora nessun commento`,
"enterFirstComment":`Diventa il primo a commentare.`,
"App_Share":`Condividi applicazione`,
"appShareMessage":`ha condiviso l'app FR8. Fare clic sul collegamento in basso per vedere l'applicazione mobile e vedere i tempi di attesa attuali oggi.`,
"appShareMessage2":`FR8\n Fare clic sul collegamento in basso per vedere l'applicazione mobile e vedere i tempi di attesa attuali oggi.`,
"deleteCommentReplyAlert":`Sei sicuro di voler eliminare questa risposta di commento?`,
"enter_first_name_length_alert":`Il nome deve contenere almeno 3 caratteri.`,
"enter_last_name_length_alert":`Il cognome deve contenere almeno 3 caratteri.`,
"location_Setting":`Impostazioni di posizione`,
"postlikeHeading":`Persone a cui piace postare`,
"commentLikeHeading":`Le persone a cui piace commentare`,
"viewProfile":`Visualizza profilo`,
"shareListHeading":`Persone che hanno condiviso il post`,
"Reply":`Rispondere`,
"Reply to":`Rispondi a`,
"Dislike":`Non mi piace`,
"Smile":`Sorriso`,
"Angry":`Arrabbiato`,
"Rolling Eyes":`Occhi Alzati`,
"Thinking":`Pensiero`,
"Stop":`Fermare`,
"switchFrom":`Ricevi notifiche di sicurezza accurate passando da`,
"Always Allow":`Consenti sempre`,
"While Using":`Durante l'utilizzo`,
"Ask next time":`Chiedi la prossima volta`,
"Never":`Mai`,
"Manage location Settings":`Gestisci le impostazioni di posizione`,
"Italian":`italiano`,
"Chinese":`Cinese semplificato (mandarino)`,
"Hindi":`hindi`,
"Filipino":`filippino`,
"Vietnamese":`vietnamita`,
"Arabic":`Arabo`,
"French":`francese`,
"Korean":`coreano`,
"Russian":`russo`,
"Bengali":`bengalese`,
"German":`Tedesco`,
regionlNotFound: 'Region not found.',
Region:"Region",
in: 'nel',
posts: 'Post',


"All":"Tutti",
"saveToPhone":"Salva su telefono",
"ADD":"INSERISCI",
"deleteAccount":"Eliminare l'account",
"deleteAccountAlert":"Sei sicuro di voler cancellare il tuo account?",
"replyWrite":"Scrivi una risposta...",
"Camera":"Telecamera",
"Image Gallery":"galleria di immagini",
"regionlNotFound":"Regione non trovata.",
"Region":"Regione",
"regionSelectAlert":"L'utente può selezionare un massimo di 3 regioni.",

"CALL":"CHIAMATA",
"ADDRESS":"INDIRIZZO",
"MIN":"MIN",
"About":"Di",
"Overview":"Panoramica",
"Review":"Revisione",
"Timelines":"Linea del tempo",
"Rate & Review":"Vota e recensione",
"ratings":"Vota e recensione",
"Write Your Review":"Scrivi la tua recensione",
"Just now":"Proprio adesso",
'waitTimeIndicator':'Indicatore del tempo di attesa',
currentWaitTime:"Tempo di attesa medio attuale",

};

module.exports={
constants
};

