import {imageBaseUrl} from '../Config/index'
const constants = {
  // TermsUrl:"http://18.205.207.176:3000/public/pdf/Fr8_App_Terms_Of_Use.pdf",
  TermsUrl:"https://www.fr8.ai/terms",
  // TermsUrl: imageBaseUrl +"public/pdf/Fr8_App_Terms_Of_Use.pdf",
  // PrivacyUrl:"http://18.205.207.176:3000/public/pdf/Fr8_App_Privacy_Policy.pdf",
  PrivacyUrl:"https://www.fr8.ai/privacy",
  // PrivacyUrl: imageBaseUrl + "public/pdf/Fr8_App_Privacy_Policy.pdf",
//   "Notifications"	:`通知`,
// No_notifications	:`找不到通知。`,
posts	:`帖子`,
// Timeline	:`时间线`,
// trackAtimeLine	:`跟踪您的等待时间`,
// hours	:`小时`,
// minutes	:`分钟`,
// seconds	:`秒`,
post	:`帖子`,
// video	:`视频`,
// photoL	:`照片`,
// photoLibraryL	:`照片库`,
// Profile	:`个人资料`,
// My_Network	:`我的网络`,
// Friends	:`好友`,
// Friend_Request	:`好友请求`,
// App_Settings	:`应用程序设定`,
// Log_out	:`退出`,
// My_Freighting_Network	:`我的货运网络`,
// Search_friends	:`搜索朋友，终点站，联系人`,
// Places	:`地方`,
// Nearby_Terminals	:`附近的终点站`,
// Contacts	:`联系人`,
// Invite	:`邀请`,
// Un_Follow	:`取消关注`,
// Change_Mobile_Number	:`更改手机号码`,
// Terms_And_Conditions	:`条款和条件`,
// Privacy_Policy	:`隐私政策`,
// Change_Language	:`改变语言`,
// Support_Center	:`支持中心`,
// Edit_Profile	:`编辑个人资料`,
// Update	:`更新资料`,
// Driver	:`司机`,
// 'Owner Operator'	:`所有经营者`,
// Company	:`公司`,
// 'Air Cargo Carrier'	:`航空货运商`,
// Exporter	:`出口商`,
// 'Freight Broker'	:`货运经纪人`,
// Importer	:`进口商`,
// Shipper	:`托运人`,
// Trucking	:`货车运输`,
// Warehouse	:`仓库`,
// Interchange_Receipt	:`交接单`,
// Equiment_Photo	:`设备照片`,
// Share	:`分享`,
// Edit	:`编辑`,
// Delete	:`删除`,
// Post_Create	:`建立帖子`,
// distance	:`距离`,
// Submit	:`提交`,
// Alert	:`警报`,
// logOutAlert	:`您确定要退出吗？`,
// Cancel	:`取消`,
// Yes	:`是`,


//   Italian:	'Italian',
//   Chinese:	'Chinese Simplified (Mandarin)', 
//   Hindi:	'Hindi',
//    Filipino :	 'Filipino' ,
//   Vietnamese:	'Vietnamese',
//   Arabic:	'Arabic',
//   French:	'French',
//   Korean:	'Korean',
//   Russian:	'Russian',
//    Bengali :	 'Bengali' ,
//   German:	'German',

//   //new added
//   'useLocation':"Use your location",
//   'allowToUseAllLocation':"To see maps for automatically tracked activities, allow FR8 to use your location all of the time.",
//   'enablePrecisesLocation':"FR8 will use your location in the background to enable your precise recordings of your trips in terminals and calculate wait time and time stamp.",
//   'noThanks':"No thanks",
//   'turnOn':"Turn on"
  

"Email":`电子邮件`,
"Enter_Email":`输入电子邮件`,
"Password":`密码`,
"Enter_Password":`输入密码`,
"Enter_New_Password":`输入新密码`,
"Forgot_Your_Password":`忘记密码？`,
"Login":`登录`,
"Doesnt_have_an_account":`没有帐号？`,
"Sign_up":`注册`,
"Enter_Name":`输入名称`,
"Enter_first_Name":`输入名字`,
"Enter_last_Name":`输入姓氏`,
"Enter_Your_Phone_Number":`输入您的电话号码`,
"Enter_Six_Digit_Verification_Code":`输入6位数验证码`,
"Resend_Verification_Code":`重新发送验证码`,
"Contact_Permission":`请启用联系人权限，以确保您的朋友安全。`,
"Register":`注册`,
"Full_Name":`全名`,
"Enter_Full_Name":`输入全名`,
"Username":`用户名称`,
"Enter_Username":`输入用户名称`,
"Email_Address":`电邮地址`,
"Enter_Email_Address":`请输入电邮地址`,
"User_Type":`用户类型`,
"Select_User_Type":`选择用户类型`,
"Phone_Number":`电话号码`,
"Enter_Phone_Number":`输入电话号码`,
"Date_Of_Birth":`出生日期`,
"Select_Date_Of_Birth":`选择出生日期`,
"Confirm_Password":`确认密码`,
"Enter_Confirm_Password":`输入确认密码`,
"Agree_Terms_and_Condition":`同意条款和条件`,
"Forgot_Password":`忘记密码`,
"Submit":`提交`,
"OTP":`一次性密码`,
"Enter_OTP":`输入一次性密码`,
"Reset_Password":`重设密码`,
"Edit_Profile":`编辑个人信息`,
"Edit_Phone_Number":`编辑电话号码`,
"Update":`更新`,
"Change_Password":`更改密码`,
"Old_Password":`旧密码`,
"Enter_Old_Password":`输入旧密码`,
"FAQs":`常见问题`,
"Social_Media_Accounts":`社交媒体帐户`,
"Settings":`设置`,
"FR8":`FR8`,
"Support_Center":`支持中心`,
"Terms_And_Conditions":`条款和条件`,
"Privacy_Policy":`隐私政策`,
"Change_Language":`变更语言`,
"Logout":`退出`,
"Log_out":`退出`,
"Confirm":`确认`,
"Cancel":`取消`,
"Please_Select":`请选择`,
"Warn_Contacts":`警告联络人`,
"Search_contacts":`搜索联系人`,
"Friend_Requests":`好友请求`,
"Friend_Request":`好友请求`,
"My_Posts":`我的帖子`,
"Search_friends":`搜索朋友，货运站，联系人`,
"My_Freighting_Network":`我的货运网络`,
"My_Network":`我的网络`,
"Places":`地方`,
"Friends":`好友`,
"Nearby_Terminals":`附近的货运站`,
"Explore":`探索`,
"Contacts":`联络人`,
"Name_Of_User":`用户名称`,
"Add_Friend":`添加好友`,
"Remove_Friend":`删除朋友`,
"Chat":`聊天室`,
"Post_Details":`帖子详细信息`,
"Live_Streams":`即时串流`,
"CreatePost":`建立帖子`,
"SocialMediaAccounts":`社交媒体帐户`,
"Instagram":`Instagram的`,
"Google":`谷歌`,
"Facebook":`Facebook`,
"Support":`支持`,
"Tittle":`标题`,
"DescriptionText":`描述`,
"Enter_Tittle":`输入标题`,
"UserName":`用户名称`,
"TerminalDetails":`货运站详细信息`,
"Location":`位置`,
"Un_Follow":`取消关注`,
"Follow":`关注`,
"Record":`记录`,
"Warn":`警告`,
"ChatHistory":`聊天记录`,
"TerminalName":`货运站名称`,
"Terminal":`货运站`,
"English":`英语`,
"Spanish":`西班牙语`,
"Driver_Type":`驱动类型`,
"Select_Driver_Type":`选择驱动程序类型`,
"Users":`用户`,
"Enter_Title":`输入标题`,
"Type_Message_Here":`在此处输入信息...`,
"Skip":`略过`,
"Friend_request_not_found":`找不到好友请求。`,
"Change_Mobile_Number":`更改手机号码`,
"resend_Otp":`重新发送验证码`,
"post":`邮政`,
"Friend":`朋友`,
"NotificationDetail":`通知详情`,
"noResult":`没有找到结果。`,
"enter_email_alert":`请输入电邮地址。`,
"enter_valid_email_alert":`请输入有效的电邮地址。`,
"enter_password_alert":`请输入密码。`,
"enter_full_name_alert":`请输入全名。`,
"enter_last_name_alert":`请输入姓氏。`,
"enter_full_name_aplhanumeric_alert":`请输入全名的字母数字。`,
"enter_user_name_alert":`请输入用户名称。`,
"enter_user_name_length_alert":`用户名的长度应至少为 3 个字符。`,
"enter_user_type_alert":`请选择用户类型。`,
"enter_driver_type_alert":`请选择驱动程序类型。`,
"enter_phone_number_alert":`请输入电话号码。`,
"enter_phone_number_length_alert":`电话号码应介于8到15之间。`,
"enter_Numbers_allowed__phone_alert":`电话字段中仅允许输入数字。`,
"enter_date_of_birth_alert":`请选择出生日期。`,
"enter_password_length_alert":`密码必须至少包含6个字符。`,
"enter_confirm_password_alert":`请输入确认密码。`,
"enter_password_not_match_alert":`密码和确认密码必须相同。`,
"enter_terms_conditions_alert":`输入条款和条件警报："请接受条款和条件。"`,
"enter_otp_alert":`请输入验证码。`,
"enter__valid_otp_alert":`请输入有效的验证码。`,
"enter_old_password_alert":`请输入旧密码。`,
"enter_old_password_length_alert":`旧密码必须至少包含6个字符。`,
"enter_new_password_alert":`请输入新密码。`,
"enter_new_password_length_alert":`新密码必须至少包含6个字符。`,
"enter_old_cofirm_not_valid_alert":`旧密码和确认密码必须相同。`,
"Stream_stopped_by_user":`实况视频结束`,
"Loading_streams":`正在加载流`,
"you_are_live_now":`您正在直播。`,
"end_publisher_video":`您确定要结束此直播视频吗？`,
"logOutAlert":`您确定要退出吗？`,
"end_publisher_video_successfully":`实况视频结束。`,
"Alert":`警报`,
"PhoneNumber_required_for_login":`登录需要输入电话号码，这也有助于我们管理社区并保护用户。`,
"Privacy_policy":`继续表示您同意我们`,
"Terms":`使用条款`,
"Policy":`隐私政策`,
"Why_you_need_my_phone_number":`为什么需要我的电话号码`,
"Why_we_need_your_phone_number":`为什么需要您的电话号码`,
"verifyAccount":`验证您的帐户`,
"terminalNotFound":`找不到货运站。`,
"Profile":`个人信息`,
"App_Settings":`应用程序设置`,
"estimatedTime":`预计时间`,
"estimatedWaitTime":`等待的分钟数`,
"youHaveLeft":`你离开了`,
"Citizen_safety_message":`Fr8是货运网络。我们需要一个电话号码来验证您的身份，并确保在适当情况下可以从网络中删除违反我们社区标准的人。`,
"something_went_wrong":`出了些问题。`,
"please_check_your_internet_connection":`请检查您的互联网连接。`,
"startEndAlert":`开始时间应小于结束时间。`,
"addPost":`添加帖子`,
"permissionTitle': 'You had denied the permission to take photo from library',":`您已拒绝从图书馆拍照的权限`,
"permissionBody":`您要访问此权限然后允许设置权限吗？`,
"videoPermissionTitle":`您已拒绝从图书馆拍摄视频的权限`,
"TimeLine_post_not_found":`找不到时间线帖子。`,
"Timeline_Posts":`时间线帖子`,
"Timeline":`时间线`,
"trackAtimeLine":`追踪您的等待时间`,
"Journey":`未找到时间线。`,
"KM":`公里`,
"Distance_Travelled":`行进距离`,
"hrs":`小时`,
"secs":`秒`,
"mins":`分钟`,
"time":`时间`,
"wait_time":`平均等待时间`,
"Equiment_Photo":`设备照片`,
"Interchange_Receipt":`交接单`,
"video":`视频`,
"Share":`分享`,
"start_time":`开始时间`,
"Report_Post":`举报帖`,
"endTime":`结束时间`,
"openTime":`开放时间`,
"closeTime":`关闭时间`,
"distance":`距离`,
"Total_time":`总时间`,
"Edit_Timeline":`编辑时间表`,
"messageAlert":`请输入一些信息。`,
"enterMessage":`输入您的信息...`,
"Trending_Post":`热门帖子`,
"PleaseEnterReportResion":`请输入报告原因。`,
"trendingPostNotFound":`找不到热门帖子。`,
"Accept":`接受`,
"Reject":`拒绝`,
"Allow":`允许`,
"Invite":`邀请`,
"postNotFound":`找不到帖子。`,
"Cancel_Friend_Request":`取消好友请求`,
"User_Posts":`用户帖子`,
"Notifications":`通知`,
"No_notifications":`找不到通知。`,
"And":`和`,
"deletePostAlert":`您确定您要删除这个帖子？`,
"Yes":`是`,
"No":`不是`,
"enterTitle":`请输入标题。`,
"pleaseEnterMessage":`请输入信息。`,
"Post_Create":`建立帖子`,
"description":`输入您的描述...`,
"enterDescription":`请输入描述。`,
"descriptionMax":`请输入描述（少于1000个字符）。`,
"descriptionMin":`描述必须至少10个字符长。`,
"Preview":`预览`,
"messageMax":`请输入少于1000个字符的信息。`,
"noUser":`找不到用户。`,
"New":`新`,
"No_chat_found":`找不到最近的聊天`,
"Search_Terminal":`搜索货运站`,
"Receipt_Private":`收据私人`,
"Edit":`编辑`,
"Delete":`删除`,
"postShareMessage":`已分享帖子 点击下方链接查看帖子`,
"postShareMessage2":`已分享帖子 点击下方链接查看帖子`,
"shareSubject":`FR8 时间线帖子`,
"messageCopy":`邮件已复制`,
"avaliable24Hours":`24 小时可用`,
"photo":`照片`,
"photoLibrary":`照片库`,
"photoL":`照片`,
"photoLibraryL":`照片库`,
"reportUser":`举报用户`,
"reasonOfReport":`举报原因`,
"reportPostAlert":`您确定要举报此帖子吗？`,
// "ForegroundServiceTitle":`FR8 应用程序正在后台管理您的位置`,
"ForegroundServiceTitle":`Detention Pay Tracker 正在运行`,
"Portuguese":`葡萄牙`,
"interChangeDelete":`您确定要删除交换收据吗？`,
"equipmentDelete":`您确定要删除设备照片吗？`,
"deleteVideo":`您确定要删除视频吗？`,
"sentAMessage":`发了一条消息：`,
"editMessage":`编辑消息`,
"continue":`继续`,
"noContact":`未找到联系人`,
"Driver":`司机`,
"Owner Operator":`所有者对经营者`,
"Company":`公司`,
"Air Cargo Carrier":`航空货运公司`,
"Exporter":`出口商`,
"Freight Broker":`货运经纪人`,
"Importer":`进口商`,
"Shipper":`托运人`,
"Trucking":`卡车运输`,
"Warehouse":`仓库`,
"Company Driver":`公司司机`,
"OKAY":`好的`,
"installMessage":`您好 FR8 您想邀请安装该应用程序。`,
"warned":`警告`,
"WaitingAt":`等待`,
"openFr8":`打开 Fr8 应用程序以显示您的预计等待时间。`,
"day":`日`,
"days":`天`,
"hour":`  小时`,
"hours":`  小时`,
"minute":`  分钟`,
"minutes":`  分钟`,
"second":`  第二`,
"seconds":`  秒`,
"openApp":`打开应用程序以同步您的状态`,
"openAppBody":`为获得最佳体验，请允许 FR8 应用程序在后台保持打开状态。这可以保持您的时间线和终端时间戳准确。`,
"Comment":`评论`,
"Comments":`注释`,
"Like":`喜欢`,
"noComment":`未找到评论`,
"deleteCommentAlert":`您确定要删除评论吗？`,
"enterTheComment":`请输入评论。`,
"enterYourComment":`输入您的评论...`,
"DeeplinkShare":`分享为链接`,
"Shares":`分享`,
"shareasPost":`分享帖子`,
"hasShared":`已分享`,
"whatsOnMind":`你在想什么？`,
"inGate":`在`,
"outGate":`出去`,
"With":`和`,
"others":`其他`,
"tagFriends":`标记朋友`,
"done":`完毕`,
"friendSearch":`搜索好友`,
"checkIN":`报到`,
"tagUsers":`标记用户`,
"safeTrip":` 您现在可以分享您的等待时间。一路平安！`,
"addLocation":`添加位置`,
"locationSelect":`请选择位置。`,
"attach":`附加文件`,
"selectImage":`请选择要发布的图片或视频。`,
"noPlace":`未找到地点`,
"deleteMedia":`您确定要删除此媒体吗？`,
"deleteNotification":`确定要删除此通知吗？`,
"loading":`正在加载…`,
"next":`下一个`,
"ttlUserInterminal":`终端内用户数：`,
"members":`会员里面`,
"member":`会员里面`,
"useLocation":`使用您的位置`,
"firstPermissionTitle":`要查看自动跟踪活动的地图，请允许 FR8 始终使用您的位置。`,
"noThanks":`不，谢谢`,
"turnOn":`打开`,
"newVersion":`新版本`,
"versionDescription":`此版本的应用程序已过时，请更新到最新版本以解锁惊人的新功能，以帮助您获得最准确和惊人的新功能。不要忘记将位置权限设置为始终允许，以便应用在后台为您计算终端等待时间。`,
"firstPermissionDesc":`FR8 将在后台使用您的位置来精确记录您在终端的行程并计算等待时间和时间戳。`,
"validUserName":`只允许使用字母 (a-z)、数字 (0-9)、句点 (.) 和下划线 (_)。`,
"user_name_start":`用户名不应以句点 (.)`,
"onlyNumberAlert":`用户名不能只包含数字。`,
"user_name_end":`用户名不应以句点 (.) 结尾`,
"twoDots":`用户名中的一个句点 (.) 不应超过一行。`,
"Ok":`好的`,
"followingTerminal":`下列的`,
"pdfDownload":`下载PDF`,
"timelineCancel":`您确定要取消时间线吗？`,
"Truck Stop":`卡车停靠站`,
"Gas Station":`加油站`,
"Weight Station":`称重站`,
"location_name_enter":`请输入位置名称。`,
"locationNameLong":`位置名称的长度应至少为 2 个字符。`,
"locationAddressLong":`位置地址的长度应至少为 2 个字符。`,
"locationAddress":`请输入位置地址。`,
"Name":`名称`,
"Hold to Stop":`按住停止`,
"Location Address":`位置地址`,
"Phone Number":`电话号码`,
"Add":`添加`,
"Category":`类别`,
"backgroundProcess":`当您移动到其他屏幕时，您的时间线将在后台运行。`,
"NotMoving":`还没动？`,
"oneMinuteLongerAlert":`为了完成和保存，FR8 需要至少 1 分钟以上的活动，并改变位置。`,
"editPost":`编辑帖子`,
"vedioLimit":`视频时长应最长为 30 秒。`,
"selectCurentLocation":`选择当前位置`,
"noCommentYet":`暂时没有评论`,
"enterFirstComment":`成为第一个发表评论的人。`,
"App_Share":`分享申请`,
"appShareMessage":`已分享 FR8 应用程序。 单击下面的链接以查看移动应用程序并查看今天的当前等待时间。`,
"appShareMessage2":` FR8 \n 单击下面的链接以查看移动应用程序并查看今天的当前等待时间。`,
"deleteCommentReplyAlert":`您确定要删除此评论回复吗？`,
"enter_first_name_length_alert":`名字的长度至少应为 3 个字符。`,
"enter_last_name_length_alert":`姓氏至少应包含 3 个字符。`,
"location_Setting":`位置设置`,
"postlikeHeading":`喜欢帖子的人`,
"commentLikeHeading":`喜欢评论的人`,
"viewProfile":`查看资料`,
"shareListHeading":`分享帖子的人`,
"Reply":`回复`,
"Reply to":`回复`,
"Dislike":`不喜欢`,
"Smile":`微笑`,
"Angry":`生气的`,
"Rolling Eyes":`翻白眼`,
"Thinking":`思维`,
"Stop":`停止`,
"switchFrom":`通过切换接收准确的安全通知`,
"Always Allow":`总是允许`,
"While Using":`使用时`,
"Ask next time":`下次问`,
"Never":`绝不`,
"Manage location Settings":`管理位置设置`,
"Italian":`意大利语`,
"Chinese":`简体中文（普通话）`,
"Hindi":`印地语`,
"Filipino":`菲律宾语`,
"Vietnamese":`越南语`,
"Arabic":`阿拉伯`,
"French":`法语`,
"Korean":`韩国人`,
"Russian":`俄语`,
"Bengali":`孟加拉`,
"German":`德语`,
regionlNotFound: 'Region not found.',
Region:"Region",
in: '在',


"All":"全部",
"saveToPhone":"保存到手机",
"ADD":"添加",
"deleteAccount":"删除帐户",
"deleteAccountAlert":"您确定要删除您的帐户吗？",
"replyWrite":"写回复...",
"Camera":"相机",
"Image Gallery":"图片库",
"regionlNotFound":"未找到区域。",
"Region":"地区",
"regionSelectAlert":"用户最多可以选择 3 个区域。",
"CALL":"称呼",
"ADDRESS":"地址",
"MIN":"最小",
"About":"关于",
"Overview":"概述",
"Review":"审查",
"Timelines":"时间线",
"Rate & Review":"评分和评论",
"ratings":"评分和评论",
"Write Your Review":"写你的评论",
"Just now":"现在",
'waitTimeIndicator':'等待时间指示器',
currentWaitTime:"当前平均等待时间",
addmobile:'添加手机号码',
addAccount:'新增帐户',
};

module.exports = {
  constants
};
