import { imageBaseUrl } from '../Config/index'
const constants = {
  // TermsUrl:"http://18.205.207.176:3000/public/pdf/Fr8_App_Terms_Of_Use.pdf",
  TermsUrl:"https://www.fr8.ai/terms",
  // TermsUrl: imageBaseUrl +"public/pdf/Fr8_App_Terms_Of_Use.pdf",
  // PrivacyUrl:"http://18.205.207.176:3000/public/pdf/Fr8_App_Privacy_Policy.pdf",
  PrivacyUrl:"https://www.fr8.ai/privacy",
  // PrivacyUrl: imageBaseUrl + "public/pdf/Fr8_App_Privacy_Policy.pdf",

  "Email": `Эл. адрес`,
  "Enter_Email": `Введите адрес электронной почты`,
  "Password": `Пароль`,
  "Enter_Password": `Введите пароль`,
  "Enter_New_Password": `Введите новый пароль`,
  "Forgot_Your_Password": `Забыли пароль?`,
  "Login": `Войти`,
  "Doesnt_have_an_account": `Нет аккаунта?`,
  "Sign_up": `Зарегистрироваться`,
  "Enter_Name": `Введите имя`,
  "Enter_first_Name": `Введите имя`,
  "Enter_last_Name": `Введите фамилию`,
  "Enter_Your_Phone_Number": `Введите свой номер телефона`,
  "Enter_Six_Digit_Verification_Code": `Введите 6-значный код подтверждения`,
  "Resend_Verification_Code": `Отправить заново код подтверждения`,
  "Contact_Permission": `Пожалуйста, включите разрешение контактов, чтобы ваши друзья были в безопасности.`,
  "Register": `Зарегистрироваться`,
  "Full_Name": `Полное имя`,
  "Enter_Full_Name": `Введите полное имя`,
  "Username": `Имя пользователя`,
  "Enter_Username": `Введите имя пользователя`,
  "Email_Address": `Адрес электронной почты`,
  "Enter_Email_Address": `Введите адрес электронной почты`,
  "User_Type": `Тип пользователя`,
  "Select_User_Type": `Выберите тип пользователя`,
  "Phone_Number": `Номер телефона`,
  "Enter_Phone_Number": `Введите номер телефона`,
  "Date_Of_Birth": `Дата рождения`,
  "Select_Date_Of_Birth": `Выберите дату рождения`,
  "Confirm_Password": `Подтвердите Пароль`,
  "Enter_Confirm_Password": `Подтвердите Пароль`,
  "Agree_Terms_and_Condition": `Согласен(-на) с условиями использования`,
  "Forgot_Password": `Забыли пароль`,
  "Submit": `Добавить`,
  "OTP": `OTP`,
  "Enter_OTP": `Введите OTP`,
  "Reset_Password": `Сброс пароля`,
  "Edit_Profile": `Редактировать профиль`,
  "Edit_Phone_Number": `Изменить номер телефона`,
  "Update": `Обновить`,
  "Change_Password": `Изменить пароль`,
  "Old_Password": `Прежний пароль`,
  "Enter_Old_Password": `Введите прежний пароль`,
  "FAQs": `FAQs`,
  "Social_Media_Accounts": `Аккаунты социальных сетей`,
  "Settings": `Настройки`,
  "FR8": `FR8`,
  "Support_Center": `Центр поддержки`,
  "Terms_And_Conditions": `Условия и положения`,
  "Privacy_Policy": `Политика конфиденциальности`,
  "Change_Language": `Изменить язык`,
  "Logout": `Выйти`,
  "Log_out": `Выйти`,
  "Confirm": `Подтвердить`,
  "Cancel": `Отмена`,
  "Please_Select": `Пожалуйста выберите`,
  "Warn_Contacts": `Предупредить контакты`,
  "Search_contacts": `Поиск контактов`,
  "Friend_Requests": `Запросы в друзья`,
  "Friend_Request": `Запрос в друзья`,
  "My_Posts": `Мои публикации`,
  "Search_friends": `Поиск друзей, терминалов, контактов`,
  "My_Freighting_Network": `Моя транспортная сеть`,
  "My_Network": `Моя сеть`,
  "Places": `Места`,
  "Friends": `Друзья`,
  "Nearby_Terminals": `Ближайшие терминалы`,
  "Explore": `Исследовать`,
  "Contacts": `Контакты`,
  "Name_Of_User": `Имя пользователя`,
  "Add_Friend": `Добавить в друзья`,
  "Remove_Friend": `Удалить друга`,
  "Chat": `Чат`,
  "Post_Details": `Подробности публикации`,
  "Live_Streams": `Прямые трансляции`,
  "CreatePost": `Создать публикацию`,
  "SocialMediaAccounts": `Аккаунты в социальных сетях`,
  "Instagram": `Instagram`,
  "Google": `Google`,
  "Facebook": `Facebook`,
  "Support": `Поддержка`,
  "Tittle": `Название`,
  "DescriptionText": `Описание`,
  "Enter_Tittle": `Введите название`,
  "UserName": `Имя пользователя`,
  "TerminalDetails": `Детали терминала`,
  "Location": `Расположение`,
  "Un_Follow": `Отписаться`,
  "Follow": `Подписаться`,
  "Record": `Запись`,
  "Warn": `Предупредить`,
  "ChatHistory": `История чата`,
  "TerminalName": `Название терминала"`,
  "Terminal": `Терминал`,
  "English": `Английский`,
  "Spanish": `Испанский `,
  "Driver_Type": `Тип водителя`,
  "Select_Driver_Type": `Выберите тип водителя`,
  "Users": `Пользователи`,
  "Enter_Title": `Введите название`,
  "Type_Message_Here": `Напечатайте сообщение...`,
  "Skip": `Пропустить`,
  "Friend_request_not_found": `Запрос в друзья не найден.`,
  "Change_Mobile_Number": `Изменить номер мобильного телефона`,
  "resend_Otp": `Отправить заново код подтверждения`,
  "post": `Сообщение`,
  "Friend": `Друг`,
  "NotificationDetail": `Детали уведомления`,
  "noResult": `Результатов не найдено.`,
  "enter_email_alert": `Пожалуйста, введите адрес электронной почты.`,
  "enter_valid_email_alert": `Пожалуйста введите верный адрес электронной почты.`,
  "enter_password_alert": `Пожалуйста введите пароль.`,
  "enter_full_name_alert": `Пожалуйста, введите полное имя.`,
  "enter_last_name_alert": `Пожалуйста, введите фамилию.`,
  "enter_full_name_aplhanumeric_alert": `Пожалуйста, введите буквенно-цифровое полное имя.`,
  "enter_user_name_alert": `Пожалуйста, введите имя пользователя.`,
  "enter_user_name_length_alert": `Имя пользователя должно состоять не менее чем из 3 символов.`,
  "enter_user_type_alert": `Пожалуйста, выберите тип пользователя.`,
  "enter_driver_type_alert": `Пожалуйста, выберите тип водителя.`,
  "enter_phone_number_alert": `Пожалуйста, введите номер телефона.`,
  "enter_phone_number_length_alert": `Номер телефона должен быть от 8 до 15.`,
  "enter_Numbers_allowed__phone_alert": `В поле телефона можно указать только номер.`,
  "enter_date_of_birth_alert": `Пожалуйста, выберите дату рождения.`,
  "enter_password_length_alert": `Пароль должен состоять минимум из 6 символов.`,
  "enter_confirm_password_alert": `Пожалуйста, подтвердите пароль.`,
  "enter_password_not_match_alert": `Пароль и подтверждение должны совпадать.`,
  "enter_terms_conditions_alert": `enter_terms_conditions_alert: "Пожалуйста, примите условия и положения.",`,
  "enter_otp_alert": `Пожалуйста, введите код подтверждения.`,
  "enter__valid_otp_alert": `Пожалуйста, введите верный код подтверждения.`,
  "enter_old_password_alert": `Пожалуйста, введите прежний пароль.`,
  "enter_old_password_length_alert": `Прежний пароль должен состоять не менее чем из 6 символов.`,
  "enter_new_password_alert": `Пожалуйста, введите новый пароль.`,
  "enter_new_password_length_alert": `Новый пароль должен состоять не менее чем из 6 символов.`,
  "enter_old_cofirm_not_valid_alert": `Прежний пароль и подтверждение должны совпадать.`,
  "Stream_stopped_by_user": `Прямой эфир завершен`,
  "Loading_streams": `Загрузка потоков`,
  "you_are_live_now": `Вы сейчас в прямом эфире.`,
  "end_publisher_video": `Вы уверены, что хотите закончить этот прямой эфир?`,
  "logOutAlert": `Вы действительно хотите выйти?`,
  "end_publisher_video_successfully": `Прямой эфир завершен.`,
  "Alert": `Предупреждение`,
  "PhoneNumber_required_for_login": `Номер телефона необходим для входа в систему, он также помогает нам модерировать сообщество и защищать наших пользователей.`,
  "Privacy_policy": `ПРОДОЛЖАЯ, ВЫ СОГЛАШАЕТЕСЬ С НАШИМИ`,
  "Terms": `УСЛОВИЯ ЭКСПЛУАТАЦИИ`,
  "Policy": `ПОЛИТИКА КОНФИДЕНЦИАЛЬНОСТИ`,
  "Why_you_need_my_phone_number": `ЗАЧЕМ ВАМ МОЙ НОМЕР`,
  "Why_we_need_your_phone_number": `ЗАЧЕМ НАМ НУЖЕН ВАШ НОМЕР ТЕЛЕФОНА`,
  "verifyAccount": `ПОДТВЕРДИТЕ ВАШ АККАУНТ`,
  "terminalNotFound": `Терминал не найден.`,
  "Profile": `Профиль`,
  "App_Settings": `Настройки приложения`,
  "estimatedTime": `Расчетное время`,
  "estimatedWaitTime": `Минуты ожидания`,
  "youHaveLeft": `Ты ушел`,
  "Citizen_safety_message": `Fr8 - это транспортная сеть. Нам необходим номер телефона как для подтверждения вашей личности, так и для гарантии того, что нарушители наших стандартов могут быть удалены из сети, когда это необходимо.`,
  "something_went_wrong": `Что-то пошло не так.`,
  "please_check_your_internet_connection": `Пожалуйста, проверьте ваше интернет-соединение.`,
  "startEndAlert": `Время начала должно быть меньше времени окончания.`,
  "addPost": `Добавить публикацию`,
  "permissionTitle': 'You had denied the permission to take photo from library',": `Вы отказали в разрешении взять фото из библиотеки`,
  "permissionBody": `Хотели бы вы получить доступ к этому, а затем дать разрешение в настройках?`,
  "videoPermissionTitle": `Вы отказали в разрешении взять видео из библиотеки`,
  "TimeLine_post_not_found": `Публикации в Таймлайне не найдено.`,
  "Timeline_Posts": `Публикации в Таймлайне`,
  "Timeline": `Таймлайн`,
  "trackAtimeLine": `Отслеживайте время ожидания`,
  "Journey": `Временная шкала не найдена.`,
  "KM": `км`,
  "Distance_Travelled": `Пройденное расстояние`,
  "hrs": `часы`,
  "secs": `секунды`,
  "mins": `минут`,
  "time": `Время`,
  "wait_time": `Средн. время ожидания`,
  "Equiment_Photo": `Фото оборудования`,
  "Interchange_Receipt": `Квитанция об обмене`,
  "video": `Видео`,
  "Share": `Поделиться`,
  "start_time": `Время начала`,
  "Report_Post": `Пожаловаться на сообщение`,
  "endTime": `Время окончания'`,
  "openTime": `Время открытия`,
  "closeTime": `Время закрытия`,
  "distance": `Расстояние`,
  "Total_time": `Общее время`,
  "Edit_Timeline": `Редактировать таймлайн`,
  "messageAlert": `Пожалуйста, введите какое-нибудь сообщение.`,
  "enterMessage": `Введите ваше сообщение...`,
  "Trending_Post": `Популярная публикация`,
  "PleaseEnterReportResion": `Пожалуйста, укажите причину жалобы.`,
  "trendingPostNotFound": `Популярных публикаций не найдено.`,
  "Accept": `Принять`,
  "Reject": `Отклонить`,
  "Allow": `Разрешить`,
  "Invite": `Пригласить`,
  "postNotFound": `Публикаций не найдено.`,
  "Cancel_Friend_Request": `Отменить запрос на добавление в друзья`,
  "User_Posts": `Публикации пользователей`,
  "Notifications": `Уведомления`,
  "No_notifications": `Уведомлений не найдено.`,
  "And": `И`,
  "deletePostAlert": `Вы уверены, что хотите удалить эту публикацию?`,
  "Yes": `Да`,
  "No": `Нет`,
  "enterTitle": `Пожалуйста, введите название.`,
  "pleaseEnterMessage": `Пожалуйста, введите сообщение.`,
  "Post_Create": `Создать публикацию`,
  "description": `Введите свое описание ...`,
  "enterDescription": `Пожалуйста, введите описание.`,
  "descriptionMax": `Пожалуйста, введите описание менее 1000 символов.`,
  "descriptionMin": `Описание должно быть не менее 10 символов.`,
  "Preview": `Предварительный просмотр`,
  "messageMax": `Пожалуйста, введите сообщение длиной менее 1000 символов.`,
  "noUser": `Пользователь не найден.`,
  "New": `Новое`,
  "No_chat_found": `Недавний чат не найден`,
  "Search_Terminal": `Поиск терминала`,
  "Receipt_Private": `Квитанция Частная`,
  "Edit": `Редактировать`,
  "Delete": `Удалить`,
  "postShareMessage": `поделился записью Нажмите на ссылку ниже, чтобы просмотреть сообщение`,
  "postShareMessage2": `поделился записью Нажмите на ссылку ниже, чтобы просмотреть сообщение`,
  "shareSubject": `FR8 TimeLine Post`,
  "messageCopy": `Сообщение скопировано`,
  "avaliable24Hours": `Доступно 24 часа`,
  "photo": `ФОТО`,
  "photoLibrary": `ФОТО БИБЛИОТЕКА`,
  "photoL": `Фото`,
  "photoLibraryL": `Библиотека фотографий`,
  "reportUser": `Пожаловаться на пользователя`,
  "reasonOfReport": `Причина сообщения`,
  "reportPostAlert": `Вы уверены, что хотите пожаловаться на это сообщение?`,
  // "ForegroundServiceTitle": `Приложение FR8 управляет вашим местоположением в фоновом режиме`,
  "ForegroundServiceTitle": `Отслеживание выплат за содержание под стражей запущено`,
  "Portuguese": `Португалия`,
  "interChangeDelete": `Вы уверены, что хотите удалить квитанцию `,
  "equipmentDelete": `Вы уверены, что хотите удалить фото оборудования?`,
  "deleteVideo": `Вы уверены, что хотите удалить видео?`,
  "sentAMessage": `отправил сообщение:`,
  "editMessage": `Редактировать сообщение`,
  "continue": `Продолжать`,
  "noContact": `Контакты не найдены`,
  "Driver": `Водитель`,
  "Owner Operator": `Собственный оператор`,
  "Company": `Компания`,
  "Air Cargo Carrier": `Воздушный грузовой перевозчик`,
  "Exporter": `Экспортер`,
  "Freight Broker": `Фрахтовый брокер`,
  "Importer": `Импортер`,
  "Shipper": `Грузоотправитель`,
  "Trucking": `Грузоперевозки`,
  "Warehouse": `Склад`,
  "Company Driver": `Водитель компании`,
  "OKAY": `ЛАДНО`,
  "installMessage": `Здравствуйте, FR8, вы бы хотели пригласить для установки приложения.`,
  "warned": `предупрежден`,
  "WaitingAt": `Ожидание в`,
  "openFr8": `Откройте приложение Fr8, чтобы увидеть примерное время ожидания.`,
  "day": `день`,
  "days": `дней`,
  "hour": `  час`,
  "hours": `  часы`,
  "minute": `  минута`,
  "minutes": `  минуты`,
  "second": `  второй`,
  "seconds": `  секунды`,
  "openApp": `Откройте приложение, чтобы синхронизировать свой статус`,
  "openAppBody": `Для оптимальной работы оставьте приложение FR8 открытым в фоновом режиме. Благодаря этому ваша временная шкала и временная метка терминала будут точными.`,
  "Comment": `Комментарий`,
  "Comments": `Комментарии`,
  "Like": `Нравится`,
  "noComment": `Комментариев не найдено`,
  "deleteCommentAlert": `Вы уверены, что хотите удалить комментарий?`,
  "enterTheComment": `Пожалуйста, введите комментарий.`,
  "enterYourComment": `Введите свой комментарий ...`,
  "DeeplinkShare": `Поделиться ссылкой`,
  "Shares": `Акции`,
  "shareasPost": `Поделиться публикацией`,
  "hasShared": `поделился`,
  "whatsOnMind": `Что у тебя на уме?`,
  "inGate": `В`,
  "outGate": `Из`,
  "With": `с участием`,
  "others": `другие`,
  "tagFriends": `Отметить друзей`,
  "done": `Выполнено`,
  "friendSearch": `Поиск друзей`,
  "checkIN": `Регистрироваться`,
  "tagUsers": `Отмеченные пользователи`,
  "safeTrip": ` Теперь вы можете поделиться своим временем ожидания. Удачной поездки!`,
  "addLocation": `Добавить местоположение`,
  "locationSelect": `Пожалуйста, выберите место.`,
  "attach": `Прикрепить файлы`,
  "selectImage": `Пожалуйста, выберите изображения или видео для публикации.`,
  "noPlace": `Места не найдены`,
  "deleteMedia": `Вы уверены, что хотите удалить этот носитель?`,
  "deleteNotification": `Вы уверены, что хотите удалить это уведомление?`,
  "loading": `Загрузка…`,
  "next": `Следующий`,
  "ttlUserInterminal": `Количество пользователей внутри терминала:`,
  "members": `Члены внутри`,
  "member": `Член внутри`,
  "useLocation": `Используйте свое местоположение`,
  "firstPermissionTitle": `Чтобы просматривать карты для автоматически отслеживаемых действий, разрешите FR8 постоянно использовать ваше местоположение.`,
  "noThanks": `Нет, спасибо`,
  "turnOn": `Включить`,
  "newVersion": `Новая версия`,
  "versionDescription": `Эта версия приложения устарела. Обновите ее до последней версии, чтобы разблокировать потрясающие новые функции, которые помогут вам получить самые точные и потрясающие новые функции. Не забудьте установить для разрешений местоположения значение «Всегда разрешать», чтобы приложение вычисляло для вас время ожидания терминала в фоновом режиме.`,
  "firstPermissionDesc": `FR8 будет использовать ваше местоположение в фоновом режиме, чтобы вы могли точно записывать ваши поездки на терминалах и рассчитывать время ожидания и отметку времени.`,
  "validUserName": `Разрешены только буквы (a-z), цифры (0-9), точки (.) И подчеркивание (_).`,
  "user_name_start": `Имя пользователя не должно начинаться с точки (.)`,
  "onlyNumberAlert": `Имя пользователя не может содержать только цифры.`,
  "user_name_end": `Имя пользователя не должно заканчиваться точкой (.)`,
  "twoDots": `Имя пользователя не должно содержать более одной точки (.) Подряд.`,
  "Ok": `Ok`,
  "followingTerminal": `Следующий`,
  "pdfDownload": `Скачать PDF`,
  "timelineCancel": `Вы уверены, что хотите отменить временную шкалу?`,
  "Truck Stop": `Остановка грузовика`,
  "Gas Station": `Заправка`,
  "Weight Station": `Весовая станция`,
  "location_name_enter": `Пожалуйста, введите название места.`,
  "locationNameLong": `Название локации должно состоять не менее чем из 2 символов.`,
  "locationAddressLong": `Адрес местоположения должен состоять не менее чем из 2 символов.`,
  "locationAddress": `Пожалуйста, введите адрес местонахождения.`,
  "Name": `Имя`,
  "Hold to Stop": `Удерживайте, чтобы остановить`,
  "Location Address": `Адрес местонахождения`,
  "Phone Number": `Телефонный номер`,
  "Add": `Добавлять`,
  "Category": `Категория`,
  "backgroundProcess": `Ваша временная шкала будет работать в фоновом режиме, когда вы переходите на другие экраны.`,
  "NotMoving": `Еще не двигаетесь?`,
  "oneMinuteLongerAlert": `Чтобы закончить и сохранить, FR8 нужно как минимум на 1 минуту больше активности со сменой местоположения.`,
  "editPost": `Редактировать пост`,
  "vedioLimit": `Продолжительность видео должна быть не более 30 секунд.`,
  "selectCurentLocation": `Выберите текущее местоположение`,
  "noCommentYet": `комментариев пока нет`,
  "enterFirstComment": `Прокомментируйте первым.`,
  "App_Share": `Поделиться приложением`,
  "appShareMessage": `поделился приложением FR8. Нажмите на ссылку ниже, чтобы увидеть мобильное приложение и узнать текущее время ожидания сегодня.`,
  "appShareMessage2": ` FR8\n Нажмите на ссылку ниже, чтобы увидеть мобильное приложение и узнать текущее время ожидания сегодня.`,
  "deleteCommentReplyAlert": `Вы уверены, что хотите удалить этот ответ на комментарий?`,
  "enter_first_name_length_alert": `Имя должно состоять не менее чем из 3 символов.`,
  "enter_last_name_length_alert": `Фамилия должна состоять не менее чем из 3 символов.`,
  "location_Setting": `Настройки местоположения`,
  "postlikeHeading": `Люди, которым нравится пост`,
  "commentLikeHeading": `Люди, которым нравятся комментарии`,
  "viewProfile": `Просмотреть профиль`,
  "shareListHeading": `Люди, которые поделились публикацией`,
  "Reply": `Отвечать`,
  "Reply to": `Ответить на`,
  "Dislike": `Не нравится`,
  "Smile": `Улыбка`,
  "Angry": `Злой`,
  "Rolling Eyes": `закатывающие глаза`,
  "Thinking": `мышление`,
  "Stop": `Останавливаться`,
  "switchFrom": `Получайте точные уведомления о безопасности, переключаясь с`,
  "Always Allow": `Всегда позволяют`,
  "While Using": `При использовании`,
  "Ask next time": `Спроси в следующий раз`,
  "Never": `Никогда`,
  "Manage location Settings": `Управление настройками местоположения`,
  "Italian": `Итальянский`,
  "Chinese": `Китайский упрощенный (мандарин)`,
  "Hindi": `хинди`,
  "Filipino": `Филиппинский`,
  "Vietnamese": `вьетнамский`,
  "Arabic": `арабский`,
  "French": `французкий язык`,
  "Korean": `корейский язык`,
  "Russian": `русский`,
  "Bengali": `Бенгальский`,
  "German": `Немецкий`,
  regionlNotFound: 'Region not found.',
  Region:"Region",
  in: 'в',
  posts: 'Публикации',


"All":"Все",
"saveToPhone":"Сохранить в телефон",
"ADD":"ДОБАВЛЯТЬ",
"deleteAccount":"Удалить аккаунт",
"deleteAccountAlert":"Вы уверены, что хотите удалить свой аккаунт?",
"replyWrite":"Напишите ответ...",
"Camera":"Камера",
"Image Gallery":"Галерея",
"regionlNotFound":"Регион не найден.",
"Region":"Область, край",
"regionSelectAlert":"Пользователь может выбрать максимум 3 региона.",

"CALL":"ВЫЗОВ",
"ADDRESS":"АДРЕС",
"MIN":"МИН",
"About":"О",
"Overview":"Обзор",
"Review":"Обзор",
"Timelines":"Хронология",
"Rate & Review":"Оценить и просмотреть",
"ratings":"Оценить и просмотреть",
"Write Your Review":"Напишите свой отзыв",
"Just now":"Прямо сейчас",
'waitTimeIndicator':`Индикатор времени ожидания`,
currentWaitTime:"Текущее среднее время ожидания",

};

module.exports = {
  constants
};
