const images = {
  buttonBackground: require("./../Images/Add_friend_button_bg.png"),
  // gifInfinty: require("./../Images/8.gif"),
  gifInfinty: require("./../Images/infinity.gif"),
  loginBackground: require("./../Images/background.png"),
  loginLogo: require("./../Images/Login_logo.png"),
  atTheRate: require("./../Images/Email_icon.png"),
  key: require("./../Images/Password_icon.png"),
  addFriend: require("./../Images/Add_friend.png"),
  userGrey: require("./../Images/User_02.png"),
  phone: require("./../Images/Phone.png"),
  calender: require("./../Images/Calender.png"),
  back: require("./../Images/Back_button.png"),
  avtarImage: require("./../Images/User_image.png"),
  pencil: require("./../Images/Edit.png"),
  otp: require("./../Images/OTP.png"),
  search: require("./../Images/Search.png"),
  arrowRight: require("./../Images/Arow_right.png"),
  dropdownArrow: require("./../Images/Dropdown_arrow.png"),
  checkBox: require("./../Images/Check_box.png"),
  unCheckBox: require("./../Images/Uncheck_box.png"),
  userChat: require("./../Images/User_chat.png"),
  user01: require("./../Images/User_01.png"),
  user05: require("./../Images/User_05.png"),
  video: require("./../Images/Video.png"),
  like: require("./../Images/Like.png"),
  disLike: require("./../Images/dislike.png"),
  share: require("./../Images/Share.png"),
  videoImage: require("./../Images/Video_image.png"),
  // play: require("./../Images/Play_01.png"),
  play: require("./../Images/Play.png"),
  views: require("./../Images/views.png"),
  header: require("./../Images/Top_bar_backgorund.png"),
  selectedTab: require("./../Images/Tab_01.png"),
  user03: require("./../Images/User_03.png"),
  arrow: require("./../Images/Arrow.png"),
  addFriend: require("./../Images/Add_friend.png"),
  image01: require("./../Images/Image_01.png"),
  add: require("./../Images/Add.png"),
  uploadFull: require("./../Images/Upload_Full.png"),
  facebookBack: require("./../Images/facebook_button.png"),
  instagramBack: require("./../Images/Insta_button.png"),
  googleBack: require("./../Images/Google_button.png"),
  facebookLogo: require("./../Images/facebook_icon.png"),
  instagramLogo: require("./../Images/Insta_icon.png"),
  googleLogo: require("./../Images/Google_icon.png"),
  live: require("./../Images/Live.png"),
  sideMenu: require("./../Images/Right_side_menu.png"),
  security: require("./../Images/Security.png"),
  chat: require("./../Images/MsgClient.png"),
  map: require("./../Images/map_01.png"),
  send: require("./../Images/Send.png"),
  location: require("./../Images/Location.png"),
  LocationNav: require("./../Images/LocationNav.png"),
  camera: require("./../Images/Record.png"),
  warn: require("./../Images/Warn.png"),
  userBackground: require("./../Images/userBackground.png"),
  info: require("./../Images/Info.png"),
  userIcon: require("./../Images/User_icon.png"),
  notLike: require("./../Images/NotLike.png"),
  notDisLike: require("./../Images/NotDislike.png"),
  videoDummy: require("./../Images/videoThumbnail.png"),
  smartphone: require("./../Images/smartphone.png"),

  userMail: require("./../Images/mail.png"),
  userNew: require("./../Images/user.png"),
  backLeft: require("./../Images/back2.png"),
  backArrow: require("./../Images/back.png"),
  postDark: require("./../Images/problem.png"),
  fullscreen: require('./../Images/full-screen.png'),
  mute:require('./../Images/mute.png'),
  volume: require('./../Images/volume.png'),
  cameraImage: require('../Images/imagecamera.png'),
  cameraVideo: require('../Images/cameraVideo.png'),
  cancel: require('../Images/cancel.png'),
  bracket: require('../Images/0761.png'),
  bracketIn: require('../Images/bracketout.png'),
  locationPoint: require('../Images/location21.png'),
  locationMove: require('../Images/locationMove.png'),
  profileClient: require('../Images/ProfileClient.png'),
  editPen:require('../Images/editpen.png'),
  homeClient:require('../Images/homeClient2.png'),
  flashClient:require('../Images/flashClient.png'),
  addClient:require('../Images/addClient.png'),
  clockClient:require('../Images/clockCLientNew.png'),
  notificationClient:require('../Images/notificationClient.png'),
  homeClient2:require('../Images/homeClient.png'),
  flashClient2:require('../Images/flashClient2.png'),
  // addClient:require('../Images/addClient.png'),
  clockClient2:require('../Images/clockCLientNew2.png'),
  notificationClient2:require('../Images/notificationClient2.png'),
  chassis:require('../Images/chassis.jpeg'),
  portTrminal:require('../Images/portTrminal.jpg'),
  rail:require('../Images/rail.jpg'),
  empty:require('../Images/empty.jpg'),
  wherehouse:require('../Images/wherehouse.jpg'),
  start:require('../Images/start.gif'),
  pause:require('../Images/pause.gif'),
  stop:require('../Images/stop29.gif'),
  startSpanish:require('../Images/startSpanish.gif'),
  pauseSpanish:require('../Images/pauseSpanish.gif'),
  stopSpanish:require('../Images/stopSpanish.gif'),
  startPortuguse:require('../Images/Comecar.gif'),
  pausePortuguse:require('../Images/pausa.gif'),
  stopPortuguse:require('../Images/Pare.gif'),
  community1:require('../Images/communityActive.png'),
  community2:require('../Images/communitywhite.png'),
  rail1:require('../Images/rail1.jpg'),
  port1:require('../Images/port1.jpg'),
  Empty1:require('../Images/Empty1.jpg'),
  warehouse1:require('../Images/warehouse1.jpg'),
  chassis:require('../Images/Chassis1.jpg'),
  eightGif: require('../Images/8.gif'),
  warn1: require('../Images/warn1.png'),
  ratings: require('../Images/ratings.png'),
  downArrow: require('../Images/downArrow.png'),
  upArrow: require('../Images/upArrow.png'),
  calls: require('../Images/calls.png'),
  loc: require('../Images/loc1.png'),
  fr8Background: require('../Images/fr8Background.png'),
};
module.exports = {
  images
};
