import {imageBaseUrl} from '../Config/index'

const constants = {
  // TermsUrl:"http://18.205.207.176:3000/public/pdf/Fr8_App_Terms_Of_Use.pdf",
  // PrivacyUrl:"http://18.205.207.176:3000/public/pdf/Fr8_App_Privacy_Policy.pdf",
  // // TermsUrl:"http://1.6.98.141/Mobile/fr8/public/pdf/Fr8_App_Terms_Of_Use.pdf",
  // TermsUrl: imageBaseUrl +"public/pdf/Fr8_App_Terms_Of_Use.pdf",
  // // PrivacyUrl:"http://1.6.98.141/Mobile/fr8/public/pdf/Fr8_App_Privacy_Policy.pdf",
  // PrivacyUrl: imageBaseUrl + "public/pdf/Fr8_App_Privacy_Policy.pdf",
  TermsUrl:"https://www.fr8.ai/terms",
  // TermsUrl: imageBaseUrl +"public/pdf/Fr8_App_Terms_Of_Use.pdf",
  // PrivacyUrl:"http://18.205.207.176:3000/public/pdf/Fr8_App_Privacy_Policy.pdf",
  PrivacyUrl:"https://www.fr8.ai/privacy",
  Email: "Email",
  Enter_Email: "Digite o e-mail",//need change
  Password: "Senha",
  Enter_Password: "Inserir_Senha",
  Enter_New_Password: "Inserir Nova Senha",
  Forgot_Your_Password: "Esqueceu Sua Senha?",
  Login: "Entrar",
  Doesnt_have_an_account: "Não tem uma conta?",
  Sign_up: "Cadastro",

  Enter_Name: "Inserir nome",
  Enter_first_Name: "Introduza o primeiro nome",
  Enter_last_Name: "Insira o último nome",
  Enter_Your_Phone_Number: "Inserir seu número de telefone",
  Enter_Six_Digit_Verification_Code: "Inserir código de verificação com 6 dígitos",
  Resend_Verification_Code: "Reenviar código de verificação",
  Contact_Permission:
    "Por favor, ative a permissão de contactos para manter seus amigos seguros.",

  Register: "Registro",
  Full_Name: "Nome Completo",
  Enter_Full_Name: "Inserir Nome Completo",
  Username: "Nome de usuário",
  Enter_Username: "Inserir nome de usuário",
  Email_Address: "Endereço de email",
  Enter_Email_Address: "Inserir endereço de email",
  User_Type: "Tipo de Usuário",
  Select_User_Type: "Selecionar tipo de usuário",
  Phone_Number: "Número de telefone",
  Enter_Phone_Number: "Inserir número de telefone",
  Date_Of_Birth: "Data de Nascimento",
  Select_Date_Of_Birth: "Selecionar Data de Nascimento",
  Confirm_Password: "Confirmar Senha",
  Enter_Confirm_Password: "Inserir Confirmação de Senha",
  Agree_Terms_and_Condition: "Aceitar Termos e Condiçoes",

  Forgot_Password: "Esqueci a Senha",
  Submit: "Submeter",
  OTP: "OTP",
  Enter_OTP: "Inserir OTP",
  Reset_Password: "Redefinir Senha",
  Edit_Profile: "Editar Perfil",
  Edit_Phone_Number: "Editar Número de Telefone",
  Update: "Atualizar",
  Change_Password: "Alterar Senha",
  Old_Password: "Senha Antiga",
  Enter_Old_Password: "Inserir Senha Antiga",
  FAQs: "FAQs",
  Social_Media_Accounts: "Redes Sociais",
  Settings: "Definições",
  "FR8": "FR8",
  Support_Center: "Centro de Suporte",
  Terms_And_Conditions: "Termos e Condições",
  Privacy_Policy: "Política de Privacidade",
  Change_Language: "Alterar Idioma",
  Logout: "Sair",
  Log_out: "Sair",
  Confirm: "Confirmar",
  Cancel: "Cancelar",
  Please_Select: "Por Favor, Selecione",
  Warn_Contacts: "Avisar Contatos",
  Search_contacts: "Buscar Contatos",
  Friend_Requests: "Pedidos de Amizade",
  Friend_Request: "Pedido de Amizade",
  My_Posts: "Minhas Postagens",
  Search_friends: "Buscar amigos, terminais, contatos",
  My_Freighting_Network: "Minha Rede de Fretagem",
  'My_Network': 'Minha Rede',
  Places: "Locais",
  Friends: "Amigos",
  Nearby_Terminals: "Terminais Próximos",
  Explore: "Explorar",
  Contacts: "Contatos",
  Name_Of_User: "Nome de Usuário",
  Add_Friend: "Adicionar Amigo",
  Remove_Friend: "Remover Amigo",
  Chat: "Bate-papo",
  Post_Details: "Detalhes da Postagem",
  Live_Streams: "Transmissões ao Vivo",
  CreatePost: "Criar Postagem",
  SocialMediaAccounts: "Redes Sociais",
  Instagram: "Instagram",
  Google: "Google",
  Facebook: "Facebook",
  Support: "Apoio",
  Tittle: "Título",
  Enter_Tittle: "Inserir Título",
  FR8: "FR8",
  UserName: "Nome de Usuário",
  TerminalDetails: "Detalhes do Terminal",
  Location: "Localização",
  Un_Follow: "Deixar de Seguir",
  Follow: "Seguir",
  Record: "Gravar",
  Warn: "Avisar",
  ChatHistory: "Histórico de Bate-papo",
  TerminalName: "Nome do Terminal",
  Terminal: 'Terminal',
  English: "Inglês",
  Spanish: "Espanhol",
  Driver_Type: "Tipo de Motorista",
  Select_Driver_Type: "Selecionar tipo de motorista",
  Users: "Usuários",
  Enter_Title: "Inserir Título",
  Type_Message_Here: "Escrever Mensagem Aqui...",
  Skip: "Pular",
  Friend_request_not_found: "Pedido de amizade não achado.",
  Change_Mobile_Number: "Alterar Número de Celular",
  resend_Otp: "Reenviar código de verificação",

  posts: 'Postagens',
  post: 'Publicar',
  Friend: 'Amiga',
  'noResult': 'Nenhum resultado encontrado.',

  /////////////// Alert Message /////////////////////

  enter_email_alert: "Por favor insira um endereço de email.",
  enter_valid_email_alert: "Por favor insira um endereço de email válido.",
  enter_password_alert: "Por favor insira uma senha.",
  // enter_full_name_alert: "Por favor insira o nome completo.",
  // enter_full_name_aplhanumeric_alert: "Por favor use carateres alfanuméricos no nome completo.",
  enter_full_name_alert: "Por favor, insira o primeiro nome.",
  enter_full_name_aplhanumeric_alert: "Insira o nome alfanumérico.",
  enter_user_name_alert: "Por favor insira um nome de usuário.",
  enter_user_type_alert: "Por favor selecione o tipo de usuário.",
  enter_driver_type_alert: "Por favor selecione o tipo de motorista.",
  enter_phone_number_alert: "Por favor insira um número de telefone.",
  enter_phone_number_length_alert: "O número de telefone deve ter entre 8 e 15 dígitos.",
  enter_Numbers_allowed__phone_alert: "Apenas são permitidos números no campo do telefone.",
  enter_date_of_birth_alert: "Por favor selecione uma data de nascimento.",
  enter_password_length_alert: "A senha deve ter pelo menos 6 carateres.",
  enter_confirm_password_alert: "Por favor insira a confirmação da senha",
  enter_password_not_match_alert: "A senha e confirmação da senha devem ser iguais.",
  enter_terms_conditions_alert: "Por favor aceite os termos & condições.",
  enter_otp_alert: "Por favor insira o código de verificação.",
  enter__valid_otp_alert: "Por favor insira um código de verificação válido.",
  enter_old_password_alert: "Por favor insira a senha antiga.",
  enter_old_password_length_alert:
    "A senha antiga deve ter pelo menos 6 carateres.",
  enter_new_password_alert: "Por favor insira uma senha nova.",
  enter_new_password_length_alert:
    "A senha nova deve ter pelo menos 6 carateres.",
  enter_old_cofirm_not_valid_alert:
    "A senha antiga e a confirmação de senha devem ser iguais.",
  Stream_stopped_by_user: "Transmissão ao vivo terminada por ",
  Loading_streams: "Carregando transmissões",
  you_are_live_now: "Você está ao vivo agora.",
  end_publisher_video: "Você tem certeza que quer terminar o vídeo ao vivo?",
  logOutAlert: "Você tem certeza que quer sair?",
  end_publisher_video_successfully: "A transmissão ao vivo terminou.",
  Alert: "Alerta",
  PhoneNumber_required_for_login:
    "Um número de telefone é necessário para entrar. Também nos ajuda a moderar a comunidade e proteger nossos usuários.",
  Privacy_policy:
    "AO CONTINUAR, VOCÊ CONCORDA COM NOSSOS",
  Terms: "TERMOS DE USO",
  Policy: "POLÍTICA DE PRIVACIDADE",
  Why_you_need_my_phone_number: "PORQUE VOCÊS PRECISAM DE MEU NÚMERO DE TELEFONE",
  Why_we_need_your_phone_number: "PORQUE NÓS PRECISAMOS DE SEU NÚMERO DE TELEFONE",
  verifyAccount: "VERIFICAR CONTA",
  terminalNotFound: 'Terminal não achado.',
  Profile: 'Perfil',
  App_Settings: 'Definições do Aplicativo',
  'estimatedTime': 'Tempo estimado',
  // 'estimatedWaitTime': 'Tempo de espera estimado',
  'estimatedWaitTime': 'Minutos esperados',
  'youHaveLeft': "Você saiu",

  Citizen_safety_message:
    "Fr8 é uma rede de fretagem. Solicitamos um número de telefone para verificar sua identidade e garantir que aqueles que violam os padrões de nossa comunidade possam ser removidos da rede, quando apropriado.",
  ///////////// Api message //////////////////
  "something_went_wrong": "Ocorreu um erro.",
  "please_check_your_internet_connection":
    "Por favor verifique sua conexão de Internet.",
  startEndAlert: "A hora de início deve ser anterior à hora de fim.",
  'addPost': 'Adicionar Postagem',
  'permissionTitle': 'Você recusou a permissão para tirar fotos da biblioteca',
  'permissionBody': 'Você gostaria de acessar isso e ativar a permissão nas definições?',
  'videoPermissionTitle': "Você recusou a permissão para tirar vídeos da biblioteca",
  'TimeLine_post_not_found': 'Publique sua atualização.',
  Timeline_Posts: 'Postagens da cronologia',
  'Timeline': 'Cronologia',
  // 'trackAtimeLine':'Track a wait time',
  'trackAtimeLine': 'Monitore seu tempo de espera',
  'Journey': 'Nenhuma linha do tempo encontrada.',
  'KM': 'mi',
  'Distance_Travelled': 'Distância Percorrida',
  hrs: ' hrs',
  secs: ' segs',
  mins: " mins",
  time: 'Tempo',
  'wait_time': 'Tempo de espera médio',
  'Equiment_Photo': 'Foto de equipamento',
  'Interchange_Receipt': 'Recibo de intercâmbio',
  'video': 'Vídeo',
  'Share': 'Partilhar',
  start_time: 'No',
  Report_Post: 'Denunciar Postagem',
  endTime: 'Fora',
  closeTime: 'Hora de fechamento',
  openTime: 'Tempo aberto',
  'distance': "Distância",
  'Total_time': 'Tempo Total',
  'Edit_Timeline': 'Editar Cronologia',
  'messageAlert': 'Por favor insira uma mensagem.',
  'enterMessage': 'Inserir mensagem...',
  'Trending_Post': 'Postagem Popular',
  'PleaseEnterReportResion': 'Por favor indique a razão da denúncia.',
  'trendingPostNotFound': 'Nenhuma postagem popular achada.',
  'Accept': 'Aceitar',
  'Reject': 'Rejeitar',
  'Allow': "Permitir",
  'Invite': 'Convidar',
  'postNotFound': 'Nenhuma postagem achada.',
  'Cancel_Friend_Request': 'Cancelar Pedido de Amizade',
  'User_Posts': "Postagens do Usuário",
  'Notifications': 'Notificações',
  No_notifications: 'Sem notificações achadas.',
  'And': 'E',
  'deletePostAlert': 'postagem?',
  'Yes': 'Sim',
  'No': 'Não',
  'enterTitle': 'Por favor insira um título.',
  'pleaseEnterMessage': 'Por favor insira uma mensagem.',
  'Post_Create': 'Criar Postagem',
  'description': 'Inserir descrição...',
  'enterDescription': 'Por favor insira a descrição.',
  'descriptionMax': 'Por favor insira uma descrição com menos de 1000 carateres.',
  'descriptionMin': 'A descrição deve ter pelo menos 10 carateres.',
  'Preview': "Pré-visualizar",
  'messageMax': 'Por favor insira uma mensagem com menos de 1000 carateres.',
  'noUser': 'Nenhum usuário achado.',
  'New': 'Novo',
  'No_chat_found': 'Nenhum bate-papo recente achado',
  'Search_Terminal': 'Buscar Terminal',
  // "Receipt_Private": 'Recibo Privado',
  "Receipt_Private": 'Tornar privado',
  'Edit': 'Editar',
  'Delete': 'Excluir',
  'postShareMessage': ' compartilhou a postagem \n Clique no link abaixo para ver a postagem ',
  'postShareMessage2': ' compartilhou a postagem \n Clique no link abaixo para ver a postagem ',
  'shareSubject': 'FR8 Postagem TimeLine',
  'messageCopy': 'Mensagem copiada',
  'avaliable24Hours': 'Disponível 24 horas',
  "photo": "FOTO",
  'photoLibrary': 'BIBLIOTECA DE FOTOS',

  "photoL": "foto",
  'photoLibraryL': 'Biblioteca de fotos',

  'reportUser': 'Reportar',
  'reasonOfReport': 'Razão do Relatório',
  'reportPostAlert': 'Tem certeza que deseja denunciar esta postagem?',
  // "ForegroundServiceTitle": "O aplicativo FR8 está gerenciando sua localização em segundo plano",
  "ForegroundServiceTitle": "O rastreador de pagamento de detenção está em execução",
  "Portuguese": "Portugal",
  "interChangeDelete": "Tem certeza de que deseja excluir o recibo de troca?",
  "equipmentDelete": "Tem certeza de que deseja excluir a foto do equipamento?",
  "deleteVideo": "Tem certeza que deseja excluir o vídeo?",
  'sentAMessage': 'enviou uma mensagem:',
  "editMessage": "Editar Mensagem",
  'continue': 'Continuar',
  'noContact': 'Nenhum contato encontrado',


  'Driver': "Motorista",
  'Owner Operator': 'Operador próprio',
  "Company": 'Companhia',
  "Air Cargo Carrier": 'Transportadora de carga aérea',
  "Exporter": "Exportador",
  "Freight Broker": 'Corretora de mercadorias',
  "Importer": "Importador",
  "Shipper": "Remetente",
  "Trucking": "Caminhão",
  "Warehouse": "Armazém",
  'Owner Operator': 'Operador próprio',
  'Company Driver': 'Motorista da empresa',
  'OKAY':'CERTO',
  'installMessage':'Ei, baixe o aplicativo FR8 para calcular os tempos de espera nos terminais ferroviários portuários: http://onelink.to/fr8app',
  'warned':'avisou',
  "WaitingAt":'Esperando em',
  'openFr8':'Abra o aplicativo Fr8 para mostrar o tempo estimado de espera.',
  "day":"dia",
  "days":"dias",
  "hour":" hora",
  "hours":" horas",
  "minute":" minuto",
  "minutes":" minutos",
  "second":" segundo",
  "seconds":" segundos",
  // 'openApp':'Abra o aplicativo FR8.',

  'openApp': 'Abra o aplicativo para sincronizar seu status',
  'openAppBody': 'Para obter a melhor experiência, deixe o aplicativo FR8 permanecer aberto em segundo plano. Isso mantém a sua linha do tempo e o carimbo de hora do terminal precisos.',
  "Comment":"Comente",
  "Comments":"Comentários",
  "Like":"Gostar",
  'noComment':"Nenhum comentário encontrado",
  'deleteCommentAlert':"Tem certeza que deseja deletar o comentário?",
  'enterTheComment':"Por favor, insira o comentário.",
  'enterYourComment':"Insira seu comentário ...",
  'DeeplinkShare':'Compartilhamento Deeplink',
  'Shares': 'Ações',
  'shareasPost':"Compartilhar postagem",
  'hasShared':'compartilhou',
  'whatsOnMind':"O que está em sua mente?",
  'inGate':'No',
  'outGate':'Fora',
  'enter_last_name_alert': "Por favor, insira o sobrenome.",
  'With':'com',
  'others':'outros',
  'tagFriends':'Marcar amigos',
  'done':'Feito',
  'friendSearch':'Procurar amigos',
  'checkIN':'Check-in',
  'tagUsers':'Usuários marcados',
  'safeTrip':'Agora você pode compartilhar seu tempo de espera. Tenha uma viagem segura!',
  'addLocation':'Adicionar local',
  'locationSelect':'Selecione o local.',
  'attach':'Anexar arquivos',
  'selectImage':'Selecione imagens ou vídeo para postar.',
  'noPlace':'Nenhum lugar encontrado',
  'deleteMedia':'Tem certeza de que deseja excluir esta mídia?',
  'deleteNotification':'Tem certeza de que deseja excluir esta notificação?',
  'loading':'Carregando...',
  'next':"Próximo",
  'ttlUserInterminal':'Número de usuários dentro do terminal: ',
  'members':'membros dentro',
  'member':'membro dentro',
  DescriptionText:'Descrição',
  NotificationDetail:'Detalhes de Notificação',

  //newly added
  useLocation:'Use your location',
  firstPermissionTitle:'To see maps for automatically tracked activities, allow FR8 to use your location all of the time.',
  noThanks:'No thanks',
  turnOn:'Turn on',
  newVersion:'New version ',
  // versionDescription:'The version of the app you are using is outdated, please update to the latest version for the most accurate wait times.',
  versionDescription:`Esta versão do aplicativo está desatualizada, atualize para a versão mais recente para desbloquear novos recursos incríveis para ajudá-lo a obter os novos recursos mais precisos e surpreendentes. Não se esqueça de definir as permissões de localização para Sempre permitir para que o aplicativo calcule os tempos de espera do terminal para você em segundo plano.`,
  firstPermissionDesc:'FR8 will use your location in the background to enable your precise recordings of your trips in terminals and calculate wait time and time stamp.',
  enter_user_name_length_alert: "O nome de usuário deve ter pelo menos 3 caracteres.",
  validUserName:'Apenas letras (a-z), números (0-9), pontos (.) E sublinhados (_) são permitidos.',
  user_name_start: "O nome de usuário não deve começar com pontos (.)",
  onlyNumberAlert:"O nome de usuário não pode conter apenas números.",
  user_name_end:"O nome de usuário não deve terminar com pontos (.)", 
  twoDots:'O nome de usuário não deve ter mais um ponto (.) Em uma linha.',
Ok:"OK",
followingTerminal:'Seguindo',
pdfDownload:'baixar PDF',
"Equipment Depot":"Equipment Depot",
timelineCancel:'Tem certeza de que deseja cancelar a linha do tempo?',
"Truck Stop":"Parada de caminhão",
"Gas Station":"Posto de gasolina",
"Weight Station":"Estação de Peso",
location_name_enter:"Insira o nome do local.",
locationNameLong:'O nome do local deve ter pelo menos 2 caracteres.',
locationAddressLong:"O endereço do local deve ter pelo menos 2 caracteres.",
locationAddress:"Por favor, insira o endereço do local.",
Name:"Nome",
"Hold to Stop":"Segure para parar",
"Location Address":"Endereço de localização",
"Phone Number":"Número de telefone",
"Add":"Adicionar",
"Category":"Categoria",
backgroundProcess:"Sua linha do tempo será executada em segundo plano quando você passar para outras telas.",
NotMoving:"Ainda não está se movendo?",
oneMinuteLongerAlert:"Para finalizar e salvar, o FR8 precisa de pelo menos 1 minuto a mais de atividade, com mudança de local.",
editPost:"Edit Post",
vedioLimit:"A duração do vídeo deve ser de no máximo 30 segundos.",
selectCurentLocation:"Selecione a localização atual",
noCommentYet:"Nenhum comentário ainda",
enterFirstComment:"Seja o primeiro a comentar.",
App_Share:'Compartilhar aplicativo',
'appShareMessage': ' compartilhou o aplicativo FR8. Clique no link abaixo para ver o aplicativo móvel e ver os tempos de espera atuais hoje.',
'appShareMessage2': ' FR8\n Clique no link abaixo para ver o aplicativo móvel e ver os tempos de espera atuais hoje.',
location_Setting:'Configurações de localização',
postlikeHeading:'Pessoas que gostam de postar',
commentLikeHeading:'Quem curte comenta',
viewProfile:'Ver perfil',
shareListHeading:'Pessoas que compartilharam a postagem',
enter_first_name_length_alert: "O primeiro nome deve ter pelo menos 3 caracteres.",
enter_last_name_length_alert: "O sobrenome deve ter pelo menos 3 caracteres.",
'deleteCommentReplyAlert':"Tem certeza de que deseja excluir esta resposta de comentário?",
Reply :"Responder",
"Reply to": "Responder a",
Like: "Como",
Dislike :"Não gosto",
Smile :"Sorriso",
Angry :"Nervoso",
"Rolling Eyes":"Virando os olhos",
Thinking:"Pensando",
Stop:"Pare",
switchFrom:'Receba notificações de segurança precisas mudando de',
'Always Allow':'Sempre permitir',
'While Using':'Enquanto estiver usando',
'Ask next time':'Pergunte da próxima vez',
'Never':'Nunca',
"Manage location Settings":'Gerenciar configurações de localização',

/////////////////////////////////
"Italian":`italiano`,
"Chinese":`Chino simplificado (mandarín)`,
"Hindi":`hindi`,
"Filipino":`Filipino`,
"Vietnamese":`vietnamita`,
"Arabic":`Arábica`,
"French":`francés`,
"Korean":`coreano`,
"Russian":`ruso`,
"Bengali":`bengalí`,
"German":`alemán`,
regionlNotFound: 'Region not found.',
Region:"Region",
in: 'dentro',

"All":"Tudo",
"saveToPhone":"Salvar no telefone",
"ADD":"ADICIONAR",
"deleteAccount":"Deletar conta",
"deleteAccountAlert":"Tem certeza de que deseja excluir sua conta?",
"replyWrite":"Escreva uma resposta...",
"Camera":"Câmera",
"Image Gallery":"Galeria de imagens",
"regionlNotFound":"Região não encontrada.",
"Region":"Região",
"regionSelectAlert":"O usuário pode selecionar no máximo 3 regiões.",
"CALL":"LIGAR",
"ADDRESS":"MORADA",
"MIN":"MIN",
"About":"Sobre",
"Overview":"Visão geral",
"Review":"Análise",
"Timelines":"Linhas do tempo",
"Rate & Review":"Avalie e analise",
"ratings":"Avalie e analise",
"Write Your Review":"Escreva sua revisão",
"Just now":"Agora mesmo",
'waitTimeIndicator':'Indicador de tempo de espera',
currentWaitTime:"Tempo médio de espera atual",
addmobile:'Adicionar número de celular',
addAccount:'Adicionar Conta',



};

module.exports = {
  constants
};
